/* CCNA 200-301 v1.1 — Exam C, part 2 (c051–c100). Data center + operations theme: spine-leaf fabric (SPINE-1/2,
   LEAF-1..4, DC-CORE, DC-EDGE) in 10.60.0.0/16 and 2001:db8:60::/48 — longest-prefix puzzles with overlapping routes,
   AD vs metric, ECMP, host routes, OSPF cost with 10G links, DR/BDR on the server-farm segment, OSPF neighbor faults,
   GLBP/HSRP for server gateways, NAT pools, NTP hierarchy, SNMPv3/syslog, QoS at the DC edge, FTP image transfers,
   TACACS+, management ACLs, DAI, WPA3-Enterprise. Domains 3 (25), 4 (10), 5 (15). All text original. Spec: dev/specs/ccna.md §6. */
export const CCNA_BANK_C_P2 = [
{id:"c051",obj:"3.2.a",d:3,cat:"rtable",t:"mc",
 q:"Refer to the exhibit. During a migration, DC-EDGE holds both static routes and OSPF routes toward DC-CORE's two links. DC-EDGE receives a packet for the backup appliance at 10.60.41.77. Which route does DC-EDGE use to forward it?",
 ex:"DC-EDGE# show ip route\nCodes: L - local, C - connected, S - static, O - OSPF\n       * - candidate default\n\nGateway of last resort is 203.0.113.1 to network 0.0.0.0\n\nS*    0.0.0.0/0 [1/0] via 203.0.113.1\n      10.0.0.0/8 is variably subnetted, 8 subnets, 6 masks\nS        10.60.0.0/16 [1/0] via 10.60.250.6\nO        10.60.32.0/19 [110/2] via 10.60.250.2, 00:12:34, GigabitEthernet0/1\nS        10.60.40.0/22 [1/0] via 10.60.250.6\nO        10.60.41.128/25 [110/3] via 10.60.250.2, 00:12:34, GigabitEthernet0/1\nC        10.60.250.0/30 is directly connected, GigabitEthernet0/1\nL        10.60.250.1/32 is directly connected, GigabitEthernet0/1\nC        10.60.250.4/30 is directly connected, GigabitEthernet0/2\nL        10.60.250.5/32 is directly connected, GigabitEthernet0/2\n      203.0.113.0/24 is variably subnetted, 2 subnets, 2 masks\nC        203.0.113.0/30 is directly connected, GigabitEthernet0/0\nL        203.0.113.2/32 is directly connected, GigabitEthernet0/0",
 o:[
  {t:"10.60.40.0/22, via 10.60.250.6",ok:true,x:"10.60.40.0/22 spans 10.60.40.0 to 10.60.43.255, so it contains 10.60.41.77. The /16, /19 and /22 all match; the /22 is the longest, so it wins. AD is never compared, because the prefixes are different."},
  {t:"10.60.41.128/25, via 10.60.250.2",ok:false,x:"This /25 covers only 10.60.41.128 to 10.60.41.255. The host part .77 is in the lower half of 10.60.41.0/24, so this entry does not match at all."},
  {t:"10.60.32.0/19, via 10.60.250.2",ok:false,x:"The /19 (10.60.32.0 to 10.60.63.255) does match, but a /22 also matches and is more specific. Being OSPF rather than static does not matter here; prefix length is checked first."},
  {t:"10.60.0.0/16, via 10.60.250.6",ok:false,x:"The /16 matches, but it is the least specific of the three 10.60 routes that contain the address. It is used only for 10.60 destinations that no longer prefix covers."}
 ],
 w:"Longest prefix match first: list every route that contains the address (check the range, not just the first octets), then pick the longest mask. AD and metric only break ties between identical prefixes."},
{id:"c052",obj:"5.7",d:5,cat:"l2sec",t:"mc",
 q:"Refer to the exhibit. After dynamic ARP inspection was enabled for VLAN 30 on LEAF-3, the backup server on Gi1/0/14, which uses the static address 10.60.30.20, lost contact with its gateway 10.60.30.1. Servers in VLAN 30 that lease addresses through DHCP are unaffected. Which action restores the backup server while keeping its port inspected by DAI?",
 ex:"LEAF-3# show logging | include DAI\n%SW_DAI-4-DHCP_SNOOPING_DENY: 1 Invalid ARPs (Req) on Gi1/0/14, vlan 30.\n  ([0050.56aa.1001/10.60.30.20/0000.0000.0000/10.60.30.1/09:12:41 UTC\n  Sat Oct 3 2026])\n\nLEAF-3# show ip dhcp snooping binding | include 10.60.30.20\nLEAF-3#",
 o:[
  {t:"Permit 10.60.30.20 with MAC 0050.56aa.1001 in an ARP ACL and apply it to VLAN 30 with ip arp inspection filter",ok:true,x:"DAI checks the sender IP and MAC of ARP packets on untrusted ports against the DHCP snooping bindings. A statically addressed server never leases, so it has no binding. An ARP ACL supplies the missing IP-to-MAC pair while the port stays untrusted and inspected."},
  {t:"Enter ip dhcp snooping trust on Gi1/0/14",ok:false,x:"DHCP snooping trust only lets DHCP server messages in on that port. It does not create a binding, and DAI trust is a separate setting, so the server's ARPs would still be dropped (and a rogue DHCP server could now answer there)."},
  {t:"Raise the ip arp inspection limit rate on Gi1/0/14",ok:false,x:"The log reason is DHCP_SNOOPING_DENY: no matching binding. Exceeding the rate limit would err-disable the port instead; a higher limit does not make an unknown sender valid."},
  {t:"Disable ip arp inspection validate src-mac for VLAN 30",ok:false,x:"The optional validate checks compare MAC addresses in the Ethernet and ARP headers. Turning them off removes extra checks but does not add the missing IP-to-MAC binding."}
 ],
 w:"DAI trusts only what DHCP snooping learned. Statically addressed hosts need an ARP ACL (ip arp inspection filter) or a static binding; trusting the port works but removes the protection."},
{id:"c053",obj:"3.4.c",d:3,cat:"ospf",t:"mc",
 q:"Refer to the exhibit. Vlan50 is the server-farm segment shared by LEAF-3 (RID 10.60.255.13), LEAF-4 (10.60.255.14), DC-CORE (10.60.255.20) and the firewall FW-1 (10.60.255.15). LEAF-3 uses the default OSPF priority on Vlan50. LEAF-4 loses power. What is the result once OSPF detects the failure?",
 ex:"LEAF-3# show ip ospf neighbor\n\nNeighbor ID     Pri   State           Dead Time   Address         Interface\n10.60.255.14    100   FULL/DR         00:00:35    10.60.50.4      Vlan50\n10.60.255.20     50   FULL/BDR        00:00:31    10.60.50.2      Vlan50\n10.60.255.15      1   2WAY/DROTHER    00:00:38    10.60.50.5      Vlan50",
 o:[
  {t:"DC-CORE becomes the DR, and FW-1 becomes the BDR",ok:true,x:"The BDR takes over as DR without a new DR election. A new BDR is then elected among the remaining eligible routers: LEAF-3 and FW-1 both have priority 1, so the higher router ID, 10.60.255.15, wins."},
  {t:"DC-CORE becomes the DR, and LEAF-3 becomes the BDR",ok:false,x:"LEAF-3 and FW-1 tie on priority 1, and the tie goes to the higher router ID. 10.60.255.15 is higher than 10.60.255.13, so FW-1 is the new BDR."},
  {t:"A complete new election runs, and LEAF-3 becomes the DR",ok:false,x:"OSPF promotes the existing BDR instead of re-electing the DR. Even in a fresh election, DC-CORE's priority of 50 would beat LEAF-3's priority of 1."},
  {t:"DC-CORE becomes the DR, and the BDR role stays empty until LEAF-4 returns and takes back the DR role",ok:false,x:"A new BDR is elected right away. DR/BDR elections are not preemptive, so when LEAF-4 returns with priority 100 it becomes a DROTHER rather than reclaiming the DR role."}
 ],
 w:"DR fails: the BDR is promoted, then a new BDR is elected by priority, then highest router ID. No preemption: a returning high-priority router waits as DROTHER until the next election."},
{id:"c054",obj:"4.2",d:4,cat:"svc",t:"mc",
 q:"Refer to the exhibit. 10.60.0.123 is the data center's GPS-disciplined time appliance. The leaf switches are configured with ntp server 10.60.255.20, DC-CORE's Loopback0 address, and no other NTP commands. After LEAF-1 synchronizes, which statement is true?",
 ex:"DC-CORE# show ntp associations\n\n  address         ref clock       st   when   poll reach  delay  offset   disp\n*~10.60.0.123     .GPS.            1     41     64   377  0.712   0.104  0.938\n * sys.peer, # selected, + candidate, - outlyer, x falseticker, ~ configured\n\nDC-CORE# show ntp status\nClock is synchronized, stratum 2, reference is 10.60.0.123",
 o:[
  {t:"LEAF-1 runs at stratum 3 and lists 10.60.255.20 as its sys.peer",ok:true,x:"Each NTP hop adds one to the stratum. The GPS appliance is stratum 1, DC-CORE learned from it and is stratum 2, so a leaf that learns from DC-CORE is stratum 3 with DC-CORE as its selected peer."},
  {t:"LEAF-1 runs at stratum 1, because its time ultimately comes from GPS",ok:false,x:"Stratum counts distance from the reference clock. Only a server attached directly to the reference (the appliance) is stratum 1."},
  {t:"LEAF-1 cannot synchronize until DC-CORE is configured with ntp master",ok:false,x:"A synchronized IOS device answers NTP clients on its own. ntp master would make DC-CORE trust its internal clock as a source, which is meant for networks with no upstream time."},
  {t:"LEAF-1 runs at stratum 2, because a client copies its server's stratum",ok:false,x:"A client never copies the server's stratum; it reports one higher than the source it synchronized to."}
 ],
 w:"NTP stratum = upstream stratum + 1 (GPS appliance 1, DC-CORE 2, leaves 3). A synchronized IOS client also serves time; ntp master is only for networks without an upstream source."},
{id:"c055",obj:"3.1.a",d:3,cat:"rtable",t:"ms",pick:2,
 q:"Refer to the exhibit. Which two statements about LEAF-2's routing table are true? (Choose two.)",
 ex:"LEAF-2# show ip route\nCodes: L - local, C - connected, S - static, O - OSPF\n       E2 - OSPF external type 2, * - candidate default\n\nGateway of last resort is 10.60.0.5 to network 0.0.0.0\n\nO*E2  0.0.0.0/0 [110/1] via 10.60.0.5, 00:12:34, TenGigabitEthernet1/0/1\n                [110/1] via 10.60.0.69, 00:12:34, TenGigabitEthernet1/0/2\n      10.0.0.0/8 is variably subnetted, 9 subnets, 3 masks\nC        10.60.0.4/30 is directly connected, TenGigabitEthernet1/0/1\nL        10.60.0.6/32 is directly connected, TenGigabitEthernet1/0/1\nC        10.60.0.68/30 is directly connected, TenGigabitEthernet1/0/2\nL        10.60.0.70/32 is directly connected, TenGigabitEthernet1/0/2\nO        10.60.40.0/24 [110/3] via 10.60.0.5, 00:12:34, TenGigabitEthernet1/0/1\n                       [110/3] via 10.60.0.69, 00:12:34, TenGigabitEthernet1/0/2\nC        10.60.41.0/24 is directly connected, Vlan41\nL        10.60.41.1/32 is directly connected, Vlan41\nS        10.60.99.0/24 [1/0] via 10.60.41.254\nO        10.60.250.0/30 [110/3] via 10.60.0.5, 00:12:34, TenGigabitEthernet1/0/1\n                        [110/3] via 10.60.0.69, 00:12:34, TenGigabitEthernet1/0/2",
 o:[
  {t:"Traffic to 10.60.40.0/24 is shared across both spine uplinks",ok:true,x:"The entry lists two next hops with the same metric (3), so OSPF installed both paths. IOS load-shares across equal-cost paths by default."},
  {t:"Traffic to 203.0.113.50 uses a default route that another router injected into OSPF",ok:true,x:"No specific route covers 203.0.113.50, so the gateway of last resort is used. O*E2 marks a candidate default learned through OSPF as an external type 2 route, which is what default-information originate on an edge router produces."},
  {t:"In [110/3], 110 is the OSPF cost and 3 is the hop count",ok:false,x:"The first number is the administrative distance (110 for OSPF); the second is the OSPF metric, a cost. OSPF does not track hop count."},
  {t:"The L entries are neighbors' addresses learned through ARP",ok:false,x:"L marks LEAF-2's own interface addresses as /32 local routes. ARP entries are never shown in the routing table."},
  {t:"Traffic to 10.60.99.20 follows the default route, because static routes are used only when OSPF has no route",ok:false,x:"10.60.99.0/24 is a static route that contains 10.60.99.20, and it is more specific than 0.0.0.0/0, so the static route is used. Static routes are not a fallback by nature."}
 ],
 w:"Read an entry left to right: code (O, O*E2, S, C, L), prefix/mask, [AD/metric], next hop, age, exit interface. Indented lines without a prefix are extra equal-cost next hops."},
{id:"c056",obj:"5.8",d:5,cat:"vpn",t:"mc",
 q:"Refer to the exhibit. The TACACS+ server 10.60.10.49 is up and reachable from DC-CORE. The security team has disabled the account jdoe on that server, but a local account jdoe with the same password still exists on DC-CORE. What happens when jdoe opens an SSH session to DC-CORE?",
 ex:"aaa new-model\n!\ntacacs server TACS-1\n address ipv4 10.60.10.49\n key 7 0822455D0A16\n!\naaa authentication login VTY-AUTH group tacacs+ local\n!\nusername jdoe privilege 15 secret 5 $1$Wq3d$eVSeArjeNa0S1HCF62lWIX\n!\nline vty 0 15\n login authentication VTY-AUTH\n transport input ssh",
 o:[
  {t:"The login fails, because the local database is used only when the TACACS+ server does not respond",ok:true,x:"A method list moves to the next method only on an error (no response). A reachable server that answers FAIL ends the process, so the local account is never checked."},
  {t:"The login succeeds, because DC-CORE falls back to the local database after TACACS+ rejects the user",ok:false,x:"This is the common misreading. A reject is a definitive answer, not an error, so IOS does not try the local method."},
  {t:"The login succeeds, because the vty lines ignore AAA when transport input ssh is configured",ok:false,x:"transport input only chooses which protocols the vty lines accept. login authentication VTY-AUTH applies to SSH sessions on those lines."},
  {t:"The login succeeds at user EXEC level, because TACACS+ rejects only the privilege level, not the user",ok:false,x:"The server disabled the account, so authentication itself fails. Privilege levels belong to authorization, which never starts here."}
 ],
 w:"AAA method lists fall through only when a server is unreachable (ERROR). A reject (FAIL) from a live server is final, so a local backup account cannot bypass a disabled central account."},
{id:"c057",obj:"3.5",d:3,cat:"fhrp",t:"mc",
 q:"Refer to the exhibit. LEAF-3 (10.60.30.2) and LEAF-4 (10.60.30.3) provide the default gateway 10.60.30.1 for the database servers in VLAN 30. How does server srv-db14 reach other subnets?",
 ex:"LEAF-3# show glbp brief\nInterface   Grp  Fwd Pri State    Address         Active router   Standby router\nVl30        3    -   150 Active   10.60.30.1      local           10.60.30.3\nVl30        3    1   -   Active   0007.b400.0301  local           -\nVl30        3    2   -   Listen   0007.b400.0302  10.60.30.3      -\n\nsrv-db14:~$ ip neigh show 10.60.30.1\n10.60.30.1 dev ens192 lladdr 00:07:b4:00:03:02 REACHABLE",
 o:[
  {t:"LEAF-4 forwards its traffic, because LEAF-4 owns the virtual MAC that LEAF-3 handed out in the ARP reply",ok:true,x:"LEAF-3 is the AVG (Active on the row without a forwarder number), so it answers ARP for 10.60.30.1. It gave srv-db14 the MAC of forwarder 2, 0007.b400.0302, and forwarder 2 is active on 10.60.30.3, LEAF-4."},
  {t:"LEAF-3 forwards its traffic, because LEAF-3 is the active router for the group",ok:false,x:"Active on the group row means LEAF-3 is the AVG, which answers ARP. Frames are forwarded by whichever AVF owns the destination MAC, and this server was given forwarder 2's MAC."},
  {t:"Its packets alternate between LEAF-3 and LEAF-4 one packet at a time",ok:false,x:"GLBP balances per host, through the MAC each host receives in its ARP reply. All of srv-db14's off-subnet frames go to one virtual MAC."},
  {t:"Its packets are dropped until it ARPs again, because forwarder 2 is in the Listen state",ok:false,x:"Listen is LEAF-3's view: it is the backup for forwarder 2. On LEAF-4 forwarder 2 is Active, so frames sent to 0007.b400.0302 are forwarded normally."}
 ],
 w:"GLBP: one virtual IP, several virtual MACs (0007.b400.GGFF: group, forwarder). The AVG answers ARP and spreads hosts across up to four AVFs, so both routers forward at once."},
{id:"c058",obj:"3.3.d",d:3,cat:"static",t:"mc",
 q:"Refer to the exhibit. The DR site, 10.70.0.0/16, is learned through OSPF over the data center interconnect. An engineer added a static route through DC-EDGE (10.60.250.5) to be used only if the OSPF route disappears. The interconnect is up, but DR-site traffic from DC-CORE now leaves through DC-EDGE. Which change fixes the problem?",
 ex:"DC-CORE# show running-config | include ip route\nip route 10.70.0.0 255.255.0.0 10.60.250.5 100\n\nDC-CORE# show ip route | include 10.70\nS        10.70.0.0/16 [100/0] via 10.60.250.5",
 o:[
  {t:"Configure the static route with an administrative distance greater than 110, such as 130",ok:true,x:"For the same prefix, IOS installs the source with the lowest AD. 100 is lower than OSPF's 110, so the static route wins today. A distance above 110 keeps it hidden until the OSPF route is withdrawn."},
  {t:"Remove the distance value so the static route uses its default AD",ok:false,x:"The default AD of a static route is 1, which beats OSPF even more decisively. The route would still be preferred."},
  {t:"Raise the OSPF cost on the interconnect so the static route is no longer preferred",ok:false,x:"OSPF cost is compared only between OSPF paths. The choice between a static route and an OSPF route for the same prefix is made on administrative distance."},
  {t:"Add the permanent keyword to the static route",ok:false,x:"permanent keeps a static route in the table even when its exit interface goes down. It does nothing to make the route a backup."}
 ],
 w:"Floating static = same prefix, AD set above the dynamic source: above 110 to back up OSPF, above 90 for EIGRP. An AD below 110 silently overrides OSPF."},
{id:"c059",obj:"4.7",d:4,cat:"qos",t:"mc",
 q:"Refer to the exhibit. Ops-floor calls and video meetings to the DR site cross DC-EDGE's WAN link on Gi0/3. Which statement describes how DC-EDGE treats this traffic while the link is congested?",
 ex:"class-map match-any VOICE\n match dscp ef\nclass-map match-any VIDEO\n match dscp af41\n!\npolicy-map DC-EDGE-WAN\n class VOICE\n  priority percent 10\n class VIDEO\n  bandwidth percent 30\n class class-default\n  fair-queue\n!\ninterface GigabitEthernet0/3\n description WAN to DR site\n service-policy output DC-EDGE-WAN",
 o:[
  {t:"EF voice is sent first from a strict-priority queue, but voice above 10% of the link is dropped while congestion lasts",ok:true,x:"priority creates a low-latency queue that is always serviced first. During congestion IOS polices that queue to the configured rate so voice cannot starve the other classes."},
  {t:"AF41 video gets strict priority up to 30%, and voice waits behind it",ok:false,x:"bandwidth gives a class-based weighted fair queue with a minimum guarantee, not strict priority. Only the class with priority is served ahead of everything else."},
  {t:"The policy marks voice as EF and video as AF41 as they leave Gi0/3",ok:false,x:"match dscp classifies packets that already carry those markings. Re-marking would need set dscp under a class."},
  {t:"Video is capped at exactly 30% of the link even when other classes are idle",ok:false,x:"bandwidth is a minimum guarantee under congestion. Video can use idle bandwidth that other classes leave unused."}
 ],
 w:"LLQ: priority = strict queue for voice, policed to its rate only under congestion. bandwidth = CBWFQ minimum guarantee. match classifies; set marks."},
{id:"c060",obj:"5.6",d:5,cat:"acl",t:"mc",
 q:"Refer to the exhibit. Which administrator workstation can open a management session to DC-CORE?",
 ex:"DC-CORE# show access-lists VTY-MGMT\nStandard IP access list VTY-MGMT\n    10 permit 10.60.20.0, wildcard bits 0.0.1.255\n    20 deny   any log\n\nDC-CORE# show running-config | section line vty\nline vty 0 4\n access-class VTY-MGMT in\n login local\n transport input ssh\nline vty 5 15\n access-class VTY-MGMT in\n login local\n transport input ssh",
 o:[
  {t:"10.60.21.200, using SSH",ok:true,x:"Wildcard 0.0.1.255 leaves the last bit of the third octet free, so entry 10 matches 10.60.20.0 through 10.60.21.255. The vty lines accept SSH, so this session is allowed."},
  {t:"10.60.22.15, using SSH",ok:false,x:"10.60.22.x is outside the 10.60.20.0/23 range that 0.0.1.255 covers, so entry 20 denies and logs the attempt."},
  {t:"10.60.20.33, using Telnet",ok:false,x:"The source address is permitted, but transport input ssh makes the vty lines refuse Telnet."},
  {t:"10.60.19.240, using SSH",ok:false,x:"The block starts at 10.60.20.0. 10.60.19.240 falls below it and is denied by entry 20."}
 ],
 w:"access-class filters who may reach the vty lines, whatever device address they target. Wildcard 0.0.1.255 = a /23 (two third-octet values). transport input decides SSH vs Telnet."},
{id:"c061",obj:"3.4.a",d:3,cat:"ospf",t:"mc",
 q:"Refer to the exhibit. During a jumbo-frame rollout, LEAF-1's uplinks were reconfigured. The adjacency with SPINE-2 has been in this state for ten minutes. Which action resolves the problem?",
 ex:"LEAF-1# show ip ospf neighbor\n\nNeighbor ID     Pri   State           Dead Time   Address         Interface\n10.60.255.1       0   FULL/  -        00:00:34    10.60.0.1       TenGigabitEthernet1/0/1\n10.60.255.2       0   EXSTART/  -     00:00:37    10.60.0.65      TenGigabitEthernet1/0/2\n\nLEAF-1# show ip interface TenGigabitEthernet1/0/2 | include MTU\n  MTU is 9000 bytes\nSPINE-2# show ip interface TenGigabitEthernet1/0/1 | include MTU\n  MTU is 1500 bytes",
 o:[
  {t:"Make the IP MTU the same on both ends of the LEAF-1 to SPINE-2 link",ok:true,x:"OSPF puts the interface MTU in its database description packets. A router rejects DBDs that advertise a larger MTU than its own, so the pair never finishes EXSTART/EXCHANGE until the MTUs match."},
  {t:"Set the OSPF priority to 1 on both ends so that a DR can be elected",ok:false,x:"The links are point-to-point (state FULL/ -), where no DR is elected and priority 0 is normal. The healthy SPINE-1 adjacency shows the same values."},
  {t:"Make the hello and dead timers match on both ends",ok:false,x:"With mismatched timers the hellos would be ignored and SPINE-2 would not appear in the table at all. Reaching EXSTART proves the hello parameters agree."},
  {t:"Configure a unique router ID on SPINE-2",ok:false,x:"The neighbor IDs 10.60.255.1 and 10.60.255.2 are different from each other and from LEAF-1. Nothing here points to a duplicate router ID."}
 ],
 w:"Stuck in EXSTART/EXCHANGE = MTU mismatch (fix the MTU, or ip ospf mtu-ignore as a workaround). Missing entirely = hello/dead, area, subnet or authentication mismatch."},
{id:"c062",obj:"3.2.a",d:3,cat:"rtable",t:"ms",pick:2,
 q:"Refer to the exhibit. 2001:DB8:60:FFF1::2 is SPINE-1 and 2001:DB8:60:FFF2::2 is SPINE-2. Which two destination addresses does DC-CORE forward to SPINE-1? (Choose two.)",
 ex:"DC-CORE# show ipv6 route static\nIPv6 Routing Table - default - 11 entries\nCodes: C - Connected, L - Local, S - Static\n\nS   ::/0 [1/0]\n     via 2001:DB8:60:FFFF::1\nS   2001:DB8:60::/48 [1/0]\n     via 2001:DB8:60:FFF2::2\nS   2001:DB8:60:40::/62 [1/0]\n     via 2001:DB8:60:FFF1::2\nS   2001:DB8:60:41::/64 [1/0]\n     via 2001:DB8:60:FFF2::2",
 o:[
  {t:"2001:db8:60:40::25",ok:true,x:"A /62 fixes the first 14 bits of the fourth hextet, so 2001:DB8:60:40::/62 covers 40, 41, 42 and 43. Hextet 40 matches the /62, and only the /48 and default also match, so SPINE-1 is used."},
  {t:"2001:db8:60:43:a::1",ok:true,x:"Hextet 43 is the last block inside the /62, and no /64 is more specific for it. The /62 is the longest match, so the packet goes to SPINE-1."},
  {t:"2001:db8:60:41::25",ok:false,x:"This address matches the /62, but 2001:DB8:60:41::/64 is longer and points to SPINE-2."},
  {t:"2001:db8:60:4::25",ok:false,x:"The fourth hextet is 0004, not 0040; leading zeros are what was omitted. 0004 is outside 40 to 43, so only the /48 matches and the packet goes to SPINE-2."},
  {t:"2001:db8:60:44::25",ok:false,x:"Hextet 44 is one past the /62 range (40 to 43). The /48 is the longest match, so the packet goes to SPINE-2."},
  {t:"2001:db8:61:40::25",ok:false,x:"The third hextet is 61, so the address is outside 2001:DB8:60::/48 entirely. Only the default route matches, toward 2001:DB8:60:FFFF::1."}
 ],
 w:"IPv6 longest match works like IPv4: expand the hextets (leading zeros are dropped, 4 means 0004), work out the range each prefix covers, then take the longest one that contains the address."},
{id:"c063",obj:"5.1",d:5,cat:"secbase",t:"mc",
 q:"An ops-team review of the leaf switches records three items: (1) the out-of-band management firmware has a flaw that lets a crafted request skip the login check; (2) a ransomware group is known to scan data centers for this flaw; (3) a public script automates sending the crafted request. How should the three items be classified?",
 o:[
  {t:"(1) vulnerability, (2) threat, (3) exploit",ok:true,x:"The flaw is a weakness in the system (vulnerability). The group with intent and capability to use it is the threat. The script that turns the weakness into access is the exploit."},
  {t:"(1) exploit, (2) threat, (3) vulnerability",ok:false,x:"This reverses items 1 and 3. A flaw that exists in the firmware is a vulnerability; the tool that takes advantage of it is the exploit."},
  {t:"(1) threat, (2) vulnerability, (3) exploit",ok:false,x:"A ransomware group is an actor, not a weakness, so it cannot be a vulnerability. The firmware flaw is the vulnerability."},
  {t:"(1) vulnerability, (2) exploit, (3) mitigation",ok:false,x:"A mitigation reduces risk, such as patching or restricting management access. A script that sends the attack request does the opposite; it is the exploit."}
 ],
 w:"Vulnerability = the weakness. Threat = who or what could use it. Exploit = the method or code that uses it. Mitigation = what reduces the risk (patch, ACL, out-of-band isolation)."},
{id:"c064",obj:"3.4",d:3,cat:"ospf",t:"mc",
 q:"Refer to the exhibit. Traffic from DC-CORE to the LEAF-4 server LAN takes the 1-Gb/s link instead of the 10-Gb/s path through the spines. Why does OSPF choose this path?",
 ex:"Topology (all links in OSPF area 0, default OSPF settings):\n  DC-CORE Te1/0/1 --10G-- SPINE-1 --10G-- Te1/0/1 LEAF-4\n  DC-CORE Te1/0/2 --10G-- SPINE-2 --10G-- Te1/0/2 LEAF-4\n  DC-CORE Gi1/0/3 -----------1G----------- Gi1/0/3 LEAF-4\n  LEAF-4 Gi1/0/1: server LAN 10.60.43.0/24 (1G)\n\nDC-CORE# show ip route ospf | include 10.60.43\nO        10.60.43.0/24 [110/2] via 10.60.0.122, 00:12:34, GigabitEthernet1/0/3",
 o:[
  {t:"The default 100-Mb/s reference bandwidth makes 1G and 10G links both cost 1, so the direct path (2) beats the spine path (3)",ok:true,x:"Cost = reference / interface bandwidth, rounded down, minimum 1. Every interface of 100 Mb/s or faster costs 1, so OSPF cannot tell 1G from 10G. Two interfaces on the direct path cost 2; three on the spine path cost 3."},
  {t:"OSPF prefers GigabitEthernet ports because they have a lower administrative distance",ok:false,x:"AD belongs to the route source (OSPF is 110 for every OSPF route), not to interface types. All candidate paths here are OSPF paths."},
  {t:"OSPF counts hops rather than bandwidth, so the direct link always wins",ok:false,x:"OSPF adds interface costs. It only looks like hop count here because every cost is 1; with a reference bandwidth above 10 Gb/s the spine path would win."},
  {t:"The spine path has a different cost, and OSPF uses unequal paths only when variance is configured",ok:false,x:"variance is an EIGRP feature. OSPF installs only the lowest-cost path (or several equal ones); the spine path loses because its total cost is higher."}
 ],
 w:"Default OSPF reference bandwidth is 100 Mb/s: Fa, Gi and Te all cost 1. In fabrics with 10G or faster links, raise auto-cost reference-bandwidth on every router so cost reflects speed."},
{id:"c065",obj:"4.4",d:4,cat:"mon",t:"mc",
 q:"Refer to the exhibit. The commands were entered on DC-CORE so that the NMS at 10.60.10.25 can poll it and receive its notifications. Which statement is true?",
 ex:"snmp-server view OPS-VIEW iso included\nsnmp-server group OPS-RO v3 priv read OPS-VIEW\nsnmp-server user nms01 OPS-RO v3 auth sha N0c-Auth-26 priv aes 128 N0c-Priv-26\nsnmp-server host 10.60.10.25 version 3 priv nms01\nsnmp-server enable traps",
 o:[
  {t:"SNMP messages between DC-CORE and the NMS are authenticated with SHA and encrypted with AES-128",ok:true,x:"The v3 group uses the priv security level (authPriv), and user nms01 has both an auth (SHA) and a priv (AES 128) password. Polls and notifications are therefore both authenticated and encrypted."},
  {t:"nms01 works as a community string and is sent in clear text",ok:false,x:"Community strings belong to SNMPv1 and v2c. In SNMPv3, nms01 is a user name, and its authentication and privacy keys protect the messages."},
  {t:"The NMS can change DC-CORE's configuration with SNMP set requests",ok:false,x:"The group grants only a read view. Without a write view, set requests are refused."},
  {t:"Messages are authenticated but not encrypted, because priv applies only to notifications",ok:false,x:"priv is a security level for the whole exchange, polls included. Authentication without encryption is the auth level (authNoPriv)."}
 ],
 w:"SNMPv3 levels: noAuthNoPriv (user name only), authNoPriv (HMAC, e.g. SHA), authPriv (HMAC plus encryption, e.g. AES). v1/v2c communities are clear text."},
{id:"c066",obj:"3.4.b",d:3,cat:"ospf",t:"build",ordered:true,
 q:"SPINE-1 Te1/0/4 already runs OSPF process 1, area 0, as a point-to-point network. On LEAF-4, starting in global configuration mode, set the router ID to 10.60.255.14 and enable OSPF on uplink Te1/0/1 with interface-level commands (no network statements) so it goes FULL with SPINE-1 without a DR/BDR election. Drag the commands into the answer area in order. Leave the commands that are not needed.",
 pool:["router ospf 1","router-id 10.60.255.14","interface TenGigabitEthernet1/0/1","ip ospf 1 area 0","ip ospf network point-to-point","ip ospf priority 255","network 10.60.0.12 0.0.0.3 area 0","ip ospf 1 area 1"],
 answer:[0,1,2,3,4],
 alt:[[0,1,2,4,3],[2,3,4,0,1],[2,4,3,0,1]],
 x:"router-id sets the requested ID under the process. ip ospf 1 area 0 on the interface enables OSPF there without a network statement, and ip ospf network point-to-point matches SPINE-1 so no DR/BDR is elected and the neighbor shows FULL/ -. The two interface commands may come in either order, and the interface block may be entered before the process block. Priority is irrelevant on a point-to-point link, area 1 breaks single-area OSPF, and the network statement is excluded by the task.",
 w:"Interface-level OSPF: ip ospf <process> area <area>. Point-to-point network type on both ends of a two-router Ethernet link: no DR/BDR, faster adjacency, neighbor shown as FULL/ -."},
{id:"c067",obj:"5.9",d:5,cat:"wsec",t:"ms",pick:2,
 q:"The ops-floor WLAN is moving from WPA2-Enterprise to WPA3-Enterprise. Which two statements about WPA3-Enterprise are true? (Choose two.)",
 o:[
  {t:"Users still authenticate individually through 802.1X/EAP against a RADIUS server",ok:true,x:"Enterprise mode, in WPA2 and WPA3 alike, means per-user 802.1X authentication, with the AP or WLC acting as authenticator toward a RADIUS server."},
  {t:"Protected Management Frames are mandatory",ok:true,x:"WPA3 requires PMF (802.11w), which protects deauthentication and disassociation frames from being forged to kick users off."},
  {t:"Clients authenticate with SAE using a passphrase shared by all users",ok:false,x:"SAE replaces the PSK exchange in WPA3-Personal. Enterprise mode uses 802.1X, not a shared passphrase."},
  {t:"TKIP remains available for older ops-floor clients",ok:false,x:"WPA3 does not allow TKIP. Clients that cannot do WPA3 have to stay on a separate WPA2 WLAN or use a transition mode."},
  {t:"The 192-bit security mode must be used on every WPA3-Enterprise network",ok:false,x:"The 192-bit (CNSA) mode is an optional, stricter profile for high-security networks. Standard WPA3-Enterprise does not require it."}
 ],
 w:"WPA3-Personal = SAE with a passphrase. WPA3-Enterprise = 802.1X/EAP with optional 192-bit mode. Both require PMF and drop TKIP."},
{id:"c068",obj:"3.2.b",d:3,cat:"rtable",t:"mc",
 q:"Refer to the exhibit. To push traffic for the server 10.60.42.50 (on LEAF-3) through SPINE-2 only, an engineer added the static route shown. 10.60.0.33 is SPINE-1 and 10.60.0.97 is SPINE-2. Which path does DC-CORE now use for 10.60.42.50?",
 ex:"DC-CORE# show running-config | include ip route\nip route 10.60.42.0 255.255.254.0 10.60.0.97\n\nDC-CORE# show ip route\n<output omitted>\nS        10.60.42.0/23 [1/0] via 10.60.0.97\nO        10.60.42.0/24 [110/3] via 10.60.0.33, 00:12:34, TenGigabitEthernet1/0/1\n                       [110/3] via 10.60.0.97, 00:12:34, TenGigabitEthernet1/0/2",
 o:[
  {t:"Both spines, through the OSPF /24, because it is a longer match than the static /23",ok:true,x:"The /23 and the /24 are different prefixes, so both are installed. For 10.60.42.50 the /24 is the longer match and wins, and it has two equal-cost next hops."},
  {t:"SPINE-2 only, because the static route's AD of 1 beats OSPF's 110",ok:false,x:"AD only decides between sources offering the identical prefix and mask. A /23 and a /24 are not the same prefix, so prefix length decides first."},
  {t:"SPINE-1 only, because the first next hop listed is the active path",ok:false,x:"Both next hops under the /24 are installed and used for load sharing. Their order in the output does not make one of them a backup."},
  {t:"Neither; IOS rejects overlapping static and OSPF routes, so the default route is used",ok:false,x:"Overlapping prefixes of different lengths are normal and coexist in the table. That is what makes longest-prefix matching necessary."}
 ],
 w:"To steer a destination with a static route, match or beat the dynamic prefix length (here a /24, or a /32 host route). AD never overrides a longer match."},
{id:"c069",obj:"3.4.d",d:3,cat:"ospf",t:"mc",
 q:"Refer to the exhibit. LEAF-2 was just reloaded with this configuration, and all of its interfaces are up. Which router ID does OSPF process 1 use?",
 ex:"LEAF-2# show running-config | section interface|router ospf\ninterface Loopback0\n ip address 10.60.255.12 255.255.255.255\ninterface TenGigabitEthernet1/0/1\n no switchport\n ip address 10.60.0.6 255.255.255.252\ninterface TenGigabitEthernet1/0/2\n no switchport\n ip address 10.60.0.70 255.255.255.252\ninterface Vlan41\n ip address 10.60.41.1 255.255.255.0\nrouter ospf 1\n network 10.60.0.0 0.0.0.255 area 0\n network 10.60.41.0 0.0.0.255 area 0",
 o:[
  {t:"10.60.255.12",ok:true,x:"With no router-id command, IOS takes the highest IP address on an up loopback interface. The loopback does not have to be advertised in OSPF to be chosen."},
  {t:"10.60.41.1, because Loopback0 is not covered by any network statement",ok:false,x:"Router ID selection looks at interface addresses, not at which interfaces run OSPF. A loopback always beats non-loopback interfaces when no ID is configured."},
  {t:"10.60.0.70, the highest address on an OSPF-enabled physical interface",ok:false,x:"Physical interfaces are considered only when no loopback is up, and even then the highest active address (10.60.41.1 here) would be chosen."},
  {t:"None; OSPF does not start until a router-id command is entered",ok:false,x:"IOS chooses an ID on its own as long as some interface has an IPv4 address that is up. The process starts without manual configuration."}
 ],
 w:"OSPF router ID order: router-id command, then highest up loopback, then highest up non-loopback address. A loopback used as the RID need not be advertised."},
{id:"c070",obj:"4.1",d:4,cat:"nat",t:"mc",
 q:"Refer to the exhibit. Which statement is true?",
 ex:"DC-EDGE# show running-config | include ip nat\n ip nat outside\n ip nat inside\nip nat pool OPS-POOL 203.0.113.33 203.0.113.38 netmask 255.255.255.248\nip nat inside source list 20 pool OPS-POOL\nip nat inside source static 10.60.42.80 203.0.113.80\n\nDC-EDGE# show ip nat translations\nPro  Inside global      Inside local       Outside local      Outside global\ntcp  203.0.113.80:443   10.60.42.80:443    192.0.2.7:51544    192.0.2.7:51544\n---  203.0.113.80       10.60.42.80        ---                ---\nicmp 203.0.113.33:7     10.60.20.41:7      192.0.2.10:7       192.0.2.10:7\n---  203.0.113.33       10.60.20.41        ---                ---",
 o:[
  {t:"Ops host 10.60.20.41 was given 203.0.113.33 from OPS-POOL, and no other inside host can use that address meanwhile",ok:true,x:"The pool rule has no overload keyword, so it is one-to-one dynamic NAT. Each inside host holds one pool address for as long as its translation exists."},
  {t:"192.0.2.7 is the inside global address of the web server",ok:false,x:"192.0.2.7 is an internet client, so it appears in the outside columns. The web server's inside global address is 203.0.113.80."},
  {t:"Up to six ops hosts can share 203.0.113.33 at the same time, because the pool translates ports",ok:false,x:"Port translation (PAT) needs the overload keyword. Without it the six pool addresses serve at most six inside hosts at a time."},
  {t:"The web server is reachable from the internet only after it first sends traffic outbound",ok:false,x:"A static translation is permanent and works in both directions, as the --- entry shows. Inbound HTTPS works without any outbound traffic first."}
 ],
 w:"Inside local = real inside address; inside global = what the internet sees. Static NAT is permanent and two-way; a pool without overload is one-to-one; add overload for PAT."},
{id:"c071",obj:"5.6",d:5,cat:"acl",t:"mc",
 q:"Refer to the exhibit. ACL 120 is applied inbound on DC-CORE's fabric uplinks to protect its management address 10.60.255.20. The new NMS at 10.60.10.25 must poll DC-CORE with SNMP (UDP 161). Which configuration meets the requirement without changing the other entries?",
 ex:"DC-CORE# show access-lists 120\nExtended IP access list 120\n    10 permit tcp 10.60.20.0 0.0.0.255 host 10.60.255.20 eq 22 (41 matches)\n    20 deny ip any host 10.60.255.20 log (17 matches)\n    30 permit ip any any (90211 matches)",
 o:[
  {t:"ip access-list extended 120, then 15 permit udp host 10.60.10.25 host 10.60.255.20 eq snmp",ok:true,x:"Numbered ACLs can be edited in named-ACL mode. Sequence 15 lands between the SSH permit and the deny, so SNMP from the NMS is matched before entry 20 can drop it."},
  {t:"access-list 120 permit udp host 10.60.10.25 host 10.60.255.20 eq snmp",ok:false,x:"A new numbered entry is appended to the end (sequence 40). Entry 20 already denies everything to 10.60.255.20, so the permit would never be reached."},
  {t:"ip access-list extended 120, then 25 permit udp host 10.60.10.25 host 10.60.255.20 eq snmp",ok:false,x:"Sequence 25 sits after the deny on line 20. First match wins, so the SNMP polls are still dropped."},
  {t:"ip access-list extended 120, then 15 permit udp host 10.60.255.20 eq snmp host 10.60.10.25",ok:false,x:"This matches packets from DC-CORE's port 161 to the NMS, the replies rather than the polls. The incoming poll has the NMS as source and port 161 as destination."}
 ],
 w:"ACLs are first-match. To slot an entry above an existing deny, enter the ACL in named mode and give it a sequence number between the two lines."},
{id:"c072",obj:"3.5",d:3,cat:"fhrp",t:"mc",
 q:"Refer to the exhibit. The default gateway of application server srv-app07 is 10.60.31.1, a virtual address shared by LEAF-3 and LEAF-4. Which first hop redundancy configuration does the server's ARP entry indicate?",
 ex:"srv-app07:~$ ip neigh show 10.60.31.1\n10.60.31.1 dev ens192 lladdr 00:00:0c:07:ac:1f REACHABLE",
 o:[
  {t:"HSRP version 1, group 31",ok:true,x:"HSRPv1 virtual MACs are 0000.0C07.ACxx, where xx is the group number in hex. 0x1F is 31."},
  {t:"HSRP version 2, group 31",ok:false,x:"HSRPv2 uses 0000.0C9F.F000 to 0000.0C9F.FFFF, so group 31 would appear as 00:00:0c:9f:f0:1f."},
  {t:"VRRP, group 31",ok:false,x:"VRRP virtual MACs are 0000.5E00.01xx, so group 31 would be 00:00:5e:00:01:1f."},
  {t:"GLBP, group 31",ok:false,x:"GLBP virtual MACs start with 0007.B400, followed by the group and the forwarder number."}
 ],
 w:"Know the virtual MACs: HSRPv1 0000.0C07.ACxx, HSRPv2 0000.0C9F.Fxxx, VRRP 0000.5E00.01xx, GLBP 0007.B400.xxyy. The last digits give the group (and GLBP forwarder) in hex."},
{id:"c073",obj:"3.3.b",d:3,cat:"static",t:"mc",
 q:"Refer to the exhibit. The new test lab behind LAB-R1 (10.60.250.10) uses 10.60.128.0 through 10.60.143.255. From the data center, hosts at 10.60.130.5 are reachable but hosts at 10.60.137.20 are not. Which change on DC-CORE fixes the problem?",
 ex:"DC-CORE# show ip route static\n<output omitted>\n      10.0.0.0/8 is variably subnetted, 24 subnets, 4 masks\nS        10.60.128.0/21 [1/0] via 10.60.250.10",
 o:[
  {t:"Replace the route with ip route 10.60.128.0 255.255.240.0 10.60.250.10",ok:true,x:"128 through 143 is 16 third-octet values, a /20 (255.255.240.0). The current /21 covers only 128 through 135, which is why 10.60.137.20 is unreachable."},
  {t:"Replace the route with ip route 10.60.128.0 0.0.15.255 10.60.250.10",ok:false,x:"ip route takes a subnet mask, not a wildcard mask. IOS rejects 0.0.15.255 as an inconsistent address and mask."},
  {t:"Replace the route with ip route 10.60.128.0 255.255.252.0 10.60.250.10",ok:false,x:"255.255.252.0 is a /22 that covers only 128 through 131. Even 10.60.130.5 would keep working, but most of the lab would not."},
  {t:"Replace the route with ip route 10.60.128.0 255.255.248.0 10.60.250.10 2",ok:false,x:"Changing the AD does not change what the route covers. The /21 still stops at 10.60.135.255."}
 ],
 w:"Size the mask from the range: 16 consecutive third-octet values starting on a multiple of 16 = /20 (255.255.240.0). Static routes take a subnet mask, never a wildcard."},
{id:"c074",obj:"5.8",d:5,cat:"vpn",t:"order",
 q:"Refer to the exhibit. An administrator opens an SSH session to DC-CORE and enters a configuration command. The TACACS+ server is reachable. Drag the events into the order in which they occur.",
 ex:"aaa new-model\naaa authentication login default group tacacs+ local\naaa authorization exec default group tacacs+ local\naaa authorization commands 15 default group tacacs+ local\naaa accounting commands 15 default stop-only group tacacs+",
 pool:["TACACS+ authorizes the EXEC session and returns the privilege level","DC-CORE runs the command and sends a stop accounting record for it","The SSH session reaches a vty line on DC-CORE","DC-CORE asks TACACS+ to authorize the command before running it","DC-CORE sends the username and password to TACACS+ for authentication"],
 answer:[2,4,0,3,1],
 x:"The session must land on a vty line before the login prompt appears. Authentication proves who the user is; EXEC authorization then decides whether a shell starts and at what privilege level. Each level-15 command is authorized before it runs, and the stop-only accounting record is sent after it has run.",
 w:"AAA order: authenticate (who are you), authorize (what may you do: EXEC, then each command), account (what did you do). TACACS+ handles each step separately, which allows per-command control."},
{id:"c075",obj:"3.4.a",d:3,cat:"ospf",t:"ms",pick:2,
 q:"Refer to the exhibit. LEAF-3 and SPINE-1 do not form an OSPF adjacency, although each can ping the other. Which two configuration differences prevent the adjacency? (Choose two.)",
 ex:"LEAF-3# show running-config interface TenGigabitEthernet1/0/1\ninterface TenGigabitEthernet1/0/1\n no switchport\n ip address 10.60.0.10 255.255.255.248\n ip ospf 2 area 1\n ip ospf cost 5\n\nSPINE-1# show running-config interface TenGigabitEthernet1/0/3\ninterface TenGigabitEthernet1/0/3\n no switchport\n ip address 10.60.0.9 255.255.255.252\n ip ospf priority 50\n ip ospf 1 area 0",
 o:[
  {t:"The subnet masks differ (/29 on LEAF-3, /30 on SPINE-1)",ok:true,x:"On a broadcast network (the default for Ethernet), hellos carry the subnet mask, and both ends must agree. The pings work because each address falls inside the other's subnet, but OSPF ignores the hellos."},
  {t:"The interfaces are in different OSPF areas (1 on LEAF-3, 0 on SPINE-1)",ok:true,x:"The area ID is carried in every OSPF packet, and both ends of a link must be in the same area. LEAF-3 belongs in area 0 in this single-area design."},
  {t:"The OSPF process IDs differ (2 on LEAF-3, 1 on SPINE-1)",ok:false,x:"The process ID is only locally significant and is never sent in hellos. Routers with different process numbers form adjacencies normally."},
  {t:"The interface costs differ (5 on LEAF-3, default on SPINE-1)",ok:false,x:"Cost is applied only to the sending side's outgoing interface and is not checked between neighbors. Different costs just make routing asymmetric."},
  {t:"SPINE-1 has priority 50 and LEAF-3 has the default of 1",ok:false,x:"Priority only influences the DR/BDR election. Neighbors with different priorities still become adjacent."}
 ],
 w:"Must match for OSPF neighbors: area, subnet and mask (on broadcast links), hello/dead timers, authentication, stub flags; MTU must match to finish the DBD exchange. Need not match: process ID, cost, priority."}
,
{id:"c076",obj:"4.5",d:4,cat:"mon",t:"ms",pick:3,
 q:"Refer to the exhibit. The message was generated on DC-CORE. Which three statements are true? (Choose three.)",
 ex:"DC-CORE# show running-config | include logging|timestamps\nservice timestamps log datetime msec\nlogging trap notifications\nlogging host 10.60.20.50\n\n*Oct  3 14:02:11.417: %LINEPROTO-5-UPDOWN: Line protocol on Interface\n TenGigabitEthernet1/0/2, changed state to down",
 o:[
  {t:"The message has severity level 5, notifications",ok:true,x:"The number in the FACILITY-SEVERITY-MNEMONIC tag is the severity. Level 5 is notifications: normal but significant events such as a line protocol change."},
  {t:"LINEPROTO is the facility, the part of IOS that generated the message",ok:true,x:"The first field of the tag names the facility, here the line-protocol process. Other common facilities are LINK, OSPF, SYS and SEC."},
  {t:"DC-CORE sends the message to the collector at 10.60.20.50",ok:true,x:"logging trap notifications sends levels 0 through 5 to every logging host. Level 5 is included."},
  {t:"UPDOWN is the severity keyword",ok:false,x:"UPDOWN is the mnemonic, a short code for the specific event. The severity is the number 5 in the middle of the tag."},
  {t:"The collector would receive the message only if logging trap were set to debugging",ok:false,x:"The trap level is a ceiling: the configured level and everything more severe are sent. Debugging (7) would also include it, but notifications (5) already does."},
  {t:"The timestamp shows how long DC-CORE has been up",ok:false,x:"service timestamps log datetime msec stamps messages with the date and time. Uptime stamps come from the uptime keyword instead."}
 ],
 w:"%FACILITY-SEVERITY-MNEMONIC: 0 emergencies, 1 alerts, 2 critical, 3 errors, 4 warnings, 5 notifications, 6 informational, 7 debugging. logging trap N sends N and lower numbers."},
{id:"c077",obj:"3.2.a",d:3,cat:"rtable",t:"order",
 q:"DC-EDGE has the six routes below, and every one of them matches 10.60.41.10. Drag the routes into the order DC-EDGE would use them for a packet to 10.60.41.10: first the route used now, then the route it would use if that one were removed, and so on.",
 pool:["S* 0.0.0.0/0 [1/0]","O 10.60.40.0/22 [110/3]","S 10.60.41.10/32 [1/0]","S 10.0.0.0/8 [1/0]","O 10.60.41.0/25 [110/12]","S 10.60.0.0/16 [1/0]"],
 answer:[2,4,1,5,3,0],
 x:"Every route contains 10.60.41.10, so the choice is made purely on prefix length: /32 host route, then /25 (10.60.41.0 to .127), /22, /16, /8, and the default route last. The AD and metric values never come into play, because no two routes share the same prefix and mask.",
 w:"Longest prefix wins, regardless of route source. The default route (/0) is always the last resort."},
{id:"c078",obj:"5.3",d:5,cat:"secbase",t:"mc",
 q:"Refer to the exhibit. Which statement about access to DC-CORE is true?",
 ex:"DC-CORE# show running-config | include enable|username\nenable secret 5 $1$mERr$eVSeArjeNa0S1HCF62lWIX\nenable password Ops-Legacy1\nusername opsadmin privilege 15 secret 5 $1$k7Qa$.VSegrjGN40S1HiF62l0IX\nusername auditor secret 5 $1$Zt2p$GVSeArjeNa0S1HCF62lWIX\n\nDC-CORE# show running-config | section line\nline con 0\n login local\nline vty 0 4\n login local\n transport input ssh\nline vty 5 15\n login local\n transport input ssh",
 o:[
  {t:"auditor lands in user EXEC and must enter the enable secret, not Ops-Legacy1, to reach privileged EXEC",ok:true,x:"auditor has the default privilege level 1. When both enable secret and enable password exist, IOS uses only the enable secret; the enable password is ignored."},
  {t:"Ops-Legacy1 is accepted at the enable prompt, because enable password is checked before enable secret",ok:false,x:"The opposite is true: a configured enable secret always overrides the enable password, which is why legacy enable passwords should be removed."},
  {t:"The console accepts no logins, because no line password is configured under line con 0",ok:false,x:"login local makes the console prompt for a username and password from the local database, so no line password is needed."},
  {t:"opsadmin must enter the enable secret after logging in over SSH to reach privileged EXEC",ok:false,x:"With login local, a user defined with privilege 15 is placed directly in privileged EXEC at login."}
 ],
 w:"enable secret (hashed) overrides enable password (clear text or weak type 7). login local uses usernames, and a user's privilege level decides where they land after login."},
{id:"c079",obj:"3.2.c",d:3,cat:"rtable",t:"mc",
 q:"Refer to the exhibit. SPINE-2 is being drained for a software upgrade, so an engineer enters ip ospf cost 5 on DC-CORE Te1/0/2. Every other interface keeps the default cost of 1. What is the result for traffic from DC-CORE to 10.60.40.0/24?",
 ex:"DC-CORE# show ip route ospf\n<output omitted>\nO        10.60.40.0/24 [110/3] via 10.60.0.33, 00:12:34, TenGigabitEthernet1/0/1\n                       [110/3] via 10.60.0.97, 00:12:34, TenGigabitEthernet1/0/2",
 o:[
  {t:"Only the path through SPINE-1 (10.60.0.33) stays installed, with a metric of 3",ok:true,x:"The SPINE-1 path still costs 1 + 1 + 1 = 3. Through SPINE-2 it becomes 5 + 1 + 1 = 7. OSPF installs only the lowest-cost path, so the SPINE-2 entry is removed."},
  {t:"Both paths stay installed, and traffic is weighted roughly 5:1 toward SPINE-1",ok:false,x:"OSPF load-shares only across paths with exactly equal cost. It has no unequal-cost load balancing."},
  {t:"Only the path through SPINE-2 (10.60.0.97) stays installed, with a metric of 7",ok:false,x:"A higher cost makes a path less preferred, not more. The cost-3 path through SPINE-1 wins."},
  {t:"Both paths stay listed, with the SPINE-2 path marked as a backup with a metric of 7",ok:false,x:"The routing table holds only the best OSPF paths. The cost-7 path stays in the OSPF database and is installed only if the SPINE-1 path fails."}
 ],
 w:"ECMP needs identical total costs. Raising cost on one uplink (on the sending router's outgoing interface) drains it for traffic leaving that router; traffic toward it is governed by the far end's costs."},
{id:"c080",obj:"3.1.g",d:3,cat:"rtable",t:"mc",
 q:"Refer to the exhibit. The leaf switches normally reach the internet through a default route learned from DC-EDGE. After the ISP circuit on DC-EDGE Gi0/0 failed, the leaves show no gateway of last resort. Which statement explains this?",
 ex:"DC-EDGE# show running-config | section router ospf\nrouter ospf 1\n router-id 10.60.255.30\n network 10.60.250.0 0.0.0.7 area 0\n default-information originate\nDC-EDGE# show running-config | include ip route\nip route 0.0.0.0 0.0.0.0 203.0.113.1\nDC-EDGE# show ip interface brief | include 0/0\nGigabitEthernet0/0     203.0.113.2     YES manual down                  down\n\nLEAF-1# show ip route | include Gateway\nGateway of last resort is not set",
 o:[
  {t:"With Gi0/0 down, the static default leaves DC-EDGE's table, so default-information originate has no default to advertise",ok:true,x:"The static route's next hop 203.0.113.1 is no longer reachable through a connected interface, so the route leaves DC-EDGE's table. Without always, default-information originate advertises a default only while one is installed."},
  {t:"default-information originate never advertises a static default route; the always keyword is required",ok:false,x:"Without always, OSPF advertises the default whenever the router has one in its routing table, whatever its source. always advertises it even when none exists."},
  {t:"The leaves' default route expired because the ISP router stopped sending OSPF hellos",ok:false,x:"The ISP does not run OSPF with DC-EDGE. The default was originated by DC-EDGE itself, and it was withdrawn when DC-EDGE lost its own default."},
  {t:"DC-EDGE also needs network 0.0.0.0 255.255.255.255 area 0 to keep advertising the default",ok:false,x:"A network statement enables OSPF on matching interfaces; it does not inject a default route. Advertising a default is the job of default-information originate."}
 ],
 w:"default-information originate follows the edge router's own default route. That is desirable: when the ISP link dies, the leaves stop sending internet traffic to a dead exit. always forces the advertisement regardless."},
{id:"c081",obj:"5.5",d:5,cat:"vpn",t:"ms",pick:2,
 q:"DC-EDGE (203.0.113.2) will build a site-to-site IPsec VPN to the DR site's router at 198.51.100.20 using IKE and ESP. No NAT device sits between the peers. An inbound ACL on DC-EDGE's internet interface permits only listed traffic. Which two entries must be added so that the tunnel can come up and carry traffic? (Choose two.)",
 o:[
  {t:"permit udp host 198.51.100.20 host 203.0.113.2 eq isakmp",ok:true,x:"IKE negotiates the security associations over UDP port 500 (the isakmp keyword). Without it the tunnel never forms."},
  {t:"permit esp host 198.51.100.20 host 203.0.113.2",ok:true,x:"Once the tunnel is up, the encrypted user traffic travels in ESP, IP protocol 50. With no NAT on the path, it is not wrapped in UDP."},
  {t:"permit tcp host 198.51.100.20 host 203.0.113.2 eq 443",ok:false,x:"TCP 443 carries TLS, used by SSL/TLS remote-access VPN clients. A site-to-site IPsec tunnel does not use it."},
  {t:"permit gre host 198.51.100.20 host 203.0.113.2",ok:false,x:"GRE (IP protocol 47) is needed only for GRE tunnels. This design uses plain IPsec with ESP."},
  {t:"permit ahp host 198.51.100.20 host 203.0.113.2",ok:false,x:"ahp matches AH, IP protocol 51. The tunnel is built with ESP, so AH packets are never sent."},
  {t:"permit udp host 198.51.100.20 host 203.0.113.2 eq 1701",ok:false,x:"UDP 1701 is L2TP. A site-to-site IPsec tunnel without L2TP does not use it."}
 ],
 w:"IPsec through an ACL: UDP 500 (IKE) plus ESP (protocol 50). Add UDP 4500 when NAT-T is used because a NAT device sits in the path. AH is protocol 51."},
{id:"c082",obj:"4.3",d:4,cat:"svc",t:"mc",
 q:"Refer to the exhibit. The data center DNS server at 10.60.10.53 holds A records for every DC device. Engineers want to use device names in ping, traceroute and ssh commands from DC-CORE. Which command fixes the problem shown?",
 ex:"DC-CORE# ping leaf-3.dc.example\nTranslating \"leaf-3.dc.example\"...domain server (255.255.255.255)\n% Unrecognized host or address, or protocol not running.",
 o:[
  {t:"ip name-server 10.60.10.53",ok:true,x:"DC-CORE is trying to resolve the name, but with no name server configured it broadcasts the query to 255.255.255.255, which no DNS server answers. Pointing it at 10.60.10.53 lets the A records be used."},
  {t:"ip domain-lookup",ok:false,x:"Lookups are already enabled, which is why IOS prints Translating. The problem is where the query is sent."},
  {t:"ip dns server",ok:false,x:"This makes DC-CORE answer DNS queries for other devices. It does not tell DC-CORE where to send its own queries."},
  {t:"ip domain-name dc.example",ok:false,x:"The domain name is appended to unqualified names (and is needed for RSA keys). The name typed here is already fully qualified, and there is still no server to ask."}
 ],
 w:"IOS DNS client: ip domain-lookup (on by default) + ip name-server <address>. (255.255.255.255) in the Translating line means no name server is configured."},
{id:"c083",obj:"3.3.c",d:3,cat:"static",t:"mc",
 q:"On DC-CORE, traffic to 2001:db8:60:30::/64 follows a static route through SPINE-1. The packet broker at 2001:db8:60:30::10, inside that subnet, must instead be reached through SPINE-2 (2001:db8:60:fff2::2) without affecting the rest of the subnet. Which command meets the requirement?",
 o:[
  {t:"ipv6 route 2001:db8:60:30::10/128 2001:db8:60:fff2::2",ok:true,x:"A /128 host route is longer than the /64, so it wins for that one address only. The rest of the subnet keeps using the /64 through SPINE-1."},
  {t:"ipv6 route 2001:db8:60:30::/64 2001:db8:60:fff2::2",ok:false,x:"This adds a second /64 with the same AD as the existing one, so both are installed and the whole subnet load-shares across both spines. The broker is not singled out."},
  {t:"ipv6 route 2001:db8:60:30::10/128 FE80::2",ok:false,x:"A link-local next hop is valid only on one link, so IOS needs an exit interface with it. Without one, the next hop cannot be resolved."},
  {t:"ip route 2001:db8:60:30::10 255.255.255.255 2001:db8:60:fff2::2",ok:false,x:"ip route is the IPv4 command and takes a dotted mask. IPv6 static routes use ipv6 route with prefix-length notation."}
 ],
 w:"Host route: /32 in IPv4, /128 in IPv6. It overrides a broader route for a single address. A link-local next hop always needs an exit interface."},
{id:"c084",obj:"3.4.c",d:3,cat:"ospf",t:"ms",pick:2,
 q:"On server-farm segment Vlan50, DC-CORE must become the DR and LEAF-3 must never become DR or BDR. LEAF-4 currently has OSPF priority 100 on Vlan50, and all routers on the segment will be reloaded together in tonight's maintenance window. Which two commands meet the requirement? (Choose two.)",
 o:[
  {t:"ip ospf priority 255 on DC-CORE interface Vlan50",ok:true,x:"Priority is compared first in the election, and 255 is the maximum. DC-CORE outranks LEAF-4's 100 when everyone restarts together."},
  {t:"ip ospf priority 0 on LEAF-3 interface Vlan50",ok:true,x:"Priority 0 makes a router ineligible for DR and BDR. LEAF-3 still forms adjacencies with the DR and BDR as a DROTHER."},
  {t:"router-id 10.60.255.250 under router ospf 1 on DC-CORE",ok:false,x:"Router ID only breaks ties between equal priorities. Unless DC-CORE's priority is raised above 100, LEAF-4 still wins the election."},
  {t:"ip ospf cost 1 on DC-CORE interface Vlan50",ok:false,x:"Cost affects path selection, not the DR/BDR election."},
  {t:"ip ospf network point-to-point on LEAF-3 interface Vlan50",ok:false,x:"Point-to-point suits a two-router link. On a shared segment with four routers it creates a network-type mismatch instead of a clean opt-out; priority 0 is the right tool."}
 ],
 w:"DR election: highest priority (0 to 255, default 1), then highest router ID. Priority 0 = never DR/BDR. Changes take effect at the next election, because DR/BDR are not preempted."},
{id:"c085",obj:"5.7",d:5,cat:"l2sec",t:"ms",pick:2,
 q:"Dynamic ARP inspection is being enabled on the ops-floor access switches, where DHCP snooping already runs. Which two statements describe DAI with its default settings? (Choose two.)",
 o:[
  {t:"ARP packets received on untrusted ports are checked against the DHCP snooping binding table",ok:true,x:"DAI compares the sender IP and MAC in each ARP packet with the bindings DHCP snooping recorded. A mismatch, or no binding, causes a drop and a log message."},
  {t:"An untrusted port that receives more than 15 ARP packets per second is err-disabled",ok:true,x:"The default rate limit on untrusted ports is 15 ARP packets per second. Exceeding it puts the port into the err-disabled state to stop ARP floods."},
  {t:"All ports are trusted until they are configured otherwise",ok:false,x:"By default every port is untrusted for DAI. Uplinks to other switches and routers are usually set to trusted manually."},
  {t:"DAI drops IP packets whose source address does not match the binding table",ok:false,x:"DAI inspects only ARP. Filtering ordinary IP traffic by source address is IP Source Guard."},
  {t:"DAI builds its own binding table from ARP replies, so DHCP snooping is optional",ok:false,x:"Learning from ARP would trust exactly the packets DAI is supposed to verify. DAI relies on DHCP snooping bindings, ARP ACLs or static bindings."}
 ],
 w:"DAI: ARP only, untrusted by default, validated against DHCP snooping bindings, 15 pps default limit on untrusted ports (err-disable when exceeded). Trust uplinks."},
{id:"c086",obj:"3.4.a",d:3,cat:"ospf",t:"mc",
 q:"Refer to the exhibit. LEAF-2 has a FULL adjacency with SPINE-1 but none with SPINE-2 on Te1/0/2, and SPINE-2 does not appear in LEAF-2's neighbor table. Which change restores the adjacency without affecting other links?",
 ex:"LEAF-2# show ip ospf interface Te1/0/2 | include Address|Timer\n  Internet Address 10.60.0.70/30, Area 0, Attached via Interface Enable\n  Timer intervals configured, Hello 5, Dead 20, Wait 20, Retransmit 5\n\nSPINE-2# show ip ospf interface Te1/0/2 | include Address|Timer\n  Internet Address 10.60.0.69/30, Area 0, Attached via Interface Enable\n  Timer intervals configured, Hello 10, Dead 40, Wait 40, Retransmit 5",
 o:[
  {t:"On LEAF-2 Te1/0/2, set the hello interval to 10 seconds and the dead interval to 40 seconds",ok:true,x:"Hello and dead intervals are carried in every hello, and a router ignores hellos whose values differ from its own. Matching SPINE-2's 10/40 lets the routers see each other again."},
  {t:"On LEAF-2 Te1/0/2, set only the dead interval to 40 seconds",ok:false,x:"Both values must match. With the hello still at 5 seconds, SPINE-2 keeps discarding LEAF-2's hellos."},
  {t:"On SPINE-2, enter clear ip ospf process",ok:false,x:"Restarting the process does not change the configured timers, so the mismatch remains after it restarts."},
  {t:"On both ends, enter ip ospf network point-to-point",ok:false,x:"Explicitly configured timers stay in force after a network-type change. The hellos would still disagree, so the neighbor would still not appear."}
 ],
 w:"Hello/dead mismatch: the neighbor never appears at all. Area, subnet/mask (on broadcast links), authentication and stub flags behave the same way. Fix the interface on the odd router out."},
{id:"c087",obj:"4.7",d:4,cat:"qos",t:"build",ordered:false,
 q:"Ops-floor softphone calls cross the DC edge to the DR site. Drag the markings and targets that commonly apply to interactive voice traffic into the answer area. Leave the items that do not apply.",
 pool:["Marked DSCP EF (46)","One-way delay of 150 ms or less","Jitter of 30 ms or less","Packet loss of 1% or less","Marked DSCP AF41 (34)","Lost packets recovered through TCP retransmission","Queued in class-default with best-effort traffic"],
 answer:[0,1,2,3],
 x:"Voice is marked EF and placed in a priority queue because it is small, constant and very sensitive to delay, jitter and loss. The common design targets are about 150 ms one-way delay, 30 ms jitter and 1% loss. AF41 is the usual marking for interactive video. Voice runs over RTP/UDP, so nothing retransmits lost packets, and a late retransmission would be useless anyway. Best-effort queueing is exactly what LLQ avoids.",
 w:"Voice: EF (46), LLQ priority queue, ~150 ms delay, ~30 ms jitter, ~1% loss. Interactive video: AF41 (34) in a bandwidth class."},
{id:"c088",obj:"3.5",d:3,cat:"fhrp",t:"ms",pick:2,
 q:"The ops team is choosing between HSRP and GLBP for the server gateways on LEAF-3 and LEAF-4. Which two statements describe GLBP but not HSRP? (Choose two.)",
 o:[
  {t:"One virtual IP address is answered with different virtual MACs, so several routers forward traffic at once",ok:true,x:"GLBP's AVG answers ARP requests for the single virtual IP with the MACs of different forwarders. With HSRP, only the active router forwards for a group."},
  {t:"An AVG assigns virtual MAC addresses to up to four AVFs in the group",ok:true,x:"The active virtual gateway hands out forwarder MACs, and each active virtual forwarder handles the hosts that received its MAC. HSRP has no such roles."},
  {t:"It is a Cisco-proprietary protocol",ok:false,x:"True of GLBP, but HSRP is Cisco-proprietary too, so it does not distinguish them. VRRP is the open standard."},
  {t:"The default priority is 100, and the highest priority wins the main role",ok:false,x:"Both protocols default to priority 100 and use it to elect the active router (HSRP) or the AVG (GLBP)."},
  {t:"Hosts must be configured with a different default gateway for each router",ok:false,x:"Neither protocol needs that. Both give every host the same virtual gateway address; GLBP spreads the load through ARP replies."}
 ],
 w:"HSRP: one active router per group (load sharing only with multiple groups). GLBP: one virtual IP, AVG + up to 4 AVFs, all forwarding. Both proprietary; VRRP is the standard."},
{id:"c089",obj:"5.6",d:5,cat:"acl",t:"mc",
 q:"Refer to the exhibit. OPS-FILTER is meant to stop ops-floor PCs in VLAN 20 from opening RDP sessions to the database servers in 10.60.42.0/24. RDP still works, and entry 10 shows no matches. What is the problem?",
 ex:"LEAF-1# show ip interface Vlan20 | include access list\n  Outgoing Common access list is not set\n  Outgoing access list is OPS-FILTER\n  Inbound Common access list is not set\n  Inbound  access list is not set\n\nLEAF-1# show access-lists OPS-FILTER\nExtended IP access list OPS-FILTER\n    10 deny tcp 10.60.20.0 0.0.0.255 10.60.42.0 0.0.0.255 eq 3389 log\n    20 permit ip any any (5803 matches)",
 o:[
  {t:"The ACL is applied outbound on Vlan20, so it never sees traffic the ops PCs send into the SVI; it must be applied inbound",ok:true,x:"Packets from the ops PCs enter LEAF-1 through Vlan20, so they are inbound there. Outbound on Vlan20 the ACL sees traffic heading to the PCs, whose source is never 10.60.20.0/24, so entry 10 cannot match."},
  {t:"Entry 10 must use 3389 as the source port instead of the destination port",ok:false,x:"An RDP client connects to TCP 3389 on the server, so eq 3389 belongs after the destination, as written."},
  {t:"Entry 20 permits all traffic before entry 10 is evaluated",ok:false,x:"Entries are evaluated in sequence order. Entry 10 is checked first for every packet the ACL sees."},
  {t:"Extended ACLs cannot be applied to SVIs",ok:false,x:"Extended ACLs work on routed interfaces and SVIs alike. The direction is the problem, not the interface type."}
 ],
 w:"ACL direction is from the router's point of view: traffic from hosts on a VLAN enters its SVI (in). Zero matches on a deny that should be hit usually means wrong interface or wrong direction."},
{id:"c090",obj:"3.1.d",d:3,cat:"rtable",t:"mc",
 q:"Refer to the exhibit. DC-CORE Gi1/0/4 connects to a shared Ethernet segment, 10.60.251.0/24, where two partner routers attach. 10.80.0.0/16 sits behind PARTNER-R1 (10.60.251.2). How does DC-CORE forward a packet to 10.80.5.9?",
 ex:"DC-CORE# show ip route static\n<output omitted>\nS        10.80.0.0/16 is directly connected, GigabitEthernet1/0/4",
 o:[
  {t:"It ARPs for 10.80.5.9 itself on Gi1/0/4, so delivery depends on PARTNER-R1 answering with proxy ARP",ok:true,x:"A static route with only an exit interface treats every destination as if it were on the link. DC-CORE ARPs for the final destination itself, so delivery depends on a router answering with proxy ARP."},
  {t:"It sends an ARP request for 10.60.251.2 and forwards the packet to PARTNER-R1's MAC address",ok:false,x:"That is how a route with a next-hop address works. This entry has no next hop, so DC-CORE never ARPs for 10.60.251.2."},
  {t:"It floods the packet out Gi1/0/4 so that both partner routers receive it",ok:false,x:"Routers never flood unicast packets. The packet goes in a frame addressed to one resolved MAC, or it is dropped if ARP fails."},
  {t:"It drops the packet, because a static route on an Ethernet interface must include a next-hop address",ok:false,x:"IOS accepts an exit-interface-only static route on Ethernet and installs it as directly connected. It works, just inefficiently, through proxy ARP."}
 ],
 w:"On multiaccess links give static routes a next hop (or exit interface plus next hop). Exit-interface-only routes ARP for every destination and rely on proxy ARP."},
{id:"c091",obj:"4.6",d:4,cat:"svc",t:"mc",
 q:"Refer to the exhibit. No ip route commands are configured on DC-EDGE. Which statement about DC-EDGE is true?",
 ex:"DC-EDGE# show running-config interface GigabitEthernet0/3\ninterface GigabitEthernet0/3\n description Internet circuit 2\n ip address dhcp\n ip nat outside\n\nDC-EDGE# show ip interface brief | include 0/3\nGigabitEthernet0/3     198.51.100.18   YES DHCP   up                    up\n\nDC-EDGE# show ip route static\n<output omitted>\nS*    0.0.0.0/0 [254/0] via 198.51.100.17",
 o:[
  {t:"Gi0/3 is a DHCP client; its default route came from the lease, and a static default with the normal AD would replace it",ok:true,x:"ip address dhcp makes the interface a DHCP client, and the DHCP method column confirms it. IOS installs the lease's default gateway as a static default with AD 254, so a static default with the normal AD of 1 would be preferred."},
  {t:"DC-EDGE is acting as the DHCP server for the 198.51.100.16 subnet",ok:false,x:"ip address dhcp is the client command. A DHCP server would need an ip dhcp pool, and DC-EDGE would not lease its own interface address."},
  {t:"The address was configured manually, and DHCP in the Method column means it was checked for conflicts",ok:false,x:"The Method column shows how the address was obtained. manual means configured; DHCP means leased."},
  {t:"The default route is a floating static that an engineer configured with an AD of 254",ok:false,x:"The stem rules that out: no ip route commands exist. The entry was created automatically from the DHCP lease."}
 ],
 w:"ip address dhcp = DHCP client on a router interface. IOS also installs the offered gateway as a static default with AD 254, which any normal static default overrides."},
{id:"c092",obj:"3.4.d",d:3,cat:"ospf",t:"mc",
 q:"Refer to the exhibit. SPINE-1 Te1/0/3 connects to LEAF-3 and Te1/0/4 connects to LEAF-4; each leaf has one link to SPINE-1. LEAF-4 was staged from a copy of LEAF-3's configuration. Since then, routes to LEAF-3's and LEAF-4's server subnets keep appearing and disappearing across the fabric. What is the cause?",
 ex:"SPINE-1# show ip ospf neighbor\n\nNeighbor ID     Pri   State           Dead Time   Address         Interface\n10.60.255.11      1   FULL/DR         00:00:33    10.60.0.2       TenGigabitEthernet1/0/1\n10.60.255.12      1   FULL/DR         00:00:36    10.60.0.6       TenGigabitEthernet1/0/2\n10.60.255.13      1   FULL/DR         00:00:31    10.60.0.10      TenGigabitEthernet1/0/3\n10.60.255.13      1   FULL/DR         00:00:39    10.60.0.14      TenGigabitEthernet1/0/4",
 o:[
  {t:"LEAF-3 and LEAF-4 use the same router ID, so each keeps replacing the other's router LSA",ok:true,x:"Two different leaves report 10.60.255.13. OSPF identifies a router's LSA by its router ID, so the two leaves overwrite each other's LSA in every database, and their prefixes come and go."},
  {t:"Nothing is wrong; a neighbor reached over two links is listed once per link",ok:false,x:"That would be normal for one router with two links to SPINE-1, but here the two interfaces lead to two different leaves."},
  {t:"Both leaves are DR on their links, which is not allowed within one area",ok:false,x:"Every broadcast segment elects its own DR, so many DRs in one area is normal."},
  {t:"The dead timers differ between Te1/0/3 and Te1/0/4",ok:false,x:"The Dead Time column is a countdown that resets with each hello. Different values at a given moment are expected."}
 ],
 w:"Router IDs must be unique in the OSPF domain. When cloning configs, change the router-id and run clear ip ospf process (or reload) so the new ID takes effect."},
{id:"c093",obj:"5.2",d:5,cat:"secbase",t:"mc",
 q:"The data center security plan lists four new activities. Which one is a user awareness element rather than a training program or a physical access control?",
 o:[
  {t:"Monthly simulated phishing emails and short security reminders sent to all staff",ok:true,x:"Awareness keeps security in everyone's mind through repeated, low-effort contact such as phishing simulations, posters and reminders. It targets all users, not a specific skill."},
  {t:"A graded, hands-on course on hardening switch configurations for the ops engineers",ok:false,x:"This is training: structured instruction that builds a job-specific skill for a defined role, with an assessment."},
  {t:"Badge-plus-PIN readers and a mantrap at the data hall entrance",ok:false,x:"These are physical access controls. They restrict who can enter the space, whatever the person knows."},
  {t:"Escorting and logging every visitor inside the cage area",ok:false,x:"Visitor escort and logs are physical access controls that track and limit who is near the equipment."}
 ],
 w:"Awareness = everyone, ongoing reminders (phishing tests, posters). Training = role-specific skills, often assessed. Physical access control = badges, locks, mantraps, escorts, cameras."},
{id:"c094",obj:"3.1.f",d:3,cat:"rtable",t:"mc",
 q:"Refer to the exhibit. To make OSPF account for the 10-Gb/s links, the team enters auto-cost reference-bandwidth 100000 under router ospf 1 on every router. Which route to 10.60.43.0/24 does DC-CORE then install?",
 ex:"Topology (all links in OSPF area 0, no ip ospf cost commands):\n  DC-CORE Te1/0/1 --10G-- SPINE-1 --10G-- Te1/0/1 LEAF-4\n  DC-CORE Te1/0/2 --10G-- SPINE-2 --10G-- Te1/0/2 LEAF-4\n  DC-CORE Gi1/0/3 -----------1G----------- Gi1/0/3 LEAF-4\n  LEAF-4 Gi1/0/1: server LAN 10.60.43.0/24 (1G)\n\nNext hops from DC-CORE: SPINE-1 10.60.0.33, SPINE-2 10.60.0.97,\n                        LEAF-4 (direct) 10.60.0.122",
 o:[
  {t:"[110/120] through both SPINE-1 and SPINE-2",ok:true,x:"With a 100000-Mb/s reference, a 10G interface costs 10 and a 1G interface costs 100. Each spine path is 10 + 10 + 100 (LEAF-4's LAN) = 120; the direct path is 100 + 100 = 200. The two equal 120 paths are both installed."},
  {t:"[110/200] through LEAF-4 over Gi1/0/3",ok:false,x:"200 is the direct path's new cost, but the spine paths now cost only 120, so the direct path loses."},
  {t:"[110/3] through both SPINE-1 and SPINE-2",ok:false,x:"3 would be the spine path cost with the old 100-Mb/s reference, where every link costs 1. The new reference changes every interface cost."},
  {t:"[110/120] through SPINE-1, with SPINE-2 held as a backup",ok:false,x:"Both spine paths total exactly 120, so OSPF installs both and load-shares. OSPF does not keep an equal-cost path as a standby."}
 ],
 w:"Cost = reference bandwidth / interface bandwidth. At 100000 Mb/s: 100G = 1, 10G = 10, 1G = 100. Set the same reference on every router, or path costs become inconsistent."},
{id:"c095",obj:"4.8",d:4,cat:"svc",t:"mc",
 q:"Refer to the exhibit. An audit requires DC-EDGE to refuse SSH version 1 sessions. DC-EDGE already has a 2048-bit RSA key. Which command meets the requirement?",
 ex:"DC-EDGE# show ip ssh\nSSH Enabled - version 1.99\nAuthentication methods:publickey,keyboard-interactive,password\nAuthentication timeout: 120 secs; Authentication retries: 3\nMinimum expected Diffie Hellman key size : 1024 bits\nIOS Keys in SECSH format(ssh-rsa, base64 encoded): DC-EDGE.dc.example",
 o:[
  {t:"ip ssh version 2",ok:true,x:"Version 1.99 means the server accepts both SSHv1 and SSHv2 clients. Setting version 2 makes DC-EDGE refuse SSHv1."},
  {t:"crypto key generate rsa modulus 4096",ok:false,x:"A larger key strengthens the host key but does not change which protocol versions are accepted. The 2048-bit key already supports SSHv2."},
  {t:"transport input ssh under line vty 0 15",ok:false,x:"transport input chooses between protocols such as SSH and Telnet. It does not select the SSH version."},
  {t:"ip ssh authentication-retries 2",ok:false,x:"This only limits failed login attempts per session. Version 1 clients would still be accepted."}
 ],
 w:"SSH on IOS: hostname, ip domain-name, crypto key generate rsa (768+ bits for v2), ip ssh version 2, login local, transport input ssh. 1.99 = v1 and v2 both allowed."},
{id:"c096",obj:"5.10",d:5,cat:"wsec",t:"mc",
 q:"Refer to the exhibit. The OPS-LAB WLAN on the controller must use WPA2-Personal with the AES-based encryption (CCMP) that WPA2 is built around. A wireless audit flagged the WLAN as non-compliant. Which change fixes it?",
 ex:"WLANs > Edit 'OPS-LAB'   Security > Layer 2\n\n  Layer 2 Security          WPA+WPA2\n  WPA+WPA2 Parameters\n    WPA Policy              [ ]\n    WPA2 Policy             [x]\n    WPA2 Encryption         [ ] AES    [x] TKIP\n  Authentication Key Management\n    802.1X                  [ ] Enable\n    PSK                     [x] Enable\n    PSK Format              ASCII",
 o:[
  {t:"Check AES and clear TKIP under WPA2 Encryption",ok:true,x:"WPA2 is defined around AES-CCMP. TKIP is a legacy cipher from WPA that is deprecated and weaker. WPA2 policy, PSK key management and an ASCII passphrase are already set correctly."},
  {t:"Enable 802.1X and keep PSK enabled",ok:false,x:"802.1X is enterprise key management with a RADIUS server. The requirement is WPA2-Personal, which is PSK."},
  {t:"Enable WPA Policy alongside WPA2 Policy",ok:false,x:"That adds the original WPA with TKIP for older clients, which moves the WLAN further from the requirement."},
  {t:"Change the PSK Format from ASCII to HEX",ok:false,x:"The format only defines how the key is entered (an 8 to 63 character passphrase or 64 hex digits). It does not affect the cipher."}
 ],
 w:"WLC WPA2-Personal: Layer 2 Security WPA+WPA2, WPA2 Policy on, encryption AES, Auth Key Mgmt PSK, then the passphrase. TKIP belongs to the original WPA."},
{id:"c097",obj:"3.3.a",d:3,cat:"static",t:"mc",
 q:"Refer to the exhibit. IPv6 unicast routing is enabled on DC-EDGE. The ISP router on the Gi0/0 link uses 2001:DB8:A0:1::1. Which command gives DC-EDGE a default route for every IPv6 destination it has no more specific route for?",
 ex:"DC-EDGE# show ipv6 interface brief\nGigabitEthernet0/0     [up/up]\n    FE80::A8BB:CCFF:FE00:200\n    2001:DB8:A0:1::2\nGigabitEthernet0/1     [up/up]\n    FE80::A8BB:CCFF:FE00:210\n    2001:DB8:60:FFFF::1",
 o:[
  {t:"ipv6 route ::/0 2001:db8:a0:1::1",ok:true,x:"::/0 is the IPv6 default route; a zero-length prefix matches every address. The ISP's global address is on the connected Gi0/0 prefix, so the next hop resolves."},
  {t:"ipv6 route ::/128 2001:db8:a0:1::1",ok:false,x:"::/128 is a host route for the unspecified address only. It would match nothing useful."},
  {t:"ipv6 route ::/0 FE80::1",ok:false,x:"A link-local next hop must be paired with an exit interface, and FE80::1 is not shown as the ISP's address anyway."},
  {t:"ip route 0.0.0.0 0.0.0.0 2001:db8:a0:1::1",ok:false,x:"ip route builds IPv4 routes and cannot take an IPv6 next hop. IPv6 routes use ipv6 route."}
 ],
 w:"IPv6 default route: ipv6 route ::/0 <next hop>. Use a global next hop, or an exit interface plus a link-local next hop. ipv6 unicast-routing must be on."},
{id:"c098",obj:"5.4",d:5,cat:"secbase",t:"mc",
 q:"A new policy requires every password configured on the data center devices to have at least 12 characters. After a change on DC-CORE, IOS rejects the command username ops2 secret Dc!2026 with a password-length error. Which command enforces this policy?",
 o:[
  {t:"security passwords min-length 12",ok:true,x:"This global command makes IOS refuse new user, enable and line passwords shorter than the configured length, which is what the error shows."},
  {t:"service password-encryption",ok:false,x:"This only obscures clear-text passwords in the configuration with weak type 7 encoding. It enforces no length."},
  {t:"login block-for 120 attempts 5 within 60",ok:false,x:"This blocks logins for 120 seconds after 5 failures in 60 seconds. It slows password guessing but does not check how passwords are set."},
  {t:"exec-timeout 12 0 under line vty 0 15",ok:false,x:"This logs idle vty sessions out after 12 minutes. It has nothing to do with password length."}
 ],
 w:"Password policy on IOS: security passwords min-length (length), enable secret / username secret (strong hashing), login block-for (guessing), exec-timeout (idle sessions). Better still: MFA or certificates."},
{id:"c099",obj:"4.9",d:4,cat:"mon",t:"mc",
 q:"DC-CORE copies a new 480-MB software image from the file server 10.60.20.60 with copy ftp: flash:. A transit ACL between them permits only TCP port 21 in each direction. The FTP login succeeds, but the transfer fails before any of the file arrives. What is the reason?",
 o:[
  {t:"FTP carries the file over a separate TCP data connection, which the ACL does not permit",ok:true,x:"TCP 21 is only the control connection used for login and commands. The file itself moves over a second TCP connection (port 20 in active mode, a negotiated port in passive mode), which this ACL blocks."},
  {t:"FTP sends files over UDP port 69, which the ACL does not permit",ok:false,x:"UDP 69 is TFTP. FTP runs entirely over TCP."},
  {t:"FTP cannot transfer files larger than 32 MB",ok:false,x:"That ceiling belongs to classic TFTP (512-byte blocks and a 16-bit block counter). FTP has no such limit."},
  {t:"The username and password must be sent again on TCP port 20 before the transfer starts",ok:false,x:"Credentials are exchanged once, on the control connection. The data connection carries only file contents."}
 ],
 w:"FTP: TCP, login with credentials, control on 21 plus a separate data connection. TFTP: UDP 69, no login, simple and slow. Both copy images and configs to and from IOS."},
{id:"c100",obj:"5.8",d:5,cat:"vpn",t:"mc",
 q:"The ops team must choose a protocol for administrator logins to the data center switches and routers. Requirements: each configuration command must be authorized individually, and the entire packet body, not just the password, must be encrypted. Which choice meets the requirements, and why?",
 o:[
  {t:"TACACS+, because it separates authorization from authentication and encrypts the whole payload over TCP 49",ok:true,x:"TACACS+ handles authentication, authorization and accounting as separate exchanges, which allows per-command authorization, and it encrypts the full body of every packet."},
  {t:"RADIUS, because it encrypts the whole payload over UDP 1812",ok:false,x:"RADIUS uses UDP 1812/1813 but encrypts only the password attribute. The rest of the packet is sent in clear text."},
  {t:"RADIUS, because it is the only one of the two that supports command authorization",ok:false,x:"RADIUS returns authorization together with authentication and has no per-command exchange. Per-command authorization is a TACACS+ strength."},
  {t:"TACACS+, because it combines authentication and authorization in one reply over UDP 49",ok:false,x:"TACACS+ runs over TCP, not UDP, and it separates the AAA functions. Combining authentication and authorization is how RADIUS works."}
 ],
 w:"TACACS+: TCP 49, full-body encryption, separate AAA, per-command authorization: best for device administration. RADIUS: UDP 1812/1813, password-only encryption, combined authN/authZ: best for network access (802.1X, VPN)."}
];
