/* CCNA Exam B — part 1 (b001–b050): branch office + WAN edge. d1 Network Fundamentals 20 · d2 Network Access 20 · d6 Automation & Programmability 10.
   Branch: BR1 (Gi0/0 trunk to BSW1 Gi0/1, VLAN 10 native on the physical interface, subinterfaces for 20 voice / 30 cameras / 40 AP mgmt / 50 guest / 90 mgmt),
   BSW1/BSW2 access switches, FlexConnect or cloud-managed APs, dual stack 2001:db8:b1::/48. Switch, STP, trunk, CDP and IPv6 exhibits generated with
   core/sims/ios and trimmed; client OS, WLC GUI, JSON, YAML and HTTP output hand-written. All text original. Spec: dev/specs/ccna.md §6. */
export const CCNA_BANK_B_P1 = [
{id:"b001",obj:"2.1.a",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. An IP phone is cabled to BSW1 Fa0/7 and a staff PC is cabled to the phone's PC port. The phone keeps leasing an address from the VLAN 10 staff scope instead of the 10.20.20.0/24 voice scope. VLAN 20 (VOICE) exists on BSW1 and is allowed on the uplink trunk. Which command on Fa0/7 fixes the problem and keeps the PC in VLAN 10?",
 ex:"BSW1# show interfaces fa0/7 switchport\nName: Fa0/7\nSwitchport: Enabled\nAdministrative Mode: static access\nOperational Mode: static access\nAdministrative Trunking Encapsulation: dot1q\nOperational Trunking Encapsulation: native\nNegotiation of Trunking: Off\nAccess Mode VLAN: 10 (STAFF)\nTrunking Native Mode VLAN: 1 (default)\nAdministrative Native VLAN tagging: enabled\nVoice VLAN: none",
 o:[
  {t:"switchport voice vlan 20",ok:true,x:"Voice VLAN: none means the switch never tells the phone (through CDP or LLDP-MED) to tag its traffic, so the phone sends untagged frames into access VLAN 10. With voice VLAN 20 set, the phone tags voice in VLAN 20 and the PC stays untagged in VLAN 10."},
  {t:"switchport access vlan 20",ok:false,x:"This moves all untagged traffic, and the PC with it, into VLAN 20. The phone would get a voice address but the PC would land in the voice subnet."},
  {t:"switchport mode trunk",ok:false,x:"Trunking does not tell the phone which VLAN to use for voice. With no voice VLAN advertised the phone still sends untagged frames, which a trunk places in its native VLAN."},
  {t:"switchport trunk native vlan 20",ok:false,x:"The native VLAN only matters when the port is trunking. Fa0/7 is a static access port, so this changes nothing for the phone."}
 ],
 w:"Phone port: switchport mode access, switchport access vlan <data>, switchport voice vlan <voice>. The switch advertises the voice VLAN in CDP/LLDP-MED; the phone tags voice and passes the PC's frames untagged."},
{id:"b002",obj:"1.6",d:1,cat:"tcpip",t:"mc",
 q:"The branch warehouse is getting a scanner VLAN on BR1 subinterface Gi0/0.60. It must hold 300 handheld scanners, the address plan assigns the block starting at 10.20.64.0, the gateway must use the first usable address, and the subnet must leave the fewest unused addresses. Which interface command meets the requirements?",
 o:[
  {t:"ip address 10.20.64.1 255.255.254.0",ok:true,x:"300 hosts need 9 host bits (2^9 - 2 = 510), so the mask is /23. 10.20.64.0/23 runs from 10.20.64.0 to 10.20.65.255, and the first usable address is 10.20.64.1."},
  {t:"ip address 10.20.64.1 255.255.255.0",ok:false,x:"A /24 gives only 254 usable addresses, fewer than the 300 scanners."},
  {t:"ip address 10.20.64.1 255.255.252.0",ok:false,x:"A /22 (1022 usable) fits, but it leaves more than 700 addresses unused. A /23 meets the need with far less waste."},
  {t:"ip address 10.20.65.1 255.255.254.0",ok:false,x:"10.20.65.1 is inside 10.20.64.0/23, but it is not the first usable address. That is 10.20.64.1."}
 ],
 w:"Find the smallest n where 2^n - 2 covers the hosts (300 → n = 9 → /23). Check the boundary: a /23 starts on an even third octet (64 is). First usable = network + 1; broadcast = next network - 1."},
{id:"b003",obj:"6.6",d:6,cat:"cfgmgmt",t:"mc",
 q:"Refer to the exhibit. The network team runs this file to update all branch routers. Which statement describes how it works?",
 ex:"---\n- name: Branch NTP baseline\n  hosts: branch_routers\n  gather_facts: no\n  connection: ansible.netcommon.network_cli\n\n  tasks:\n    - name: Point routers at the HQ NTP server\n      cisco.ios.ios_config:\n        lines:\n          - ntp server 10.10.1.123\n\n    - name: Save the configuration if it changed\n      cisco.ios.ios_config:\n        save_when: modified",
 o:[
  {t:"A control node pushes the lines over SSH to each router in the inventory group branch_routers; no agent is installed",ok:true,x:"This is an Ansible playbook in YAML. The control node connects with network_cli (SSH to the IOS CLI), runs each task in order against every host in the group, and nothing has to be installed on the routers."},
  {t:"Each router runs an agent that periodically pulls this manifest from a central server",ok:false,x:"That pull model describes Puppet and Chef. Ansible is agentless and pushes changes when someone runs the playbook."},
  {t:"It is a Terraform configuration written in HCL, and the apply step records the routers in a state file",ok:false,x:"The file is YAML with hosts and tasks, which is Ansible's playbook format. Terraform files are HCL resource blocks with a state file and plan/apply."},
  {t:"The routers must expose a REST API, because this tool cannot manage devices through the CLI",ok:false,x:"network_cli drives the device CLI over SSH. Ansible can also use NETCONF or REST modules, but this playbook does not need them."}
 ],
 w:"Ansible: agentless, push, SSH or APIs, YAML playbooks of tasks run against inventory groups, modules such as cisco.ios.ios_config. Puppet/Chef: agent-based pull. Terraform: declarative HCL, plan/apply, state file."},
{id:"b004",obj:"1.4",d:1,cat:"parts",t:"mc",
 q:"Refer to the exhibit. Users at the desk on BSW1 Fa0/12 complain about slow file transfers. The PC's NIC reports an auto-negotiated 100 Mb/s full-duplex link, and the error counters keep rising after clear counters. What is the most likely cause?",
 ex:"BSW1# show interfaces fa0/12\nFastEthernet0/12 is up, line protocol is up (connected)\n  Hardware is Fast Ethernet, address is 0001.4200.020c (bia 0001.4200.020c)\n  MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100 usec,\n     reliability 238/255, txload 1/255, rxload 3/255\n  Encapsulation ARPA, loopback not set\n  Keepalive set (10 sec)\n  Full-duplex, 100Mb/s, media type is 10/100BaseTX\n  5 minute input rate 412000 bits/sec, 61 packets/sec\n  5 minute output rate 389000 bits/sec, 58 packets/sec\n     1840212 packets input, 1288140211 bytes, 0 no buffer\n     Received 2214 broadcasts (1876 multicasts)\n     0 runts, 0 giants, 0 throttles\n     4127 input errors, 4127 CRC, 0 frame, 0 overrun, 0 ignored\n     1702334 packets output, 1190455721 bytes, 0 underruns\n     0 output errors, 0 collisions, 1 interface resets\n     0 babbles, 0 late collision, 0 deferred",
 o:[
  {t:"Damaged cabling or electrical interference between the PC and the switch",ok:true,x:"CRC errors mean frames arrived with a bad frame check sequence. Both ends agree on full duplex, and there are no runts, collisions or buffer drops, which points at the physical path: a crushed cable, a bad patch cord or interference."},
  {t:"A duplex mismatch between the switch port and the PC",ok:false,x:"Both sides negotiated full duplex. A mismatch would show late collisions on the half-duplex side and usually runts on the full-duplex side, and neither appears."},
  {t:"A speed mismatch between the switch port and the PC",ok:false,x:"With mismatched speeds the link does not come up at all. The port is up/up at 100 Mb/s, the same as the NIC."},
  {t:"The switch is overloaded and dropping frames it has no buffer space for",ok:false,x:"Buffer shortage shows up as no buffer, overrun or ignored counts, which are all zero. The load is under 0.5 Mb/s on a 100 Mb/s port."}
 ],
 w:"CRC errors with no collisions on a full-duplex link = physical layer (cable, connector, EMI, NIC). CRC/runts on one end plus late collisions on the other = duplex mismatch. Speed mismatch = link down."},
{id:"b005",obj:"2.5.b",d:2,cat:"stp",t:"mc",
 q:"Refer to the exhibit. BSW1 is the root bridge for VLAN 10 and connects to BSW2 Gi0/1 and BSW3 Gi0/1. BSW2 Gi0/2 connects to BSW3 Gi0/2. All links are 1 Gb/s. Which statement describes BSW3 Gi0/2?",
 ex:"BSW3# show spanning-tree vlan 10\nVLAN0010\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    24586\n             Address     0001.4200.0100\n             Cost        4\n             Port        25 (GigabitEthernet0/1)\n             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec\n\n  Bridge ID  Priority    32778  (priority 32768 sys-id-ext 10)\n             Address     0001.4200.0300\n             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec\n             Aging Time  300 sec\n\nInterface           Role Sts Cost      Prio.Nbr Type\n------------------- ---- --- --------- -------- -----------------------\nGi0/1               Root FWD 4         128.25   P2p\nGi0/2               Altn BLK 4         128.26   P2p",
 o:[
  {t:"It is an alternate port that discards frames and can become the root port immediately if Gi0/1 fails",ok:true,x:"Gi0/2 offers a path to the root through BSW2 (cost 8), worse than Gi0/1's direct path (cost 4). RSTP makes it an alternate port, kept discarding (shown as BLK), ready to take over as root port at once."},
  {t:"It is a backup port because BSW3 has two paths to the root bridge",ok:false,x:"A backup port is a second port onto a segment where the same switch already has the designated port, as through a hub. Gi0/2 hears a better BPDU from another switch, so it is alternate."},
  {t:"It is in the listening state and will forward after two forward-delay intervals",ok:false,x:"Listening exists only in legacy 802.1D. Rapid PVST+ uses discarding, learning and forwarding, and an alternate port is promoted without waiting on timers."},
  {t:"It is the designated port for the BSW2-BSW3 link because BSW3 has the higher bridge ID",ok:false,x:"Both switches advertise root path cost 4 onto that link, so the lower bridge ID wins. Gi0/2 being Altn shows BSW2 sent the superior BPDU, so BSW2 has the lower bridge ID and owns the designated port."}
 ],
 w:"RSTP roles: root, designated, alternate (a backup path to the root through another switch), backup (a redundant port onto a segment this switch already serves). States: discarding, learning, forwarding."},
{id:"b006",obj:"1.10",d:1,cat:"tcpip",t:"mc",
 q:"Refer to the exhibit. A user typed a static IPv4 configuration on this Mac in VLAN 10 (10.20.10.0/24). It reaches the internet and HQ servers, but not the branch camera server 10.20.30.15, which other staff PCs reach without problems. Proxy ARP is disabled on BR1's LAN interfaces. What explains the problem?",
 ex:"mac$ ifconfig en0\nen0: flags=8863<UP,BROADCAST,SMART,RUNNING,SIMPLEX,MULTICAST> mtu 1500\n        ether 3c:22:fb:5e:10:21\n        inet6 fe80::1c4d:2a9:5e11:8f02%en0 prefixlen 64 secured scopeid 0x6\n        inet 10.20.10.88 netmask 0xffff0000 broadcast 10.20.255.255\n        status: active\nmac$ netstat -rn -f inet\nRouting tables\n\nInternet:\nDestination        Gateway            Flags        Netif Expire\ndefault            10.20.10.1         UGScg          en0\n10.20/16           link#6             UCS            en0",
 o:[
  {t:"The 0xffff0000 (/16) mask makes the Mac treat 10.20.30.15 as on-link, so it ARPs for it instead of using 10.20.10.1",ok:true,x:"With /16, every 10.20.x.x address looks local, so the Mac ARPs for 10.20.30.15 on VLAN 10. The server is in another VLAN and never answers, and with proxy ARP off BR1 does not answer for it either. The mask should be 0xffffff00."},
  {t:"The default gateway 10.20.10.1 is wrong for this subnet",ok:false,x:"10.20.10.1 is BR1's VLAN 10 gateway, and internet and HQ traffic reaches it. The gateway is right; it simply isn't used for 10.20.x.x destinations."},
  {t:"BR1 has no route to the 10.20.30.0/24 camera subnet",ok:false,x:"Other staff PCs reach the camera server through BR1, so BR1 can route to that subnet."},
  {t:"The 10.20.255.255 broadcast lets the Mac's ARP requests reach every branch VLAN",ok:false,x:"Switches keep a broadcast inside its VLAN and routers do not forward it. That is exactly why the ARP for 10.20.30.15 goes unanswered."}
 ],
 w:"Client checks: Windows ipconfig /all; macOS ifconfig and netstat -rn; Linux ip addr and ip route. A mask that is too short makes remote hosts look local (ARP, no gateway); too long makes local hosts look remote."},
{id:"b007",obj:"2.1.c",d:2,cat:"vlan",t:"build",ordered:true,
 q:"Cameras will use VLAN 30 (10.20.30.0/24). BSW1 already carries VLAN 30, tagged, on its trunk to BR1 Gi0/0, which is up. Starting in global configuration mode on BR1, drag the commands needed to route VLAN 30 with 10.20.30.1 as the gateway into the answer area in the order they must be entered. Not all commands are used.",
 pool:["encapsulation dot1Q 30","switchport mode trunk","interface GigabitEthernet0/0.30","ip address 10.20.30.1 255.255.255.0","encapsulation dot1Q 30 native","interface vlan 30"],
 answer:[2,0,3],
 x:"Router-on-a-stick uses one subinterface per VLAN. The subinterface must be tied to its VLAN with encapsulation dot1Q before IOS accepts an IP address on it. switchport and interface vlan are switch commands, and the native keyword would make BR1 expect VLAN 30 untagged while BSW1 tags it.",
 w:"ROAS per VLAN: interface g0/0.N, encapsulation dot1Q N, ip address. The subinterface number is only a label; the VLAN comes from the encapsulation command. The physical interface must be up."},
{id:"b008",obj:"1.1.a",d:1,cat:"parts",t:"ms",pick:2,
 q:"The branch has BR1, an ISR router, and BSW1, a Layer 2 access switch. Which two functions does BR1 perform that BSW1 does not? (Choose two.)",
 o:[
  {t:"Forwarding packets between different IP subnets based on the destination IP address",ok:true,x:"Routing between subnets is a Layer 3 function. BSW1 forwards frames only within a VLAN; VLAN-to-VLAN traffic must go through BR1."},
  {t:"Translating branch private addresses to a public address for internet traffic",ok:true,x:"NAT/PAT runs on the router at the internet edge. A Layer 2 switch does not look at or rewrite IP addresses."},
  {t:"Learning source MAC addresses to build a MAC address table",ok:false,x:"MAC learning is the switch's core job. A router keeps an ARP table but does not learn MAC addresses to forward frames."},
  {t:"Flooding frames whose destination MAC address is unknown",ok:false,x:"Unknown-unicast flooding is switch behaviour. A router never floods; it routes or drops."},
  {t:"Placing end devices into VLANs through access ports",ok:false,x:"Access ports and VLAN membership are configured on the switch."},
  {t:"Supplying PoE to IP phones",ok:false,x:"Phones are powered by the switch ports they plug into, not by the router."}
 ],
 w:"Router: Layer 3 forwarding between subnets, WAN links, NAT, broadcast boundary. Layer 2 switch: MAC learning, forwarding, flooding and filtering inside VLANs, access ports, PoE. A Layer 3 switch adds routing with SVIs."},
{id:"b009",obj:"2.3",d:2,cat:"l2link",t:"ms",pick:2,
 q:"Refer to the exhibit. Which two statements are true? (Choose two.)",
 ex:"BSW1# show cdp entry BSW2\n-------------------------\nDevice ID: BSW2\nEntry address(es):\n  IP address: 10.20.90.12\nPlatform: cisco WS-C2960,  Capabilities: Switch IGMP\nInterface: GigabitEthernet0/2,  Port ID (outgoing port): GigabitEthernet0/1\nHoldtime : 155 sec\n\nVersion :\nCisco IOS Software, C2960 Software (C2960-LANBASEK9-M), Version 15.2(4)E7,\nRELEASE SOFTWARE (fc1)\n\nadvertisement version: 2\nNative VLAN: 10\nDuplex: full\nManagement address(es):\n  IP address: 10.20.90.12",
 o:[
  {t:"BSW1 connects to BSW2 through BSW1's own GigabitEthernet0/2",ok:true,x:"'Interface' is the local port on the switch where the command was run. 'Port ID (outgoing port)' is the neighbor's port."},
  {t:"BSW2 advertises 10.20.90.12 as its management address",ok:true,x:"The entry and management addresses come from BSW2's own advertisement, here its VLAN 90 management SVI. CDP is a quick way to find a neighbor's address for SSH without a diagram."},
  {t:"BSW2's port facing BSW1 is GigabitEthernet0/2",ok:false,x:"That is BSW1's local port. BSW2 sent the advertisement out its Gi0/1, shown as the Port ID."},
  {t:"BSW2 may be several router hops away, because CDP travels in IP packets",ok:false,x:"CDP is a Layer 2 protocol sent to a multicast MAC address and never routed. Every CDP neighbor is directly connected."},
  {t:"The output comes from LLDP, which IOS runs on all ports by default",ok:false,x:"This is CDP output. LLDP is disabled by default on IOS and is read with show lldp neighbors."}
 ],
 w:"show cdp neighbors: device, local interface, holdtime, capability, platform, port ID. show cdp neighbors detail or show cdp entry NAME adds IP addresses, IOS version, native VLAN and duplex."},
{id:"b010",obj:"6.2",d:6,cat:"sdn",t:"mc",
 q:"Today each branch router runs OSPF and builds its own routing table, and engineers configure each device separately over SSH. The company is evaluating a controller-based design. Which statement correctly compares the two approaches?",
 o:[
  {t:"Traditionally each device runs its own control plane; a controller centralizes policy and programs devices through APIs",ok:true,x:"In the current design every router computes its own view and is configured box by box. A controller holds a network-wide view, turns intent into device configuration and pushes it through southbound APIs."},
  {t:"With a controller, the controller forwards all user traffic, so devices no longer need a data plane",ok:false,x:"Forwarding stays on the routers and switches. The controller works in the control and management planes."},
  {t:"Traditional networks already centralize the control plane in a management server, and controllers distribute it",ok:false,x:"This reverses the two. Traditional devices each run their own control plane."},
  {t:"A controller-based design requires removing every routing protocol from the network",ok:false,x:"Controller-based fabrics still run routing in the underlay (SD-Access uses IS-IS, for example). The controller automates and orchestrates on top of it."}
 ],
 w:"Traditional: per-device control plane, per-box CLI, change by hand. Controller-based: central view and policy, templates, southbound APIs to devices, northbound REST APIs to apps; the data plane stays on the devices."},
{id:"b011",obj:"1.8",d:1,cat:"ipv6",t:"mc",
 q:"Refer to the exhibit. The branch is moving to dual stack, and BR1 Gi0/0 serves VLAN 10. PCs should build global IPv6 addresses with SLAAC, but they have only link-local IPv6 addresses and no IPv6 default gateway. IPv4 works. Which command fixes the problem?",
 ex:"BR1# show running-config | include ipv6\n ipv6 address FE80::1 link-local\n ipv6 address 2001:DB8:B1:10::1/64\n\nC:\\> ipconfig\n\nEthernet adapter Ethernet:\n\n   Connection-specific DNS Suffix  . : branch.example\n   Link-local IPv6 Address . . . . . : fe80::5d2a:91c4:7e10:3b6f%12\n   IPv4 Address. . . . . . . . . . . : 10.20.10.37\n   Subnet Mask . . . . . . . . . . . : 255.255.255.0\n   Default Gateway . . . . . . . . . : 10.20.10.1",
 o:[
  {t:"ipv6 unicast-routing in global configuration mode",ok:true,x:"Without it IOS acts as an IPv6 host: it sends no router advertisements and forwards no IPv6 packets. The filter shows no ipv6 unicast-routing line. Once enabled, BR1 advertises 2001:db8:b1:10::/64 and the PCs autoconfigure with FE80::1 as gateway."},
  {t:"ipv6 enable on Gi0/0",ok:false,x:"Configuring an IPv6 address already enables IPv6 on the interface. ipv6 enable only creates a link-local address, and BR1 already has one."},
  {t:"ipv6 address autoconfig on Gi0/0",ok:false,x:"This makes BR1 itself a SLAAC client that learns an address from another router. BR1 would still send no RAs to the PCs."},
  {t:"ipv6 nd managed-config-flag on Gi0/0",ok:false,x:"This RA flag tells hosts to use stateful DHCPv6. BR1 is not sending RAs at all, and the branch has no DHCPv6 server."}
 ],
 w:"Router IPv6 basics: ipv6 unicast-routing (global), then interface addresses. RAs then go out LAN interfaces automatically, and hosts use SLAAC with the router's link-local address as default gateway."},
{id:"b012",obj:"2.6",d:2,cat:"wlan",t:"mc",
 q:"The branch has no local wireless controller; its lightweight APs join the WLC at HQ across the WAN. Staff traffic must be switched onto VLAN 10 at the branch instead of being tunneled to HQ, and connected clients must stay online if the WAN fails. Which AP mode meets these requirements?",
 o:[
  {t:"FlexConnect",ok:true,x:"FlexConnect APs keep CAPWAP control to the central WLC but can switch WLAN traffic locally onto branch VLANs. If the WAN drops, they go standalone and keep serving connected clients on locally switched WLANs."},
  {t:"Local",ok:false,x:"Local mode tunnels all client data in CAPWAP to the WLC, so staff traffic would hairpin through HQ, and clients drop when the WAN fails."},
  {t:"Bridge",ok:false,x:"Bridge (mesh) mode links APs to each other wirelessly to extend coverage. It does not provide local switching for a WAN-connected branch."},
  {t:"Monitor",ok:false,x:"A monitor-mode AP serves no clients at all; it only scans channels for rogues and intrusion detection."}
 ],
 w:"AP modes: local (default, client data in CAPWAP to the WLC), FlexConnect (branch, local switching, survives WAN loss), monitor, sniffer, rogue detector, SE-Connect, bridge/mesh."},
{id:"b013",obj:"1.3.a",d:1,cat:"parts",t:"ms",pick:2,
 q:"BSW1 needs a 1-Gb/s uplink to a new switch in the warehouse, a 160 m cable run from the branch wiring closet. Which two cabling options support this link? (Choose two.)",
 o:[
  {t:"1000BASE-SX transceivers over multimode fiber",ok:true,x:"1000BASE-SX reaches roughly 220 to 550 m over multimode fiber depending on the fiber grade, so 160 m is well within range."},
  {t:"1000BASE-LX transceivers over single-mode fiber",ok:true,x:"1000BASE-LX over single-mode fiber reaches several kilometers. It is more reach than needed, but it works."},
  {t:"1000BASE-T over Cat 6 UTP",ok:false,x:"Twisted-pair Ethernet is limited to 100 m per segment, whatever the cable category."},
  {t:"1000BASE-T over Cat 6a shielded cable",ok:false,x:"Better cable improves noise immunity and supports 10GBASE-T, but the 100 m limit still applies."},
  {t:"A Cat 5e crossover cable, with auto-MDIX disabled on both ends",ok:false,x:"Crossover or straight-through only changes which pairs transmit and receive. It does not extend the 100 m limit."}
 ],
 w:"Copper twisted pair (10BASE-T to 10GBASE-T): 100 m. Multimode fiber (SX, larger core, cheaper optics): hundreds of meters inside buildings and campuses. Single-mode fiber (LX/LR, laser, 9-micron core): kilometers."},
{id:"b014",obj:"2.2.a",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. Guest users on BSW2 Fa0/13-20 (VLAN 50) get no DHCP lease. BSW2 Gi0/1 trunks to BSW1 Gi0/2, and BSW1 Gi0/1 trunks to BR1, which routes VLAN 50 on Gi0/0.50. Staff and voice VLANs work, and both switches use VTP transparent mode. What is the cause?",
 ex:"BSW1# show interfaces trunk\nPort        Mode             Encapsulation  Status        Native vlan\nGi0/1       on               802.1q         trunking      10\nGi0/2       on               802.1q         trunking      10\n\nPort        Vlans allowed on trunk\nGi0/1       10,20,40,50,90\nGi0/2       10,20,40,50,90\n\nPort        Vlans allowed and active in management domain\nGi0/1       10,20,40,90\nGi0/2       10,20,40,90\n\nPort        Vlans in spanning tree forwarding state and not pruned\nGi0/1       10,20,40,90\nGi0/2       10,20,40,90",
 o:[
  {t:"VLAN 50 does not exist in BSW1's VLAN database, so BSW1 does not forward its frames",ok:true,x:"VLAN 50 is allowed but missing from 'allowed and active in management domain'. A switch only carries VLANs that exist locally, so guest frames die at BSW1. Creating it with vlan 50 on BSW1 fixes the path."},
  {t:"VLAN 50 is not in the allowed list on BSW1's trunks",ok:false,x:"Both trunks list 10,20,40,50,90 as allowed. The allowed list is not the problem."},
  {t:"The trunks use native VLAN 10, which blocks tagged VLAN 50 frames",ok:false,x:"The native VLAN only decides which VLAN crosses the link untagged. Every other allowed VLAN is tagged and carried normally."},
  {t:"VTP pruning removed VLAN 50 because no BSW1 access port uses it",ok:false,x:"Pruning does not apply in transparent mode, and pruning would only affect the last list. VLAN 50 is already missing from the 'active' list."}
 ],
 w:"show interfaces trunk has three VLAN lists: allowed (configured), allowed and active (also exists locally), forwarding and not pruned (also STP forwarding). A VLAN dropping out of the second list does not exist on that switch."},
{id:"b015",obj:"6.7",d:6,cat:"api",t:"ms",pick:3,
 q:"Refer to the exhibit. A script receives this record for BR1 from the branch controller. Which three statements are true? (Choose three.)",
 ex:"{\n  \"hostname\": \"BR1\",\n  \"managementIp\": \"10.20.90.1\",\n  \"reachable\": true,\n  \"uptimeDays\": \"212\",\n  \"interfaces\": [\n    { \"name\": \"GigabitEthernet0/0\", \"vlan\": 10, \"ipv4\": \"10.20.10.1\" },\n    { \"name\": \"GigabitEthernet0/0.20\", \"vlan\": 20, \"ipv4\": \"10.20.20.1\" }\n  ],\n  \"location\": null\n}",
 o:[
  {t:"The value of \"interfaces\" is an array that contains two objects",ok:true,x:"Square brackets mark an array; each element in braces is an object with its own key/value pairs."},
  {t:"The value of \"reachable\" is a Boolean",ok:true,x:"true is written without quotes, which makes it the JSON Boolean literal rather than a string."},
  {t:"The value of \"vlan\" is a number in both interface objects",ok:true,x:"10 and 20 have no quotes, so they are numbers."},
  {t:"The value of \"uptimeDays\" is a number",ok:false,x:"\"212\" is in double quotes, so it is a string. A script that does math on it must convert it first."},
  {t:"The record is invalid because \"location\" has no value",ok:false,x:"null is a valid JSON value meaning 'no value'. The record parses correctly."},
  {t:"The outermost element is an array of key/value pairs",ok:false,x:"The record starts with a brace, so it is an object. Arrays use square brackets."}
 ],
 w:"JSON: objects {} hold key/value pairs with double-quoted keys; arrays [] hold ordered values; value types are string (quoted), number, true/false, null, object, array. A number in quotes is a string."},
{id:"b016",obj:"1.13.d",d:1,cat:"switching",t:"mc",
 q:"Refer to the exhibit. On BSW1, Fa0/1-12 are access ports in VLAN 10, and Gi0/1 and Gi0/2 are trunks carrying VLANs 10 and 20. The PC on Fa0/7 sends a unicast frame with destination MAC address 00e0.4c00.0c22. What does BSW1 do with the frame?",
 ex:"BSW1# show mac address-table dynamic\n          Mac Address Table\n-------------------------------------------\n\nVlan    Mac Address       Type        Ports\n----    -----------       --------    -----\n  10    0001.4200.0101    DYNAMIC     Gi0/1\n  10    00e0.4c00.0401    DYNAMIC     Fa0/5\n  10    00e0.4c00.0517    DYNAMIC     Fa0/7\n  20    0001.4200.0101    DYNAMIC     Gi0/1\n  20    00e0.4c00.0c22    DYNAMIC     Gi0/2\nTotal Mac Addresses for this criterion: 5",
 o:[
  {t:"Floods it out every other port that carries VLAN 10, because that address is unknown in VLAN 10",ok:true,x:"The lookup uses only the frame's own VLAN. 00e0.4c00.0c22 is known in VLAN 20, not VLAN 10, so this is an unknown unicast: it leaves all VLAN 10 access ports and both trunks except Fa0/7."},
  {t:"Forwards it only out Gi0/2, where that address was learned",ok:false,x:"That entry belongs to VLAN 20. A switch never uses another VLAN's entry, which is what keeps VLANs separate."},
  {t:"Forwards it out Gi0/1 to BR1 so it can be routed into VLAN 20",ok:false,x:"Only frames addressed to BR1's own MAC (0001.4200.0101) are sent to the router. A Layer 2 switch does not redirect traffic between VLANs."},
  {t:"Drops it because the destination is in a different VLAN",ok:false,x:"The switch has no VLAN 10 entry for the address, so it cannot conclude anything about where it lives. Unknown unicasts are flooded, not dropped."}
 ],
 w:"The MAC table is keyed by VLAN plus MAC. Known unicast goes out one port; unknown unicast, broadcast and most multicast are flooded within the VLAN, never back out the receiving port."},
{id:"b017",obj:"2.5.a",d:2,cat:"stp",t:"mc",
 q:"Refer to the exhibit. BSW1 must become the root bridge for VLAN 20, and BSW2's configuration must not change. Which command on BSW1 achieves this?",
 ex:"BSW1# show spanning-tree vlan 20\nVLAN0020\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    24596\n             Address     0001.4200.0100\n             Cost        4\n             Port        26 (GigabitEthernet0/2)\n             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec\n\n  Bridge ID  Priority    28692  (priority 28672 sys-id-ext 20)\n             Address     0001.4200.0200\n             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec\n             Aging Time  300 sec\n\nInterface           Role Sts Cost      Prio.Nbr Type\n------------------- ---- --- --------- -------- -----------------------\nGi0/2               Root FWD 4         128.26   P2p",
 o:[
  {t:"spanning-tree vlan 20 priority 20480",ok:true,x:"BSW1's bridge priority becomes 20500 (20480 + VLAN 20), lower than the root's 24596, so BSW1 wins the election whatever the MAC addresses."},
  {t:"spanning-tree vlan 20 priority 24576",ok:false,x:"That gives BSW1 24596, a tie with the current root. The tie goes to the lower MAC, and the root's 0001.4200.0100 is lower than BSW1's 0001.4200.0200, so the root does not change."},
  {t:"spanning-tree vlan 20 priority 24000",ok:false,x:"Bridge priority must be a multiple of 4096 from 0 to 61440. IOS rejects 24000."},
  {t:"spanning-tree vlan 20 root secondary",ok:false,x:"root secondary sets priority 28672, which BSW1 already has. It prepares a backup root, not a new primary."}
 ],
 w:"Bridge ID = priority (multiple of 4096) + VLAN ID (sys-id-ext) + MAC. Lowest wins; a priority tie falls to the lowest MAC. root primary sets 24576, or 4096 below the current root if that is not low enough."},
{id:"b018",obj:"1.5",d:1,cat:"tcpip",t:"mc",
 q:"A branch PC sends three 1000-byte TCP segments to an HQ server with relative sequence numbers 1, 1001 and 2001. The segment with sequence number 1001 is lost; the other two arrive. Which acknowledgment number does the server send after the third segment arrives?",
 o:[
  {t:"1001",ok:true,x:"TCP acknowledgments are cumulative and name the next byte the receiver expects. Bytes 1 to 1000 arrived and byte 1001 did not, so the server keeps asking for 1001 even though bytes 2001 to 3000 are buffered."},
  {t:"2001",ok:false,x:"That would acknowledge bytes 1001 to 2000, which never arrived."},
  {t:"3001",ok:false,x:"That would acknowledge everything, including the lost segment, and the PC would never resend it."},
  {t:"1000",ok:false,x:"The acknowledgment number is the next byte expected, not the last byte received."}
 ],
 w:"Sequence number = first byte in the segment; ACK = next byte expected (cumulative). A gap holds the ACK in place, and duplicate ACKs or a timeout trigger a resend. UDP has no sequencing, ACKs or retransmission."},
{id:"b019",obj:"2.1.a",d:2,cat:"vlan",t:"build",ordered:false,
 q:"BSW1 Fa0/9 is a new desk port. A staff PC (VLAN 10) connects through an IP phone that must use voice VLAN 20, the port must never negotiate a trunk, and it must start forwarding as soon as the link comes up. Interface configuration mode for Fa0/9 is already entered. Drag the commands that are required into the answer area. Leave the commands that do not apply.",
 pool:["switchport mode access","switchport trunk native vlan 20","switchport access vlan 10","switchport mode trunk","switchport voice vlan 20","spanning-tree portfast","switchport access vlan 20"],
 answer:[0,2,4,5],
 x:"A phone port stays an access port: the PC's untagged frames go to access VLAN 10 and the phone tags voice in VLAN 20 once the switch advertises it. PortFast makes this edge port forward immediately. Trunk mode and a native VLAN are not used for a phone, and access VLAN 20 would put the PC into the voice subnet.",
 w:"Data + voice on one access port: mode access, access vlan (data), voice vlan (voice), portfast. The phone tags voice with 802.1Q, yet the port stays an access port, not a trunk."},
{id:"b020",obj:"1.2.d",d:1,cat:"parts",t:"mc",
 q:"The company has 40 branches. Each branch router has one private WAN circuit to HQ and none to other branches, so a call between two branches passes through the HQ router. Which WAN topology does this describe?",
 o:[
  {t:"Hub and spoke",ok:true,x:"HQ is the hub and each branch is a spoke with a single circuit to it. Branch-to-branch traffic crosses the hub, which is cheap to build but adds a hop and makes the hub critical."},
  {t:"Full mesh",ok:false,x:"In a full mesh every site links to every other site. With 41 sites that would be 820 circuits."},
  {t:"Partial mesh",ok:false,x:"A partial mesh adds direct links between some important site pairs. Here no branch has a link to another branch."},
  {t:"Spine-leaf",ok:false,x:"Spine-leaf is a data center switching design where every leaf connects to every spine. It does not describe WAN circuits."}
 ],
 w:"Hub and spoke: fewest circuits, central control, hub is a single point of failure. Full mesh: n(n-1)/2 links, most resilient and costly. Partial mesh: only the pairs that matter. Single-homed vs dual-homed describes a site's internet links."},
{id:"b021",obj:"6.5",d:6,cat:"api",t:"order",
 q:"A script must list the branch devices known to the controller. The controller issues tokens at /api/v1/auth/token and returns devices at /api/v1/network-device. Drag the steps into the order the script performs them.",
 pool:["Send a GET to /api/v1/network-device with the token in the X-Auth-Token header","Send a POST to /api/v1/auth/token with the username and password in a Basic authorization header","Parse the device list from the JSON body of the 200 OK response","Read the token value from the JSON body of the authentication response"],
 answer:[1,3,0,2],
 x:"Token-based REST APIs authenticate once: the credentials go in an HTTP Basic header on a POST to the token endpoint, and the reply carries a token. Later requests present the token in a header instead of the password. The GET reads the resource, and a 200 OK carries the JSON data.",
 w:"REST auth types: HTTP Basic (base64 user:password, use HTTPS), token in a header after login, API key, OAuth. CRUD: POST create, GET read, PUT/PATCH update, DELETE delete."},
{id:"b022",obj:"2.2.c",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. BSW1 was replaced and its trunk to BR1 rebuilt. Phones in VLAN 20 still reach 10.20.20.1, but staff PCs in VLAN 10 cannot reach their gateway, 10.20.10.1. BR1 must not be changed. Which command on BSW1 Gi0/1 restores connectivity?",
 ex:"BR1# show running-config interface g0/0\ninterface GigabitEthernet0/0\n description BRANCH-LAN-TRUNK\n ip address 10.20.10.1 255.255.255.0\n ip nat inside\nend\n\nBR1# show running-config interface g0/0.20\ninterface GigabitEthernet0/0.20\n encapsulation dot1Q 20\n ip address 10.20.20.1 255.255.255.0\nend\n\nBSW1# show interfaces trunk\nPort        Mode             Encapsulation  Status        Native vlan\nGi0/1       on               802.1q         trunking      1\n\nPort        Vlans allowed on trunk\nGi0/1       10,20,30,40,50,90",
 o:[
  {t:"switchport trunk native vlan 10",ok:true,x:"BR1 serves VLAN 10 on the physical interface, which only handles untagged frames. With native VLAN 1, BSW1 tags VLAN 10 frames, and BR1 has no dot1Q 10 subinterface to accept them. Making VLAN 10 native sends it untagged, as BR1 expects."},
  {t:"switchport trunk allowed vlan add 10",ok:false,x:"VLAN 10 is already in the allowed list."},
  {t:"switchport trunk native vlan 20",ok:false,x:"Voice would then arrive untagged on BR1's physical interface and the phones would break, while VLAN 10 would still be tagged."},
  {t:"switchport mode access and switchport access vlan 10",ok:false,x:"An access port carries only VLAN 10, so the voice, camera, guest and management VLANs would lose their path to BR1."}
 ],
 w:"On a router-on-a-stick trunk, untagged frames go to the physical interface (or a subinterface with encapsulation dot1Q N native). The switch's native VLAN on that link must match, or that VLAN arrives tagged where the router expects none."},
{id:"b023",obj:"1.9.a",d:1,cat:"ipv6",t:"mc",
 q:"Refer to the exhibit. A PC in VLAN 10 configures itself with SLAAC from BR1's router advertisements. Which address does the PC use as its IPv6 default gateway?",
 ex:"BR1# show ipv6 interface g0/0\nGigabitEthernet0/0 is up, line protocol is up\n  IPv6 is enabled, link-local address is FE80::1\n  No Virtual link-local address(es):\n  Global unicast address(es):\n    2001:DB8:B1:10::1, subnet is 2001:DB8:B1:10::/64\n  Joined group address(es):\n    FF02::1\n    FF02::2\n    FF02::1:FF00:1\n  MTU is 1500 bytes\n  ICMP error messages limited to one every 100 milliseconds\n  ICMP redirects are enabled\n  ICMP unreachables are sent\n  ND DAD is enabled, number of DAD attempts: 1\n  ND reachable time is 30000 milliseconds (using 30000)\n  ND advertised reachable time is 0 (unspecified)\n  ND advertised retransmit interval is 0 (unspecified)\n  ND router advertisements are sent every 200 seconds\n  ND router advertisements live for 1800 seconds\n  Hosts use stateless autoconfig for addresses.",
 o:[
  {t:"FE80::1",ok:true,x:"Hosts take the gateway from the source address of the router advertisement, and routers always source RAs from their link-local address. A short fixed link-local such as FE80::1 makes the gateway easy to recognize."},
  {t:"2001:DB8:B1:10::1",ok:false,x:"The global address is reachable, but RAs are sourced from the link-local address, so that is what the PC installs as its gateway."},
  {t:"FF02::2",ok:false,x:"FF02::2 is the all-routers multicast group that hosts send router solicitations to. A gateway must be a unicast address."},
  {t:"FF02::1:FF00:1",ok:false,x:"This is the solicited-node multicast group for addresses ending in ::1, used by Neighbor Discovery. It cannot be a gateway."}
 ],
 w:"IPv6 hosts learn the prefix, prefix length and default gateway from RAs; the gateway is the router's link-local (FE80::/10) address. Global unicast 2000::/3, unique local FC00::/7, multicast FF00::/8."},
{id:"b024",obj:"2.3",d:2,cat:"l2link",t:"mc",
 q:"Refer to the exhibit. A third-party AP on BSW1 Fa0/18 supports LLDP but not CDP. The team wants it listed as a neighbor on BSW1. What should the engineer configure?",
 ex:"BSW1# show lldp neighbors\n% LLDP is not enabled\n\nBSW1# show cdp neighbors\nCapability Codes: R - Router, T - Trans Bridge, B - Source Route Bridge\n                  S - Switch, H - Host, I - IGMP, r - Repeater, P - Phone\n\nDevice ID        Local Intrfce     Holdtme    Capability  Platform  Port ID\nBR1              Gig 0/1           160        R I         ISR4321   Gig 0/0\nBSW2             Gig 0/2           155        S I         WS-C2960  Gig 0/1",
 o:[
  {t:"lldp run in global configuration mode",ok:true,x:"LLDP is disabled by default on IOS. lldp run turns it on globally, and every interface then sends and receives LLDP by default."},
  {t:"lldp enable under interface Fa0/18",ok:false,x:"There is no lldp enable interface command. Per-interface control uses lldp transmit and lldp receive, and neither works while LLDP is off globally."},
  {t:"cdp run in global configuration mode",ok:false,x:"CDP is already running, as the CDP output shows, and the AP does not speak CDP."},
  {t:"no cdp enable on Fa0/18 so the port falls back to LLDP",ok:false,x:"Disabling CDP does not start LLDP. The two protocols are configured independently."}
 ],
 w:"CDP: Cisco-proprietary, on by default, cdp run / cdp enable. LLDP (IEEE 802.1AB): vendor-neutral, off by default on IOS, lldp run / lldp transmit / lldp receive, shown with show lldp neighbors [detail]."},
{id:"b025",obj:"1.11.b",d:1,cat:"wlbasics",t:"mc",
 q:"A branch AP advertises the BR-STAFF and BR-GUEST SSIDs on its 5-GHz radio. A wireless survey shows both SSIDs on channel 36 from that AP, with BSSIDs that differ only in the last hex digit. What explains this?",
 o:[
  {t:"The AP gives each SSID on a radio its own BSSID, a MAC address derived from the radio's base MAC",ok:true,x:"One radio can serve several WLANs. Each gets its own BSSID so clients can tell the networks apart, and vendors derive them from the radio MAC, which is why they are nearly identical."},
  {t:"Two physical APs are mounted in the same spot, one for each SSID",ok:false,x:"A single radio can advertise several SSIDs. Consecutive BSSIDs on the same channel point to one radio."},
  {t:"The BSSID is the network name, and it changes with each SSID's security setting",ok:false,x:"The SSID is the name. The BSSID is a 48-bit MAC address that identifies one SSID on one AP radio."},
  {t:"One of the SSIDs is a rogue AP impersonating the branch network",ok:false,x:"Both SSIDs are the branch's own WLANs on the same radio. A rogue would normally show an unrelated MAC address."}
 ],
 w:"SSID: the network name (up to 32 characters). BSSID: the MAC address of one SSID on one AP radio. ESS: several APs sharing an SSID so clients can roam. IBSS: ad hoc, no AP."},
{id:"b026",obj:"2.1.b",d:2,cat:"vlan",t:"ms",pick:2,
 q:"Refer to the exhibit. BSW1 Gi0/1 and Gi0/2 are operating as trunks. Which two statements are true? (Choose two.)",
 ex:"BSW1# show vlan brief\n\nVLAN Name                             Status    Ports\n---- -------------------------------- --------- -------------------------\n1    default                          active    Fa0/6, Fa0/7, Fa0/8, Fa0/9\n                                                Fa0/10, Fa0/11, Fa0/12, Fa0/13\n                                                Fa0/14, Fa0/15, Fa0/16, Fa0/17\n                                                Fa0/18, Fa0/19, Fa0/20, Fa0/21\n                                                Fa0/22, Fa0/23, Fa0/24\n10   STAFF                            active    Fa0/1, Fa0/2, Fa0/3, Fa0/4\n                                                Fa0/5\n20   VOICE                            active\n90   MGMT                             active\n1002 fddi-default                     act/unsup\n1003 token-ring-default               act/unsup\n1004 fddinet-default                  act/unsup\n1005 trnet-default                    act/unsup",
 o:[
  {t:"A device plugged into Fa0/20 is placed in VLAN 1",ok:true,x:"Every switch port starts in VLAN 1, the default VLAN, until it is assigned elsewhere. Unused ports are best moved to an unused VLAN and shut down."},
  {t:"Gi0/1 and Gi0/2 are missing because show vlan brief does not list trunk ports",ok:true,x:"show vlan brief lists access ports under their VLAN. Trunks are checked with show interfaces trunk."},
  {t:"VLAN 1 can be deleted with no vlan 1 once every port has been moved out of it",ok:false,x:"VLAN 1 can never be deleted or renamed, and neither can VLANs 1002-1005."},
  {t:"VLAN 20 is not carried on the trunks because no access port is assigned to it",ok:false,x:"A VLAN with no access ports still exists and is carried on any trunk that allows it."},
  {t:"Fa0/23 and Fa0/24 are disabled because they are still in the default VLAN",ok:false,x:"Being in VLAN 1 does not disable a port. The ports forward normally in the default VLAN."},
  {t:"VLAN 1 can be renamed to UNUSED to mark it as a parking VLAN",ok:false,x:"IOS refuses to rename the default VLAN. Create a separate VLAN for parking unused ports."}
 ],
 w:"VLAN 1: default for every port, default native VLAN, cannot be deleted or renamed. Best practice: assign every used port, park unused ports in an unused VLAN and shut them down, and use a native VLAN other than 1."},
{id:"b027",obj:"6.3.a",d:6,cat:"sdn",t:"build",ordered:false,
 q:"Controller-based architectures separate the control plane from the data plane. Drag the functions that BR1 performs in its data plane into the answer area. Leave the functions that do not apply.",
 pool:["Exchanging OSPF hello packets with HQ1","Forwarding a packet out the interface chosen by the routing table","Building the routing table by running SPF","Rewriting the Ethernet header for the next hop before sending a packet","Accepting an SSH session from an administrator","Dropping a transit packet that matches a deny entry in an inbound ACL","Sending CDP advertisements to BSW1"],
 answer:[1,3,5],
 x:"The data plane does the per-packet work: look up the destination, apply ACL or NAT actions, rewrite the Layer 2 header and send the packet out. OSPF hellos, SPF and CDP build the information the data plane uses, which is control plane work. An SSH session to the router is management plane.",
 w:"Data plane: forwarding, encapsulation, ACL/NAT/QoS actions on transit traffic. Control plane: routing protocols, STP, ARP, CDP/LLDP. Management plane: SSH, SNMP, syslog, APIs. SDN moves much of the control plane into a controller."},
{id:"b028",obj:"1.6",d:1,cat:"tcpip",t:"ms",pick:2,
 q:"BR1 subinterface Gi0/0.40 is configured with ip address 10.20.40.97 255.255.255.224 for AP management. Which two addresses can be assigned to APs in this subnet? (Choose two.)",
 o:[
  {t:"10.20.40.126",ok:true,x:"/27 blocks are 32 addresses. 10.20.40.97 is in 10.20.40.96/27, which runs to broadcast 10.20.40.127, so .126 is the last usable host."},
  {t:"10.20.40.100",ok:true,x:"10.20.40.100 falls between .97 and .126, the usable range of 10.20.40.96/27."},
  {t:"10.20.40.127",ok:false,x:"10.20.40.127 is the subnet's broadcast address."},
  {t:"10.20.40.96",ok:false,x:"10.20.40.96 is the network address of the subnet."},
  {t:"10.20.40.128",ok:false,x:"10.20.40.128 starts the next /27 (.128-.159) and is that subnet's network address."},
  {t:"10.20.40.95",ok:false,x:"10.20.40.95 is the broadcast address of the previous /27 (.64-.95)."}
 ],
 w:"/27 = mask 255.255.255.224, block size 256 - 224 = 32. Subnets start at multiples of 32: 10.20.40.96/27 has network .96, hosts .97-.126, broadcast .127."},
{id:"b029",obj:"2.5.d",d:2,cat:"stp",t:"mc",
 q:"Refer to the exhibit. BSW1 is the root bridge for VLAN 10. Fa0/24 was configured with spanning-tree guard root because it connects to a contractor's lab switch. The contractor then set that switch's VLAN 10 priority to 0. What is the state of Fa0/24?",
 ex:"%SPANTREE-2-ROOTGUARD_BLOCK: Root guard blocking port FastEthernet0/24 on\n VLAN0010.\n\nBSW1# show spanning-tree vlan 10 | begin Interface\nInterface           Role Sts Cost      Prio.Nbr Type\n------------------- ---- --- --------- -------- -----------------------\nGi0/1               Desg FWD 4         128.25   P2p\nFa0/5               Desg FWD 19        128.5    P2p Edge\nFa0/24              Desg BKN*19        128.24   P2p *ROOT_Inc",
 o:[
  {t:"It is root-inconsistent and forwards nothing; it recovers by itself once the superior BPDUs stop",ok:true,x:"Root guard blocks a port that receives a superior BPDU instead of letting the other switch take over as root. The port shows BKN with ROOT_Inc and returns to forwarding automatically when those BPDUs stop."},
  {t:"It is error-disabled and must be reset with shutdown and no shutdown",ok:false,x:"That is BPDU guard's action. Root guard only blocks while superior BPDUs keep arriving and needs no manual recovery."},
  {t:"The contractor's switch is now the root bridge, and Fa0/24 is BSW1's root port",ok:false,x:"Preventing that is the whole point of root guard. BSW1 stays root and Fa0/24 stays a designated port that is blocked."},
  {t:"It stops sending and receiving BPDUs but keeps forwarding user traffic",ok:false,x:"That describes BPDU filter, which can create loops. Fa0/24 is blocked (BKN), so nothing is forwarded."}
 ],
 w:"Root guard: on designated ports that must never lead to the root; superior BPDU = root-inconsistent, auto-recovery. BPDU guard: on PortFast edge ports; any BPDU = err-disabled. Loop guard: stops a port going designated when BPDUs stop. BPDU filter: stops BPDUs."},
{id:"b030",obj:"1.7",d:1,cat:"tcpip",t:"mc",
 q:"BR1's NAT access list must match every source address in the private 172.16.0.0/12 block with one entry. Which entry does this?",
 o:[
  {t:"access-list 10 permit 172.16.0.0 0.15.255.255",ok:true,x:"A /12 mask is 255.240.0.0, and the wildcard is its inverse, 0.15.255.255. The entry matches 172.16.0.0 through 172.31.255.255, exactly the RFC 1918 block."},
  {t:"access-list 10 permit 172.16.0.0 0.0.255.255",ok:false,x:"This matches only 172.16.0.0/16 and misses 172.17.0.0 through 172.31.255.255."},
  {t:"access-list 10 permit 172.16.0.0 0.31.255.255",ok:false,x:"Ignoring 5 bits of the second octet matches 172.0.0.0 to 172.31.255.255, which includes public 172.0-172.15 addresses."},
  {t:"access-list 10 permit 172.16.0.0 255.240.0.0",ok:false,x:"That is the subnet mask, not a wildcard. Read as a wildcard it ignores the first 12 bits and requires the last 20 to be zero, matching addresses like 10.16.0.0, not the private block."}
 ],
 w:"RFC 1918: 10.0.0.0/8 (wildcard 0.255.255.255), 172.16.0.0/12 (0.15.255.255, so 172.16-172.31), 192.168.0.0/16 (0.0.255.255). Private addresses are not routed on the internet and need NAT to get there."},
{id:"b031",obj:"2.4",d:2,cat:"l2link",t:"ms",pick:2,
 q:"Refer to the exhibit. BSW1 Fa0/23 and Fa0/24 connect to BSW2 Fa0/23 and Fa0/24. Which two channel-group modes on BSW2's ports allow the bundle to form with LACP? (Choose two.)",
 ex:"BSW1# show running-config interface fa0/23\ninterface FastEthernet0/23\n switchport mode trunk\n channel-group 1 mode active\nend\n\nBSW1# show running-config interface fa0/24\ninterface FastEthernet0/24\n switchport mode trunk\n channel-group 1 mode active\nend",
 o:[
  {t:"active",ok:true,x:"Both sides send LACPDUs and negotiate the bundle."},
  {t:"passive",ok:true,x:"A passive port answers LACPDUs but never starts the exchange. BSW1 is active, so it starts and BSW2 answers."},
  {t:"on",ok:false,x:"on builds a static channel with no negotiation protocol. BSW1 sends LACPDUs that BSW2 never answers, so the modes do not match and the bundle does not form correctly."},
  {t:"desirable",ok:false,x:"desirable is a PAgP mode. LACP on one side and PAgP on the other never negotiate."},
  {t:"auto",ok:false,x:"auto is the passive PAgP mode and cannot negotiate with LACP."}
 ],
 w:"LACP (802.3ad, open): active+active or active+passive. PAgP (Cisco): desirable+desirable or desirable+auto. Static: on+on only. passive+passive and auto+auto never form. Members must match speed, duplex and VLAN settings."},
{id:"b032",obj:"1.13.b",d:1,cat:"switching",t:"order",
 q:"A store-and-forward switch receives a unicast frame on an access port. Drag the steps into the order the switch performs them.",
 pool:["Look up the destination MAC address in the MAC table for the frame's VLAN","Receive the entire frame and check its FCS, discarding it if the check fails","Send the frame out the matching port, or flood it in the VLAN if the destination is unknown","Add or refresh the source MAC address with the incoming port and VLAN, resetting its aging timer"],
 answer:[1,3,0,2],
 x:"A store-and-forward switch buffers the whole frame and verifies the FCS before acting on it, so damaged frames go no further. It learns from the source address, then makes its forwarding decision from the destination: a known unicast leaves one port, an unknown unicast is flooded within the VLAN.",
 w:"Learn from the source, forward on the destination. Dynamic entries age out after 300 seconds of silence by default. Cut-through switching starts forwarding once it has read the destination MAC and does not check the FCS first."},
{id:"b033",obj:"6.5",d:6,cat:"api",t:"mc",
 q:"Refer to the exhibit. A script uses one token to read and then rename a branch VLAN on the controller. What explains the result of the second request?",
 ex:"10:41:02 >> GET /api/v1/sites/branch-14/vlans/30 HTTP/1.1\n            X-Auth-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...\n10:41:02 << HTTP/1.1 200 OK\n\n10:41:05 >> PUT /api/v1/sites/branch-14/vlans/30 HTTP/1.1\n            X-Auth-Token: eyJhbGciOiJSUzI1NiIsInR5cCI6IkpXVCJ9...\n            Content-Type: application/json\n            {\"vlanId\": 30, \"name\": \"CAMERAS\"}\n10:41:05 << HTTP/1.1 403 Forbidden",
 o:[
  {t:"The token is valid, but its account is not authorized to change VLANs",ok:true,x:"403 Forbidden means the server knows who is calling and refuses the action. The same token worked for the GET three seconds earlier, so authentication succeeded; the role behind it lacks write rights."},
  {t:"The token has expired, and the script must request a new one",ok:false,x:"A missing, invalid or expired token returns 401 Unauthorized, and this token worked three seconds earlier."},
  {t:"PUT is not allowed; changing an existing resource requires POST",ok:false,x:"PUT (or PATCH) is the update verb; POST creates a new resource. A method the resource does not support would return 405."},
  {t:"The JSON body is malformed",ok:false,x:"A malformed body returns 400 Bad Request. This body is valid JSON."}
 ],
 w:"2xx success (200 OK, 201 Created, 204 No Content). 4xx client error (400 bad request, 401 not authenticated, 403 authenticated but not allowed, 404 not found). 5xx server error (500)."},
{id:"b034",obj:"2.5.c",d:2,cat:"stp",t:"mc",
 q:"An engineer enters spanning-tree portfast default in global configuration mode on BSW1, which has access ports Fa0/1-24 and trunks Gi0/1-2. What is the effect?",
 o:[
  {t:"PortFast is enabled on every port operating in access mode; the trunk ports are not affected",ok:true,x:"The global default applies only to non-trunking ports. Each access port becomes an edge port and moves straight to forwarding when a device connects."},
  {t:"PortFast is enabled on every port, including Gi0/1 and Gi0/2",ok:false,x:"Trunks need spanning-tree portfast trunk on the interface. The global default skips them, which protects the uplinks."},
  {t:"Only ports already configured with spanning-tree portfast become edge ports",ok:false,x:"The point of the global default is to enable PortFast on access ports without per-port commands."},
  {t:"BPDU guard is enabled on every access port",ok:false,x:"That takes spanning-tree portfast bpduguard default. With PortFast alone, a port that receives a BPDU simply loses its edge status."}
 ],
 w:"PortFast: edge ports skip discarding and learning at link-up. Per port: spanning-tree portfast. Global: spanning-tree portfast default (access ports only). Pair with BPDU guard: spanning-tree portfast bpduguard default."},
{id:"b035",obj:"1.12",d:1,cat:"wlbasics",t:"ms",pick:2,
 q:"The branch runs a small server that hosts both virtual machines and containers. Which two statements describe containers compared with virtual machines? (Choose two.)",
 o:[
  {t:"Containers on a host share the host operating system's kernel",ok:true,x:"A container engine isolates processes on one OS kernel. Each VM, by contrast, boots its own guest OS on virtual hardware from the hypervisor."},
  {t:"Containers are lightweight and usually start in seconds because they package only the app and its dependencies",ok:true,x:"With no guest OS to boot, containers start quickly and many more fit on one host than VMs."},
  {t:"Each container includes a full guest operating system with its own kernel",ok:false,x:"That describes a virtual machine."},
  {t:"Containers can run only on a type 1 hypervisor",ok:false,x:"Containers run on a container engine on an ordinary OS, which may itself be on bare metal or inside a VM."},
  {t:"A container can run an app built for a different kernel than the host's, such as a Windows app on a Linux host",ok:false,x:"Because containers share the host kernel, the app must suit that kernel. Running a different OS needs a VM."}
 ],
 w:"VM: hypervisor (type 1 bare metal, type 2 hosted) plus a full guest OS per VM; strong isolation, heavier. Container: engine on a host OS, shared kernel, app plus libraries; fast and dense. VRF: separate routing tables inside one router."},
{id:"b036",obj:"2.8",d:2,cat:"mgmt",t:"mc",
 q:"Refer to the exhibit. An audit requires that BR1's web management interface accept only encrypted sessions. SSH access must keep working. Which command meets the requirement?",
 ex:"BR1# show running-config | include http|line vty|transport\nip http server\nip http authentication local\nip http secure-server\nline vty 0 4\n transport input ssh",
 o:[
  {t:"no ip http server",ok:true,x:"ip http server is the clear-text HTTP listener on TCP 80. Removing it leaves ip http secure-server (HTTPS on TCP 443) as the only web access."},
  {t:"no ip http secure-server",ok:false,x:"This removes HTTPS and leaves the unencrypted HTTP listener, the opposite of the requirement."},
  {t:"transport input ssh under line vty 0 4",ok:false,x:"vty transport controls Telnet and SSH, and it is already SSH only. The web server does not use vty transport."},
  {t:"ip http authentication enable",ok:false,x:"This changes which password the web server checks, not whether the session is encrypted."}
 ],
 w:"Management access: console (local, out of band), Telnet TCP 23 (clear text), SSH TCP 22, HTTP TCP 80 (clear text), HTTPS TCP 443, cloud-managed dashboards. Central AAA: TACACS+ (TCP 49) or RADIUS (UDP 1812/1813)."},
{id:"b037",obj:"1.9.c",d:1,cat:"ipv6",t:"mc",
 q:"A PC in the branch camera VLAN must send a packet to the camera server 2001:db8:b1:30::5c:3a10 on its own subnet and has no neighbor cache entry for it. To which destination address does the PC send its Neighbor Solicitation?",
 o:[
  {t:"FF02::1:FF5C:3A10",ok:true,x:"The solicited-node group is FF02::1:FF followed by the last 24 bits of the target. The address ends in ...:005c:3a10, so the last 24 bits are 5C:3A10."},
  {t:"FF02::1:FF00:3A10",ok:false,x:"This uses only the last 16 bits. The solicited-node group takes 24 bits, which includes the 5C."},
  {t:"FF02::1",ok:false,x:"All-nodes multicast would interrupt every host on the link, like an IPv4 ARP broadcast. Neighbor Discovery uses the solicited-node group to avoid that."},
  {t:"FF02::2",ok:false,x:"All-routers is where hosts send router solicitations, not address resolution requests."}
 ],
 w:"Solicited-node = FF02::1:FF + last 24 bits of the unicast address. Other link-local groups: FF02::1 all nodes, FF02::2 all routers, FF02::1:2 DHCPv6 servers and relays."},
{id:"b038",obj:"2.6",d:2,cat:"wlan",t:"ms",pick:2,
 q:"A new branch will use cloud-managed APs: an engineer configures SSIDs and policies on a vendor web dashboard, and the APs pull their configuration from it. Which two statements describe this design? (Choose two.)",
 o:[
  {t:"Client data is switched locally at the branch and does not pass through the cloud",ok:true,x:"Only management and monitoring traffic goes to the cloud. User traffic goes from the AP to the local switch like any wired traffic."},
  {t:"Each AP needs outbound internet access to reach the dashboard for configuration and monitoring",ok:true,x:"The APs open connections to the cloud service to fetch configuration and report status, so the branch firewall must allow them out."},
  {t:"All client traffic is tunneled in CAPWAP to the cloud dashboard before it is forwarded",ok:false,x:"That would send every packet across the internet and back. Cloud-managed APs keep the data plane local."},
  {t:"Clients are disconnected as soon as the internet link fails",ok:false,x:"The APs keep their last configuration and keep serving clients. Only changes and monitoring stop until the link returns."},
  {t:"Each AP is configured individually through its own CLI or web page",ok:false,x:"That is the autonomous model. A cloud dashboard configures every AP from one place."}
 ],
 w:"Autonomous: each AP configured alone. Lightweight + WLC: CAPWAP to a controller (local mode tunnels data, FlexConnect switches locally). Cloud-managed: management plane in the cloud, data plane local, APs need outbound internet."},
{id:"b039",obj:"6.3.b",d:6,cat:"sdn",t:"mc",
 q:"The controller that manages the branch pushes configuration templates to BR1 and BSW1 and collects their state using NETCONF and SSH. Which interface does this describe?",
 o:[
  {t:"Southbound API",ok:true,x:"Southbound interfaces connect the controller to the devices it programs. NETCONF, RESTCONF, CLI over SSH, SNMP and OpenFlow are examples."},
  {t:"Northbound API",ok:false,x:"Northbound APIs face the applications and scripts above the controller, usually REST over HTTPS with JSON."},
  {t:"East-west interface between clustered controllers",ok:false,x:"East-west traffic synchronizes peer controllers. It does not program BR1 or BSW1."},
  {t:"The data plane",ok:false,x:"Pushing configuration and reading state are control and management functions. The data plane forwards user traffic."}
 ],
 w:"Northbound: apps and scripts to the controller (REST, JSON). Southbound: controller to devices (NETCONF, RESTCONF, OpenFlow, SNMP, CLI/SSH). The controller in the middle holds the network-wide view."},
{id:"b040",obj:"1.8",d:1,cat:"ipv6",t:"mc",
 q:"The branch has been assigned 2001:db8:b1::/48. The plan writes the VLAN number as the 16-bit subnet ID, so VLAN 30 uses subnet ID 0030. Which command gives BR1 Gi0/0.30 the first address in the VLAN 30 /64?",
 o:[
  {t:"ipv6 address 2001:db8:b1:30::1/64",ok:true,x:"The fourth hextet is the subnet ID (0030, written 30), and ::1 fills the interface ID with zeros and a final 1. The prefix length is /64."},
  {t:"ipv6 address 2001:db8:b1::30:1/64",ok:false,x:"The :: fills zeros before 30, so the subnet ID becomes 0 and 30 lands in the interface ID. The address is in 2001:db8:b1::/64."},
  {t:"ipv6 address 2001:db8:b1:30::1/48",ok:false,x:"/48 is the whole site prefix. The interface would treat every branch subnet as on-link."},
  {t:"ipv6 address 2001:db8:b1:3::1/64",ok:false,x:"Leading zeros can be dropped but trailing zeros cannot. :3: means 0003, a different subnet."}
 ],
 w:"A /48 site plus a 16-bit subnet ID gives 65,536 /64s. Shortening rules: drop leading zeros in a hextet, replace one run of all-zero hextets with ::, never drop trailing zeros."},
{id:"b041",obj:"2.7",d:2,cat:"wlan",t:"mc",
 q:"Branch APs run in FlexConnect mode. They get their management address untagged in VLAN 40 and switch the BR-STAFF and BR-GUEST WLANs locally to VLANs 10 and 50. How should the BSW1 port for each AP be configured?",
 o:[
  {t:"As an 802.1Q trunk with native VLAN 40, allowing VLANs 10, 40 and 50",ok:true,x:"The AP sends its own CAPWAP and management traffic untagged and tags locally switched client traffic with each WLAN's VLAN. A trunk with the AP management VLAN as native carries both."},
  {t:"As an access port in VLAN 40",ok:false,x:"An access port carries only VLAN 40, so the tagged client frames for VLANs 10 and 50 would be dropped."},
  {t:"As an access port in VLAN 10 with PortFast",ok:false,x:"The AP's management traffic would land in the staff VLAN, and guest frames tagged for VLAN 50 would be dropped."},
  {t:"As a trunk with native VLAN 1 that allows only VLANs 10 and 50",ok:false,x:"The AP's untagged management traffic would land in VLAN 1 instead of 40, and VLAN 40 is not allowed anyway."}
 ],
 w:"AP in local mode: access port (client data rides the CAPWAP tunnel). FlexConnect with local switching: trunk, native = AP management VLAN. WLC distribution ports: trunks, often bundled as a LAG (EtherChannel mode on)."},
{id:"b042",obj:"1.11.c",d:1,cat:"wlbasics",t:"mc",
 q:"A laptop at the far end of the branch warehouse reports a received signal of -67 dBm from the AP, and the AP measures a noise floor of -92 dBm on that channel. What is the signal-to-noise ratio?",
 o:[
  {t:"25 dB",ok:true,x:"SNR is the signal minus the noise floor: -67 - (-92) = 25 dB. The signal is 25 dB above the noise, which is generally enough for data and voice."},
  {t:"-25 dB",ok:false,x:"This subtracts the signal from the noise. A usable link always has the signal above the noise, so SNR is positive."},
  {t:"159 dB",ok:false,x:"Adding the two magnitudes is not meaningful. In dB, a ratio is found by subtraction."},
  {t:"67 dB",ok:false,x:"67 is just the signal level with the sign dropped. SNR compares the signal with the noise floor."}
 ],
 w:"dBm is absolute power; dB is a ratio. SNR (dB) = signal (dBm) - noise (dBm). +3 dB doubles power and -3 dB halves it; +10 dB is ten times. RSSI closer to 0 is stronger (-60 beats -75)."},
{id:"b043",obj:"2.1.c",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. Cameras in VLAN 30 cannot ping their gateway, 10.20.30.1. Hosts in VLANs 10 and 20 work normally. Which change fixes the problem?",
 ex:"BR1# show running-config | section interface GigabitEthernet0/0\ninterface GigabitEthernet0/0\n description BRANCH-LAN-TRUNK\n ip address 10.20.10.1 255.255.255.0\n ip nat inside\ninterface GigabitEthernet0/0.20\n encapsulation dot1Q 20\n ip address 10.20.20.1 255.255.255.0\ninterface GigabitEthernet0/0.30\n encapsulation dot1Q 3\n ip address 10.20.30.1 255.255.255.0\n\nBSW1# show interfaces trunk\nPort        Mode             Encapsulation  Status        Native vlan\nGi0/1       on               802.1q         trunking      10\n\nPort        Vlans allowed on trunk\nGi0/1       10,20,30,40,50,90\n\nPort        Vlans allowed and active in management domain\nGi0/1       10,20,30,40,50,90\n\nPort        Vlans in spanning tree forwarding state and not pruned\nGi0/1       10,20,30,40,50,90",
 o:[
  {t:"Change Gi0/0.30 to encapsulation dot1Q 30",ok:true,x:"BSW1 tags camera frames with VLAN 30, but Gi0/0.30 accepts only tag 3. The subinterface number is just a label; the encapsulation command decides which VLAN it serves."},
  {t:"Add VLAN 30 to the allowed list on BSW1 Gi0/1",ok:false,x:"VLAN 30 is already allowed, active and forwarding on the trunk."},
  {t:"Renumber the subinterface as Gi0/0.3 to match its encapsulation",ok:false,x:"The number does not have to match anything. Gi0/0.3 with dot1Q 3 would still ignore frames tagged for VLAN 30."},
  {t:"Make VLAN 30 the native VLAN on BSW1 Gi0/1",ok:false,x:"Untagged camera frames would reach BR1's physical interface, which serves 10.20.10.0/24, and VLAN 10 would arrive tagged and break."}
 ],
 w:"Router-on-a-stick checks: on the router, encapsulation dot1Q N and an IP in the right subnet per subinterface; on the switch, the VLAN allowed, active and forwarding on the trunk, and native VLANs that match."},
{id:"b044",obj:"6.1",d:6,cat:"sdn",t:"mc",
 q:"The branch routers are provisioned from a controller template. A compliance report shows that 7 of 60 routers no longer match the template after engineers made local CLI changes during outages. Which benefit of automation does the report demonstrate?",
 o:[
  {t:"Detecting configuration drift so devices can be returned to a known standard",ok:true,x:"With templates as the source of truth, the controller can compare each device's running configuration with the intended one and flag or fix differences. Manual networks rarely notice drift until it causes an outage."},
  {t:"Faster forwarding, because the controller takes over packet switching",ok:false,x:"The controller does not forward user traffic. Compliance checking is a management function."},
  {t:"Removing any need for CLI access on network devices",ok:false,x:"The report itself shows engineers still used the CLI. Automation reduces manual changes; it does not remove the CLI."},
  {t:"Replacing routing protocols with static routes generated by the controller",ok:false,x:"The report is about configuration consistency, not about how routes are learned."}
 ],
 w:"Automation brings consistent templates, fewer typing errors, fast rollout at scale, compliance and drift detection, and repeatable changes. Engineers shift from typing commands to defining intent and reviewing results."},
{id:"b045",obj:"1.1.h",d:1,cat:"parts",t:"ms",pick:2,
 q:"IP phones and APs on BSW1 receive power over their Ethernet cables. Which two statements about PoE on BSW1 are true? (Choose two.)",
 o:[
  {t:"BSW1 is the power sourcing equipment (PSE), and the phones and APs are powered devices (PDs)",ok:true,x:"The switch port supplies the power and the end device draws it. A midspan injector can also act as the PSE when the switch lacks PoE."},
  {t:"BSW1 applies power only after detecting a valid PoE signature, so a non-PoE laptop on the same port is not harmed",ok:true,x:"The PSE tests for the PD's signature resistance, then classifies the device before powering it. A device without a signature never gets power."},
  {t:"802.3af PoE supplies up to 30 W per port",ok:false,x:"802.3af supplies 15.4 W at the switch port. 30 W is 802.3at (PoE+), and 802.3bt raises it to 60 W or 90 W."},
  {t:"PoE requires a separate power cable alongside the data cable",ok:false,x:"PoE delivers power over the same twisted-pair cable that carries the data."},
  {t:"Every port draws its full class wattage from the budget whether or not a device is connected",ok:false,x:"Power is allocated only to ports with a detected PD, which is why the switch can track a total power budget."}
 ],
 w:"PoE (802.3af) 15.4 W, PoE+ (802.3at) 30 W, 802.3bt 60 W or 90 W, measured at the PSE. The switch detects and classifies the PD before powering it and allocates from a total power budget."},
{id:"b046",obj:"2.9",d:2,cat:"wlan",t:"mc",
 q:"Refer to the exhibit. Guests on the BR-GUEST WLAN can reach each other's laptops. The requirement is that the WLC must not pass traffic directly between guest clients. Which change meets the requirement?",
 ex:"WLANs > Edit 'BR-GUEST'\n Advanced:\n   Allow AAA Override        : [ ] Enabled\n   Coverage Hole Detection   : [x] Enabled\n   Enable Session Timeout    : [x] 1800 (secs)\n   Aironet IE                : [x] Enabled\n   Override Interface ACL    : IPv4 None   IPv6 None\n   P2P Blocking Action       : Disabled\n   Client Exclusion          : [x] Enabled  60 (secs)\n   Maximum Allowed Clients   : 0\n   DHCP Server               : [ ] Override\n   DHCP Addr. Assignment     : [ ] Required",
 o:[
  {t:"Set P2P Blocking Action to Drop",ok:true,x:"Peer-to-peer blocking stops the controller from bridging traffic between clients on the same WLAN. Drop discards it; Forward-UpStream sends it to the upstream switch so a router or firewall can decide."},
  {t:"Check DHCP Addr. Assignment Required",ok:false,x:"This forces clients to get a DHCP address before they can pass traffic. It stops static-address users, not client-to-client traffic."},
  {t:"Lower the session timeout to 300 seconds",ok:false,x:"Clients would simply reauthenticate more often; their traffic to each other is unaffected."},
  {t:"Enable Allow AAA Override",ok:false,x:"AAA override lets a RADIUS server assign a VLAN, QoS or ACL per user. The guest WLAN uses no RADIUS server, and it would not block peer traffic."}
 ],
 w:"WLC WLAN tabs: General (SSID, status, interface), Security (Layer 2 WPA2/WPA3 PSK or 802.1X, Layer 3 web auth), QoS (Platinum voice, Gold video, Silver best effort, Bronze background), Advanced (timeouts, P2P blocking, client exclusion, DHCP required)."},
{id:"b047",obj:"1.2.f",d:1,cat:"parts",t:"mc",
 q:"The branch's file server will move from a rack in the branch closet to a virtual machine in a public cloud IaaS service. Which statement is true after the move?",
 o:[
  {t:"The provider maintains the physical hosts and hypervisor, while the company still manages the server's OS and application",ok:true,x:"In IaaS the provider runs the facility, hardware, storage and virtualization layer. The customer still owns everything from the guest OS up, including patching."},
  {t:"The company must buy the server hardware up front, so costs shift from operating to capital expense",ok:false,x:"This is reversed. Cloud services are rented, shifting spending from capital to operating expense."},
  {t:"Branch users reach the server without depending on the WAN or internet circuit",ok:false,x:"The server is now off site, so the branch's internet or WAN circuit becomes critical for reaching it."},
  {t:"The provider becomes responsible for patching the server's operating system",ok:false,x:"That is true of SaaS and largely of PaaS. With IaaS, the guest OS is still the customer's responsibility."}
 ],
 w:"On premises: you own and run everything (capital expense). Cloud: provider runs the infrastructure, pay as you go. IaaS: you manage OS and up; PaaS: you manage apps and data; SaaS: you just use the application."},
{id:"b048",obj:"6.3",d:6,cat:"sdn",t:"ms",pick:2,
 q:"BR1 will join an SD-WAN fabric. It builds IPsec tunnels to HQ over both the internet circuit and a private MPLS circuit, and branch subnets are advertised only inside those tunnels. Which two statements are true? (Choose two.)",
 o:[
  {t:"The internet and MPLS networks form the underlay, which must provide reachability between the tunnel endpoints",ok:true,x:"The underlay is the transport. It only has to carry packets between the routers' WAN addresses; it never sees the traffic inside the tunnels."},
  {t:"The tunnels form the overlay, so the providers never need routes for the branch's 10.20.0.0/16 subnets",ok:true,x:"Branch and HQ subnets are exchanged inside the overlay. The providers see only tunnel packets between the edge routers' transport addresses."},
  {t:"Because an overlay exists, BR1 no longer needs any routing in the underlay",ok:false,x:"The tunnel endpoints must still reach each other across each transport, for example with a default route toward each provider."},
  {t:"The SD-WAN controllers forward user traffic between the branch and HQ",ok:false,x:"The controllers handle control and management. User traffic flows edge to edge through the tunnels."},
  {t:"The underlay must use the same 10.20.0.0/16 addressing as the branch LAN",ok:false,x:"The underlay uses the providers' addressing, such as BR1's public address on Gi0/2. The overlay hides the LAN addressing from it."}
 ],
 w:"Underlay: the physical or transport network and its routing. Overlay: virtual topology of tunnels (IPsec, VXLAN, GRE) built on top. Fabric: underlay plus overlay managed as one system, as in SD-Access or SD-WAN."},
{id:"b049",obj:"2.9",d:2,cat:"wlan",t:"order",
 q:"On the WLC, an engineer must create a new WLAN with SSID BR-IOT that uses WPA2-Personal and places clients on the iot interface. Drag the steps into a valid order.",
 pool:["Open the WLANs tab, choose Create New and click Go","Click Apply to save the WLAN settings","Enter the profile name and the SSID BR-IOT, then click Apply","On the Security > Layer 2 tab, select WPA2 with PSK key management and enter the passphrase","On the General tab, set the interface to iot and check Status Enabled"],
 answer:[0,2,4,3,1],
 alt:[[0,2,3,4,1]],
 x:"The WLAN must exist before it can be edited, so Create New and the profile/SSID page come first; that first Apply opens the WLAN's edit page. The General and Security tabs can be completed in either order, and the final Apply saves the settings from every tab.",
 w:"WLC GUI: WLANs > Create New > Go, then profile name, SSID and ID, Apply, then General (status, interface), Security (Layer 2 WPA2/WPA3 with PSK or 802.1X), QoS and Advanced, then Apply."},
{id:"b050",obj:"6.4",d:6,cat:"sdn",t:"mc",
 q:"An engineer asks a generative AI assistant to write the IOS configuration for a new branch router from a short text description. Which practice is most important before the output is used?",
 o:[
  {t:"Review and test the generated configuration, because generative AI can produce plausible but incorrect commands",ok:true,x:"Generative models predict likely text; they can invent commands, use the wrong syntax for the platform or miss security settings. Peer review and a lab test catch these before production."},
  {t:"Apply it directly, because AI output generated from vendor documentation is always valid",ok:false,x:"No generative model guarantees correctness. Treat the output like a draft from a new team member."},
  {t:"Feed it labeled traffic data first, because generative AI needs flow records to write configurations",ok:false,x:"Labeled flow data trains predictive models such as anomaly detectors. A text prompt is enough for a generative assistant to produce a draft."},
  {t:"Use the output only as a traffic baseline, because generative AI forecasts link utilization",ok:false,x:"Baselines and forecasts come from predictive AI and machine learning. Generative AI creates new content such as text or configuration."}
 ],
 w:"Generative AI creates content (configs, summaries, chat answers) and can hallucinate, so validate it. Predictive AI/ML learns from data to forecast or flag anomalies, such as capacity trends or unusual client onboarding times."},
];
