/* CCNA 200-301 v1.1 — Exam A, part 1 (a001–a050). Campus build-out theme: access/distribution switches, VLANs, trunks,
   Rapid PVST+, campus wireless, plus automation. All text original. Spec: dev/specs/ccna.md §6. */
export const CCNA_BANK_A_P1 = [
{id:"a001",obj:"2.5.b",d:2,cat:"stp",t:"mc",
 q:"Refer to the exhibit. ACC-3 uplinks to DIST-1 on Gi0/1 and to DIST-2 on Gi0/2. DIST-1 is the root bridge for VLAN 10 and DIST-2 reaches the root over its own direct 1-Gb/s link. The fiber on ACC-3 Gi0/1 is cut. What happens on ACC-3 in VLAN 10?",
 ex:"ACC-3# show spanning-tree vlan 10\nVLAN0010\n  Spanning tree enabled protocol rstp\n  Root ID    Priority    24586\n             Address     0001.4200.0100\n             Cost        4\n             Port        25 (GigabitEthernet0/1)\n             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec\n\n  Bridge ID  Priority    32778  (priority 32768 sys-id-ext 10)\n             Address     0001.4200.0300\n             Hello Time   2 sec  Max Age 20 sec  Forward Delay 15 sec\n             Aging Time  300 sec\n\nInterface           Role Sts Cost      Prio.Nbr Type\n------------------- ---- --- --------- -------- --------------\nGi0/1               Root FWD 4         128.25   P2p\nGi0/2               Altn BLK 4         128.26   P2p",
 o:[
  {t:"Gi0/2 becomes the root port and starts forwarding almost at once, with a root path cost of 8",ok:true,x:"An RSTP alternate port is a pre-computed backup root port. When the root port fails it is promoted and moved to forwarding without timers. The new cost is DIST-2's cost of 4 plus Gi0/2's own cost of 4."},
  {t:"Gi0/2 becomes the root port but spends 30 seconds in listening and learning before it forwards",ok:false,x:"That is legacy 802.1D behaviour (2 x 15-second forward delay). Rapid PVST+ promotes an alternate port to root port immediately."},
  {t:"ACC-3 declares itself root for VLAN 10 until DIST-1's BPDUs reach it again",ok:false,x:"ACC-3 still receives superior BPDUs on Gi0/2. In RSTP, DIST-2 sends BPDUs carrying DIST-1 as root, and a priority of 32778 can never beat 24586."},
  {t:"Gi0/2 becomes a backup port and remains in the discarding state",ok:false,x:"A backup port is a redundant link to a segment the same switch already serves as designated, such as two ports on one hub. Gi0/2 leads to another switch, so it is alternate and becomes root port here."}
 ],
 w:"RSTP alternate port = backup path to the root via another switch; it takes over as root port instantly. Root path cost = neighbor's advertised cost + local port cost."},
{id:"a002",obj:"1.6",d:1,cat:"tcpip",t:"mc",
 q:"The new staff VLAN on DIST-1 must hold 450 hosts. The address plan gives it the next free block starting at 10.40.4.0, and the SVI must take the first usable address. Which configuration gives VLAN 10 the smallest subnet that fits?",
 o:[
  {t:"interface vlan 10 / ip address 10.40.4.1 255.255.254.0",ok:true,x:"A /23 has 9 host bits: 2^9 - 2 = 510 usable addresses, enough for 450. 10.40.4.0 is on a /23 boundary (4 is a multiple of 2), so .4.1 is the first host."},
  {t:"interface vlan 10 / ip address 10.40.4.1 255.255.255.0",ok:false,x:"A /24 holds only 254 hosts, well short of 450."},
  {t:"interface vlan 10 / ip address 10.40.4.1 255.255.252.0",ok:false,x:"A /22 (1022 hosts) would work but is twice as large as needed. The question asks for the smallest subnet that fits."},
  {t:"interface vlan 10 / ip address 10.40.4.0 255.255.254.0",ok:false,x:"10.40.4.0 is the network address of 10.40.4.0/23. IOS rejects it as an interface address (bad mask / network address)."}
 ],
 w:"Hosts = 2^h - 2. 450 hosts needs h = 9, which is /23 (255.255.254.0), block size 2 in the third octet."},
{id:"a003",obj:"6.7",d:6,cat:"api",t:"ms",pick:2,
 q:"Refer to the exhibit. A script pulls this inventory record for an access switch from the campus controller. Which two statements about the data are true? (Choose two.)",
 ex:"{\n  \"switch\": \"ACC-3\",\n  \"mgmt\": {\n    \"ip\": \"10.40.100.13\",\n    \"vlan\": 100\n  },\n  \"ports\": [\n    { \"name\": \"Gi0/1\", \"mode\": \"trunk\",  \"enabled\": true },\n    { \"name\": \"Fa0/7\", \"mode\": \"access\", \"vlan\": 10, \"enabled\": true },\n    { \"name\": \"Fa0/8\", \"mode\": \"access\", \"vlan\": 10, \"enabled\": false }\n  ]\n}",
 o:[
  {t:"The value of \"ports\" is an array that holds three objects",ok:true,x:"Square brackets mark an array; each element inside is an object in curly braces, and there are three of them."},
  {t:"The value of \"enabled\" is a Boolean, not a string",ok:true,x:"true and false appear without quotes, so they are JSON Booleans. \"true\" in quotes would be a string."},
  {t:"The value of \"mgmt\" is an array of two strings",ok:false,x:"\"mgmt\" is an object (curly braces) with two key/value pairs. One value is a string (\"10.40.100.13\") and the other is a number (100)."},
  {t:"The VLAN value 100 is a string because VLAN IDs are labels",ok:false,x:"100 has no quotes, so JSON treats it as a number. Only quoted values are strings."},
  {t:"The record is invalid because the Gi0/1 object has no \"vlan\" key",ok:false,x:"JSON does not require objects in an array to share the same keys. Missing keys are a data-model question, not a syntax error."},
  {t:"The outermost structure of the record is an array",ok:false,x:"The record starts with { and ends with }, so the outermost structure is an object."}
 ],
 w:"JSON: {} object of key/value pairs, [] ordered array, quoted text = string, bare numbers = number, true/false = Boolean, null = null. Keys are always quoted strings."},
{id:"a004",obj:"1.13.c",d:1,cat:"switching",t:"mc",
 q:"Refer to the exhibit. On ACC-2, Fa0/1-12 are access ports in VLAN 10, Fa0/13-24 are access ports in VLAN 20, and Gi0/1 is a trunk allowing all VLANs. PC1 on Fa0/1 sends a unicast frame to 00e0.4c00.0601. What does ACC-2 do with the frame?",
 ex:"ACC-2# show mac address-table\n          Mac Address Table\n-------------------------------------------\n\nVlan    Mac Address       Type        Ports\n----    -----------       --------    -----\n  10    0001.4200.0100    DYNAMIC     Gi0/1\n  10    00e0.4c00.0301    DYNAMIC     Fa0/1\n  10    00e0.4c00.0401    DYNAMIC     Fa0/2\n  20    0001.4200.0100    DYNAMIC     Gi0/1\n  20    00e0.4c00.0501    DYNAMIC     Fa0/13\nTotal Mac Addresses for this criterion: 5",
 o:[
  {t:"It floods the frame out every other forwarding port in VLAN 10, including trunk Gi0/1",ok:true,x:"00e0.4c00.0601 is not in the VLAN 10 table, so it is an unknown unicast. The switch floods it within VLAN 10 only, out every port except the one it came in on, and the trunk carries it tagged for VLAN 10."},
  {t:"It drops the frame because the destination MAC address is unknown",ok:false,x:"Switches never drop unknown unicast by default; they flood it so the frame can still reach the host, then learn its port when it replies."},
  {t:"It floods the frame out every port on the switch in both VLAN 10 and VLAN 20",ok:false,x:"Flooding is bounded by the VLAN. A frame received in VLAN 10 is never sent out VLAN 20 access ports."},
  {t:"It forwards the frame only out Gi0/1 toward the default gateway's MAC address",ok:false,x:"A switch does not use the default gateway for Layer 2 forwarding. The destination is unknown, so the frame is flooded in VLAN 10, not sent to one port."}
 ],
 w:"Known unicast: forward out one port. Unknown unicast, broadcast and (by default) multicast: flood out all ports in the same VLAN except the ingress port."},
{id:"a005",obj:"2.2.c",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. The campus standard is native VLAN 99 on every trunk. ACC-3 Gi0/1 is cabled to DIST-1 Gi1/0/3. Which action fixes the problem and keeps the standard?",
 ex:"ACC-3#\n%CDP-4-NATIVE_VLAN_MISMATCH: Native VLAN mismatch discovered on\n GigabitEthernet0/1 (99), with DIST-1 GigabitEthernet1/0/3 (1).\n\nACC-3# show interfaces trunk\nPort        Mode             Encapsulation  Status        Native vlan\nGi0/1       on               802.1q         trunking      99\n\nPort        Vlans allowed on trunk\nGi0/1       10,20,30,99,100",
 o:[
  {t:"On DIST-1 Gi1/0/3, enter switchport trunk native vlan 99",ok:true,x:"The message shows ACC-3 uses native 99 and DIST-1 Gi1/0/3 uses 1. Setting DIST-1's trunk to native 99 makes both ends match and follows the standard."},
  {t:"On ACC-3 Gi0/1, enter switchport trunk native vlan 1",ok:false,x:"Both ends would then match and the CDP message would stop, but the trunk would use native VLAN 1, which breaks the campus standard."},
  {t:"On DIST-1 Gi1/0/3, enter switchport trunk allowed vlan add 99",ok:false,x:"The allowed list controls which VLANs cross the trunk. It does not change which VLAN is sent untagged, so the native mismatch remains."},
  {t:"On ACC-3 Gi0/1, enter switchport nonegotiate",ok:false,x:"This only turns off DTP. The link is already trunking; the problem is the untagged VLAN on each end."}
 ],
 w:"Native VLAN must match on both ends of an 802.1Q trunk. A mismatch merges the two VLANs' untagged traffic; CDP reports it with %CDP-4-NATIVE_VLAN_MISMATCH."},
{id:"a006",obj:"1.10",d:1,cat:"tcpip",t:"mc",
 q:"Refer to the exhibit. A technician statically addressed this workstation in the engineering VLAN, whose gateway SVI is 10.40.21.129/25. The workstation can ping other hosts in its VLAN but cannot reach anything in other buildings. What is the cause?",
 ex:"C:\\> ipconfig /all\n\nEthernet adapter Ethernet:\n\n   Connection-specific DNS Suffix  . :\n   Physical Address. . . . . . . . . : 3C-52-82-1A-7E-04\n   DHCP Enabled. . . . . . . . . . . : No\n   IPv4 Address. . . . . . . . . . . : 10.40.21.130(Preferred)\n   Subnet Mask . . . . . . . . . . . : 255.255.255.128\n   Default Gateway . . . . . . . . . : 10.40.21.1\n   DNS Servers . . . . . . . . . . . : 10.40.0.53",
 o:[
  {t:"The default gateway is outside the host's subnet; it should be 10.40.21.129",ok:true,x:"10.40.21.130/25 lives in 10.40.21.128/25 (.129-.254). 10.40.21.1 is in 10.40.21.0/25, so the PC cannot ARP for it and has no working path off its subnet."},
  {t:"The subnet mask is invalid because a 10.x.x.x address requires 255.0.0.0",ok:false,x:"Classful masks have not applied for decades. A /25 on a 10.x address is perfectly valid and matches the SVI."},
  {t:"DHCP is disabled, so the workstation has no route to other subnets",ok:false,x:"Static addressing works fine if the values are right. DHCP is only one way to receive the gateway; the gateway entered here is the problem."},
  {t:"The DNS server is on a different subnet, which blocks off-subnet traffic",ok:false,x:"DNS servers are normally on other subnets. DNS affects name lookups, not whether packets can leave the subnet."}
 ],
 w:"Check a client's IP, mask and gateway together: the gateway must be an address inside the host's own subnet."},
{id:"a007",obj:"6.5",d:6,cat:"api",t:"mc",
 q:"The campus controller exposes each switch port as a resource at /api/v1/interfaces/{id}. An engineer must change only the description of one port, sending just the description field and leaving every other attribute as it is. Which HTTP method fits?",
 o:[
  {t:"PATCH",ok:true,x:"PATCH applies a partial update: only the fields in the body change, and everything else on the resource is kept."},
  {t:"PUT",ok:false,x:"PUT replaces the whole resource with the representation in the body. Sending only the description could reset or remove the attributes that were left out."},
  {t:"POST",ok:false,x:"POST creates a new resource (or triggers an action) under a collection. It is not the method for editing one field of an existing port."},
  {t:"GET",ok:false,x:"GET only reads a resource. It never changes anything on the server."}
 ],
 w:"CRUD to HTTP: Create = POST, Read = GET, Update = PUT (replace) or PATCH (partial), Delete = DELETE."},
{id:"a008",obj:"2.6",d:2,cat:"wlan",t:"mc",
 q:"Security staff want one lightweight AP in the main library to stop serving clients and spend all of its time scanning every channel for rogue APs and wireless attack signatures, reporting what it finds to the WLC. Which AP mode should be set?",
 o:[
  {t:"Monitor",ok:true,x:"Monitor mode turns the AP into a dedicated sensor. It serves no clients and scans all channels for rogue detection, wIPS and location data."},
  {t:"Local",ok:false,x:"Local mode is the default. The AP serves clients on its channel and only goes off-channel briefly to scan, so it is not dedicated to detection."},
  {t:"FlexConnect",ok:false,x:"FlexConnect lets an AP across a WAN keep serving clients and switch traffic locally if the link to the WLC fails. It still serves clients."},
  {t:"Bridge",ok:false,x:"Bridge mode builds mesh or point-to-point wireless backhaul links between APs. It has nothing to do with dedicated rogue scanning."}
 ],
 w:"AP modes: local (default, serves clients, CAPWAP to WLC), FlexConnect (remote sites, local switching), monitor (sensor only), sniffer (captures for an analyzer), bridge (mesh), SE-Connect (spectrum analysis)."},
{id:"a009",obj:"1.4",d:1,cat:"parts",t:"mc",
 q:"Refer to the exhibit. A print server cabled directly to ACC-6 Fa0/14 is slow. Its NIC was hard-coded to 100 Mb/s full duplex; the switch port was left at its defaults. What explains the counters, and what fixes the problem?",
 ex:"ACC-6# show interfaces fastEthernet0/14\nFastEthernet0/14 is up, line protocol is up (connected)\n  Hardware is Fast Ethernet, address is 00a1.b2c3.4d0e\n  MTU 1500 bytes, BW 100000 Kbit/sec, DLY 100 usec,\n     reliability 255/255, txload 3/255, rxload 2/255\n  Encapsulation ARPA, loopback not set\n  Half-duplex, 100Mb/s, media type is 10/100BaseTX\n  ...\n     0 input errors, 0 CRC, 0 frame, 0 overrun, 0 ignored\n     48211 packets output, 6930214 bytes, 0 underruns\n     0 output errors, 2215 collisions, 3 interface resets\n     0 babbles, 836 late collision, 0 deferred",
 o:[
  {t:"Autonegotiation failed and the switch fell back to half duplex; set duplex full and speed 100 on Fa0/14",ok:true,x:"With the peer hard-coded, the switch senses 100 Mb/s but cannot learn duplex, so it falls back to half. It then sees collisions, including late ones, while the full-duplex NIC never waits. Matching the settings ends the mismatch."},
  {t:"The speeds do not match; set speed 10 on Fa0/14",ok:false,x:"Both sides already run 100 Mb/s, as the output shows. A real speed mismatch normally keeps the link down entirely, and 10 Mb/s would make it slower."},
  {t:"Electrical noise is corrupting frames; replace the cable with shielded cable",ok:false,x:"Noise shows up as CRC and input errors, and both are zero here. The errors are collisions on a half-duplex port."},
  {t:"Too many devices share the collision domain; replace the hub on Fa0/14 with a switch",ok:false,x:"The stem says the print server connects directly. Collisions on a point-to-point link mean one side is half duplex, not that the segment is crowded."}
 ],
 w:"Duplex mismatch fingerprint: the half-duplex side logs collisions and late collisions; the full-duplex side logs CRC errors and runts. Hard-code both ends or let both negotiate."},
{id:"a010",obj:"1.9.d",d:1,cat:"ipv6",t:"mc",
 q:"The VLAN 30 SVI on DIST-2 has MAC address 0c2a.7f31.4b90 and is configured with ipv6 address 2001:db8:acad:30::/64 eui-64. Which global unicast address does the SVI get?",
 o:[
  {t:"2001:DB8:ACAD:30:E2A:7FFF:FE31:4B90",ok:true,x:"Split the MAC into 0c2a7f and 314b90, insert FFFE between them, and flip the 7th bit of the first byte: 0x0C (0000 1100) becomes 0x0E (0000 1110). Interface ID 0E2A:7FFF:FE31:4B90."},
  {t:"2001:DB8:ACAD:30:C2A:7FFF:FE31:4B90",ok:false,x:"FFFE was inserted correctly but the universal/local (7th) bit was not flipped. Modified EUI-64 always inverts it, so 0C becomes 0E."},
  {t:"2001:DB8:ACAD:30:E2A:FFFE:7F31:4B90",ok:false,x:"FFFE belongs in the exact middle of the 48-bit MAC, after the third byte (0c2a7f), not after the second."},
  {t:"2001:DB8:ACAD:30::E2A:7F31:4B90",ok:false,x:"This drops FFFE entirely. Modified EUI-64 builds a 64-bit ID by inserting FFFE; a 48-bit MAC alone cannot fill it."}
 ],
 w:"Modified EUI-64: split the MAC in half, insert FFFE, flip bit 7 of the first byte (00 to 02, 0C to 0E, 52 to 50)."},
{id:"a011",obj:"2.1.a",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. An IP phone is cabled to ACC-4 Fa0/7, and a staff PC is cabled to the phone's PC port. How do the two devices' frames arrive on Fa0/7?",
 ex:"ACC-4# show running-config interface fastEthernet0/7\ninterface FastEthernet0/7\n description Room 2-114 phone + PC\n switchport access vlan 10\n switchport mode access\n switchport voice vlan 30\n spanning-tree portfast\nend",
 o:[
  {t:"Phone frames carry an 802.1Q tag for VLAN 30; PC frames arrive untagged and go into VLAN 10",ok:true,x:"With a voice VLAN, the switch tells the phone (via CDP) to tag voice traffic with VLAN 30. The PC's frames pass through the phone untagged and land in the access VLAN, 10."},
  {t:"Both arrive untagged, and the switch sorts them into VLANs 10 and 30 by MAC address",ok:false,x:"An access port does not sort untagged frames into VLANs by MAC. The voice VLAN works because the phone tags its frames."},
  {t:"Both arrive tagged: the phone uses VLAN 30 and the PC uses VLAN 10",ok:false,x:"The PC is unaware of VLANs and sends untagged frames. Only the phone tags, and only with the voice VLAN."},
  {t:"Fa0/7 becomes a full trunk to the phone carrying all VLANs, with the PC tagged in VLAN 10",ok:false,x:"The port stays in access mode; show interfaces trunk will not list it. It accepts only untagged data-VLAN frames and frames tagged with the voice VLAN."}
 ],
 w:"Access port + voice VLAN: data VLAN untagged for the PC, voice VLAN tagged by the phone (learned via CDP or LLDP-MED). The port is still an access port."},
{id:"a012",obj:"6.2",d:6,cat:"sdn",t:"mc",
 q:"The campus team configures each of its 140 switches over CLI, one device at a time. It is evaluating a controller-based design for the new buildings. Which statement correctly describes the controller-based approach?",
 o:[
  {t:"Intent and policy are defined once on a central controller, which programs the devices through southbound APIs",ok:true,x:"The controller centralizes the management and much of the control logic, then pushes configuration to every device. Engineers stop touching each box individually."},
  {t:"All user traffic is forwarded through the controller, which replaces the switches' data plane",ok:false,x:"The data plane stays on the switches; frames and packets are still forwarded in hardware on each device. Sending every frame through a controller would not scale."},
  {t:"Devices no longer need management IP addresses, because the controller reaches them over Layer 2",ok:false,x:"The controller talks to devices over IP using protocols such as NETCONF, RESTCONF or SSH, so devices still need management addresses."},
  {t:"Switches keep no forwarding tables, because the controller makes every forwarding decision",ok:false,x:"Devices still hold MAC, routing and forwarding tables. The controller programs policy; it does not replace per-packet forwarding on each device."}
 ],
 w:"Traditional: distributed control plane, box-by-box config. Controller-based: centralized policy and management, devices programmed via southbound APIs, data plane stays on the devices."},
{id:"a013",obj:"1.11.a",d:1,cat:"wlbasics",t:"mc",
 q:"Three APs cover overlapping areas of a lecture hall in a US deployment using the 2.4-GHz band (channels 1-11). AP-1 uses channel 1 and AP-2 uses channel 6. Which channel should AP-3 use so that none of the three APs overlap?",
 o:[
  {t:"11",ok:true,x:"2.4-GHz channels are 5 MHz apart but about 22 MHz wide, so only channels five apart do not overlap. In the US that set is 1, 6 and 11."},
  {t:"3",ok:false,x:"Channel 3 overlaps both channel 1 and channel 6, adding interference to both APs."},
  {t:"8",ok:false,x:"Channel 8 is only two channels (10 MHz) from 6, so their spectrum overlaps heavily."},
  {t:"9",ok:false,x:"Channel 9 is three channels (15 MHz) from 6, which still overlaps a roughly 22-MHz-wide signal."}
 ],
 w:"2.4 GHz nonoverlapping channels in the US: 1, 6, 11. Use 5 GHz when you need more clean channels."},
{id:"a014",obj:"2.4",d:2,cat:"l2link",t:"mc",
 q:"Refer to the exhibit. ACC-5 Gi0/1-2 connect to DIST-2 Gi0/1-2. Both switches have channel-group 1 mode passive on both ports. Which change lets the bundle form using LACP?",
 ex:"ACC-5# show etherchannel summary\nFlags:  D - down        P - bundled in port-channel\n        I - stand-alone s - suspended\n        R - Layer3      S - Layer2\n        U - in use      f - failed to allocate aggregator\n\nNumber of channel-groups in use: 1\nNumber of aggregators:           1\n\nGroup  Port-channel  Protocol    Ports\n------+-------------+-----------+-----------------------------\n1      Po1(SD)       LACP        Gi0/1(I) Gi0/2(I)",
 o:[
  {t:"On ACC-5 Gi0/1-2, change to channel-group 1 mode active",ok:true,x:"Passive only answers LACP; it never starts the negotiation. With one side active and the other passive, LACP runs and the ports bundle (flags P, Po1 SU)."},
  {t:"On ACC-5 Gi0/1-2, change to channel-group 1 mode desirable",ok:false,x:"Desirable is a PAgP mode. PAgP and LACP cannot negotiate with each other, so this cannot bundle with DIST-2's LACP passive ports."},
  {t:"On ACC-5 Gi0/1-2, change to channel-group 1 mode on",ok:false,x:"Mode on sends no negotiation frames and bundles only with a peer that is also on. Against LACP passive it does not form a working channel."},
  {t:"Shut down and re-enable interface Port-channel1 on both switches",ok:false,x:"Bouncing the port-channel changes nothing. Passive/passive will still never send the first LACP packet."}
 ],
 w:"EtherChannel modes that form a channel: LACP active+active or active+passive; PAgP desirable+desirable or desirable+auto; on+on. Passive+passive and auto+auto never form."},
{id:"a015",obj:"1.5",d:1,cat:"tcpip",t:"build",ordered:false,
 q:"The campus is moving its phone system to VoIP, which carries the audio stream in RTP over UDP. Drag the characteristics of UDP into the answer area. Leave the characteristics that do not apply.",
 pool:["Connectionless: no session setup before data is sent","No acknowledgments or retransmission of lost segments","Fixed 8-byte header","Three-way handshake before the first data segment","Sequence numbers used to reorder and recover segments","Sliding-window flow control","Low overhead suited to delay-sensitive voice"],
 answer:[0,1,2,6],
 x:"UDP sends datagrams with no handshake, no acknowledgments, no retransmission and no windowing, using an 8-byte header (ports, length, checksum). That low overhead suits voice: a late packet is useless, so resending it would only add delay. The handshake, sequencing for recovery and sliding windows belong to TCP.",
 w:"TCP: connection-oriented, reliable, ordered, flow-controlled, 20-byte minimum header. UDP: connectionless, best effort, 8-byte header; used by voice/video, DNS queries, DHCP, TFTP, SNMP, syslog."},
{id:"a016",obj:"2.9",d:2,cat:"wlan",t:"mc",
 q:"Refer to the exhibit. Wi-Fi handsets on the CAMPUS-VOICE WLAN have choppy audio whenever the library is busy. Which change on this WLAN gives voice traffic the correct treatment?",
 ex:"WLANs > Edit 'CAMPUS-VOICE'\n  [General] [Security] [QoS] [Policy-Mapping] [Advanced]\n\n  QoS tab\n    Quality of Service (QoS) : Bronze (background)\n    Application Visibility   : [ ] Enabled\n    AVC Profile              : none\n    WMM Policy               : Allowed",
 o:[
  {t:"Set Quality of Service (QoS) to Platinum (voice)",ok:true,x:"On the WLC, Platinum is the profile for voice, Gold for video, Silver for best effort and Bronze for background. Bronze puts the handsets' calls in the lowest queue."},
  {t:"Set Quality of Service (QoS) to Gold (video)",ok:false,x:"Gold is better than Bronze but is meant for video. Voice belongs in Platinum, the highest profile."},
  {t:"Set Quality of Service (QoS) to Silver (best effort)",ok:false,x:"Silver is the default best-effort profile, so voice would still compete equally with all data traffic."},
  {t:"Set WMM Policy to Disabled",ok:false,x:"WMM is what carries 802.11e priority markings over the air. Disabling it removes wireless QoS, and many voice clients need WMM."}
 ],
 w:"WLC QoS profiles: Platinum = voice, Gold = video, Silver = best effort (default), Bronze = background. Voice WLANs also need WMM allowed or required."},
{id:"a017",obj:"1.7",d:1,cat:"tcpip",t:"mc",
 q:"A contractor's addressing plan for the new science building lists the four subnets below. The campus edge translates only RFC 1918 addresses. Which subnet is NOT a private address range and will cause problems?",
 o:[
  {t:"172.32.10.0/24",ok:true,x:"The private Class B block is 172.16.0.0/12, which runs 172.16.0.0 to 172.31.255.255. 172.32.x.x is outside it and is public address space."},
  {t:"172.31.200.0/24",ok:false,x:"172.31.x.x is the last /16 inside 172.16.0.0/12, so it is private."},
  {t:"10.255.8.0/24",ok:false,x:"Everything in 10.0.0.0/8 is private, including 10.255.x.x."},
  {t:"192.168.250.0/24",ok:false,x:"192.168.0.0/16 is private, so any 192.168.x.0/24 is fine."}
 ],
 w:"RFC 1918: 10.0.0.0/8, 172.16.0.0/12 (172.16-172.31), 192.168.0.0/16. 172.32 and above, and 172.15 and below, are public."},
{id:"a018",obj:"2.3",d:2,cat:"l2link",t:"mc",
 q:"Refer to the exhibit. A technician consoled into ACC-2 must document the uplink. Which statement is correct?",
 ex:"ACC-2# show cdp neighbors detail\n-------------------------\nDevice ID: DIST-1\nEntry address(es):\n  IP address: 10.40.100.1\nPlatform: cisco WS-C3650-24TS,  Capabilities: Router Switch IGMP\nInterface: GigabitEthernet0/1,  Port ID (outgoing port): GigabitEthernet1/0/1\nHoldtime : 127 sec\n\nadvertisement version: 2\nDuplex: full\n\nTotal cdp entries displayed : 1",
 o:[
  {t:"ACC-2 Gi0/1 connects to DIST-1 Gi1/0/1, and DIST-1 advertises 10.40.100.1",ok:true,x:"In CDP output, Interface is the local port on ACC-2 and Port ID is the neighbor's port. The Entry address is the IP the neighbor advertises."},
  {t:"DIST-1 Gi0/1 connects to ACC-2 Gi1/0/1",ok:false,x:"This swaps the two ends. Interface (Gi0/1) is local to ACC-2, the switch where the command ran; Port ID (Gi1/0/1) belongs to DIST-1."},
  {t:"ACC-2 learned this from LLDP, which IOS runs by default",ok:false,x:"This is CDP output. CDP is on by default on Cisco IOS devices; LLDP is off until lldp run is entered."},
  {t:"The neighbor has been up for 127 seconds",ok:false,x:"Holdtime is how long ACC-2 keeps the entry if no new CDP message arrives (counting down from 180 by default). It says nothing about the neighbor's uptime."}
 ],
 w:"CDP fields: Device ID = neighbor name, Interface = your local port, Port ID = neighbor's port, Holdtime = seconds left before the entry expires. Only the detail form shows IP and version."},
{id:"a019",obj:"6.3",d:6,cat:"sdn",t:"mc",
 q:"Refer to the exhibit. The new campus fabric is described below. Which part of the design is the underlay?",
 ex:"Campus fabric (text topology)\n  Border nodes : CORE-1, CORE-2\n  Edge nodes   : ACC-1 ... ACC-8\n  Links        : every edge node has routed /31 uplinks to both\n                 border nodes; IS-IS advertises each node's loopback\n  Users        : VLAN 10 hosts on ACC-1 talk to VLAN 10 hosts on\n                 ACC-7 inside VXLAN tunnels between edge loopbacks\n  Controller   : manages the fabric through a REST-based GUI/API",
 o:[
  {t:"The routed /31 links and IS-IS that give every node reachability to the other loopbacks",ok:true,x:"The underlay is the physical network and its routing protocol. It only has to deliver packets between node loopbacks so the tunnels can be built on top."},
  {t:"The VXLAN tunnels between edge-node loopbacks",ok:false,x:"Tunnels built over the routed network are the overlay. They carry user traffic across the fabric."},
  {t:"VLAN 10 stretched between ACC-1 and ACC-7",ok:false,x:"The stretched VLAN is a service the overlay provides to users. The underlay routes only between nodes and has no VLAN 10."},
  {t:"The controller's REST API",ok:false,x:"The API is the management and northbound side of the design. It configures the fabric but is neither the underlay nor the overlay."}
 ],
 w:"Underlay = physical links + routing between devices. Overlay = virtual tunnels (VXLAN, etc.) over it carrying user traffic. Fabric = underlay + overlay managed as one."},
{id:"a020",obj:"1.12",d:1,cat:"wlbasics",t:"mc",
 q:"CORE-1 must carry guest Wi-Fi traffic and the building-management (HVAC) network. Both use 10.0.0.0/24, and they must never route to each other, yet both share CORE-1's uplinks. Which technology lets CORE-1 keep a separate routing table for each?",
 o:[
  {t:"VRFs, with each network in its own VRF",ok:true,x:"A VRF is a separate routing and forwarding table inside one router. Overlapping prefixes are fine because each VRF only sees its own routes, and traffic cannot cross between them unless leaked on purpose."},
  {t:"Separate VLANs for each network on CORE-1",ok:false,x:"VLANs separate Layer 2 broadcast domains. Their SVIs still share CORE-1's single global routing table, which cannot hold 10.0.0.0/24 twice."},
  {t:"A Type 1 hypervisor running a virtual router for each network",ok:false,x:"Server virtualization could host separate virtual routers, but it does not give CORE-1 itself multiple routing tables. VRFs are the built-in feature for that."},
  {t:"Containers running each network's DHCP service",ok:false,x:"Containers isolate applications on a host OS. They have no effect on how CORE-1 routes the two networks."}
 ],
 w:"VRF = virtual routing table on one device; allows overlapping IPs and path isolation. VMs share hardware through a hypervisor; containers share the host OS kernel."},
{id:"a021",obj:"2.5.d",d:2,cat:"stp",t:"ms",pick:2,
 q:"Access ports Fa0/1-24 on ACC-8 connect to classroom PCs. A port must start forwarding as soon as a PC connects, and must be error-disabled if a BPDU ever arrives on it, for example from a switch a student plugs in. Which two interface commands meet both requirements? (Choose two.)",
 o:[
  {t:"spanning-tree portfast",ok:true,x:"PortFast makes an access port an edge port that skips straight to forwarding when the link comes up."},
  {t:"spanning-tree bpduguard enable",ok:true,x:"BPDU guard error-disables the port the moment any BPDU is received, which stops a rogue switch from joining the topology."},
  {t:"spanning-tree guard root",ok:false,x:"Root guard reacts only to superior BPDUs and puts the port in root-inconsistent (blocking) state. It does not err-disable the port and ignores inferior BPDUs."},
  {t:"spanning-tree bpdufilter enable",ok:false,x:"BPDU filter stops sending and processing BPDUs on the port. It would hide a loop instead of shutting the port."},
  {t:"spanning-tree guard loop",ok:false,x:"Loop guard protects non-designated ports from becoming designated when BPDUs stop arriving. It is for uplinks, not edge ports."},
  {t:"switchport nonegotiate",ok:false,x:"This disables DTP. It has no effect on STP or BPDUs."}
 ],
 w:"Edge ports: PortFast + BPDU guard. Root guard on ports that should never lead to the root (from the distribution side). Loop guard on uplinks. BPDU filter only with care."},
{id:"a022",obj:"1.2.b",d:1,cat:"parts",t:"mc",
 q:"Refer to the exhibit. Which design change best supports the planned growth?",
 ex:"Current campus (two-tier, collapsed core)\n  Core/distribution pair : CD-1, CD-2 (data center building)\n  Buildings B1-B3         : access switches dual-homed to CD-1/CD-2\n\nPlanned growth (next three years)\n  Buildings B4-B12 added, each with its own distribution pair\n  (DIST-4A/4B ... DIST-12A/12B) feeding that building's\n  access switches",
 o:[
  {t:"Add a dedicated core layer that interconnects every building's distribution pair",ok:true,x:"With many distribution blocks, a separate core (three-tier) gives each building just two uplinks to the core and avoids a mesh between distribution pairs. It also keeps fast, simple transport in the middle."},
  {t:"Run a full mesh of links between all the distribution pairs",ok:false,x:"Ten-plus distribution pairs in a full mesh would need dozens of links and grow quadratically with every new building. This is the problem a core layer solves."},
  {t:"Trunk every new access switch directly to CD-1 and CD-2 and skip building distribution",ok:false,x:"That creates long Layer 2 paths and very large STP/broadcast domains across buildings, and runs out of ports on CD-1/CD-2."},
  {t:"Rebuild the campus as a spine-leaf fabric with every access switch connected to every spine",ok:false,x:"Spine-leaf suits data center east-west traffic between servers. Connecting every closet switch in twelve buildings to every spine is not practical for a campus."}
 ],
 w:"Two-tier (collapsed core) fits small campuses. Add a core (three-tier) when there are many distribution blocks. Spine-leaf is the data center design."},
{id:"a023",obj:"2.7",d:2,cat:"wlan",t:"mc",
 q:"WLC-1, an AireOS controller, has both distribution ports cabled to DIST-1 Gi1/0/23-24, and LAG is enabled on the controller. Which configuration must DIST-1 use on those two ports?",
 o:[
  {t:"An 802.1Q trunk bundled with channel-group 5 mode on",ok:true,x:"AireOS LAG does not run LACP or PAgP, so the switch side must be a static EtherChannel (mode on). The bundle is a trunk carrying the WLC's management and client VLANs."},
  {t:"An 802.1Q trunk bundled with channel-group 5 mode active",ok:false,x:"LACP active waits for LACP replies that an AireOS controller never sends, so the bundle does not form."},
  {t:"An 802.1Q trunk bundled with channel-group 5 mode desirable",ok:false,x:"Desirable starts PAgP, which the AireOS controller does not support either, so no bundle forms."},
  {t:"Two separate access ports in the management VLAN, with no EtherChannel",ok:false,x:"With LAG enabled, the WLC treats its ports as one logical link. It needs a bundle on the switch, and an access port would carry only one VLAN."}
 ],
 w:"AireOS WLC LAG = static EtherChannel (mode on) trunk on the switch. Lightweight APs in local mode usually use access ports in the AP VLAN."},
{id:"a024",obj:"1.6",d:1,cat:"tcpip",t:"mc",
 q:"Refer to the exhibit. Which address can be statically assigned to a lab PC in VLAN 20?",
 ex:"DIST-2# show running-config interface vlan 20\ninterface Vlan20\n description Student labs\n ip address 10.40.20.65 255.255.255.224\nend",
 o:[
  {t:"10.40.20.94",ok:true,x:"A /27 has a block size of 32: .0, .32, .64, .96. .65 is in 10.40.20.64/27, with hosts .65-.94 and broadcast .95. .94 is the last usable host."},
  {t:"10.40.20.95",ok:false,x:".95 is the broadcast address of 10.40.20.64/27 and cannot be assigned to a host."},
  {t:"10.40.20.96",ok:false,x:".96 is the network address of the next subnet, 10.40.20.96/27, so it is outside VLAN 20."},
  {t:"10.40.20.62",ok:false,x:".62 belongs to 10.40.20.32/27 (.33-.62), a different subnet from the SVI."}
 ],
 w:"Block size = 256 - mask octet (256 - 224 = 32). Find the multiple of the block size at or below the address: that's the network. Next block minus 1 is the broadcast."},
{id:"a025",obj:"6.3.b",d:6,cat:"sdn",t:"mc",
 q:"A Python script on an operations server requests device inventory and client-health scores from the campus SDN controller using REST calls over HTTPS. Which interface is the script using?",
 o:[
  {t:"The controller's northbound API",ok:true,x:"Northbound APIs face up from the controller toward applications, scripts and dashboards. REST over HTTPS is the usual form."},
  {t:"The controller's southbound API",ok:false,x:"Southbound APIs face down from the controller toward the network devices (NETCONF, RESTCONF, OpenFlow, SSH/CLI). The script is not a network device."},
  {t:"The data plane of the access switches",ok:false,x:"The data plane forwards user traffic on each device. The script talks to the controller, not through device forwarding logic."},
  {t:"The fabric underlay",ok:false,x:"The underlay is the routed physical network between fabric nodes. It is transport, not an API."}
 ],
 w:"Northbound = apps to controller (usually REST). Southbound = controller to devices (NETCONF, RESTCONF, OpenFlow, CLI/SSH)."},
{id:"a026",obj:"2.8",d:2,cat:"mgmt",t:"mc",
 q:"The campus wants switch administrators authenticated against a central server. Each command an administrator enters must be authorized separately, and the whole body of every AAA packet must be encrypted. Which protocol meets these requirements?",
 o:[
  {t:"TACACS+",ok:true,x:"TACACS+ (TCP 49) separates authentication, authorization and accounting, so it can authorize each command, and it encrypts the entire packet body. That makes it the usual choice for device administration."},
  {t:"RADIUS",ok:false,x:"RADIUS (UDP 1812/1813) combines authentication and authorization and encrypts only the password field. It is the usual choice for network access (802.1X, VPN), not per-command device administration."},
  {t:"Local usernames with login local on the vty lines",ok:false,x:"Local accounts live on each switch, so there is no central server and no per-command authorization."},
  {t:"SSH version 2",ok:false,x:"SSH encrypts the management session itself. It is a transport, not an AAA protocol, and does not authorize commands."}
 ],
 w:"TACACS+: Cisco-developed, TCP 49, full-body encryption, separate AAA, per-command authorization (device admin). RADIUS: open standard, UDP 1812/1813, password-only encryption (network access)."},
{id:"a027",obj:"1.1.h",d:1,cat:"parts",t:"mc",
 q:"The new lecture-hall APs each need 25.5 W delivered at the AP to run every radio at full power. Which is the minimum PoE standard the access switch ports must support?",
 o:[
  {t:"IEEE 802.3at (PoE+)",ok:true,x:"802.3at supplies up to 30 W at the switch port, which leaves 25.5 W at the powered device after cable loss: exactly what these APs need."},
  {t:"IEEE 802.3af (PoE)",ok:false,x:"802.3af supplies 15.4 W at the port and about 12.95 W at the device. The AP would boot in a reduced-power mode or not at all."},
  {t:"IEEE 802.3bt (PoE++)",ok:false,x:"802.3bt (60 W or 90 W at the port) would work, but it is more than needed. The question asks for the minimum standard."},
  {t:"IEEE 802.3ad",ok:false,x:"802.3ad is the original link aggregation (LACP) standard. It has nothing to do with power."}
 ],
 w:"PoE at the switch port / at the device: 802.3af 15.4 W / 12.95 W; 802.3at (PoE+) 30 W / 25.5 W; 802.3bt Type 3 60 W, Type 4 90 W."},
{id:"a028",obj:"2.2.a",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. ACC-6 Gi0/1 connects to DIST-2 Gi0/2. Neither port has been configured, and DIST-2 Gi0/2 shows the same switchport output. Which single change makes the link a trunk?",
 ex:"ACC-6# show interfaces gigabitEthernet0/1 switchport\nName: Gi0/1\nSwitchport: Enabled\nAdministrative Mode: dynamic auto\nOperational Mode: static access\nAdministrative Trunking Encapsulation: dot1q\nOperational Trunking Encapsulation: native\nNegotiation of Trunking: On\nAccess Mode VLAN: 1 (default)\nTrunking Native Mode VLAN: 1 (default)",
 o:[
  {t:"On DIST-2 Gi0/2, enter switchport mode trunk",ok:true,x:"Both ends are dynamic auto, which only responds to DTP and never asks, so the link stays access. A static trunk on one end sends DTP requests, and the dynamic auto end agrees to trunk."},
  {t:"On both ports, enter switchport nonegotiate",ok:false,x:"Nonegotiate turns off DTP and is rejected while the port is dynamic. Even on a static port it would only stop negotiation; it would not make the link a trunk."},
  {t:"On both ports, enter switchport trunk native vlan 99",ok:false,x:"This sets which VLAN would be untagged if the link were a trunk. It does not change the dynamic auto mode, so the link stays access."},
  {t:"On both ports, enter switchport trunk allowed vlan all",ok:false,x:"The allowed list only applies once a port is trunking. It does not change the administrative mode."}
 ],
 w:"DTP: trunk + anything except access = trunk; desirable + desirable/auto = trunk; auto + auto = access. Best practice: static trunk plus switchport nonegotiate."},
{id:"a029",obj:"1.8",d:1,cat:"ipv6",t:"mc",
 q:"Refer to the exhibit. Which interface command produced the first global unicast address listed?",
 ex:"EDGE-R1# show ipv6 interface gigabitEthernet0/0\nGigabitEthernet0/0 is up, line protocol is up\n  IPv6 is enabled, link-local address is FE80::201:42FF:FE00:101\n  No Virtual link-local address(es):\n  Global unicast address(es):\n    2001:DB8:ACAD:20:201:42FF:FE00:101, subnet is 2001:DB8:ACAD:20::/64 [EUI]\n    2001:DB8:ACAD:21::1, subnet is 2001:DB8:ACAD:21::/64\n  Joined group address(es):\n    FF02::1\n    FF02::2\n    FF02::1:FF00:1\n    FF02::1:FF00:101\n  MTU is 1500 bytes",
 o:[
  {t:"ipv6 address 2001:db8:acad:20::/64 eui-64",ok:true,x:"The [EUI] flag shows the router built the interface ID itself with modified EUI-64 from its MAC (0001.4200.0101 becomes 0201:42FF:FE00:0101). Only the eui-64 keyword produces that flag."},
  {t:"ipv6 address 2001:db8:acad:20:201:42ff:fe00:101/64",ok:false,x:"Typing the full address by hand gives the same address, but IOS lists it without the [EUI] flag, like the 2001:DB8:ACAD:21::1 entry."},
  {t:"ipv6 address fe80::201:42ff:fe00:101 link-local",ok:false,x:"This sets the link-local address, shown on the 'link-local address is' line. It does not create a global unicast address."},
  {t:"ipv6 enable",ok:false,x:"ipv6 enable creates only an automatic link-local address. It never adds a 2001:DB8 global unicast address."}
 ],
 w:"show ipv6 interface flags: [EUI] = modified EUI-64 interface ID; no flag = manual. Every IPv6 interface joins FF02::1, routers join FF02::2, plus a solicited-node group FF02::1:FFxx:xxxx per address."},
{id:"a030",obj:"2.1.c",d:2,cat:"vlan",t:"mc",
 q:"Refer to the exhibit. Students on ACC-2 in VLAN 20 cannot ping their gateway, 10.40.20.1. ACC-2 has VLAN 20 with ports assigned, and its uplink trunks to DIST-1 Gi1/0/1 with all VLANs allowed. Which action fixes the problem?",
 ex:"DIST-1# show ip interface brief | include Vlan\nVlan1                  unassigned      YES unset  administratively down down\nVlan10                 10.40.10.1      YES manual up                    up\nVlan20                 10.40.20.1      YES manual up                    down\n\nDIST-1# show vlan brief\nVLAN Name                             Status    Ports\n---- -------------------------------- --------- -----------------\n1    default                          active    Gi1/0/2, Gi1/0/3\n10   VLAN0010                         active\n1002 fddi-default                     act/unsup\n1003 token-ring-default               act/unsup\n1004 fddinet-default                  act/unsup\n1005 trnet-default                    act/unsup",
 o:[
  {t:"Create VLAN 20 on DIST-1 with the vlan 20 command",ok:true,x:"An SVI is up/up only if its VLAN exists on the switch and at least one port carrying it is forwarding. VLAN 20 is missing from DIST-1's VLAN database, so Vlan20 is up/down."},
  {t:"Enter no shutdown under interface vlan 20 on DIST-1",ok:false,x:"Status is already 'up', so the SVI is not administratively down. The down line protocol comes from the missing VLAN."},
  {t:"Enter ip routing on DIST-1",ok:false,x:"Routing between VLANs needs ip routing, but even without it the SVI would be up/up and the students could ping their gateway. VLAN 10 works fine here."},
  {t:"Add VLAN 20 to the allowed list on DIST-1 Gi1/0/1",ok:false,x:"The stem says the trunk allows all VLANs. Even so, a trunk does not carry a VLAN that does not exist on the switch."}
 ],
 w:"SVI up/down checklist: VLAN exists locally, an access or trunk port in that VLAN is up and forwarding, and the SVI is not shut down."},
{id:"a031",obj:"6.4",d:6,cat:"sdn",t:"mc",
 q:"The campus operations team is reviewing AI tools. Which use is an example of predictive AI rather than generative AI?",
 o:[
  {t:"A model trained on months of optic temperature and error telemetry flags transceivers likely to fail within two weeks",ok:true,x:"Predictive AI and ML learn patterns from historical data to forecast an outcome or spot an anomaly, here a future hardware failure, so it can be fixed before users notice."},
  {t:"An assistant drafts a VLAN and trunk configuration from a plain-language request",ok:false,x:"Producing new content such as config text from a prompt is generative AI. Its output still needs review before it is pushed."},
  {t:"A chatbot writes a prose summary of last night's syslog messages",ok:false,x:"Writing a new natural-language summary is a generative task, even though it reads operational data."},
  {t:"A script pushes the same NTP configuration to every switch each night",ok:false,x:"That is rule-based automation. It applies a fixed template and involves no learning or prediction."}
 ],
 w:"Predictive AI/ML: forecasts and anomaly detection from historical telemetry (capacity, failures, baselines). Generative AI: creates new content (config drafts, summaries, chat answers)."},
{id:"a032",obj:"1.3.a",d:1,cat:"parts",t:"mc",
 q:"A new athletics complex will connect to CORE-1 with a 10-Gb/s uplink. The cable run between the buildings is about 6 km. Which media should be installed?",
 o:[
  {t:"Single-mode fiber with 10GBASE-LR optics",ok:true,x:"Single-mode fiber has a narrow core and laser optics, so it reaches kilometers. 10GBASE-LR is specified to 10 km, which covers the 6 km run."},
  {t:"OM4 multimode fiber with 10GBASE-SR optics",ok:false,x:"Multimode fiber's wider core causes modal dispersion. 10GBASE-SR on OM4 reaches only about 400 m."},
  {t:"Category 6A UTP copper",ok:false,x:"10GBASE-T over Cat6A is limited to 100 m, far short of 6 km, and copper between buildings also raises grounding and lightning issues."},
  {t:"Category 8 copper",ok:false,x:"Cat8 supports 25/40 Gb/s but only to about 30 m. It is meant for data center top-of-rack links."}
 ],
 w:"Copper Ethernet: 100 m. Multimode fiber (LED/VCSEL, larger core): hundreds of meters, cheaper optics. Single-mode fiber (laser, ~9-micron core): kilometers."},
{id:"a033",obj:"2.5.a",d:2,cat:"stp",t:"mc",
 q:"Refer to the exhibit. The design calls for DIST-1 to be root for VLAN 20, yet VLAN 20 traffic to the data center takes an odd path. Each switch's VLAN 20 bridge ID is shown. Which switch is actually the root bridge for VLAN 20?",
 ex:"VLAN 20 bridge IDs (from show spanning-tree vlan 20)\n\nSwitch  Bridge ID Priority                         Address\n------  -----------------------------------------  --------------\nDIST-1  24596  (priority 24576 sys-id-ext 20)      0001.4200.0100\nDIST-2  28692  (priority 28672 sys-id-ext 20)      0001.4200.0200\nACC-4    4116  (priority 4096 sys-id-ext 20)       0001.4200.0400\nACC-5   32788  (priority 32768 sys-id-ext 20)      0001.4200.0050",
 o:[
  {t:"ACC-4",ok:true,x:"The lowest bridge ID wins, and priority is compared first. ACC-4's 4116 (4096 + VLAN 20) beats every other switch, so the MAC addresses never come into play. Someone set priority 4096 on an access switch."},
  {t:"ACC-5",ok:false,x:"ACC-5 has the lowest MAC address, but MAC is only a tie-breaker when priorities are equal. Its priority, 32788, is the highest here."},
  {t:"DIST-1",ok:false,x:"DIST-1 is the intended root, and 24596 beats DIST-2 and ACC-5, but it loses to ACC-4's 4116."},
  {t:"DIST-2",ok:false,x:"DIST-2's 28692 is lower than ACC-5's but higher than both DIST-1's and ACC-4's."}
 ],
 w:"Root bridge = lowest bridge ID: priority (multiple of 4096) + VLAN ID (sys-id-ext), then lowest MAC. Use spanning-tree vlan X root primary on the switch that should be root, and root guard toward access switches."},
{id:"a034",obj:"1.13.a",d:1,cat:"switching",t:"mc",
 q:"A legacy UDP label printer on ACC-7 Fa0/18 (VLAN 40) receives jobs but sends almost nothing; its last frame was its DHCP request at boot. A capture on another VLAN 40 port shows copies of the print jobs arriving there, starting about five minutes after the printer last sent a frame. What explains this?",
 o:[
  {t:"The printer's dynamic MAC entry aged out after the default 300 seconds, so frames to it are flooded as unknown unicast",ok:true,x:"A switch refreshes a dynamic entry only when the MAC appears as a source. With no frames from the printer for 300 seconds, the entry ages out and every frame to it is flooded in VLAN 40."},
  {t:"Port security on Fa0/18 is in restrict mode and copies frames to other ports",ok:false,x:"Restrict mode drops frames from violating source MACs and logs them. It never copies traffic to other ports."},
  {t:"A static MAC entry for the printer forces the switch to flood its frames",ok:false,x:"A static entry never ages out and makes the switch forward to exactly one port, the opposite of what was seen."},
  {t:"The trunk to DIST-1 does not allow VLAN 40, so ACC-7 floods the frames",ok:false,x:"Trunk allowed lists do not cause local flooding. The flooding starts on a timer, which points to MAC aging."}
 ],
 w:"MAC learning uses the source address; the default aging time on Catalyst switches is 300 seconds. A silent host ages out and its traffic is flooded until it transmits again."},
{id:"a035",obj:"6.5",d:6,cat:"api",t:"mc",
 q:"Refer to the exhibit. An engineer tests the campus controller's REST API from a jump host. What should the engineer do next?",
 ex:"$ curl -i https://10.40.100.50/api/v1/network-device\nHTTP/1.1 401 Unauthorized\nContent-Type: application/json\n\n{\"error\": \"missing or invalid token\"}",
 o:[
  {t:"Authenticate to obtain a token, then resend the GET with the token in the request header",ok:true,x:"401 means the request lacked valid credentials. Many controller APIs issue a token from an authentication call; later calls carry it in a header such as X-Auth-Token or Authorization: Bearer."},
  {t:"Change the method from GET to POST",ok:false,x:"Using the wrong method on a resource returns 405 Method Not Allowed. The body here clearly complains about the token."},
  {t:"Correct the URI, because the resource does not exist",ok:false,x:"A missing resource returns 404 Not Found. The server recognized the path and asked for credentials."},
  {t:"Wait for the controller to recover from an internal error",ok:false,x:"Server faults are 5xx codes such as 500 Internal Server Error. 4xx codes mean the client must fix its request."}
 ],
 w:"HTTP codes: 200 OK, 201 Created, 204 No Content, 400 Bad Request, 401 Unauthorized (no/invalid auth), 403 Forbidden (authenticated but not allowed), 404 Not Found, 500 Internal Server Error."},
{id:"a036",obj:"2.5.a",d:2,cat:"stp",t:"order",
 q:"Drag the steps into the order Rapid PVST+ follows to build a loop-free topology for VLAN 10 across the campus switches.",
 pool:["Each non-root switch selects one root port: its lowest-cost path to the root","All switches elect the root bridge: the lowest bridge ID","On each link, the port with the best path to the root becomes the designated port","Every remaining port becomes an alternate or backup port and discards"],
 answer:[1,0,2,3],
 x:"Nothing can be measured until a root exists, so the root bridge is elected first. Each non-root switch then picks its root port by lowest root path cost (then neighbor bridge ID, then port ID). Each segment then gets one designated port, and the ports left over become alternate (or backup) and discard.",
 w:"Root bridge, then root ports, then designated ports, then alternate/backup. Root bridge ports are all designated."},
{id:"a037",obj:"1.9",d:1,cat:"ipv6",t:"ms",pick:3,
 q:"Refer to the exhibit. A Linux workstation in the staff VLAN shows these IPv6 addresses. Which three statements are true? (Choose three.)",
 ex:"$ ip -6 addr show dev ens33\n2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 state UP qlen 1000\n    inet6 2001:db8:acad:10:5054:ff:fe3a:91c2/64 scope global dynamic\n       valid_lft 2591932sec preferred_lft 604732sec\n    inet6 fd4a:91c7:2e10:10::25/64 scope global\n       valid_lft forever preferred_lft forever\n    inet6 fe80::5054:ff:fe3a:91c2/64 scope link\n       valid_lft forever preferred_lft forever",
 o:[
  {t:"fd4a:91c7:2e10:10::25 is a unique local address: routable inside the campus but not on the internet",ok:true,x:"FD00::/8 is the locally assigned half of the ULA range FC00::/7. ULAs are like RFC 1918 space: usable inside an organization, never routed on the internet."},
  {t:"fe80::5054:ff:fe3a:91c2 is a link-local address valid only on the segment attached to ens33",ok:true,x:"FE80::/10 addresses (scope link) are created automatically on every IPv6 interface and are never forwarded by routers."},
  {t:"The interface ID 5054:ff:fe3a:91c2 was built with modified EUI-64 from MAC 52:54:00:3a:91:c2",ok:true,x:"Take MAC 52:54:00 | 3a:91:c2, insert ff:fe, then flip bit 7 of the first byte: 0x52 (0101 0010) becomes 0x50. Result: 5054:00ff:fe3a:91c2."},
  {t:"The interface ID 5054:ff:fe3a:91c2 was built from MAC 50:54:00:3a:91:c2",ok:false,x:"This forgets the bit flip. In the interface ID the first byte is 0x50, so the original MAC byte was 0x52."},
  {t:"The fe80:: address can be used as the source to reach servers in other VLANs",ok:false,x:"Routers never forward packets with a link-local source or destination off the link. Off-link traffic uses a global or unique local address."},
  {t:"The fd4a: address was also built with modified EUI-64",ok:false,x:"Its interface ID is ::25, which has no FF:FE in the middle. It was set manually or by a DHCPv6 server."}
 ],
 w:"IPv6 types: global unicast 2000::/3, ULA FC00::/7 (FD00::/8 in use), link-local FE80::/10, multicast FF00::/8. Spot EUI-64 by the FF:FE in the middle of the interface ID."},
{id:"a038",obj:"2.1.b",d:2,cat:"vlan",t:"mc",
 q:"Every unused port on ACC-7 is still in VLAN 1. A technician enters no vlan 1 in global configuration to keep users from landing in the default VLAN. What is the result?",
 o:[
  {t:"IOS rejects the command; VLAN 1 cannot be deleted, so unused ports should be moved to an unused VLAN and shut down",ok:true,x:"VLAN 1 is the default VLAN and cannot be deleted or renamed. The standard practice is to assign unused ports to a parking VLAN and shut them down."},
  {t:"VLAN 1 is deleted and its ports move to VLAN 1002",ok:false,x:"VLAN 1 can never be deleted. VLANs 1002-1005 are also reserved legacy VLANs and are never used for Ethernet ports."},
  {t:"VLAN 1 is deleted and its ports become inactive until reassigned",ok:false,x:"That is what happens when you delete a normal VLAN, such as VLAN 40, that has ports in it. VLAN 1 itself cannot be removed."},
  {t:"VLAN 1 is deleted and CDP and DTP move to the native VLAN",ok:false,x:"The deletion never happens: VLAN 1 stays in the VLAN database whatever native VLAN the trunks use."}
 ],
 w:"VLAN 1: the default for every port, cannot be deleted or renamed. Harden by moving unused ports to an unused VLAN, shutting them, and using a non-1 native VLAN."},
{id:"a039",obj:"1.1.c",d:1,cat:"parts",t:"mc",
 q:"The campus edge must block a peer-to-peer file-sharing application even when it tunnels over TCP 443, apply rules per user directory group, and block exploit traffic inline. Which device meets all three requirements?",
 o:[
  {t:"A next-generation firewall",ok:true,x:"An NGFW identifies applications regardless of port (application visibility and control), maps traffic to users and groups, and includes an inline IPS that drops exploits."},
  {t:"A stateful firewall with port-based rules",ok:false,x:"A classic stateful firewall tracks sessions by addresses and ports. It sees TCP 443 and cannot tell the file-sharing app from normal HTTPS."},
  {t:"A Layer 3 switch with extended ACLs",ok:false,x:"Extended ACLs match addresses, protocols and ports. They have no application identification, user awareness or exploit signatures."},
  {t:"An IDS connected to a SPAN port",ok:false,x:"An IDS on a SPAN port only sees copies of the traffic. It can alert but cannot block inline, and it does not enforce per-group policy."}
 ],
 w:"NGFW = stateful firewall + application awareness + user identity + integrated IPS (+ URL filtering, malware protection). IDS alerts out-of-band; IPS sits inline and drops."},
{id:"a040",obj:"6.1",d:6,cat:"sdn",t:"mc",
 q:"Each semester the campus team adds a new VLAN to all 120 access switches by hand, and an audit found a dozen switches with typos or missing lines. The team now pushes the change from one template using an automation tool. What is the main operational benefit?",
 o:[
  {t:"Every switch receives the same validated configuration, which reduces configuration drift and human error",ok:true,x:"Automation applies one tested template everywhere, and can verify the result. That consistency cuts the typo-driven drift the audit found and speeds up the change."},
  {t:"Engineers no longer need to understand VLANs or trunking",ok:false,x:"Automation encodes what engineers already know; someone still has to design, review and troubleshoot the template."},
  {t:"Change control and maintenance windows are no longer needed",ok:false,x:"Automated changes still reach production. A bad template can break all 120 switches at once, so review and change control matter more."},
  {t:"The switches stop needing a control plane",ok:false,x:"Pushing configuration does not change how switches run STP, learn MACs or build forwarding tables."}
 ],
 w:"Automation brings consistency, speed, scale and fewer manual errors. It also scales mistakes, so templates need testing and change control."},
{id:"a041",obj:"2.9",d:2,cat:"wlan",t:"mc",
 q:"Refer to the exhibit. Staff laptops associate and authenticate to SSID Staff, but they get addresses in 10.40.100.0/24 instead of the staff subnet. Which change fixes this?",
 ex:"WLANs > Edit 'STAFF-WIFI'  (WLAN ID 2)\n  General tab\n    Profile Name                 : STAFF-WIFI\n    Type                         : WLAN\n    SSID                         : Staff\n    Status                       : [x] Enabled\n    Security Policies            : [WPA2][Auth(802.1X)]\n    Radio Policy                 : All\n    Interface/Interface Group(G) : management\n    Broadcast SSID               : [x] Enabled\n\nController > Interfaces\n    Interface Name   VLAN Identifier   IP Address\n    management       100               10.40.100.5\n    staff            10                10.40.10.5\n    student          20                10.40.20.5",
 o:[
  {t:"On the General tab, set Interface/Interface Group(G) to staff",ok:true,x:"The WLAN's interface decides which VLAN client traffic is bridged onto at the WLC. It points at management (VLAN 100), so clients get addresses there. Mapping it to staff puts them in VLAN 10."},
  {t:"On the Security tab, change Layer 2 security to WPA2 PSK",ok:false,x:"Authentication already works. The security method does not decide which VLAN or subnet the clients join."},
  {t:"Set Radio Policy to 802.11a only",ok:false,x:"Radio Policy limits which bands or PHY types can join. It has no effect on the client VLAN."},
  {t:"Clear Broadcast SSID",ok:false,x:"Hiding the SSID only removes it from beacons. Clients that connect still land in the management VLAN."}
 ],
 w:"WLC WLAN General tab: Profile Name, SSID, Status, Security Policies summary, Radio Policy, Interface/Interface Group = the VLAN clients are placed in. Security tab = L2/L3/AAA; QoS tab = Platinum/Gold/Silver/Bronze."},
{id:"a042",obj:"1.6",d:1,cat:"tcpip",t:"ms",pick:2,
 q:"The large guest Wi-Fi DHCP pool gave one guest 10.40.33.200/21. Which two addresses can be assigned to other hosts in the same subnet? (Choose two.)",
 o:[
  {t:"10.40.39.254",ok:true,x:"A /21 has a block size of 8 in the third octet: 32, 40, 48. 33 falls in 10.40.32.0/21, which covers 10.40.32.0-10.40.39.255. .39.254 is the last usable host."},
  {t:"10.40.32.1",ok:true,x:"10.40.32.0 is the network address, so 10.40.32.1 is the first usable host of 10.40.32.0/21."},
  {t:"10.40.39.255",ok:false,x:"This is the broadcast address of 10.40.32.0/21. It is in the subnet but cannot be assigned to a host."},
  {t:"10.40.40.1",ok:false,x:"10.40.40.0 starts the next /21 block (40-47), so this host is in a different subnet."},
  {t:"10.40.31.250",ok:false,x:"Third octet 31 belongs to the previous block, 10.40.24.0/21 (24-31)."}
 ],
 w:"/21 = 255.255.248.0, block size 8 in the third octet. Network = largest multiple of 8 at or below the octet; broadcast = next block minus 1."},
{id:"a043",obj:"2.2.b",d:2,cat:"vlan",t:"mc",
 q:"Trunk Gi1/0/3 on DIST-1 is configured with switchport trunk native vlan 99 and switchport trunk allowed vlan 10,20,30,99. No other VLAN-related global commands are configured. How does DIST-1 send frames from VLAN 99 and from VLAN 30 on this trunk?",
 o:[
  {t:"VLAN 99 frames go untagged; VLAN 30 frames carry a 4-byte 802.1Q tag with VLAN ID 30",ok:true,x:"802.1Q inserts a 4-byte tag (TPID 0x8100 plus a 12-bit VLAN ID) into every frame except those in the native VLAN, which cross untagged."},
  {t:"Both carry an 802.1Q tag, with VLAN IDs 99 and 30",ok:false,x:"Native VLAN traffic is untagged by default. Tagging the native VLAN needs the global vlan dot1q tag native command, which the stem rules out."},
  {t:"VLAN 99 frames go untagged; VLAN 30 frames are encapsulated in a 26-byte ISL header",ok:false,x:"ISL is a legacy Cisco trunking method that encapsulates the whole frame. A trunk uses one encapsulation, and these trunks are 802.1Q."},
  {t:"VLAN 99 frames are dropped, because the native VLAN must be VLAN 1",ok:false,x:"Any VLAN can be the native VLAN; using an unused, non-1 VLAN is common practice. It only has to match on both ends."}
 ],
 w:"802.1Q: 4-byte tag (TPID 0x8100, 3-bit PCP, 1-bit DEI, 12-bit VID) inserted after the source MAC. Native VLAN untagged; must match on both ends."},
{id:"a044",obj:"6.6",d:6,cat:"cfgmgmt",t:"order",
 q:"The team will manage the campus's cloud-hosted controller VMs and their virtual networks with Terraform. Drag the steps into the order used to make the first change.",
 pool:["Run terraform plan to preview the changes against the current state","Write the desired resources in .tf files using HCL","Run terraform apply to make the changes and record them in the state file","Run terraform init to download the required providers"],
 answer:[1,3,0,2],
 x:"Terraform first needs configuration files to read, since init discovers which providers the .tf files use and downloads them. Plan then compares the desired state with the state file and real infrastructure and shows what will change. Apply carries out that plan and updates the state file.",
 w:"Terraform: declarative IaC in HCL, providers, state file, workflow write, init, plan, apply. Ansible: procedural-style YAML playbooks pushed agentless over SSH."},
{id:"a045",obj:"1.5",d:1,cat:"tcpip",t:"order",
 q:"A staff PC opens a new TCP session to the intranet web server, requests a page and closes the session. Drag the events into the order in which they occur.",
 pool:["Client sends ACK","Client sends SYN","Client sends HTTP GET in a data segment","Server replies SYN-ACK","Client sends FIN after the transfer completes"],
 answer:[1,3,0,2,4],
 x:"TCP sets up the session with the three-way handshake: SYN from the client, SYN-ACK from the server, ACK from the client. Only then does application data such as the HTTP GET flow. When the exchange is over, a FIN starts the graceful close.",
 w:"TCP open: SYN, SYN-ACK, ACK. TCP close: FIN, ACK in each direction (four segments). UDP has neither."},
{id:"a046",obj:"2.8",d:2,cat:"mgmt",t:"build",ordered:true,
 q:"ACC-2 already has a hostname, a domain name and RSA keys. It must accept remote management only over SSH, authenticating against a local account. Create the account first, then configure all 16 vty lines. Drag the commands you need into the answer area in the order you enter them. Leave the commands that do not apply.",
 pool:["username netadmin privilege 15 secret C4mpus-Adm1n","line vty 0 15","login local","transport input ssh","transport input telnet ssh","login","password C4mpus-Adm1n"],
 answer:[0,1,2,3],
 alt:[[0,1,3,2]],
 x:"The local account must exist (username ... secret). Under line vty 0 15, login local checks the local user database and transport input ssh refuses Telnet. Those two lines can be entered in either order. Plain login with a line password ignores usernames, and telnet ssh would still allow cleartext Telnet.",
 w:"SSH-only vty: hostname, ip domain-name, crypto key generate rsa (768+ bits for v2), username/secret, line vty 0 15, login local, transport input ssh. Optionally ip ssh version 2."},
{id:"a047",obj:"1.11.c",d:1,cat:"wlbasics",t:"ms",pick:2,
 q:"The wireless team is moving lecture-hall clients from 2.4 GHz to 5 GHz. Which two statements about 5 GHz compared with 2.4 GHz are correct? (Choose two.)",
 o:[
  {t:"It offers many more nonoverlapping 20-MHz channels, which eases channel planning in dense rooms",ok:true,x:"5 GHz has around two dozen nonoverlapping 20-MHz channels (depending on regulatory domain), against three in 2.4 GHz, so neighboring APs rarely have to share a channel."},
  {t:"Its signal weakens more over distance and through walls, so more APs are usually needed for the same coverage",ok:true,x:"Higher frequencies lose more energy over free space and through obstacles. 5-GHz cells are smaller, which suits dense halls but needs more APs."},
  {t:"It travels farther at the same transmit power, so fewer APs are needed",ok:false,x:"The reverse is true: 2.4 GHz reaches farther. That is one reason it suffers more co-channel interference."},
  {t:"It shares its band with microwave ovens and Bluetooth, so interference is worse",ok:false,x:"Microwave ovens and Bluetooth sit in 2.4 GHz. Moving to 5 GHz avoids them."},
  {t:"It offers only three nonoverlapping channels in North America",ok:false,x:"Three nonoverlapping channels (1, 6, 11) is the 2.4-GHz limit, not 5 GHz."}
 ],
 w:"2.4 GHz: longer range, 3 nonoverlapping channels, crowded (802.11b/g/n/ax). 5 GHz: shorter range, many channels, cleaner (802.11a/n/ac/ax). 6 GHz: Wi-Fi 6E/7."},
{id:"a048",obj:"2.3",d:2,cat:"l2link",t:"ms",pick:2,
 q:"Refer to the exhibit. Third-party IP phones and APs were installed on ACC-4. Which two statements about the output are true? (Choose two.)",
 ex:"ACC-4# show lldp neighbors\nCapability codes:\n    (R) Router, (B) Bridge, (T) Telephone, (C) DOCSIS Cable Device\n    (W) WLAN Access Point, (P) Repeater, (S) Station, (O) Other\n\nDevice ID           Local Intf     Hold-time  Capability      Port ID\nDIST-1              Gi0/1          120        B,R             Gi1/0/4\nphone-2-114         Fa0/9          180        B,T             0012.ab34.cd56\nap-lib-2f           Fa0/24         120        B,W             eth0\n\nTotal entries displayed: 3",
 o:[
  {t:"ACC-4 Gi0/1 connects to port Gi1/0/4 on DIST-1",ok:true,x:"Local Intf is ACC-4's own port and Port ID is the neighbor's port, so Gi0/1 on ACC-4 leads to Gi1/0/4 on DIST-1."},
  {t:"The device on Fa0/24 advertises WLAN access point capability",ok:true,x:"Its capability list is B,W, and the legend maps W to WLAN Access Point."},
  {t:"LLDP is disabled globally on ACC-4 but enabled on these three interfaces",ok:false,x:"On IOS, LLDP runs only after the global lldp run command. Per-interface transmit/receive does nothing while it is off globally, so neighbors would not appear."},
  {t:"The phone on Fa0/9 must be a Cisco phone, because only Cisco devices send LLDP",ok:false,x:"LLDP is the IEEE 802.1AB open standard, which is why third-party phones and APs appear. CDP is the Cisco-proprietary protocol."},
  {t:"This output shows each neighbor's management IP address",ok:false,x:"The summary has no address column. show lldp neighbors detail (or show lldp entry) shows the management address."},
  {t:"The phone's entry is removed if no LLDP frame arrives within 30 seconds",ok:false,x:"The entry expires when its hold-time runs out, 180 seconds as advertised by this phone. 30 seconds is the default LLDP transmit interval, not the hold time."}
 ],
 w:"LLDP: IEEE 802.1AB, off by default on IOS (lldp run), timer 30 s, holdtime 120 s. CDP: Cisco, on by default, timer 60 s, holdtime 180 s. Both are Layer 2 and not routed."},
{id:"a049",obj:"6.6",d:6,cat:"cfgmgmt",t:"build",ordered:false,
 q:"The campus team chose Ansible to push VLAN and NTP changes to its switches. Drag the characteristics of Ansible into the answer area. Leave the characteristics that do not apply.",
 pool:["Agentless: managed switches need no installed agent","Pushes changes from a control node, typically over SSH","Playbooks are written in YAML","An inventory file lists the managed hosts and groups","Keeps a state file and compares it with real infrastructure before applying","Configuration is written in HCL","An agent on each device pulls its configuration from a central server"],
 answer:[0,1,2,3],
 x:"Ansible runs from a control node, connects to devices over SSH (or an API), and pushes tasks defined in YAML playbooks to the hosts listed in its inventory, with no agent on the switches. HCL and a state file belong to Terraform. Agent-based pull is the classic Puppet/Chef model.",
 w:"Ansible: agentless, push, SSH, YAML playbooks, inventory. Terraform: HCL, providers, state file, plan/apply. Puppet/Chef: agent-based pull (v1.0 era)."},
{id:"a050",obj:"2.7",d:2,cat:"wlan",t:"ms",pick:2,
 q:"Campus lightweight APs run in local mode and tunnel all client traffic in CAPWAP to WLC-1, which connects to DIST-1. The WLC maps the staff, student and voice WLANs to VLANs 10, 20 and 30. Which two switch port configurations are correct? (Choose two.)",
 o:[
  {t:"Each AP's switch port is an access port in the AP management VLAN",ok:true,x:"In local mode, client traffic stays inside the CAPWAP tunnel to the WLC, so the AP needs only one untagged VLAN for its own address."},
  {t:"The WLC-facing ports are 802.1Q trunks carrying VLANs 10, 20 and 30 and the WLC management VLAN",ok:true,x:"The WLC removes client frames from CAPWAP and bridges them onto each WLAN's VLAN, so its uplink must be a trunk carrying all of them."},
  {t:"Each AP's switch port is a trunk carrying VLANs 10, 20 and 30",ok:false,x:"An AP trunk is needed only when the AP switches client traffic locally, as with FlexConnect local switching. Local-mode APs send it all to the WLC."},
  {t:"The WLC-facing ports are routed ports with no switchport and a single IP address",ok:false,x:"A routed port carries no VLANs, so the WLC could not place clients into VLANs 10, 20 and 30."},
  {t:"Each AP's switch port is an access port in VLAN 10 so staff clients get staff addresses",ok:false,x:"The AP's VLAN has no effect on client VLANs in local mode. The WLAN-to-interface mapping on the WLC places the clients."}
 ],
 w:"Local mode AP: access port (AP VLAN), CAPWAP to WLC. FlexConnect with local switching: trunk port. WLC: trunk (often LAG) carrying management + client VLANs."}
];
