/* CCNA Cards — Domain 5 Security Fundamentals (secbase, vpn, acl, l2sec, wsec) */
export const CCNA_CARDS_D5 = [
 /* ---------- secbase (18): 5.1–5.4 ---------- */
 {obj:"5.1",c:"secbase",q:"Vulnerability — the security term",a:"#A weakness that could be used against you\nUnpatched IOS, telnet enabled, default password",s:"A weakness in a system, design or process",g:"tvem",
  x:"A vulnerability is a flaw or gap — an unpatched IOS image, Telnet still allowed on the vty lines, an SNMP community left at public. It does nothing by itself; it only becomes dangerous when a threat actor has a way to use it. On the exam, a noun describing a weakness that exists whether or not anyone attacks it is the vulnerability. Contrast threat (the possible danger), exploit (the method) and mitigation (the fix).",
  w:"Vulnerability = the open window."},
 {obj:"5.1",c:"secbase",q:"Threat — the security term",a:"#Potential danger that could use a weakness\nAn attacker, malware, or even a careless insider",s:"Any potential danger to an asset",g:"tvem",
  x:"A threat is anything with the potential to cause harm by taking advantage of a vulnerability: an external attacker, a worm spreading across the LAN, a disgruntled employee, even a flood. Risk exists where a threat and a vulnerability meet. The exam distinguishes threat (who or what might attack) from the weakness itself (vulnerability) and the actual tool or technique (exploit).",
  w:"Threat = the burglar in the neighborhood."},
 {obj:"5.1",c:"secbase",q:"Exploit — the security term",a:"#Code or technique that uses a vulnerability\nA script that triggers a buffer overflow in a service",s:"Tool or technique that leverages a weakness",g:"tvem",
  x:"An exploit is the concrete method — a script, crafted packet sequence or malicious file — that takes advantage of a specific vulnerability to gain access or cause damage. A vulnerability with no known exploit is still a risk, but one with a public exploit is far more urgent to patch. Exam signal: 'program', 'code' or 'technique used to take advantage of' points to exploit.",
  w:"Exploit = the crowbar used on the open window."},
 {obj:"5.1",c:"secbase",q:"Mitigation technique — the security term",a:"#Action that reduces the chance or impact of an attack\nPatching, ACLs, disabling unused services, training",s:"A measure that reduces risk from a weakness",g:"tvem",
  x:"Mitigation is any countermeasure that lowers risk by removing a vulnerability or limiting what a threat can do: patching IOS, replacing Telnet with SSH, applying ACLs, enabling port security or DHCP snooping, and training users. Few mitigations eliminate risk completely; layering several (defense in depth) is the goal. On the exam, a configuration or practice that fixes or reduces the weakness is the mitigation.",
  w:"Mitigation = locking the window."},
 {obj:"5.1",c:"secbase",q:"DoS vs DDoS",a:"#Exhaust a resource so legitimate users are refused\nDDoS = many sources at once, often a botnet",
  x:"A denial-of-service attack consumes bandwidth, CPU, memory or connection tables — a TCP SYN flood that fills a server's half-open table is the classic example. A distributed DoS launches the same idea from many compromised hosts (a botnet) at once, which makes simple source-based filtering ineffective. Both attack availability rather than confidentiality. Mitigations include rate limiting, upstream scrubbing and SYN cookies.",
  w:"DoS attacks availability; the D in DDoS means a botnet."},
 {obj:"5.1",c:"secbase",q:"Reflection and amplification attack",a:"#Spoofed requests make third parties flood the victim\nSmall query in, much larger reply out (DNS, NTP)",
  x:"In a reflection attack the attacker spoofs the victim's IP as the source, so servers on the internet send their replies to the victim. Amplification adds leverage: protocols such as open DNS resolvers or NTP monlist return replies many times larger than the request. The attacker spends little bandwidth while the victim is flooded by innocent-looking servers. Ingress filtering of spoofed sources (BCP 38) is the root mitigation.",
  w:"Spoof the victim, pick a chatty protocol, let others do the flooding."},
 {obj:"5.1",c:"secbase",q:"Spoofing attacks at CCNA depth",a:"#Forging an address to impersonate another device\nIP, MAC, ARP and rogue DHCP server spoofing",
  x:"Spoofing means faking an identity field: a forged source IP (used in reflection attacks), a forged MAC to bypass filtering, gratuitous ARP replies that claim the gateway's IP, or a rogue DHCP server handing out a bogus default gateway. Layer 2 spoofing is what the 5.7 features counter: DHCP snooping stops rogue servers, Dynamic ARP Inspection stops ARP spoofing, port security limits MAC addresses.",
  w:"Spoofing = lying about who you are on the wire."},
 {obj:"5.1",c:"secbase",q:"Man-in-the-middle (on-path) attack",a:"#Attacker silently sits between two endpoints\nCan read, alter or replay traffic; ARP spoofing is a common setup",
  x:"In a man-in-the-middle attack the attacker places itself in the traffic path, often by ARP poisoning a LAN so hosts send gateway-bound frames to the attacker's MAC, or by running a rogue DHCP server that names the attacker as default gateway. The victims keep communicating and rarely notice. Encryption (SSH, TLS, IPsec) protects confidentiality; DAI and DHCP snooping prevent the LAN redirection.",
  w:"MITM = the attacker becomes the gateway."},
 {obj:"5.1",c:"secbase",q:"Reconnaissance attack",a:"#Gathering information before the real attack\nPing sweeps, port scans, DNS and whois queries",
  x:"Reconnaissance is the information-gathering phase: public records (whois, DNS lookups) to find address ranges, then ping sweeps to find live hosts and port scans to find listening services and versions. It usually does no damage itself but maps the targets for an exploit. Exam signal: 'scan', 'sweep' or 'discover which hosts and ports' is reconnaissance, not DoS.",
  w:"Recon = casing the building before the break-in."},
 {obj:"5.1",c:"secbase",q:"Virus vs worm vs trojan",a:"#Virus needs a host file and user action\nWorm self-propagates across the network; trojan hides in wanted software",
  x:"Malware types differ in how they spread. A virus attaches to a file or program and spreads when a user runs or shares it. A worm spreads on its own by exploiting network services, which is why worms can saturate links quickly. A trojan masquerades as legitimate software and carries a hidden payload, often a backdoor. Ransomware is malware whose payload encrypts data for extortion.",
  w:"Worms crawl by themselves; viruses need a ride."},
 {obj:"5.1",c:"secbase",q:"Social engineering — phishing and its variants",a:"#Manipulating people rather than systems\nPhishing (email), spear phishing, whaling, vishing (voice), smishing (SMS)",
  x:"Social engineering exploits human trust. Phishing sends mass fraudulent email; spear phishing targets a specific person or group; whaling targets executives; vishing uses phone calls and smishing uses text messages. Physical variants include tailgating through a badge door. Technical controls help, but the main mitigation is user awareness training, which ties this topic to 5.2.",
  w:"Hack the human, not the router."},
 {obj:"5.1",c:"secbase",q:"Password attacks: dictionary vs brute force",a:"#Dictionary tries likely words; brute force tries every combination\nMitigate with length, complexity, lockout, MFA",
  x:"A dictionary attack runs through lists of common passwords and words, succeeding quickly against weak choices. A brute-force attack tries every possible combination, which is guaranteed eventually but slows dramatically as length grows. On IOS, 'login block-for' throttles repeated login failures, and strong hashed secrets (type 8 or 9) make stolen hashes harder to crack offline.",
  w:"Length beats dictionary and brute force alike."},
 {obj:"5.2",c:"secbase",q:"Security program: user awareness vs training",a:"#Awareness = everyone recognizes threats\nTraining = role-specific skills; plus physical access control",
  x:"A security program has three elements in this exam topic. User awareness reaches all staff with reminders, posters and simulated phishing so they recognize and report suspicious activity. Training is more formal and job-specific, such as teaching network staff secure configuration. Physical access control keeps unauthorized people away from wiring closets and equipment. Most successful breaches start with a person, so awareness has outsized value.",
  w:"Awareness for everyone; training for the job."},
 {obj:"5.2",c:"secbase",q:"Access control vestibule (mantrap)",a:"#Two interlocking doors; only one opens at a time\nStops tailgating into a data center or wiring room",
  x:"An access control vestibule, formerly called a mantrap, is a small space with two doors where the second will not open until the first has closed and the person has authenticated, usually with a badge plus PIN or biometric. It prevents tailgating and piggybacking. It is a physical access control, alongside badge readers, locked racks, cameras and guards. Physical access to a switch console bypasses most logical controls.",
  w:"One door closes before the next opens."},
 {obj:"5.3",c:"secbase",q:"enable secret vs enable password — both configured",a:"#enable secret wins\nenable password is ignored when a secret exists",s:"The enable secret is used; the password is ignored",
  x:"Both commands protect privileged EXEC mode, but 'enable secret' stores a one-way hash (type 5 MD5 by default on classic IOS) while 'enable password' is stored in clear text unless service password-encryption is on. If both are configured, IOS uses only the secret, and it warns if you try to set them to the same value. Best practice: configure only enable secret.",
  w:"Secret beats password, every time."},
 {obj:"5.3",c:"secbase",q:"service password-encryption — what it does",a:"#Converts clear-text passwords to type 7\nWeak, reversible obfuscation — not real protection",
  x:"The global command 'service password-encryption' rewrites plain passwords in the configuration (line passwords, enable password, username password) into type 7 form so they are not readable at a glance. Type 7 uses a known Vigenere-style scheme and can be reversed instantly with free tools. It does not touch secrets, which are already hashed. Use 'secret' keywords with type 8 or 9 for real protection.",
  w:"Type 7 = shoulder-surfing protection only."},
 {obj:"5.3",c:"secbase",q:"IOS password types 0, 5, 7, 8, 9",a:"#0 clear · 7 reversible · 5 MD5 · 8 SHA-256 (PBKDF2) · 9 scrypt\nChoose 8 or 9 with 'algorithm-type sha256|scrypt'",
  x:"Type 0 is clear text and type 7 is the reversible obfuscation from service password-encryption. Type 5 is an MD5-based salted hash, the long-time default for 'enable secret' and 'username secret' on classic IOS. Type 8 (PBKDF2 with SHA-256) and type 9 (scrypt) are stronger and are selected with 'enable algorithm-type scrypt secret ...' or 'username X algorithm-type sha256 secret ...'. Type 9 is the strongest choice.",
  w:"Higher number (8, 9) = harder to crack; 7 is the trap."},
 {obj:"5.3",c:"secbase",q:"Securing the console line",a:"#line console 0 · password X · login\nWithout 'login', the password is never asked",
  x:"To require a password on the console, enter 'line console 0', set 'password' and add 'login'. The login keyword tells IOS to prompt for the line password; leaving it out means no prompt at all. Alternatively, 'login local' uses the username database instead. Pair it with 'exec-timeout' so an unattended console session closes on its own.",
  w:"password + login, or nothing is enforced."},
 {obj:"5.3",c:"secbase",q:"line vty 0 15 with login local",a:"#Prompts for a username and password from the local database\nRequires 'username X secret Y' to be configured",
  x:"With 'login local' on the vty lines, IOS ignores the line password and authenticates against usernames defined with 'username NAME secret PASSWORD'. This gives each admin their own credentials and is required for SSH, which always needs a username. Add 'transport input ssh' to block Telnet. If no username exists, nobody can log in remotely — a common lab mistake.",
  w:"login = line password; login local = username database."},
 {obj:"5.3",c:"secbase",q:"exec-timeout on a line",a:"#exec-timeout minutes [seconds]\nDefault 10 minutes; 'exec-timeout 0 0' disables (avoid)",
  x:"The line-level command 'exec-timeout' closes an idle EXEC session after the set time, so a forgotten console or SSH session does not sit open in privileged mode. The default is 10 minutes. 'exec-timeout 5 0' means 5 minutes, 0 seconds. 'exec-timeout 0 0' disables the timer entirely, which is convenient in labs but a security weakness in production.",
  w:"Idle sessions are open doors; time them out."},
 {obj:"5.3",c:"secbase",q:"login block-for — what it does",a:"#login block-for 120 attempts 3 within 60\nAfter 3 failures in 60 s, block logins for 120 s",
  x:"The global command 'login block-for SECONDS attempts N within SECONDS' slows brute-force and dictionary attacks on vty logins: if N failed attempts occur inside the window, the device enters quiet mode and refuses login attempts for the block period. 'login quiet-mode access-class' can exempt a trusted management ACL. It complements, not replaces, strong passwords and ACLs on the vty lines.",
  w:"Fail too often, wait it out."},
 {obj:"5.3",c:"secbase",q:"security passwords min-length",a:"#security passwords min-length N\nRejects new passwords shorter than N characters",
  x:"This global configuration command enforces a minimum length for passwords and secrets configured on the device from that point on, including enable secret, username secrets and line passwords. Existing shorter passwords are not removed, but new ones below the minimum are rejected with an error. It is one of the few IOS commands that directly implements a password-policy element from topic 5.4.",
  w:"IOS can enforce length, the most important complexity factor."},
 {obj:"5.4",c:"secbase",q:"Password policy elements",a:"#Length, complexity, history/rotation, lockout\nLong passphrases matter most; lock out after repeated failures",
  x:"A password policy defines minimum length, complexity (mixing character classes), how often passwords change and whether old ones can be reused, and account lockout after a number of failed attempts. Current guidance favors long passphrases and checking against breached lists over forced frequent rotation, which tends to produce predictable patterns. Lockout defeats online guessing; strong hashing protects against offline cracking.",
  w:"Long and unique beats short and complicated."},
 {obj:"5.4",c:"secbase",q:"Multifactor authentication — the three factors",a:"#Something you know, have, are\nPassword + token or phone = MFA; two passwords = one factor",s:"Know, have, are — from two or more categories",
  x:"MFA requires proof from at least two different categories: something you know (password, PIN), something you have (hardware token, smartphone app, smart card) and something you are (fingerprint, face). Two passwords or a password plus security question are still single-factor because both are 'know'. Exam questions often hide the trap of two items from the same category.",
  w:"Two of the same category is not MFA."},
 {obj:"5.4",c:"secbase",q:"Certificates and biometrics as password alternatives",a:"#Certificate = device or user proves possession of a private key\nBiometric = physical trait (fingerprint, face, iris)",
  x:"Certificate-based authentication uses a digital certificate signed by a trusted certificate authority; the user or device proves it holds the matching private key, so there is no password to steal or guess, and it is common with 802.1X EAP-TLS. Biometrics authenticate with a physical characteristic and fall into 'something you are'. Both are often combined with a PIN to make MFA.",
  w:"Certs prove you hold a key; biometrics prove you are you."},

 /* ---------- vpn (14): 5.5, 5.8 ---------- */
 {obj:"5.5",c:"vpn",q:"Site-to-site IPsec VPN",a:"#Permanent tunnel between two gateways\nHosts send normal traffic; routers or firewalls encrypt it",s:"Always-on tunnel between two VPN gateways",g:"vpntype",
  x:"A site-to-site VPN joins whole networks, such as a branch and headquarters, by building an IPsec tunnel between two gateways (routers or firewalls) over the internet. End hosts need no VPN software and are unaware of the tunnel; the gateway encrypts traffic that matches the policy before forwarding it. It is typically always on, replacing or backing up private WAN links.",
  w:"Site-to-site: transparent to hosts, gateway to gateway."},
 {obj:"5.5",c:"vpn",q:"Remote-access VPN",a:"#One user device to the corporate VPN gateway\nClient software (e.g., IPsec or SSL VPN client) or clientless browser",s:"On-demand tunnel from a single user device",g:"vpntype",
  x:"A remote-access VPN connects an individual teleworker's laptop or phone to the organization's VPN headend, usually on demand. Full-tunnel access uses installed client software over IPsec or TLS; a clientless SSL/TLS VPN runs inside a web browser and typically exposes only web-based applications. Unlike site-to-site, the end user's device is a tunnel endpoint and the user must authenticate.",
  w:"Remote access: the laptop is the tunnel endpoint."},
 {obj:"5.5",c:"vpn",q:"Clientless SSL/TLS VPN",a:"#Browser-only access over HTTPS\nNo installed client; limited to web-delivered apps",s:"Browser portal over TLS, no installed client",g:"vpntype",
  x:"A clientless VPN lets a remote user open a browser to the VPN gateway's HTTPS portal, authenticate, and reach published internal web applications through the portal. Nothing beyond the browser is installed, which suits unmanaged or kiosk devices, but non-web applications are generally not reachable. It is a remote-access option; site-to-site VPNs use IPsec between gateways.",
  w:"Clientless = the browser is the client."},
 {obj:"5.5",c:"vpn",q:"ESP vs AH in IPsec",a:"#ESP: encryption + integrity + authentication (IP protocol 50)\nAH: integrity + authentication only, no encryption (IP protocol 51)",
  x:"IPsec offers two security protocols. Encapsulating Security Payload (IP protocol 50) encrypts the payload and also provides integrity and origin authentication, so it is used in almost every modern VPN. Authentication Header (IP protocol 51) authenticates and integrity-checks the packet including much of the outer IP header but gives no confidentiality, and it fails through NAT because NAT changes the header fields AH protects. Exam signal: need confidentiality, choose ESP.",
  w:"ESP encrypts; AH only authenticates."},
 {obj:"5.5",c:"vpn",q:"IKE — role in IPsec",a:"#Negotiates keys and security associations\nUDP 500 (4500 with NAT traversal); IKEv1 or IKEv2",
  x:"Internet Key Exchange authenticates the two peers (pre-shared key or certificates), negotiates the encryption and hashing algorithms, and uses Diffie-Hellman to derive shared keys without sending them across the network. The result is a set of security associations that ESP or AH then use for the data. IKE runs over UDP 500, moving to UDP 4500 when NAT traversal is needed.",
  w:"IKE builds the tunnel; ESP carries the data."},
 {obj:"5.5",c:"vpn",q:"IPsec tunnel mode vs transport mode",a:"#Tunnel: whole original packet encrypted, new IP header added\nTransport: only the payload protected, original header kept",
  x:"In tunnel mode IPsec wraps the entire original IP packet and adds a new outer header addressed between the gateways, hiding the internal addresses — the normal choice for site-to-site VPNs. Transport mode protects only the payload and keeps the original IP header, so it suits end-to-end protection between two hosts or protecting a GRE tunnel whose endpoints are already the routers.",
  w:"Tunnel mode hides the inner addresses; transport mode does not."},
 {obj:"5.5",c:"vpn",q:"GRE over IPsec — why combine them",a:"#GRE carries multicast and routing protocols; IPsec adds encryption\nPlain IPsec tunnels carry only unicast IP",
  x:"A classic policy-based IPsec tunnel carries only unicast IP and cannot run routing protocols such as OSPF, which rely on multicast. GRE can encapsulate multicast, broadcast and non-IP traffic but provides no encryption. Running GRE inside IPsec gives a routed tunnel interface that carries OSPF adjacencies while IPsec keeps the traffic confidential. GRE itself is IP protocol 47.",
  w:"GRE for routing protocols, IPsec for secrecy."},
 {obj:"5.8",c:"vpn",q:"Authentication vs authorization vs accounting",a:"#Who are you? · What may you do? · What did you do?\nThe three A's of AAA",s:"Identity, permissions, and records of activity",
  x:"AAA separates access control into three functions. Authentication verifies identity, for example a username and password checked by a server. Authorization determines what that identity may do, such as privilege level 15 or a restricted command set. Accounting records what happened — login times, commands entered, session length — for auditing and billing. A question about logging commands an admin ran is accounting.",
  w:"Authenticate, authorize, account — in that order."},
 {obj:"5.8",c:"vpn",q:"TACACS+ vs RADIUS",a:"#TACACS+: TCP 49, encrypts the whole body, separates the three A's\nRADIUS: UDP 1812/1813, encrypts only the password, open standard",
  x:"TACACS+ originated at Cisco, runs over TCP port 49, encrypts the entire payload and handles authentication, authorization and accounting separately, which makes it ideal for device administration with per-command authorization. RADIUS is an open standard over UDP (1812 authentication, 1813 accounting; older 1645/1646), encrypts only the password and combines authentication with authorization, which suits network access such as 802.1X and VPN users.",
  w:"Admins on routers: TACACS+. Users on the network: RADIUS."},
 {obj:"5.8",c:"vpn",q:"aaa new-model — what it does",a:"#Enables AAA on the device\nReplaces line password logins with AAA method lists",
  x:"The global command 'aaa new-model' turns on the AAA framework. After it, the vty lines no longer use the 'password' plus 'login' pair; with no method list defined they authenticate against the local username database, and 'aaa authentication login' method lists can point to TACACS+ or RADIUS servers instead. Always create a local username first, or you can lock yourself out of remote access.",
  w:"aaa new-model first, then method lists."},
 {obj:"5.8",c:"vpn",q:"aaa authentication login default group tacacs+ local",a:"#Try TACACS+ first; use local users only if the server is unreachable\nA reject from the server does not fall back",
  x:"Methods in an AAA list are tried in order, but the next method is used only if the previous one returns an error, such as no server responding. If the TACACS+ server answers and rejects the credentials, authentication fails and the local database is not consulted. Listing 'local' last therefore provides emergency access during a server outage without weakening normal control.",
  w:"Fallback on error, not on rejection."},
 {obj:"5.8",c:"vpn",q:"802.1X — the three roles",a:"#Supplicant · Authenticator · Authentication server\nPC · switch or WLC/AP · RADIUS server",s:"Supplicant, authenticator, authentication server",
  x:"802.1X provides port-based network access control. The supplicant is software on the client that supplies credentials. The authenticator is the switch (or wireless controller/AP) that blocks the port except for EAP traffic and relays EAPOL messages to the server. The authentication server, normally RADIUS, checks credentials and tells the authenticator to allow or deny the port.",
  w:"Client asks, switch relays, RADIUS decides."},
 {obj:"5.8",c:"vpn",q:"802.1X — what flows between the authenticator and the server",a:"#EAP carried inside RADIUS\nClient to switch: EAPOL (EAP over LAN)",
  x:"On the client side the supplicant and authenticator exchange EAP frames encapsulated directly in Ethernet (EAPOL). The authenticator re-packages that EAP inside RADIUS messages toward the authentication server. Until the server returns Access-Accept, the switch port only passes EAPOL traffic, so the client cannot reach DHCP or anything else on the network.",
  w:"EAPOL on the access link, RADIUS upstream."},
 {obj:"5.8",c:"vpn",q:"Why use a AAA server instead of local accounts",a:"#Central accounts, per-command authorization, audit logs\nOne place to add or disable an admin for every device",
  x:"Local usernames must be created and removed on every router and switch, which does not scale and leaves stale accounts behind. A central AAA server (TACACS+ or RADIUS) holds identities once, can authorize specific commands or privilege levels per user and records accounting logs of who did what. Local accounts are still kept as the fallback for when the server is unreachable.",
  w:"Central AAA scales; local accounts are the emergency key."},

 /* ---------- acl (18): 5.6 ---------- */
 {obj:"5.6",c:"acl",q:"Standard numbered ACL — numbers and match fields",a:"#1–99 and 1300–1999\nMatch source IPv4 address only",s:"1–99 / 1300–1999, source address only",g:"acltype",
  x:"Standard ACLs can examine only the source IPv4 address of a packet; they cannot filter by destination, protocol or port. Numbered standard lists use 1–99 and the expanded range 1300–1999. Because they are so coarse, they are placed close to the destination so they do not block the source from reaching other networks. They are also used to identify traffic for NAT, vty access and route filtering.",
  w:"Standard = source only."},
 {obj:"5.6",c:"acl",q:"Extended numbered ACL — numbers and match fields",a:"#100–199 and 2000–2699\nProtocol, source, destination, and ports",s:"100–199 / 2000–2699, protocol + src + dst + ports",g:"acltype",
  x:"Extended ACLs match on protocol (ip, tcp, udp, icmp and others), source and destination addresses, and for TCP/UDP the source and destination ports. Numbered extended lists use 100–199 and 2000–2699. Their precision lets them drop unwanted traffic close to the source, saving bandwidth across the network, without affecting other flows from that same host.",
  w:"Extended = who, to where, and what service."},
 {obj:"5.6",c:"acl",q:"Where to place a standard ACL",a:"#As close to the destination as possible\nSource-only matching would otherwise block too much",s:"Near the destination",g:"aclplace",
  x:"Since a standard ACL sees only the source address, applying it near the source would deny that host's traffic to every destination, not just the one you meant to protect. Placing it on the interface closest to the protected destination limits the effect to that network. The cost is that denied traffic crosses the network before being dropped, which is acceptable for standard lists.",
  w:"Standard near destination."},
 {obj:"5.6",c:"acl",q:"Where to place an extended ACL",a:"#As close to the source as possible\nDrop unwanted traffic before it uses WAN bandwidth",s:"Near the source",g:"aclplace",
  x:"An extended ACL can match the exact destination and service, so it can be applied near the source without collateral damage. Dropping the traffic early prevents it from consuming links and router resources along the path. This is the reverse of standard ACL placement and a frequent exam pairing: extended near source, standard near destination.",
  w:"Extended near source."},
 {obj:"5.6",c:"acl",q:"Implicit deny at the end of every ACL",a:"#deny any (hidden, not shown in the config)\nAn ACL with only deny lines blocks everything",
  x:"Every IPv4 ACL ends with an invisible 'deny any' (or 'deny ip any any' for extended). Traffic that matches no configured entry is dropped. A list containing only deny statements therefore drops all traffic on that interface, so most ACLs need a final 'permit any' or 'permit ip any any' when the goal is to block only specific flows. The implicit deny does not show hit counts; add an explicit 'deny ip any any log' to see them.",
  w:"No match = denied."},
 {obj:"5.6",c:"acl",q:"ACL processing order",a:"#Top-down, first match wins\nLater lines are never checked once a line matches",
  x:"IOS compares a packet against ACL entries in sequence order and acts on the first entry that matches, ignoring everything below it. A broad permit placed above a specific deny makes the deny unreachable. Write more specific entries first and broader entries later. Named and numbered ACLs both show sequence numbers in 'show access-lists', which reflect this order.",
  w:"Specific before general."},
 {obj:"5.6",c:"acl",q:"Wildcard mask basics",a:"#0 bit = must match · 1 bit = ignore\n/24 network → 0.0.0.255; /30 → 0.0.0.3",
  x:"A wildcard mask tells the ACL which address bits to check. Zero bits must match the address in the entry exactly; one bits can be anything. For a contiguous subnet, the wildcard is 255.255.255.255 minus the subnet mask, so 255.255.255.240 (/28) becomes 0.0.0.15. A wildcard of 0.0.0.0 matches one host and 255.255.255.255 matches everything.",
  w:"Wildcard = 255.255.255.255 minus the mask."},
 {obj:"5.6",c:"acl",q:"Wildcard to match 172.16.32.0/20",a:"#172.16.32.0 0.0.15.255\n255.255.240.0 inverted = 0.0.15.255",
  x:"A /20 mask is 255.255.240.0. Subtracting from 255.255.255.255 gives 0.0.15.255, so the entry is '172.16.32.0 0.0.15.255', matching 172.16.32.0 through 172.16.47.255. The third octet block size is 16, and 32 is a multiple of 16, so 172.16.32.0 is a valid network boundary. A wrong base such as 172.16.40.0 with the same wildcard still matches the same range, but IOS rewrites it.",
  w:"/20 → third-octet wildcard 15."},
 {obj:"5.6",c:"acl",q:"host and any keywords",a:"#host 10.1.1.5 = 10.1.1.5 0.0.0.0\nany = 0.0.0.0 255.255.255.255",
  x:"IOS provides two shortcuts. 'host A.B.C.D' matches a single address and equals that address with wildcard 0.0.0.0. 'any' matches every address and equals 0.0.0.0 with wildcard 255.255.255.255. In a standard ACL you may also type an address alone, which IOS treats as a host match. The running configuration displays these keyword forms.",
  w:"host = exact match; any = everything."},
 {obj:"5.6",c:"acl",q:"Extended port operators eq, gt, lt, neq, range",a:"#eq 443 · gt 1023 · lt 1024 · neq 23 · range 20 21\nUsed only with tcp or udp",
  x:"Port operators follow the source or destination address in a TCP or UDP entry. 'eq' matches one port, 'gt' and 'lt' match above or below a value, 'neq' matches anything except one port, and 'range' matches an inclusive span. Placement matters: 'permit tcp any host 10.1.1.10 eq 80' tests the destination port because it follows the destination address. Ports cannot be used with 'ip' or 'icmp'.",
  w:"The operator applies to whichever address it follows."},
 {obj:"5.6",c:"acl",q:"Keyword established in an extended ACL",a:"#Matches TCP segments with ACK or RST set\nLets return traffic in, blocks new inbound connections",
  x:"'established' matches TCP packets that have the ACK or RST bit set, which means they belong to an existing session. Applied inbound on an outside interface, 'permit tcp any 10.1.0.0 0.0.255.255 established' lets replies to internal clients back in while blocking new connection attempts (initial SYNs have no ACK). It works only with TCP and is stateless, not a true firewall.",
  w:"established = ACK or RST bit set."},
 {obj:"5.6",c:"acl",q:"Apply an ACL to an interface",a:"#ip access-group NAME|NUMBER in|out\nIn = as packets enter; out = as packets leave",
  x:"An ACL does nothing until it is applied. In interface configuration mode, 'ip access-group 110 in' filters packets arriving on that interface before the routing decision, while 'out' filters packets the router is sending out that interface. Traffic generated by the router itself is not filtered by an outbound ACL. Applying a list that does not exist yet permits all traffic.",
  w:"access-group on interfaces; access-class on vty lines."},
 {obj:"5.6",c:"acl",q:"How many ACLs per interface",a:"#One per interface, per direction, per protocol\nA second ip access-group in replaces the first",
  x:"An interface can have one IPv4 ACL inbound, one IPv4 ACL outbound, and the same again for IPv6. Entering a second 'ip access-group' in the same direction silently replaces the previous one rather than adding to it. To combine rules, put all entries into a single ACL. This 'three P's' rule — per protocol, per direction, per interface — is a regular exam item.",
  w:"Three P's: protocol, direction, interface."},
 {obj:"5.6",c:"acl",q:"Restricting SSH/Telnet access to the device",a:"#line vty 0 15 · access-class 10 in\nA standard ACL filters who can reach the vty lines",
  x:"To limit which hosts can open remote management sessions, create an ACL (usually standard) listing the management subnet and apply it to the vty lines with 'access-class 10 in'. This filters connections to the router itself regardless of which interface they arrive on, which is simpler and more complete than adding entries to every interface ACL. Note the different keyword: access-class, not access-group.",
  w:"access-class protects the router's own vty lines."},
 {obj:"5.6",c:"acl",q:"Named ACL syntax",a:"#ip access-list extended WEB-IN\nEnters ACL config mode; entries get sequence numbers 10, 20, 30",
  x:"Named ACLs are created with 'ip access-list standard NAME' or 'ip access-list extended NAME', which enters a sub-mode where each permit or deny line is a separate entry. A descriptive name documents the purpose, and IOS assigns sequence numbers in steps of 10 by default. Numbered ACLs can also be edited in this mode using 'ip access-list extended 110'.",
  w:"Names document intent."},
 {obj:"5.6",c:"acl",q:"Insert or delete one line in an existing ACL",a:"#15 permit tcp host 10.1.1.9 any eq 22 · no 20\nSequence numbers place new lines between old ones",
  x:"In ACL configuration mode, typing a sequence number before an entry inserts it at that position, so '15 deny ...' lands between lines 10 and 20. 'no 20' removes only line 20. Without sequence numbers, new entries are appended at the end, often below a 'permit any' where they never match. 'ip access-list resequence NAME 10 10' renumbers if gaps run out.",
  w:"Sequence numbers make ACLs editable."},
 {obj:"5.6",c:"acl",q:"show access-lists — what to look for",a:"#Each entry with its (N matches) hit counter\nVerifies which line traffic is actually matching",
  x:"'show access-lists' lists every ACL with its sequence numbers and a match counter after each entry, such as '20 permit tcp any host 10.1.1.10 eq www (152 matches)'. A counter that never rises suggests the line is shadowed by an earlier entry or the ACL is applied in the wrong direction. 'show ip interface g0/1' confirms which ACL is applied inbound and outbound. 'clear access-list counters' resets the numbers.",
  w:"Hit counters reveal which line is doing the work."},
 {obj:"5.6",c:"acl",q:"Block one host's web traffic to a server, allow everything else",a:"#deny tcp host 10.1.1.5 host 10.2.2.10 eq 80\npermit ip any any",
  x:"An extended ACL needs the protocol, source, destination and port for a targeted block. Following the deny with 'permit ip any any' prevents the implicit deny from dropping all other traffic. Apply it inbound on the interface nearest 10.1.1.5 so the denied traffic never crosses the network. Forgetting the permit is the most common reason an ACL breaks connectivity.",
  w:"Targeted deny, then permit the rest."},

 /* ---------- l2sec (12): 5.7 ---------- */
 {obj:"5.7",c:"l2sec",q:"Port security defaults",a:"#switchport port-security\nMax 1 MAC, violation shutdown, on an access (or trunk) port",
  x:"Port security is enabled per interface with 'switchport port-security' after making the port a static access port ('switchport mode access'); it is rejected on a dynamic (DTP) port. Defaults are a maximum of one secure MAC address, violation mode shutdown, and addresses learned dynamically. 'switchport port-security maximum 2' allows, for example, an IP phone plus a PC.",
  w:"Default: one MAC, shutdown on violation."},
 {obj:"5.7",c:"l2sec",q:"Port security violation mode protect",a:"#Drops frames from unknown MACs silently\nNo log message, violation counter does not increase",s:"Drop silently — no log, no counter",g:"psmode",
  x:"In protect mode the switch discards traffic from MAC addresses beyond the allowed maximum but keeps the port up and forwards frames from the secure addresses. It generates no syslog or SNMP notification and does not increment the security violation counter, so it is the hardest mode to troubleshoot. Use it only when silent filtering is truly desired.",
  w:"Protect = quiet drop."},
 {obj:"5.7",c:"l2sec",q:"Port security violation mode restrict",a:"#Drops unknown MACs, logs and counts the violation\nPort stays up",s:"Drop, send syslog/SNMP, increment counter",g:"psmode",
  x:"Restrict mode drops frames from unauthorized MACs like protect mode, but also sends a syslog message and SNMP trap and increments the security violation count shown by 'show port-security interface'. The port remains up for legitimate devices, making restrict a good balance between availability and visibility.",
  w:"Restrict = drop and tell."},
 {obj:"5.7",c:"l2sec",q:"Port security violation mode shutdown",a:"#Port goes err-disabled, logs, counter increments\nThe default mode",s:"Err-disable the port, log, increment counter",g:"psmode",
  x:"Shutdown, the default violation mode, places the interface in the err-disabled state as soon as a violation occurs, stopping all traffic including from legitimate devices. A syslog message is generated and the violation counter increases. 'show interfaces status' displays err-disabled and 'show port-security interface' shows 'Secure-shutdown'.",
  w:"Shutdown = err-disabled, everything stops."},
 {obj:"5.7",c:"l2sec",q:"Recovering an err-disabled port",a:"#shutdown then no shutdown on the interface\nOr errdisable recovery cause psecure-violation (auto)",
  x:"After removing the offending device, an administrator restores a port that port security err-disabled by entering 'shutdown' followed by 'no shutdown' on that interface. Automatic recovery can be configured globally with 'errdisable recovery cause psecure-violation' and 'errdisable recovery interval SECONDS' (default 300). If the cause is still present, the port will be disabled again.",
  w:"shut / no shut brings it back."},
 {obj:"5.7",c:"l2sec",q:"Sticky secure MAC addresses",a:"#switchport port-security mac-address sticky\nLearned MACs are added to the running-config",
  x:"Sticky learning lets the switch learn secure MACs dynamically and then write them into the running configuration as 'switchport port-security mac-address sticky H.H.H' entries. Saving the configuration makes them survive a reload, giving the convenience of dynamic learning with the persistence of static entries. Without sticky, dynamically learned secure MACs are lost at reboot.",
  w:"Sticky = learn once, keep in the config."},
 {obj:"5.7",c:"l2sec",q:"DHCP snooping — trusted vs untrusted ports",a:"#Untrusted (default): server messages like OFFER/ACK dropped\nTrusted: uplinks toward the real DHCP server",
  x:"With DHCP snooping enabled, every port is untrusted by default. Untrusted ports may send client messages (DISCOVER, REQUEST) but any server-type message such as OFFER or ACK arriving there is dropped, which stops rogue DHCP servers. Ports leading toward the legitimate server, including uplinks and trunks, are configured with 'ip dhcp snooping trust'.",
  w:"Trust only the path to the real server."},
 {obj:"5.7",c:"l2sec",q:"Enable DHCP snooping on a switch",a:"#ip dhcp snooping\nip dhcp snooping vlan 10,20 · ip dhcp snooping trust (uplink)",
  x:"DHCP snooping needs two global commands: 'ip dhcp snooping' to turn the feature on, and 'ip dhcp snooping vlan LIST' to activate it on specific VLANs — without the VLAN command nothing is inspected. Then mark the uplinks toward the server with 'ip dhcp snooping trust'. 'show ip dhcp snooping' verifies the enabled VLANs and trusted interfaces.",
  w:"Global on + per-VLAN on + trust the uplink."},
 {obj:"5.7",c:"l2sec",q:"DHCP snooping binding table",a:"#MAC, IP, lease, VLAN, interface for each client\nBuilt from DHCP ACKs seen on untrusted ports",
  x:"As DHCP snooping watches successful exchanges, it records each client's MAC address, leased IP, lease time, VLAN and switch port in the binding table, viewed with 'show ip dhcp snooping binding'. Dynamic ARP Inspection and IP Source Guard use this table to verify that hosts are using only the addresses they were assigned. Snooping also drops DHCP RELEASE messages that do not come from the port in the binding.",
  w:"The binding table is the source of truth for DAI."},
 {obj:"5.7",c:"l2sec",q:"DHCP snooping rate limit and option 82",a:"#ip dhcp snooping limit rate 10 (packets/s on an untrusted port)\nOption 82 inserted by default; can upset some servers",
  x:"'ip dhcp snooping limit rate N' on an untrusted interface caps DHCP packets per second; exceeding it err-disables the port, which defeats DHCP starvation floods. By default the switch also inserts DHCP option 82 (relay agent information) into client requests. Some DHCP servers, including an IOS router acting as server, drop such requests; 'no ip dhcp snooping information option' disables the insertion.",
  w:"Rate limit stops starvation; option 82 can confuse servers."},
 {obj:"5.7",c:"l2sec",q:"Dynamic ARP Inspection — how it decides",a:"#Checks ARP sender MAC/IP against the snooping binding table\nMismatch on an untrusted port is dropped",
  x:"DAI intercepts ARP messages on untrusted ports and compares the sender's MAC and IP addresses with the DHCP snooping binding table (or ARP ACLs for static hosts). An ARP reply claiming the gateway's IP from a host whose binding says otherwise is dropped and logged, which defeats ARP poisoning and the man-in-the-middle attacks that depend on it. It also rate limits ARP on untrusted ports (15 pps default).",
  w:"DAI relies on DHCP snooping's table."},
 {obj:"5.7",c:"l2sec",q:"Configure Dynamic ARP Inspection",a:"#ip arp inspection vlan 10\nip arp inspection trust on uplinks; verify with show ip arp inspection",
  x:"DAI is enabled per VLAN with the global command 'ip arp inspection vlan LIST'. All ports are untrusted by default, so uplinks to other switches and routers get 'ip arp inspection trust' to avoid dropping valid ARP from devices without bindings. DHCP snooping must be running on the same VLANs so the binding table exists; hosts with static IPs need an ARP ACL or they will be blocked.",
  w:"DAI per VLAN, trust the uplinks, snooping underneath."},

 /* ---------- wsec (10): 5.9–5.10 ---------- */
 {obj:"5.9",c:"wsec",q:"WEP — why it is not used",a:"#Static key with a weak RC4 and 24-bit IV\nCracked in minutes; never acceptable",s:"RC4 with tiny IV — broken",g:"wlanproto",
  x:"Wired Equivalent Privacy, part of the original 802.11 standard, uses RC4 with a short 24-bit initialization vector and a shared static key. Because IVs repeat quickly, captured traffic reveals the key with freely available tools. It provides no meaningful security and has been deprecated; the exam treats any WEP answer as the insecure choice.",
  w:"WEP = broken."},
 {obj:"5.9",c:"wsec",q:"WPA (original) — encryption",a:"#TKIP with RC4, per-packet keys and MIC\nInterim fix for WEP hardware; now deprecated",s:"TKIP — interim fix for WEP hardware",g:"wlanproto",
  x:"The Wi-Fi Alliance released WPA as a stop-gap that could run on WEP-era hardware via firmware upgrade. It introduced TKIP, which still uses RC4 but rotates keys per packet and adds a message integrity check. It supports Personal (PSK) and Enterprise (802.1X) modes. TKIP has known weaknesses and is deprecated in favor of AES.",
  w:"WPA = TKIP."},
 {obj:"5.9",c:"wsec",q:"WPA2 — encryption",a:"#AES-CCMP\nBased on 802.11i; Personal (PSK) or Enterprise (802.1X)",s:"AES-CCMP, 802.11i",g:"wlanproto",
  x:"WPA2 implements the full 802.11i standard and requires CCMP, which uses AES for encryption and integrity. It offers Personal mode with a pre-shared passphrase and Enterprise mode with 802.1X/EAP authentication against a RADIUS server. WPA2-Personal's four-way handshake can be captured and the passphrase attacked offline, which WPA3's SAE was designed to fix.",
  w:"WPA2 = AES-CCMP."},
 {obj:"5.9",c:"wsec",q:"WPA3 — the key improvements",a:"#SAE replaces PSK handshake · PMF mandatory · forward secrecy\nEnterprise 192-bit mode uses GCMP-256",s:"SAE, mandatory PMF, forward secrecy",g:"wlanproto",
  x:"WPA3-Personal replaces the PSK four-way handshake key derivation with Simultaneous Authentication of Equals, which resists offline dictionary attacks and provides forward secrecy, so a later-discovered passphrase cannot decrypt old captures. Protected Management Frames are mandatory, blocking forged deauthentication frames. WPA3-Enterprise adds an optional 192-bit mode using GCMP-256 for high-security networks.",
  w:"WPA3 = SAE + PMF."},
 {obj:"5.9",c:"wsec",q:"Personal (PSK) vs Enterprise (802.1X) mode",a:"#Personal: one shared passphrase for everyone\nEnterprise: per-user credentials via 802.1X/EAP and RADIUS",
  x:"Personal mode authenticates every client with the same pre-shared key, which is simple but means a departing employee forces a passphrase change for everyone. Enterprise mode uses 802.1X: the client (supplicant) authenticates with its own credentials or certificate through the AP or WLC (authenticator) to a RADIUS server, enabling per-user access, revocation and accounting.",
  w:"Personal = shared secret; Enterprise = individual identity."},
 {obj:"5.9",c:"wsec",q:"OWE (Enhanced Open)",a:"#Encryption on open networks without a password\nDiffie-Hellman per client; no authentication",
  x:"Opportunistic Wireless Encryption, marketed as Wi-Fi Enhanced Open, lets clients join an open SSID such as a guest or cafe network while still encrypting each session with a key derived from a Diffie-Hellman exchange. It stops passive eavesdropping between users but does not authenticate anyone, so it is not a replacement for WPA3-Personal or Enterprise where access must be restricted.",
  w:"OWE = encrypted but still open."},
 {obj:"5.10",c:"wsec",q:"WLC GUI: create a WLAN",a:"#WLANs > Create New > Go\nEnter profile name, SSID, and WLAN ID",
  x:"On an AireOS WLC, the WLANs tab lists existing WLANs; choosing 'Create New' and clicking Go opens a form for the type, profile name, SSID and WLAN ID. After Apply, the edit page has General, Security, QoS and Advanced tabs. The WLAN is created disabled until 'Status: Enabled' is checked on the General tab.",
  w:"Create New, then configure tabs, then enable."},
 {obj:"5.10",c:"wsec",q:"WLC GUI: configure WPA2-PSK",a:"#Security > Layer 2: WPA+WPA2, WPA2 policy, AES\nAuth Key Mgmt: PSK, format ASCII, enter passphrase",
  x:"On the WLAN's Security tab, Layer 2 Security is set to WPA+WPA2; check WPA2 Policy and AES encryption (leave TKIP off). Under Authentication Key Management, enable PSK and disable 802.1X, set the PSK format to ASCII and type the passphrase (8–63 characters). Apply the change. Choosing 802.1X instead would require a RADIUS server under the AAA Servers tab.",
  w:"WPA2 + AES + PSK + ASCII passphrase."},
 {obj:"5.10",c:"wsec",q:"WLC GUI: map the WLAN to a VLAN",a:"#General tab: Interface/Interface Group = dynamic interface\nThe dynamic interface ties the SSID to a VLAN",
  x:"A WLC dynamic interface represents a VLAN with an IP address on the controller. On the WLAN's General tab, the Interface/Interface Group drop-down selects which dynamic interface (and therefore which VLAN) client traffic from that SSID is bridged onto. Create the dynamic interface first under Controller > Interfaces, and make sure the switch trunk to the WLC allows that VLAN.",
  w:"SSID to interface to VLAN."},
 {obj:"5.10",c:"wsec",q:"WLC GUI: WLAN created but clients cannot see it",a:"#Check Status: Enabled on the General tab\nNew WLANs are disabled by default",
  x:"A WLAN built through the GUI stays administratively disabled until 'Status: Enabled' is checked on the General tab and applied; the WLANs list shows each one's admin status. Other items to verify are 'Broadcast SSID' if clients rely on scanning, the radio policy (all bands) and that the interface mapping points to a working VLAN. Remember to Save Configuration so it survives a reboot.",
  w:"Enable it, then save it."},
];
