/* GENERATED by dev/tools/gen-pbq.mjs — do not edit by hand. Topology keys were read from the IOS simulator;
   config-order items are graded by replaying the student's order in the simulator (core/sims/ios/ui/configOrder.js). */
export const PBQ_ORDER = [
 {
  "id": "po-ssh",
  "type": "ccna-order",
  "obj": "4.8",
  "d": 4,
  "title": "Order: enable SSH on a router",
  "device": "router",
  "steps": [
   "hostname R1",
   "ip domain-name ccna.lab",
   "crypto key generate rsa modulus 2048",
   "line vty 0 4",
   "transport input ssh",
   "login local"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "The router must end up with an RSA key named after its hostname and domain.",
   "VTY lines must accept only SSH and use the local user database."
  ],
  "why": "The key label is hostname.domain, so both must exist before `crypto key generate rsa`; the two VTY commands only work inside line configuration mode. Any order that satisfies those two constraints is accepted."
 },
 {
  "id": "po-roas",
  "type": "ccna-order",
  "obj": "2.1",
  "d": 2,
  "title": "Order: router-on-a-stick sub-interfaces",
  "device": "router",
  "steps": [
   "interface g0/0",
   "no shutdown",
   "interface g0/0.10",
   "encapsulation dot1q 10",
   "ip address 10.1.10.1 255.255.255.0",
   "interface g0/0.20",
   "encapsulation dot1q 20",
   "ip address 10.1.20.1 255.255.255.0"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Enable the physical interface.",
   "VLAN 10 and VLAN 20 each need a sub-interface with 802.1Q encapsulation and the gateway address."
  ],
  "why": "IOS refuses an IP address on a sub-interface until `encapsulation dot1q` is set. Blocks for the physical interface and each sub-interface can come in any order."
 },
 {
  "id": "po-ospf",
  "type": "ccna-order",
  "obj": "3.4",
  "d": 3,
  "title": "Order: single-area OSPF with a loopback router ID",
  "device": "router",
  "steps": [
   "interface loopback 0",
   "ip address 1.1.1.1 255.255.255.255",
   "router ospf 1",
   "router-id 1.1.1.1",
   "network 10.0.12.0 0.0.0.3 area 0",
   "passive-interface g0/0",
   "default-information originate"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Create Loopback0 with 1.1.1.1/32.",
   "Run OSPF 1 with router ID 1.1.1.1, area 0 on 10.0.12.0/30, Gi0/0 passive, and advertise a default route."
  ],
  "why": "`router-id`, `network`, `passive-interface` and `default-information originate` are router-configuration commands, so they follow `router ospf 1`."
 },
 {
  "id": "po-acl",
  "type": "ccna-order",
  "obj": "5.6",
  "d": 5,
  "title": "Order: named extended ACL and apply it",
  "device": "router",
  "steps": [
   "ip access-list extended LAB-WEB",
   "deny tcp host 10.1.10.66 any eq 80",
   "permit tcp 10.1.10.0 0.0.0.255 any eq 80",
   "interface g0/0",
   "ip access-group LAB-WEB in"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Host 10.1.10.66 must not browse (TCP 80); the rest of 10.1.10.0/24 may.",
   "Apply the ACL inbound on Gi0/0."
  ],
  "why": "ACEs are evaluated top-down and the first match wins, so the host-specific deny must come before the subnet permit — reversed, the permit would match .66 first."
 },
 {
  "id": "po-pat",
  "type": "ccna-order",
  "obj": "4.1",
  "d": 4,
  "title": "Order: PAT for a LAN",
  "device": "router",
  "steps": [
   "interface g0/0",
   "ip nat inside",
   "interface g0/1",
   "ip nat outside",
   "exit",
   "access-list 1 permit 10.1.10.0 0.0.0.255",
   "ip nat inside source list 1 interface g0/1 overload"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Gi0/0 faces the LAN, Gi0/1 faces the ISP.",
   "All of 10.1.10.0/24 shares Gi0/1's address."
  ],
  "why": "`ip nat inside|outside` belong under their interfaces; the ACL and the NAT rule are global commands (entered after leaving interface mode) and can be entered in either order."
 },
 {
  "id": "po-dhcp",
  "type": "ccna-order",
  "obj": "4.6",
  "d": 4,
  "title": "Order: DHCP pool with exclusions",
  "device": "router",
  "steps": [
   "ip dhcp excluded-address 10.1.10.1 10.1.10.10",
   "ip dhcp pool LAN",
   "network 10.1.10.0 255.255.255.0",
   "default-router 10.1.10.1",
   "dns-server 10.1.10.5"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Never lease 10.1.10.1–10.1.10.10.",
   "Pool LAN hands out 10.1.10.0/24 with gateway 10.1.10.1 and DNS 10.1.10.5."
  ],
  "why": "`network`, `default-router` and `dns-server` are DHCP-pool commands; the exclusion is global and may come before or after the pool."
 },
 {
  "id": "po-ec",
  "type": "ccna-order",
  "obj": "2.4",
  "d": 2,
  "title": "Order: LACP EtherChannel trunk",
  "device": "switch",
  "steps": [
   "interface range g0/1 - 2",
   "channel-group 1 mode active",
   "interface port-channel 1",
   "switchport mode trunk",
   "switchport trunk native vlan 99"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Bundle Gi0/1–2 into Po1 with LACP, actively negotiating.",
   "Po1 is a trunk with native VLAN 99."
  ],
  "why": "`channel-group` creates Port-channel1, and the trunk settings belong on the Port-channel so they apply to every member."
 },
 {
  "id": "po-psec",
  "type": "ccna-order",
  "obj": "5.7",
  "d": 5,
  "title": "Order: port security on an access port",
  "device": "switch",
  "steps": [
   "interface f0/5",
   "switchport mode access",
   "switchport port-security",
   "switchport port-security maximum 2",
   "switchport port-security violation restrict",
   "switchport port-security mac-address sticky"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Fa0/5 is a static access port.",
   "Allow 2 sticky MACs; restrict on violation."
  ],
  "why": "Port security is rejected on a dynamic (DTP) port, so `switchport mode access` must come before `switchport port-security`. The other port-security lines can be in any order."
 },
 {
  "id": "po-float",
  "type": "ccna-order",
  "obj": "3.3",
  "d": 3,
  "title": "Order: primary and floating default routes",
  "device": "router",
  "steps": [
   "interface g0/1",
   "ip address 203.0.113.2 255.255.255.252",
   "no shutdown",
   "interface s0/1/0",
   "ip address 198.51.100.2 255.255.255.252",
   "no shutdown",
   "exit",
   "ip route 0.0.0.0 0.0.0.0 203.0.113.1",
   "ip route 0.0.0.0 0.0.0.0 198.51.100.1 10"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Address and enable both WAN interfaces.",
   "Default via 203.0.113.1; backup default via 198.51.100.1 with AD 10."
  ],
  "why": "Interface lines belong under their interface; the two static routes are global commands. They can even be entered before the interfaces exist — IOS keeps a static route whose next hop is not reachable yet and installs it once it is."
 },
 {
  "id": "po-vlan",
  "type": "ccna-order",
  "obj": "2.2",
  "d": 2,
  "title": "Order: access VLAN and trunk",
  "device": "switch",
  "steps": [
   "vlan 10",
   "name SALES",
   "interface f0/1",
   "switchport mode access",
   "switchport access vlan 10",
   "interface g0/1",
   "switchport mode trunk",
   "switchport trunk allowed vlan 10,99"
  ],
  "prompt": "Drag the configuration lines into an order that works when typed from global configuration mode.",
  "task": [
   "Create VLAN 10 named SALES and put Fa0/1 in it.",
   "Gi0/1 is a trunk that allows VLANs 10 and 99."
  ],
  "why": "`name` is a VLAN-configuration command, so it must directly follow `vlan 10`. Interface blocks can come in either order."
 }
];
export const PBQ_TOPO = [
 {
  "id": "pt-stp-triangle",
  "type": "diagram",
  "obj": "2.5",
  "d": 2,
  "title": "STP port roles: triangle with a configured root",
  "prompt": "Label every inter-switch port with its spanning-tree role for VLAN 1.",
  "w": 480,
  "h": 320,
  "reuse": true,
  "devices": {
   "root": {
    "n": "Root port",
    "s": "ROOT"
   },
   "desg": {
    "n": "Designated port",
    "s": "DESG"
   },
   "altn": {
    "n": "Alternate (blocking)",
    "s": "BLOCK"
   }
  },
  "palette": [
   "root",
   "desg",
   "altn"
  ],
  "nodes": [
   {
    "id": "SW1",
    "label": "SW1\nprio 4096 · 0001.4200.0100",
    "x": 240,
    "y": 50,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "SW2",
    "label": "SW2\nprio 32768 · 0001.4200.0200",
    "x": 90,
    "y": 250,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "SW3",
    "label": "SW3\nprio 32768 · 0001.4200.0300",
    "x": 390,
    "y": 250,
    "k": "sw",
    "w": 132,
    "h": 40
   }
  ],
  "links": [
   [
    "SW1",
    "SW2"
   ],
   [
    "SW1",
    "SW3"
   ],
   [
    "SW2",
    "SW3"
   ]
  ],
  "slots": [
   {
    "id": "SW1-Gi0/1",
    "label": "SW1 Gi0/1 (cost 4)",
    "x": 186,
    "y": 122,
    "want": "desg"
   },
   {
    "id": "SW2-Gi0/1",
    "label": "SW2 Gi0/1 (cost 4)",
    "x": 144,
    "y": 178,
    "want": "root"
   },
   {
    "id": "SW1-Gi0/2",
    "label": "SW1 Gi0/2 (cost 4)",
    "x": 294,
    "y": 122,
    "want": "desg"
   },
   {
    "id": "SW3-Gi0/1",
    "label": "SW3 Gi0/1 (cost 4)",
    "x": 336,
    "y": 178,
    "want": "root"
   },
   {
    "id": "SW2-Gi0/2",
    "label": "SW2 Gi0/2 (cost 4)",
    "x": 198,
    "y": 250,
    "want": "desg"
   },
   {
    "id": "SW3-Gi0/2",
    "label": "SW3 Gi0/2 (cost 4)",
    "x": 282,
    "y": 250,
    "want": "altn"
   }
  ],
  "task": [
   "Every port between the switches is a trunk carrying VLAN 1 and is up.",
   "Drag a role onto every port slot. A role can be used more than once."
  ],
  "why": "SW1 has the lowest priority, so it is root and all its ports are designated. SW2 and SW3 each pick the port toward SW1 as root port. On the SW2–SW3 link both have cost 4 to the root, so the lower bridge ID (equal priority → lower MAC, SW2) is designated and SW3's end blocks."
 },
 {
  "id": "pt-stp-square",
  "type": "diagram",
  "obj": "2.5",
  "d": 2,
  "title": "STP port roles: four switches, mixed link speeds",
  "prompt": "Label every inter-switch port with its spanning-tree role for VLAN 1. FastEthernet costs 19, GigabitEthernet 4.",
  "w": 480,
  "h": 320,
  "reuse": true,
  "devices": {
   "root": {
    "n": "Root port",
    "s": "ROOT"
   },
   "desg": {
    "n": "Designated port",
    "s": "DESG"
   },
   "altn": {
    "n": "Alternate (blocking)",
    "s": "BLOCK"
   }
  },
  "palette": [
   "root",
   "desg",
   "altn"
  ],
  "nodes": [
   {
    "id": "SW1",
    "label": "SW1\nprio 8192 · 0001.4200.0100",
    "x": 90,
    "y": 50,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "SW2",
    "label": "SW2\nprio 32768 · 0001.4200.0200",
    "x": 390,
    "y": 50,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "SW3",
    "label": "SW3\nprio 32768 · 0001.4200.0300",
    "x": 390,
    "y": 260,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "SW4",
    "label": "SW4\nprio 32768 · 0001.4200.0400",
    "x": 90,
    "y": 260,
    "k": "sw",
    "w": 132,
    "h": 40
   }
  ],
  "links": [
   [
    "SW1",
    "SW2"
   ],
   [
    "SW2",
    "SW3"
   ],
   [
    "SW3",
    "SW4"
   ],
   [
    "SW4",
    "SW1"
   ]
  ],
  "slots": [
   {
    "id": "SW1-Gi0/1",
    "label": "SW1 Gi0/1 (cost 4)",
    "x": 198,
    "y": 50,
    "want": "desg"
   },
   {
    "id": "SW2-Gi0/1",
    "label": "SW2 Gi0/1 (cost 4)",
    "x": 282,
    "y": 50,
    "want": "root"
   },
   {
    "id": "SW2-Fa0/2",
    "label": "SW2 Fa0/2 (cost 19)",
    "x": 390,
    "y": 126,
    "want": "desg"
   },
   {
    "id": "SW3-Fa0/2",
    "label": "SW3 Fa0/2 (cost 19)",
    "x": 390,
    "y": 184,
    "want": "root"
   },
   {
    "id": "SW3-Gi0/2",
    "label": "SW3 Gi0/2 (cost 4)",
    "x": 282,
    "y": 260,
    "want": "altn"
   },
   {
    "id": "SW4-Gi0/2",
    "label": "SW4 Gi0/2 (cost 4)",
    "x": 198,
    "y": 260,
    "want": "desg"
   },
   {
    "id": "SW4-Fa0/1",
    "label": "SW4 Fa0/1 (cost 19)",
    "x": 90,
    "y": 184,
    "want": "root"
   },
   {
    "id": "SW1-Fa0/1",
    "label": "SW1 Fa0/1 (cost 19)",
    "x": 90,
    "y": 126,
    "want": "desg"
   }
  ],
  "task": [
   "Every port between the switches is a trunk carrying VLAN 1 and is up.",
   "Drag a role onto every port slot. A role can be used more than once."
  ],
  "why": "Root path cost decides root ports: SW2 reaches SW1 for 4 over Gi; SW4's direct Fa link costs 19, SW3 has two paths costing 4+19 = 23 (via SW2) and 19+4 = 23 (via SW4), so the tie goes to the neighbor with the lower bridge ID. On each segment, the switch with the lower root path cost is designated; the remaining port blocks."
 },
 {
  "id": "pt-stp-default",
  "type": "diagram",
  "obj": "2.5",
  "d": 2,
  "title": "STP port roles: nobody configured a priority",
  "prompt": "No priorities were configured. Label every inter-switch port with its role for VLAN 1 (bridge MACs are shown).",
  "w": 480,
  "h": 320,
  "reuse": true,
  "devices": {
   "root": {
    "n": "Root port",
    "s": "ROOT"
   },
   "desg": {
    "n": "Designated port",
    "s": "DESG"
   },
   "altn": {
    "n": "Alternate (blocking)",
    "s": "BLOCK"
   }
  },
  "palette": [
   "root",
   "desg",
   "altn"
  ],
  "nodes": [
   {
    "id": "ACC1",
    "label": "ACC1\nprio 32768 · 0001.4200.0100",
    "x": 240,
    "y": 260,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "DIST1",
    "label": "DIST1\nprio 32768 · 0001.4200.0200",
    "x": 90,
    "y": 50,
    "k": "sw",
    "w": 132,
    "h": 40
   },
   {
    "id": "DIST2",
    "label": "DIST2\nprio 32768 · 0001.4200.0300",
    "x": 390,
    "y": 50,
    "k": "sw",
    "w": 132,
    "h": 40
   }
  ],
  "links": [
   [
    "DIST1",
    "DIST2"
   ],
   [
    "DIST1",
    "ACC1"
   ],
   [
    "DIST2",
    "ACC1"
   ]
  ],
  "slots": [
   {
    "id": "DIST1-Gi0/1",
    "label": "DIST1 Gi0/1 (cost 4)",
    "x": 198,
    "y": 50,
    "want": "desg"
   },
   {
    "id": "DIST2-Gi0/1",
    "label": "DIST2 Gi0/1 (cost 4)",
    "x": 282,
    "y": 50,
    "want": "altn"
   },
   {
    "id": "DIST1-Gi0/2",
    "label": "DIST1 Gi0/2 (cost 4)",
    "x": 144,
    "y": 126,
    "want": "root"
   },
   {
    "id": "ACC1-Gi0/1",
    "label": "ACC1 Gi0/1 (cost 4)",
    "x": 186,
    "y": 184,
    "want": "desg"
   },
   {
    "id": "DIST2-Gi0/2",
    "label": "DIST2 Gi0/2 (cost 4)",
    "x": 336,
    "y": 126,
    "want": "root"
   },
   {
    "id": "ACC1-Gi0/2",
    "label": "ACC1 Gi0/2 (cost 4)",
    "x": 294,
    "y": 184,
    "want": "desg"
   }
  ],
  "task": [
   "Every port between the switches is a trunk carrying VLAN 1 and is up.",
   "Drag a role onto every port slot. A role can be used more than once."
  ],
  "why": "With every priority at 32768 the lowest MAC wins — here the access switch ACC1, which is why the exam keeps telling you to set root priorities on the distribution switches. Both distribution switches point their root port at ACC1; on the DIST1–DIST2 link DIST1 (lower MAC) is designated and DIST2's port blocks."
 },
 {
  "id": "pt-dr-priority",
  "type": "diagram",
  "obj": "3.4",
  "d": 3,
  "title": "OSPF DR/BDR: priorities",
  "prompt": "Label each router's OSPF role on the shared Ethernet segment.",
  "w": 480,
  "h": 300,
  "reuse": true,
  "devices": {
   "dr": {
    "n": "DR",
    "s": "DR"
   },
   "bdr": {
    "n": "BDR",
    "s": "BDR"
   },
   "drother": {
    "n": "DROTHER",
    "s": "DROTHER"
   }
  },
  "palette": [
   "dr",
   "bdr",
   "drother"
  ],
  "nodes": [
   {
    "id": "LAN",
    "label": "Ethernet segment 10.50.0.0/24",
    "x": 240,
    "y": 150,
    "k": "sw",
    "w": 200,
    "h": 30
   },
   {
    "id": "RA",
    "label": "RA\nGi0/0 10.50.0.1\npriority 1\nrouter-id 1.1.1.1",
    "x": 90,
    "y": 60,
    "k": "rtr",
    "w": 150,
    "h": 58
   },
   {
    "id": "RB",
    "label": "RB\nGi0/0 10.50.0.2\npriority 100\nrouter-id 2.2.2.2",
    "x": 390,
    "y": 60,
    "k": "rtr",
    "w": 150,
    "h": 58
   },
   {
    "id": "RC",
    "label": "RC\nGi0/0 10.50.0.3\npriority 1\nrouter-id 3.3.3.3",
    "x": 90,
    "y": 250,
    "k": "rtr",
    "w": 150,
    "h": 58
   },
   {
    "id": "RD",
    "label": "RD\nGi0/0 10.50.0.4\npriority 0\nrouter-id 4.4.4.4",
    "x": 390,
    "y": 250,
    "k": "rtr",
    "w": 150,
    "h": 58
   }
  ],
  "links": [
   [
    "RA",
    "LAN"
   ],
   [
    "RB",
    "LAN"
   ],
   [
    "RC",
    "LAN"
   ],
   [
    "RD",
    "LAN"
   ]
  ],
  "slots": [
   {
    "id": "RA-role",
    "label": "RA role",
    "x": 210,
    "y": 60,
    "want": "drother"
   },
   {
    "id": "RB-role",
    "label": "RB role",
    "x": 270,
    "y": 60,
    "want": "dr"
   },
   {
    "id": "RC-role",
    "label": "RC role",
    "x": 210,
    "y": 250,
    "want": "bdr"
   },
   {
    "id": "RD-role",
    "label": "RD role",
    "x": 270,
    "y": 250,
    "want": "drother"
   }
  ],
  "task": [
   "All four routers run OSPF on Gi0/0 in area 0 and booted at the same moment.",
   "Label each router's role on the segment."
  ],
  "why": "Highest priority wins DR (RB, 100). For BDR the priorities tie at 1 between RA and RC, so the higher router ID wins (RC, 3.3.3.3). RD has priority 0 and can never be DR or BDR even with the highest router ID."
 },
 {
  "id": "pt-dr-rid",
  "type": "diagram",
  "obj": "3.4",
  "d": 3,
  "title": "OSPF DR/BDR: router IDs without router-id",
  "prompt": "No priorities were changed. Label each router's OSPF role on the segment.",
  "w": 480,
  "h": 300,
  "reuse": true,
  "devices": {
   "dr": {
    "n": "DR",
    "s": "DR"
   },
   "bdr": {
    "n": "BDR",
    "s": "BDR"
   },
   "drother": {
    "n": "DROTHER",
    "s": "DROTHER"
   }
  },
  "palette": [
   "dr",
   "bdr",
   "drother"
  ],
  "nodes": [
   {
    "id": "LAN",
    "label": "Ethernet segment 10.50.0.0/24",
    "x": 240,
    "y": 150,
    "k": "sw",
    "w": 200,
    "h": 30
   },
   {
    "id": "RA",
    "label": "RA\nGi0/0 10.50.0.1\npriority 1\nLoopback0 10.0.0.9",
    "x": 90,
    "y": 60,
    "k": "rtr",
    "w": 150,
    "h": 58
   },
   {
    "id": "RB",
    "label": "RB\nGi0/0 10.50.0.2\npriority 1\nLoopback0 10.0.0.20",
    "x": 390,
    "y": 60,
    "k": "rtr",
    "w": 150,
    "h": 58
   },
   {
    "id": "RC",
    "label": "RC\nGi0/0 10.50.0.3\npriority 1\nLoopback0 192.168.1.1",
    "x": 90,
    "y": 250,
    "k": "rtr",
    "w": 150,
    "h": 58
   },
   {
    "id": "RD",
    "label": "RD\nGi0/0 10.50.0.4\npriority 1\nno router-id, no loopback",
    "x": 390,
    "y": 250,
    "k": "rtr",
    "w": 150,
    "h": 58
   }
  ],
  "links": [
   [
    "RA",
    "LAN"
   ],
   [
    "RB",
    "LAN"
   ],
   [
    "RC",
    "LAN"
   ],
   [
    "RD",
    "LAN"
   ]
  ],
  "slots": [
   {
    "id": "RA-role",
    "label": "RA role",
    "x": 210,
    "y": 60,
    "want": "drother"
   },
   {
    "id": "RB-role",
    "label": "RB role",
    "x": 270,
    "y": 60,
    "want": "drother"
   },
   {
    "id": "RC-role",
    "label": "RC role",
    "x": 210,
    "y": 250,
    "want": "dr"
   },
   {
    "id": "RD-role",
    "label": "RD role",
    "x": 270,
    "y": 250,
    "want": "bdr"
   }
  ],
  "task": [
   "All four routers run OSPF on Gi0/0 in area 0 and booted at the same moment.",
   "Label each router's role on the segment."
  ],
  "why": "Router ID order: router-id command, else highest loopback, else highest active interface. RC = 192.168.1.1 (DR), RD has no loopback so its RID is 10.50.0.4 (BDR, beats 10.0.0.20 and 10.0.0.9)."
 },
 {
  "id": "pt-nexthop-lpm",
  "type": "diagram",
  "obj": "3.2",
  "d": 3,
  "title": "Next hop: longest prefix match",
  "prompt": "R1's static routes are listed in the task pane. Label the next hop R1 uses for each destination.",
  "w": 480,
  "h": 300,
  "reuse": true,
  "devices": {
   "r2": {
    "n": "10.0.12.2 (R2)",
    "s": "10.0.12.2"
   },
   "r3": {
    "n": "10.0.13.3 (R3)",
    "s": "10.0.13.3"
   },
   "isp": {
    "n": "203.0.113.1 (ISP)",
    "s": "203.0.113.1"
   }
  },
  "palette": [
   "r2",
   "r3",
   "isp"
  ],
  "nodes": [
   {
    "id": "R1",
    "label": "R1",
    "x": 240,
    "y": 150,
    "k": "rtr"
   },
   {
    "id": "R2",
    "label": "R2 10.0.12.2",
    "x": 90,
    "y": 60,
    "k": "rtr",
    "w": 110
   },
   {
    "id": "R3",
    "label": "R3 10.0.13.3",
    "x": 90,
    "y": 250,
    "k": "rtr",
    "w": 110
   },
   {
    "id": "ISP",
    "label": "ISP 203.0.113.1",
    "x": 400,
    "y": 150,
    "k": "cloud",
    "w": 130
   }
  ],
  "links": [
   [
    "R1",
    "R2"
   ],
   [
    "R1",
    "R3"
   ],
   [
    "R1",
    "ISP"
   ]
  ],
  "task": [
   "R1 routes: S 10.2.0.0/16 via 10.0.12.2 · S 10.2.5.0/24 via 10.0.13.3 · S 10.2.5.128/25 via 10.0.12.2 · S* 0.0.0.0/0 via 203.0.113.1",
   "Drag a next hop onto each destination. A next hop can be used more than once."
  ],
  "why": "The most specific matching prefix wins regardless of the order routes were entered: 10.2.5.9 → /24 (R3); 10.2.5.200 → /25 (R2); 10.2.77.1 → only the /16 (R2); 172.20.0.1 → only the default (ISP).",
  "slots": [
   {
    "id": "d0",
    "label": "to 10.2.5.9",
    "x": 300,
    "y": 40,
    "want": "r3"
   },
   {
    "id": "d1",
    "label": "to 10.2.5.200",
    "x": 420,
    "y": 60,
    "want": "r2"
   },
   {
    "id": "d2",
    "label": "to 10.2.77.1",
    "x": 300,
    "y": 250,
    "want": "r2"
   },
   {
    "id": "d3",
    "label": "to 172.20.0.1",
    "x": 420,
    "y": 270,
    "want": "isp"
   }
  ]
 },
 {
  "id": "pt-nexthop-ad",
  "type": "diagram",
  "obj": "3.2",
  "d": 3,
  "title": "Next hop: administrative distance",
  "prompt": "R1 learns some prefixes from OSPF (via R2) and has static routes for them via R3. Label the next hop R1 installs for each destination.",
  "w": 480,
  "h": 300,
  "reuse": true,
  "devices": {
   "r2": {
    "n": "10.0.12.2 (R2)",
    "s": "10.0.12.2"
   },
   "r3": {
    "n": "10.0.13.3 (R3)",
    "s": "10.0.13.3"
   },
   "isp": {
    "n": "203.0.113.1 (ISP)",
    "s": "203.0.113.1"
   }
  },
  "palette": [
   "r2",
   "r3",
   "isp"
  ],
  "nodes": [
   {
    "id": "R1",
    "label": "R1",
    "x": 240,
    "y": 150,
    "k": "rtr"
   },
   {
    "id": "R2",
    "label": "R2 10.0.12.2",
    "x": 90,
    "y": 60,
    "k": "rtr",
    "w": 110
   },
   {
    "id": "R3",
    "label": "R3 10.0.13.3",
    "x": 90,
    "y": 250,
    "k": "rtr",
    "w": 110
   },
   {
    "id": "ISP",
    "label": "ISP 203.0.113.1",
    "x": 400,
    "y": 150,
    "k": "cloud",
    "w": 130
   }
  ],
  "links": [
   [
    "R1",
    "R2"
   ],
   [
    "R1",
    "R3"
   ],
   [
    "R1",
    "ISP"
   ]
  ],
  "task": [
   "OSPF from R2 advertises 10.8.0.0/24 and 10.9.0.0/24.",
   "Statics on R1: 10.9.0.0/24 via 10.0.13.3 (AD 1) · 10.8.0.0/24 via 10.0.13.3 AD 120 · default via 203.0.113.1.",
   "10.0.13.0/24 is directly connected on Gi0/2 — label it with the R3 address it reaches it toward."
  ],
  "why": "Same prefix length, so administrative distance decides: static (1) beats OSPF (110) for 10.9.0.0/24, but OSPF (110) beats the floating static (120) for 10.8.0.0/24. A connected network is delivered directly; the label shows the neighbor on that segment.",
  "slots": [
   {
    "id": "d0",
    "label": "to 10.9.0.5",
    "x": 300,
    "y": 40,
    "want": "r3"
   },
   {
    "id": "d1",
    "label": "to 10.8.0.5",
    "x": 420,
    "y": 60,
    "want": "r2"
   },
   {
    "id": "d2",
    "label": "to 10.0.13.77",
    "x": 300,
    "y": 250,
    "want": "r3"
   },
   {
    "id": "d3",
    "label": "to 198.18.0.1",
    "x": 420,
    "y": 270,
    "want": "isp"
   }
  ]
 },
 {
  "id": "pt-nat-terms",
  "type": "diagram",
  "obj": "4.1",
  "d": 4,
  "title": "NAT address terms",
  "prompt": "PC 172.16.1.21 pings 8.8.8.8 through EDGE's PAT. Label each address with its NAT term.",
  "w": 480,
  "h": 300,
  "devices": {
   "il": {
    "n": "Inside local",
    "s": "IN-LOCAL"
   },
   "ig": {
    "n": "Inside global",
    "s": "IN-GLOBAL"
   },
   "ol": {
    "n": "Outside local",
    "s": "OUT-LOCAL"
   },
   "og": {
    "n": "Outside global",
    "s": "OUT-GLOBAL"
   }
  },
  "palette": [
   "il",
   "ig",
   "ol",
   "og"
  ],
  "nodes": [
   {
    "id": "PC",
    "label": "PC",
    "x": 50,
    "y": 150,
    "k": "pc",
    "w": 60
   },
   {
    "id": "EDGE",
    "label": "EDGE (PAT)",
    "x": 240,
    "y": 150,
    "k": "rtr",
    "w": 100
   },
   {
    "id": "NET",
    "label": "8.8.8.8",
    "x": 430,
    "y": 150,
    "k": "cloud",
    "w": 80
   },
   {
    "id": "IN",
    "label": "inside",
    "x": 140,
    "y": 270,
    "k": "box",
    "w": 70,
    "h": 24
   },
   {
    "id": "OUT",
    "label": "outside",
    "x": 340,
    "y": 270,
    "k": "box",
    "w": 70,
    "h": 24
   }
  ],
  "links": [
   [
    "PC",
    "EDGE"
   ],
   [
    "EDGE",
    "NET"
   ]
  ],
  "slots": [
   {
    "id": "src-in",
    "label": "source 172.16.1.21 (inside)",
    "x": 130,
    "y": 70,
    "want": "il"
   },
   {
    "id": "dst-in",
    "label": "destination 8.8.8.8 (inside)",
    "x": 130,
    "y": 220,
    "want": "ol"
   },
   {
    "id": "src-out",
    "label": "source 203.0.113.6 (outside)",
    "x": 350,
    "y": 70,
    "want": "ig"
   },
   {
    "id": "dst-out",
    "label": "destination 8.8.8.8 (outside)",
    "x": 350,
    "y": 220,
    "want": "og"
   }
  ],
  "task": [
   "Inside = how the address appears on the inside network; global vs local = whose address it is (ours or theirs) as seen on that side.",
   "Each term is used exactly once."
  ],
  "why": "Read straight from show ip nat translations: Inside local 172.16.1.21 (our host as seen inside), Inside global 203.0.113.6 (our host as seen outside), Outside local and Outside global both 8.8.8.8 (their host — PAT does not translate the destination)."
 },
 {
  "id": "pt-nat-interfaces",
  "type": "diagram",
  "obj": "4.1",
  "d": 4,
  "title": "NAT inside and outside interfaces",
  "prompt": "Both LANs share the serial address (PAT) and the DMZ server is published as 203.0.113.50. Label every EDGE interface.",
  "w": 480,
  "h": 300,
  "reuse": true,
  "devices": {
   "inside": {
    "n": "ip nat inside",
    "s": "INSIDE"
   },
   "outside": {
    "n": "ip nat outside",
    "s": "OUTSIDE"
   }
  },
  "palette": [
   "inside",
   "outside"
  ],
  "nodes": [
   {
    "id": "EDGE",
    "label": "EDGE",
    "x": 240,
    "y": 150,
    "k": "rtr"
   },
   {
    "id": "L1",
    "label": "LAN 172.16.1.0/24",
    "x": 70,
    "y": 60,
    "k": "pc",
    "w": 130
   },
   {
    "id": "L2",
    "label": "LAN 172.16.2.0/24",
    "x": 70,
    "y": 240,
    "k": "pc",
    "w": 130
   },
   {
    "id": "DMZ",
    "label": "DMZ web 192.168.50.10",
    "x": 410,
    "y": 250,
    "k": "srv",
    "w": 140
   },
   {
    "id": "ISP",
    "label": "ISP / Internet",
    "x": 410,
    "y": 50,
    "k": "cloud",
    "w": 120
   }
  ],
  "links": [
   [
    "EDGE",
    "L1"
   ],
   [
    "EDGE",
    "L2"
   ],
   [
    "EDGE",
    "DMZ"
   ],
   [
    "EDGE",
    "ISP"
   ]
  ],
  "slots": [
   {
    "id": "g0/0",
    "label": "Gi0/0",
    "x": 155,
    "y": 100,
    "want": "inside"
   },
   {
    "id": "g0/1",
    "label": "Gi0/1",
    "x": 155,
    "y": 200,
    "want": "inside"
   },
   {
    "id": "g0/2",
    "label": "Gi0/2",
    "x": 330,
    "y": 205,
    "want": "inside"
   },
   {
    "id": "s0/1/0",
    "label": "Se0/1/0",
    "x": 330,
    "y": 95,
    "want": "outside"
   }
  ],
  "task": [
   "Every interface that private addresses enter from is inside; the interface toward the public network is outside.",
   "A label can be used more than once."
  ],
  "why": "The DMZ server has a private address too, so its interface is inside — static NAT translates it on the way out the outside interface. The scenario was proven in the simulator: both LANs reach 8.8.8.8 and the ISP reaches 203.0.113.50."
 },
 {
  "id": "pt-ospf-passive",
  "type": "diagram",
  "obj": "3.4",
  "d": 3,
  "title": "OSPF: which interfaces should be passive?",
  "prompt": "R1 advertises all four networks in OSPF. Hellos should go only where another router listens. Label each R1 interface.",
  "w": 480,
  "h": 300,
  "reuse": true,
  "devices": {
   "passive": {
    "n": "passive-interface",
    "s": "PASSIVE"
   },
   "active": {
    "n": "Send hellos (not passive)",
    "s": "HELLOS"
   }
  },
  "palette": [
   "passive",
   "active"
  ],
  "nodes": [
   {
    "id": "R1",
    "label": "R1",
    "x": 240,
    "y": 150,
    "k": "rtr"
   },
   {
    "id": "PCS",
    "label": "Staff PCs 10.1.10.0/24",
    "x": 70,
    "y": 60,
    "k": "pc",
    "w": 140
   },
   {
    "id": "SRV",
    "label": "Servers 10.1.20.0/24",
    "x": 70,
    "y": 245,
    "k": "srv",
    "w": 140
   },
   {
    "id": "R2",
    "label": "R2",
    "x": 420,
    "y": 60,
    "k": "rtr"
   },
   {
    "id": "R3",
    "label": "R3",
    "x": 420,
    "y": 245,
    "k": "rtr"
   }
  ],
  "links": [
   [
    "R1",
    "PCS"
   ],
   [
    "R1",
    "SRV"
   ],
   [
    "R1",
    "R2"
   ],
   [
    "R1",
    "R3"
   ]
  ],
  "slots": [
   {
    "id": "g0/0",
    "label": "Gi0/0",
    "x": 155,
    "y": 100,
    "want": "passive"
   },
   {
    "id": "g0/2",
    "label": "Gi0/2",
    "x": 155,
    "y": 205,
    "want": "passive"
   },
   {
    "id": "g0/1",
    "label": "Gi0/1",
    "x": 330,
    "y": 100,
    "want": "active"
   },
   {
    "id": "s0/1/0",
    "label": "Se0/1/0",
    "x": 330,
    "y": 205,
    "want": "active"
   }
  ],
  "task": [
   "Passive interfaces keep their network in OSPF but send no hellos.",
   "A label can be used more than once."
  ],
  "why": "Hellos toward PCs and servers are wasted and let a rogue device try to peer. Passive keeps the LAN advertised (proven: R2 and R3 learn both LANs) while the router-facing links keep their adjacencies."
 }
];
