// Exam-style question pool (SY0-701). First option is always correct; the app shuffles.
export const EXQ=[
{id:"x001",obj:"4.8",d:4,q:"A SOC analyst reviews the following SIEM events for one account: 09:14 successful VPN login from Denver, US; 09:31 successful login to the HR portal from Kyiv, UA; 09:33 payroll export downloaded. Which of the following should the analyst do FIRST?",
 o:["Disable the account and terminate its active sessions","Open a ticket asking the user to confirm the login","Update the SIEM geolocation database","Reset the VPN concentrator"],
 w:"Two logins 17 minutes apart from different continents is impossible travel, and the export that follows suggests active exfiltration. Containing the account stops further damage while the investigation proceeds.",
 n:["Waiting for a user reply leaves a live attacker with a working session and access to payroll data.","A stale geolocation feed would not explain a sensitive export minutes after the anomalous login.","The VPN device is not the problem; the credential is, and rebooting it would disrupt every remote worker."]},
{id:"x002",obj:"2.2",d:2,q:"Several employees receive a text message claiming their parking permit has expired, with a shortened link to a payment page that mimics the county portal. Which of the following BEST describes this attack?",
 o:["Smishing","Vishing","Whaling","Watering hole"],
 w:"Smishing is phishing delivered over SMS, here using urgency and a lookalike payment page to harvest card details.",
 n:["Vishing uses voice calls, not text messages, to pressure victims.","Whaling targets a specific senior executive rather than a broad set of employees.","A watering-hole attack compromises a site the victims already visit rather than sending them a link."]},
{id:"x003",obj:"5.2",d:5,q:"A company must decide whether to spend $18,000 per year on a backup power system. A power outage currently destroys $60,000 of in-process work and happens roughly twice a year. The system would reduce each loss to $5,000. Which of the following is the annual savings the control provides?",
 o:["$110,000","$120,000","$55,000","$10,000"],
 w:"ALE before = $60,000 x 2 = $120,000; ALE after = $5,000 x 2 = $10,000; the difference of $110,000 far exceeds the $18,000 cost.",
 n:["$120,000 is the current ALE, not the savings; the control does not eliminate all loss.","$55,000 would be the savings per single event, but ALE is annualized over two events.","$10,000 is the residual ALE after the control is in place, not what it saves."]},
{id:"x004",obj:"3.1",d:3,q:"A manufacturer runs a 15-year-old PLC network that cannot be patched and must not be reachable from the corporate LAN. Which of the following architectures BEST meets the requirement?",
 o:["Physically isolate the PLC network with an air gap","Place the PLCs behind a web application firewall","Move the PLC management interfaces to a public cloud VPC","Enable full-disk encryption on the engineering workstations"],
 w:"An air gap removes any network path from the corporate LAN, which is the strongest mitigation for a legacy ICS segment that cannot be patched.",
 n:["A WAF inspects HTTP traffic and offers nothing for proprietary PLC protocols.","Exposing management interfaces to a cloud network increases the attack surface rather than isolating it.","Encrypting workstation disks protects data at rest but does not restrict network reachability to the PLCs."]},
{id:"x005",obj:"1.1",d:1,q:"A hospital cannot apply a vendor patch to an MRI console because the vendor has not certified it. Instead, the security team places the console on its own VLAN with a host-based firewall permitting only the imaging server. Which type of control has been implemented?",
 o:["Compensating","Directive","Deterrent","Corrective"],
 w:"A compensating control provides an alternative safeguard when the primary control, patching, cannot be applied.",
 n:["A directive control tells people what to do, such as a policy; segmentation is a technical safeguard, not guidance.","A deterrent discourages an attacker from trying; the VLAN and firewall actually block access.","A corrective control restores a system after an incident, whereas this is put in place before any compromise."]},
{id:"x006",obj:"4.5",d:4,q:"After a phishing simulation, an organization wants outbound email to be automatically rejected by recipients if it fails both SPF and DKIM alignment, and wants aggregate reports of such failures. Which of the following should the administrator publish?",
 o:["A DMARC record with p=reject and a rua address","An SPF record ending in -all","A DKIM selector record with a 2048-bit key","An MX record pointing at the secure email gateway"],
 w:"DMARC builds on SPF and DKIM by telling receivers what to do on alignment failure (reject) and where to send aggregate reports (rua).",
 n:["SPF alone declares authorized senders but cannot request reporting or enforce a receiver action tied to DKIM.","DKIM provides a signature for integrity but does not define a policy for failed messages.","MX records route inbound mail and have no role in outbound authentication policy."]},
{id:"x007",obj:"2.4",d:2,q:"A firewall log shows 4,000 authentication attempts over two hours, each using a different username from the company directory with the password Summer2024!. Only a few accounts were locked out. Which of the following attacks is occurring?",
 o:["Password spraying","Brute force against one account","Credential replay","Rainbow table attack"],
 w:"Password spraying tries one common password across many accounts, which keeps each account under the lockout threshold while still finding weak credentials.",
 n:["A brute-force attack hammers a single account with many passwords and would trigger a lockout quickly.","Credential replay reuses captured valid authentication material rather than guessing a password.","A rainbow table is used offline against stolen hashes, not against a live login service."]},
{id:"x008",obj:"5.3",d:5,q:"A regulated bank is negotiating with a cloud provider. The bank wants the contractual ability to inspect the provider's security controls with its own auditors rather than rely solely on the provider's reports. Which of the following should be added to the contract?",
 o:["A right-to-audit clause","A non-disclosure agreement","A memorandum of understanding","A service level agreement"],
 w:"A right-to-audit clause gives the customer the contractual authority to examine the vendor's controls directly.",
 n:["An NDA protects confidential information but grants no inspection rights.","An MOU is a non-binding statement of intent and would not compel access for auditors.","An SLA sets performance targets such as uptime; it does not authorize the customer to audit."]},
{id:"x009",obj:"4.4",d:4,q:"A security engineer must confirm that a web server still matches the CIS benchmark after every deployment and report drift in a machine-readable way. Which of the following tools is BEST suited to this task?",
 o:["An SCAP-compliant configuration scanner","A NetFlow collector","A packet capture appliance","A DLP agent"],
 w:"SCAP defines standard formats for expressing benchmarks and reporting compliance results, so an SCAP scanner can verify a host against CIS content automatically.",
 n:["NetFlow summarizes traffic conversations and says nothing about a host's configuration.","Packet captures show wire data, not registry or file settings on the server.","DLP watches for sensitive data leaving the organization, not for configuration drift."]},
{id:"x010",obj:"3.1",d:3,q:"An organization's SaaS provider handles the operating system, runtime, and application code, while the organization manages user accounts and the data stored in the service. Which of the following documents defines this division?",
 o:["The cloud shared responsibility matrix","The business impact analysis","The acceptable use policy","The statement of work"],
 w:"The shared responsibility matrix spells out which security tasks belong to the provider and which remain with the customer for each service model.",
 n:["A BIA ranks business processes by impact and recovery targets rather than allocating security duties.","An AUP governs how employees may use company resources and does not touch provider obligations.","A statement of work describes deliverables for a specific project rather than ongoing security ownership."]},
{id:"x011",obj:"2.2",d:2,q:"A developer discovers that a popular open-source library the application depends on was updated last week and now contains code that sends environment variables to an unknown domain. Which of the following vulnerability types does this represent?",
 o:["Malicious update in the software supply chain","Buffer overflow","Cross-site request forgery","Improper input validation"],
 w:"A trusted dependency that was altered to carry hostile code is a supply-chain attack delivered through a malicious update.",
 n:["A buffer overflow is a memory-handling flaw in code, not intentionally planted exfiltration logic.","CSRF tricks a browser into sending unwanted requests; it is not delivered through a package update.","Input validation flaws concern untrusted user data, whereas here the code itself was subverted."]},
{id:"x012",obj:"4.3",d:4,q:"A vulnerability scan flags a critical OpenSSL issue on a Linux server. The administrator checks the package version and finds the distribution backported the fix without changing the version number the scanner keys on. Which of the following BEST describes the finding?",
 o:["A false positive that should be documented and the scanner tuned","A true positive requiring an emergency patch","A false negative that requires a credentialed rescan","A zero-day that needs a compensating control"],
 w:"The scanner reported a vulnerability that is not actually present because it matched on a version string; that is a false positive and should be recorded and the check adjusted.",
 n:["The fix is already applied, so there is nothing left to patch.","A false negative would be a real flaw the scanner missed, which is the opposite of this situation.","A zero-day has no patch available, but this issue has a fix that is already installed."]},
{id:"x013",obj:"5.2",d:5,q:"The board of a startup has stated it will pursue aggressive market growth and is willing to accept higher levels of risk in new products to move faster than competitors. Which of the following BEST describes this stance?",
 o:["An expansionary risk appetite","A conservative risk appetite","A low risk threshold","Risk avoidance"],
 w:"Risk appetite is the amount of risk an organization is willing to pursue; an expansionary appetite deliberately accepts more risk for growth.",
 n:["A conservative appetite prefers minimal risk and slower, safer decisions.","A low risk threshold would trigger escalation at small levels of risk, which contradicts the board's intent.","Avoidance means stopping the risky activity entirely, whereas the board wants to pursue it."]},
{id:"x014",obj:"1.2",d:1,q:"A security team plants a spreadsheet named Executive_Salaries_2026.xlsx on a file share. The file has no business use, but any access to it triggers an alert. Which of the following BEST describes this technique?",
 o:["Honeyfile","Honeynet","Honeypot","Data masking"],
 w:"A honeyfile is a decoy document that exists only to reveal unauthorized access when it is opened or copied.",
 n:["A honeynet is an entire decoy network of systems rather than a single file.","A honeypot is a decoy host or service, not a document on a legitimate share.","Data masking hides real values in genuine data; this file contains nothing real."]},
{id:"x015",obj:"3.3",d:3,q:"A company must keep customer records for its German subsidiary inside the EU because local law restricts where that data may be stored and processed. Which of the following concepts is driving this requirement?",
 o:["Data sovereignty","Data minimization","Data masking","Data classification"],
 w:"Data sovereignty means data is subject to the laws of the country where it is stored, which can force geographic restrictions on storage and processing.",
 n:["Minimization is about collecting only what is needed, not about location.","Masking hides portions of values and does not address where the data resides.","Classification labels sensitivity but does not itself dictate geography."]},
{id:"x016",obj:"4.5",d:4,q:"An administrator wants to detect if any system files on a payment server are modified outside of an approved change, without relying on antivirus signatures. Which of the following should be deployed?",
 o:["File integrity monitoring","A network-based IDS","A web filter","NetFlow export"],
 w:"FIM records a known-good hash of each file and alerts when a file's hash changes, catching unauthorized modification regardless of how it occurred.",
 n:["A network IDS inspects packets and cannot see local file changes on the host.","A web filter controls outbound browsing and has no view of the server's file system.","NetFlow records traffic metadata, not file contents or hashes."]},
{id:"x017",obj:"2.2",d:2,q:"A user at a defense contractor receives an email that appears to be from the CFO asking for an urgent wire transfer to a new supplier account. The header shows the message came from a lookalike domain registered two days ago. Which of the following attacks is this?",
 o:["Business email compromise","Vishing","Pharming","Typosquatting a web page"],
 w:"BEC uses a spoofed or lookalike executive identity to pressure staff into fraudulent payments, which is exactly what the wire request is.",
 n:["Vishing is conducted over the phone, whereas this arrived by email.","Pharming redirects users to fake websites via DNS manipulation rather than requesting a payment by email.","Typosquatting registers misspelled domains for websites; here the lookalike domain is used to send a fraudulent email, which is BEC."]},
{id:"x018",obj:"5.4",d:5,q:"A privacy officer receives a request from a former customer in the EU asking that all personal data about them be deleted. Which of the following BEST describes what the customer is exercising?",
 o:["The data subject's right to be forgotten","The controller's duty of care","The processor's retention obligation","The organization's legal hold"],
 w:"Under privacy laws such as GDPR, the individual is the data subject and can request erasure of personal data, commonly called the right to be forgotten.",
 n:["Duty of care describes the organization's obligation to act responsibly, not a request by the individual.","A processor handles data on the controller's behalf and does not own retention decisions.","A legal hold preserves data for litigation, which is the opposite of deletion."]},
{id:"x019",obj:"4.6",d:4,q:"A company is migrating to a passwordless login for its workforce. Which of the following BEST supports this goal while remaining phishing-resistant?",
 o:["FIDO2 security keys with platform biometrics","SMS one-time codes sent to the user's phone","A longer password policy with mandatory complexity","A shared secret question set"],
 w:"FIDO2 keys use public-key cryptography bound to the origin, so nothing reusable is typed or sent and a fake login page cannot capture it.",
 n:["SMS codes are a possession factor that can still be phished or intercepted through SIM swapping, and they usually accompany a password rather than replace it.","Strengthening passwords keeps passwords, which contradicts the passwordless objective.","Secret questions are weak knowledge factors and are easily researched or phished."]},
{id:"x020",obj:"3.2",d:3,q:"A retailer wants its point-of-sale terminals to keep working even if the intrusion prevention appliance in front of them loses power. Which of the following configurations should be chosen?",
 o:["Fail-open","Fail-closed","Active-passive","Tap mode"],
 w:"Fail-open lets traffic continue to pass when the inline device fails, prioritizing availability of the POS terminals over inspection.",
 n:["Fail-closed would drop all traffic when the appliance dies, taking the terminals offline.","Active-passive describes a redundancy pair, not what a single device does when it fails.","A tap copies traffic for monitoring and cannot prevent anything, which is not what the retailer asked about."]},
{id:"x021",obj:"2.4",d:2,q:"A web server log contains the request GET /files?name=../../../../etc/passwd. Which of the following attacks is being attempted?",
 o:["Directory traversal","SQL injection","Cross-site scripting","Buffer overflow"],
 w:"The repeated ../ sequences try to escape the intended folder and read a file elsewhere on the server, which is directory traversal.",
 n:["SQL injection would include quotes, comments, or SQL keywords aimed at a database query.","XSS injects script into pages viewed by other users and would contain script tags or event handlers.","A buffer overflow sends oversized input to overwrite memory, not a path to a system file."]},
{id:"x022",obj:"4.8",d:4,q:"An incident responder must collect evidence from a compromised Linux server that is still running. Which of the following should be captured FIRST?",
 o:["Contents of RAM and running process list","A bit-for-bit image of the hard disk","Backup tapes from the previous night","Logs archived on the SIEM"],
 w:"Order of volatility dictates capturing what disappears soonest, and memory contents and process state are lost the moment the host powers off.",
 n:["The disk persists after shutdown, so it can be imaged after volatile data is preserved.","Backup tapes are stable offline media and will still be there hours later.","SIEM archives are already preserved on another system and do not change if the server is powered down."]},
{id:"x023",obj:"1.4",d:1,q:"A company wants an engineer to be able to recover an employee's encrypted files if the employee leaves without handing over their private key. Which of the following should be implemented?",
 o:["Key escrow","Key stretching","A certificate revocation list","Perfect forward secrecy"],
 w:"Key escrow stores a copy of private keys with a trusted party so authorized recovery is possible when the owner is unavailable.",
 n:["Key stretching slows brute-force attacks on passwords and has nothing to do with recovering keys.","A CRL lists revoked certificates and cannot decrypt files that were protected with a lost key.","Perfect forward secrecy generates ephemeral session keys, which would make recovery harder, not easier."]},
{id:"x024",obj:"5.5",d:5,q:"A company hires a third party to attempt to enter its data center by tailgating and cloning badges, without attacking any network services. Which of the following types of penetration test is this?",
 o:["Physical","Offensive network","Defensive","Integrated"],
 w:"A physical penetration test evaluates facility controls such as doors, badges, and guards by attempting real-world entry.",
 n:["An offensive network test targets systems and services rather than the building.","A defensive engagement focuses on how well the blue team detects and responds, not on breaking in.","An integrated test combines multiple approaches; this engagement is explicitly limited to physical entry."]},
{id:"x025",obj:"3.4",d:3,q:"An organization's disaster recovery plan calls for a secondary facility that has power, cooling, and network connectivity, plus servers that are installed but need data restored from backups before use. Which of the following describes this site?",
 o:["Warm site","Hot site","Cold site","Mirror site"],
 w:"A warm site has equipment in place but not current data, so recovery takes hours to days while backups are restored.",
 n:["A hot site is fully staged with near-real-time data and could take over almost immediately.","A cold site is little more than space and utilities, with no servers installed.","A mirror site replicates production continuously; needing to restore from backups rules it out."]},
{id:"x026",obj:"4.1",d:4,q:"A company issues smartphones that it owns and manages but allows employees limited personal use. Which of the following deployment models is being used?",
 o:["COPE","BYOD","CYOD","VDI"],
 w:"Corporate-owned, personally enabled devices are purchased and controlled by the company while permitting some personal use.",
 n:["BYOD devices belong to the employee, not the company.","CYOD lets the user pick from an approved list, but the defining feature here is company ownership with personal use, which is COPE.","VDI delivers a virtual desktop and is not a smartphone ownership model."]},
{id:"x027",obj:"2.1",d:2,q:"A threat intelligence report describes a group that defaced a pipeline company's website and posted a manifesto opposing fossil fuels. Which of the following threat actor types is MOST likely responsible?",
 o:["Hacktivist","Organized crime","Nation-state","Unskilled attacker"],
 w:"Defacement combined with a political statement points to a hacktivist motivated by philosophical or political beliefs.",
 n:["Organized crime is financially motivated and would prefer ransomware or fraud over a manifesto.","A nation-state usually pursues espionage or disruption quietly rather than public defacement with a cause.","An unskilled attacker seeks notoriety or amusement and rarely publishes an ideological message."]},
{id:"x028",obj:"5.5",d:5,q:"An external auditor asks for evidence that quarterly access reviews were performed. The IT manager provides a signed statement from each department head confirming the review happened. Which of the following does this statement represent?",
 o:["Attestation","Remediation","Due diligence","A gap analysis"],
 w:"Attestation is a formal declaration by a responsible party that a control was performed, which is what the signed statements provide.",
 n:["Remediation would be fixing a finding, not confirming a review occurred.","Due diligence describes investigating before making a decision, such as vetting a vendor.","A gap analysis compares the current state to a target state; it is not a confirmation of completed work."]},
{id:"x029",obj:"4.5",d:4,q:"A network team runs a scan and sees the following output for a database server: 22/tcp open ssh, 23/tcp open telnet, 3306/tcp open mysql, 5900/tcp open vnc. Which of the following should be addressed FIRST?",
 o:["Disable Telnet, which sends credentials in cleartext","Restrict SSH to key-based authentication","Move MySQL to a nonstandard port","Update the VNC banner"],
 w:"Telnet transmits usernames and passwords unencrypted and has no place on a database server; removing it eliminates an obvious credential exposure.",
 n:["SSH hardening is worthwhile, but SSH is already encrypted and is far less urgent than an open cleartext protocol.","Changing the MySQL port is security through obscurity and does not fix any exposure.","A banner change has no security impact compared to the cleartext login service."]},
{id:"x030",obj:"3.1",d:3,q:"A company deploys containers for its microservices and wants each service to run with only the libraries it needs, sharing the host kernel. Which of the following is an inherent security consideration of this approach?",
 o:["A kernel exploit in one container can affect every container on the host","Each container requires its own hypervisor license","Containers cannot be scanned for vulnerabilities","Containers must always run as root"],
 w:"Because containers share the host kernel, a kernel-level compromise is not isolated to a single container the way a VM escape would be to a hypervisor.",
 n:["Containers do not use a hypervisor at all; that is what distinguishes them from VMs.","Container images are routinely scanned for vulnerable packages as part of CI pipelines.","Running containers as non-root is a standard hardening practice and is fully supported."]},
{id:"x031",obj:"1.2",d:1,q:"In a zero trust design, a remote user's request to open a finance application is evaluated against device health, location, and role, and then a decision is sent to the gateway that actually allows or blocks the session. Which component makes the decision?",
 o:["The policy engine","The policy enforcement point","The implicit trust zone","The subject"],
 w:"The policy engine in the control plane evaluates signals and decides whether to grant access; the policy administrator then instructs the enforcement point.",
 n:["The policy enforcement point sits in the data plane and carries out the decision but does not make it.","An implicit trust zone is the network segment behind the enforcement point, not a decision-making component.","The subject is the user or device requesting access, not the evaluator."]},
{id:"x032",obj:"2.2",d:2,q:"A help desk analyst receives a call from someone claiming to be a new auditor who needs a temporary password reset because the CFO said it was pre-approved. No ticket exists. Which of the following BEST describes the technique being used?",
 o:["Pretexting","Tailgating","Shoulder surfing","Dumpster diving"],
 w:"Pretexting builds a believable backstory, here an auditor with executive approval, to manipulate the target into bypassing procedure.",
 n:["Tailgating is following an authorized person through a physical door, not a phone request.","Shoulder surfing observes screens or keypads in person to steal information.","Dumpster diving retrieves discarded documents; no trash is involved in this call."]},
{id:"x033",obj:"4.6",d:4,q:"A company wants developers to have administrative rights on production servers only while an approved change ticket is open, with the rights removed automatically when the ticket closes. Which of the following BEST meets this need?",
 o:["Just-in-time privileged access","Password vaulting","Role-based access with a permanent admin group","Time-of-day restrictions"],
 w:"JIT access grants elevated privileges only for the duration of an approved task and revokes them automatically, shrinking the window of standing privilege.",
 n:["Vaulting protects and rotates admin credentials but does not by itself tie access to an open ticket.","A standing admin group grants permanent privilege, the opposite of what is required.","Time-of-day rules limit access to hours, not to a specific approved change."]},
{id:"x034",obj:"5.4",d:5,q:"A hospital was fined by a regulator after an audit found patient records were retained on unencrypted laptops. Which of the following consequences of non-compliance has occurred?",
 o:["Fines","Loss of license","Contractual impact","Sanctions against an individual"],
 w:"A regulator imposing a monetary penalty is the fines consequence of non-compliance.",
 n:["The hospital was not barred from operating, so no license was lost.","No customer contract was breached in the scenario; the penalty came from a regulator.","The penalty was levied on the organization, not a sanction against a specific person."]},
{id:"x035",obj:"3.2",d:3,q:"A security architect wants to monitor traffic on a core link with an IDS but must guarantee that a sensor failure can never interrupt production traffic. Which of the following should be used?",
 o:["A network tap feeding a passive sensor","An inline IPS in fail-closed mode","A transparent proxy","A load balancer in active-active mode"],
 w:"A tap copies traffic to a passive, out-of-band sensor, so the sensor is not in the forwarding path and cannot cause an outage.",
 n:["An inline device in fail-closed mode drops traffic on failure, which is the exact outcome to avoid.","A transparent proxy is inline and therefore a potential point of failure.","A load balancer distributes traffic to servers; it is not a monitoring sensor."]},
{id:"x036",obj:"4.4",d:4,q:"A SIEM generates 900 alerts a day for a rule that fires on any failed login, and analysts have stopped looking at them. Which of the following should the SOC do to improve the situation?",
 o:["Tune the rule to correlate multiple failures per account within a short window","Disable logging of failed logins on the domain controllers","Route all failed-login alerts to email instead of the SIEM console","Increase log retention to 12 months"],
 w:"Alert tuning raises the threshold so the rule fires on meaningful patterns, reducing noise and restoring analyst attention.",
 n:["Turning off the log source destroys evidence needed for investigations and compliance.","Changing the delivery channel does not reduce the volume of low-value alerts.","Retention affects how long data is kept and has no effect on daily alert fatigue."]},
{id:"x037",obj:"2.4",d:2,q:"An attacker sends a 60-byte DNS query with a spoofed source address to hundreds of open resolvers, causing each to send a 3,000-byte response to the victim. Which of the following BEST describes this attack?",
 o:["Amplified and reflected DDoS","On-path attack","DNS cache poisoning","Domain hijacking"],
 w:"Spoofing the victim's address reflects responses off third-party servers, and the large response-to-request ratio amplifies the volume into a denial of service.",
 n:["An on-path attack intercepts traffic between two parties rather than flooding a target.","Cache poisoning inserts false records into a resolver; here the resolvers are behaving normally.","Domain hijacking takes control of a domain's registration, not its traffic volume."]},
{id:"x038",obj:"5.3",d:5,q:"Two government agencies want to document their intent to share threat intelligence and coordinate on incident response, without creating legally enforceable obligations. Which of the following documents is MOST appropriate?",
 o:["Memorandum of understanding","Master service agreement","Statement of work","Service level agreement"],
 w:"An MOU records mutual intent and expectations between parties and is typically not legally binding.",
 n:["An MSA is a binding contract that sets terms for ongoing commercial work.","An SOW defines specific deliverables under a contract and is enforceable.","An SLA sets measurable performance commitments with penalties, which the agencies want to avoid."]},
{id:"x039",obj:"4.6",d:4,q:"An employee transferred from sales to accounting six months ago and still has access to the CRM export function. Which of the following IAM processes would have prevented this?",
 o:["Periodic access recertification with removal of unneeded roles","Enforcing a stricter password expiration policy","Enabling MFA on the CRM","Implementing single sign-on"],
 w:"Regular access reviews catch privilege creep by requiring managers to reconfirm or revoke each entitlement after role changes.",
 n:["Password expiration changes the credential but leaves the excessive permission in place.","MFA strengthens authentication but does not remove authorization the user no longer needs.","SSO centralizes login and does nothing to de-provision old role assignments."]},
{id:"x040",obj:"1.2",d:1,q:"A data center entrance uses two interlocking doors: the second door will not open until the first has closed and the person has badged again. Which of the following is this control?",
 o:["Access control vestibule","Bollard","Pressure sensor","Faraday cage"],
 w:"An access control vestibule, or mantrap, traps one person between doors to prevent tailgating and piggybacking.",
 n:["Bollards are posts that stop vehicles from ramming an entrance.","A pressure sensor detects weight or footsteps but does not itself control entry.","A Faraday cage blocks electromagnetic signals and has nothing to do with door control."]},
{id:"x041",obj:"3.4",d:3,q:"A company's applications must remain available if an entire cloud region is lost, and the company also wants to avoid depending on one provider's pricing. Which of the following BEST addresses both concerns?",
 o:["Deploy the workload across multiple cloud providers in different geographic regions","Enable snapshots of each virtual machine every hour","Purchase a larger reserved instance in a single region","Move all workloads to an on-premises hot site"],
 w:"A multi-cloud, geographically dispersed design survives a regional outage and avoids single-vendor lock-in.",
 n:["Snapshots help restore data but stay within the same provider and region that could fail.","A larger instance in one region does nothing for regional loss or provider dependency.","An on-premises hot site addresses availability but concentrates rather than diversifies infrastructure."]},
{id:"x042",obj:"2.4",d:2,q:"A remote worker's laptop shows a new toolbar in the browser, ads appear on every page, and search results are redirected. CPU use is normal and no data has been encrypted. Which of the following is the MOST likely cause?",
 o:["Spyware or adware bundled with a downloaded program","A rootkit","Ransomware in its initial phase","A logic bomb"],
 w:"Browser toolbars, injected ads, and redirected searches are classic indicators of potentially unwanted adware and spyware that came along with a free download.",
 n:["A rootkit hides itself and would not announce its presence with visible toolbars and ads.","Ransomware encrypts files and demands payment; no encryption has occurred.","A logic bomb lies dormant until a trigger condition, and does not produce ongoing ad injection."]},
{id:"x043",obj:"4.1",d:4,q:"A company's hardening standard for switches requires unused ports to be shut down and management to be reachable only from a dedicated VLAN. A junior admin asks why. Which of the following is the BEST explanation?",
 o:["It reduces the attack surface by removing avenues an attacker could use to gain access","It improves link speed on the remaining ports","It is required so that DHCP snooping can function","It prevents spanning-tree loops"],
 w:"Disabling unused ports and restricting management interfaces removes services and access paths, which is the definition of reducing attack surface.",
 n:["Shutting a port has no effect on throughput of other ports.","DHCP snooping works independently of whether unused ports are disabled.","Loop prevention is handled by spanning-tree itself, not by port shutdown."]},
{id:"x044",obj:"5.4",d:5,q:"A new employee signs a document confirming they have read the policy prohibiting personal cloud storage for company files. Which of the following compliance monitoring elements does the signature satisfy?",
 o:["Acknowledgement","Due diligence","External audit","Risk transference"],
 w:"An acknowledgement records that the individual received and understood the policy, creating accountability for later violations.",
 n:["Due diligence describes the organization's own investigation before decisions, not a user's signature.","An external audit is performed by an independent party, not a new hire.","Signing a policy does not move any risk to another party."]},
{id:"x045",obj:"3.3",d:3,q:"A media company classifies its unreleased film scripts as trade secrets. Which of the following data protection methods is MOST appropriate for these files while they are stored on the shared production server?",
 o:["Encryption at rest with access limited to the production group","Hashing each script with SHA-256","Tokenizing the script contents","Publishing a watermark policy"],
 w:"Encrypting the files at rest and restricting permissions protects confidentiality of stored trade secrets even if the storage is copied.",
 n:["Hashing verifies integrity but does not keep anyone from reading the script.","Tokenization replaces discrete values like card numbers; it is not practical for full documents.","A watermark policy may deter leaks but does not prevent unauthorized reading of stored files."]},
{id:"x046",obj:"4.8",d:4,q:"A security team is building a detection for an adversary that is believed to already be inside the network but has generated no alerts. Analysts form a hypothesis about lateral movement over SMB and search historical logs for it. Which of the following activities is this?",
 o:["Threat hunting","Vulnerability scanning","Penetration testing","Root cause analysis"],
 w:"Threat hunting is a proactive, hypothesis-driven search for adversary activity that existing alerts have not detected.",
 n:["Vulnerability scanning enumerates weaknesses, not evidence of an active intruder.","Penetration testing simulates an attacker rather than searching for a real one.","Root cause analysis explains why a known incident happened; here no incident has yet been confirmed."]},
{id:"x047",obj:"2.2",d:2,q:"A company's HVAC vendor was compromised, and the attacker used the vendor's remote maintenance VPN account to reach the company's payment systems. Which of the following threat vectors does this describe?",
 o:["Supply chain via a managed service provider","Removable media","Unsupported operating system","Image-based phishing"],
 w:"The attacker entered through a trusted third-party provider's access, which is the supply-chain vector involving vendors and MSPs.",
 n:["No USB or removable device was involved in the intrusion.","The scenario does not indicate any end-of-life system was exploited.","No email or image payload was used; the vendor's legitimate credentials were."]},
{id:"x048",obj:"5.2",d:5,q:"A risk register lists a risk of ransomware with a threshold of 24 hours of downtime, and a metric tracking the number of unpatched critical vulnerabilities older than 30 days. Which of the following BEST describes that metric?",
 o:["Key risk indicator","Risk appetite","Exposure factor","Annualized rate of occurrence"],
 w:"A key risk indicator is a measurable signal that shows whether a risk is trending toward its threshold, such as aging critical vulnerabilities.",
 n:["Risk appetite is a strategic statement about how much risk the organization will pursue, not a tracked metric.","Exposure factor is the percentage of an asset lost in one event.","ARO is the expected frequency of an event per year, not a leading indicator."]},
{id:"x049",obj:"1.4",d:1,q:"A company issues employee badges as certificates and wants a browser to confirm a certificate is still valid with a single small query to the CA rather than downloading a large list. Which of the following should be used?",
 o:["OCSP","CRL","CSR","Key escrow"],
 w:"OCSP returns the status of one certificate in real time, avoiding the size and latency of a full revocation list.",
 n:["A CRL is the large downloaded list the company wants to avoid.","A CSR is used to request a certificate, not to check its status.","Key escrow stores private keys for recovery and does not report validity."]},
{id:"x050",obj:"4.8",d:4,q:"A SOC receives an alert that an endpoint is beaconing to a known command-and-control domain every 60 seconds. Which of the following is the BEST immediate response action?",
 o:["Quarantine the endpoint from the network using the EDR tool","Reimage the endpoint immediately","Add the domain to the corporate allow list","Wait for the next scheduled vulnerability scan"],
 w:"Isolating the host with EDR quarantine stops the C2 channel while preserving the system for analysis.",
 n:["Reimaging before analysis destroys evidence and does not tell you what the attacker did.","Allowing the domain would let the malicious channel continue.","A vulnerability scan does not address active compromise and delays containment."]},
{id:"x051",obj:"3.2",d:3,q:"A network engineer wants to authenticate every device that plugs into a conference room switch port before it is placed on a VLAN, using certificates issued by the corporate CA. Which of the following should be implemented?",
 o:["802.1X with EAP-TLS","Port mirroring","MAC address filtering","A captive portal"],
 w:"802.1X provides port-based network access control, and EAP-TLS uses client certificates for strong mutual authentication.",
 n:["Port mirroring copies traffic for monitoring and performs no authentication.","MAC filtering is easily bypassed by spoofing and does not use certificates.","A captive portal authenticates users through a web page, typically on guest Wi-Fi, not certificate-based port control."]},
{id:"x052",obj:"2.3",d:2,q:"A web application checks whether a user has enough balance and then, in a separate step, debits the account. An attacker submits two withdrawals at the same instant and both succeed even though the balance covered only one. Which of the following vulnerabilities was exploited?",
 o:["Race condition (time-of-check to time-of-use)","Buffer overflow","SQL injection","Integer overflow"],
 w:"The gap between checking the balance and using it lets concurrent requests both pass the check, a TOC/TOU race condition.",
 n:["A buffer overflow corrupts memory with oversized input, which is not involved here.","No database query was manipulated; the logic simply was not atomic.","An integer overflow wraps a numeric value; the balance was not miscalculated, only checked too early."]},
{id:"x053",obj:"4.1",d:4,q:"An analyst reviewing a mobile fleet notices an executive's phone has an application store that is not the vendor's, and several apps that were installed from downloaded package files. Which of the following risks does this present?",
 o:["Sideloaded apps bypass store vetting and may contain malware","The device battery will drain faster","The device cannot receive push notifications","MDM will automatically reset the phone"],
 w:"Sideloading installs software outside the official store, skipping the review and signing checks that catch malicious apps.",
 n:["Battery use is not the security concern being asked about.","Push notification behavior is unrelated to how apps were installed.","MDM can flag or block sideloading, but it does not automatically wipe a device by default."]},
{id:"x054",obj:"5.6",d:5,q:"A company's security awareness program sends simulated phishing messages quarterly and tracks who clicks. An employee who fails twice is enrolled in additional training. Which of the following BEST describes this element of the program?",
 o:["Reporting and monitoring with recurring reinforcement","Initial onboarding training","Policy acknowledgement","Anomalous behavior recognition"],
 w:"Recurring simulations with metrics and targeted follow-up are the reporting and monitoring component of an awareness program.",
 n:["Initial training happens once at hire; this is an ongoing quarterly measure.","Acknowledgement is signing that a policy was read, not measuring behavior.","Anomalous behavior recognition is about spotting unusual coworker activity, not click rates on simulations."]},
{id:"x055",obj:"3.2",d:3,q:"A company wants a single cloud-delivered service that combines SD-WAN connectivity with a secure web gateway, CASB, and zero trust network access for its remote workforce. Which of the following should be adopted?",
 o:["SASE","A site-to-site IPSec VPN","A traditional UTM appliance","A screened subnet"],
 w:"Secure access service edge merges SD-WAN networking with cloud-delivered security functions such as SWG, CASB, and ZTNA.",
 n:["A site-to-site VPN connects two locations and does not provide cloud-hosted security services for roaming users.","A UTM is an on-premises appliance rather than a cloud-delivered edge service.","A screened subnet is a network zone for public-facing servers, not a remote-access service."]},
{id:"x056",obj:"4.8",d:4,q:"After a breach, investigators must ensure a hard drive taken from the suspect workstation is admissible in court. Which of the following is MOST important to maintain?",
 o:["Chain of custody documentation for every transfer of the drive","A copy of the company's acceptable use policy","The drive's original purchase invoice","A screenshot of the SIEM dashboard"],
 w:"Chain of custody records who handled the evidence, when, and why, proving it was not tampered with between collection and court.",
 n:["The AUP may support the case but does not establish evidence integrity.","A purchase invoice shows ownership, not handling of the evidence.","A dashboard screenshot is context, not proof that the drive remained unaltered."]},
{id:"x057",obj:"2.2",d:2,q:"A company's public website was compromised by an attacker who first infected a small industry news site that the company's engineers visit every morning. Which of the following attacks was used against the engineers?",
 o:["Watering hole","Spear phishing","Brand impersonation","Vishing"],
 w:"A watering-hole attack compromises a third-party site the targets are known to frequent so that visiting it delivers the payload.",
 n:["Spear phishing sends a targeted message; no message was involved here.","Brand impersonation pretends to be a trusted company, whereas this used a genuine site.","Vishing uses voice calls, not a website."]},
{id:"x058",obj:"1.4",d:1,q:"An administrator needs one certificate that will secure mail.example.com, www.example.com, and shop.example.com. Which of the following certificate types is the MOST efficient choice?",
 o:["Wildcard certificate for *.example.com","Self-signed certificate","Root CA certificate","Code-signing certificate"],
 w:"A wildcard certificate covers every single-level subdomain of example.com, so one certificate secures all three hosts.",
 n:["A self-signed certificate is not trusted by clients and would trigger browser warnings.","A root CA certificate signs other certificates; it is not installed on web servers for TLS.","Code-signing certificates verify software publishers, not web servers."]},
{id:"x059",obj:"5.2",d:5,q:"A retailer has decided to stop storing full credit card numbers entirely and instead hands the transaction to a payment processor. Which of the following risk strategies BEST describes this decision?",
 o:["Avoidance","Acceptance","Mitigation","Exemption"],
 w:"By eliminating the activity that created the risk, storing card numbers, the retailer avoids the risk rather than managing it.",
 n:["Acceptance would keep storing the numbers and live with the exposure.","Mitigation reduces the risk with controls such as encryption while still storing the data.","An exemption is a formal approval to not follow a requirement, not a change to the business process."]},
{id:"x060",obj:"4.5",d:4,q:"A security engineer wants users to be blocked from newly registered domains and known malicious URLs regardless of whether they are on the corporate LAN or at home. Which of the following is the BEST solution?",
 o:["An agent-based web filter installed on each laptop","A centralized proxy on the corporate network","A firewall rule on the office edge router","A network-based IPS in the data center"],
 w:"An agent on the endpoint enforces URL reputation and category rules wherever the device connects, including home networks.",
 n:["A centralized proxy only protects traffic that passes through it, which home users bypass.","An edge firewall rule protects only devices behind the office router.","A data-center IPS never sees a remote laptop's direct internet browsing."]},
{id:"x061",obj:"3.1",d:3,q:"A cloud team defines its entire environment in version-controlled template files and rebuilds it from those files on every deployment. An engineer manually opens a security group port in the console, and it is silently closed at the next deployment. Which of the following explains this?",
 o:["Infrastructure as code re-applied the declared configuration and removed the drift","The cloud provider's firewall blocks all manual changes","The security group was deleted by an SOAR playbook","The change violated the acceptable use policy"],
 w:"With IaC the template is the source of truth; any manual change that is not in the code is overwritten when the pipeline reconciles the environment.",
 n:["Cloud providers permit console changes; the reversal came from the deployment, not the provider.","Nothing in the scenario indicates a SOAR playbook; the pipeline simply redeployed the template.","Policy violations do not cause technical rollback; the IaC process does."]},
{id:"x062",obj:"2.2",d:2,q:"A newly installed IP camera on the loading dock is found broadcasting video to an external IP address. The camera still uses the username and password printed in its quick-start guide. Which of the following was the MOST likely attack vector?",
 o:["Default credentials on an internet-reachable device","Bluetooth pairing exploit","Image-based phishing","Malicious USB drop"],
 w:"Unchanged default credentials let anyone who can reach the device log in, which is a well-known IoT weakness scanned for constantly.",
 n:["Bluetooth is not implicated in a network camera that is streaming out over IP.","No email or image lure was involved; the device itself was accessed directly.","No removable media was inserted into the camera."]},
{id:"x063",obj:"4.1",d:4,q:"A web application stores the session identifier in a cookie. A penetration tester was able to read it with JavaScript injected through a comment field and to capture it over an HTTP link. Which of the following cookie attributes should be set to address BOTH problems?",
 o:["HttpOnly and Secure","SameSite=None and Path=/","Max-Age and Domain","Expires and Version"],
 w:"HttpOnly hides the cookie from scripts, blocking theft via XSS, and Secure ensures the browser sends it only over HTTPS.",
 n:["SameSite=None actually loosens cross-site restrictions, and Path does not stop script access or cleartext transmission.","Max-Age and Domain control lifetime and scope, not script access or transport encryption.","Expires sets lifetime and Version is obsolete; neither addresses the two findings."]},
{id:"x064",obj:"5.1",d:5,q:"A security policy states that all users must protect their credentials. A companion document specifies a minimum of 14 characters, a ban on the last 10 passwords, and MFA for remote access. Which of the following BEST describes the companion document?",
 o:["A standard","A guideline","A procedure","A playbook"],
 w:"A standard sets mandatory, measurable requirements that implement a policy's intent, such as specific password parameters.",
 n:["A guideline is a recommendation and is not mandatory, whereas these values are required.","A procedure is a step-by-step instruction for performing a task, not a set of requirements.","A playbook is a runbook for responding to a specific incident type."]},
{id:"x065",obj:"3.2",d:3,q:"A company must administer servers in a screened subnet but does not want administrator workstations to connect to those servers directly. Which of the following should be deployed?",
 o:["A hardened jump server in the screened subnet","A wildcard certificate","A honeypot","A NetFlow collector"],
 w:"A jump server is a hardened, monitored host that administrators connect to first, and it alone is permitted to reach the managed systems.",
 n:["A certificate secures a connection but does not create a controlled administrative path.","A honeypot is a decoy for attackers and should never be a legitimate management path.","A NetFlow collector gathers traffic metadata and provides no administrative access."]},
{id:"x066",obj:"4.5",d:4,q:"Analysts see repeated failed logins from a workstation, then a successful login, then the account browsing shares it has never touched. Which of the following tools is designed to flag this deviation from the account's normal pattern?",
 o:["User behavior analytics","Vulnerability scanner","DNS filter","Load balancer"],
 w:"UBA baselines each user's typical activity and raises alerts when behavior deviates, such as sudden access to unfamiliar resources.",
 n:["A vulnerability scanner finds weaknesses in systems, not anomalies in a user's activity.","DNS filtering blocks malicious domains and does not model user behavior.","A load balancer distributes traffic and has no analytic function."]},
{id:"x067",obj:"1.3",d:1,q:"During a change advisory meeting, a proposed database upgrade is approved on condition that the team documents how to return to the previous version if the upgrade fails. Which of the following change management elements is being required?",
 o:["Backout plan","Maintenance window","Impact analysis","Standard operating procedure"],
 w:"A backout plan describes how to restore the prior state if a change goes wrong, and it is a normal condition of approval.",
 n:["A maintenance window specifies when the change may happen, not how to reverse it.","Impact analysis assesses what the change could affect before approval.","An SOP is the routine procedure for performing a task, not a recovery plan for a specific change."]},
{id:"x068",obj:"2.3",d:2,q:"A cloud tenant discovers that a vulnerability in the hypervisor allowed code running in a neighbor's virtual machine to read memory belonging to the tenant's VM. Which of the following vulnerability types is this?",
 o:["VM escape","Resource reuse","Sideloading","Firmware vulnerability"],
 w:"VM escape occurs when code breaks out of the guest boundary to interact with the hypervisor or other guests.",
 n:["Resource reuse concerns data left behind in storage or memory that is reallocated, not active cross-VM code execution.","Sideloading is installing unofficial apps on mobile devices.","The flaw was in the hypervisor software, not the hardware firmware."]},
{id:"x069",obj:"5.3",d:5,q:"Before beginning a penetration test, the consultant and the client agree in writing on the IP ranges to be tested, the hours of testing, and the emergency contact if a system crashes. Which of the following documents captures these details?",
 o:["Rules of engagement","Non-disclosure agreement","Business partnership agreement","Acceptable use policy"],
 w:"The rules of engagement define scope, timing, and communication for a test so it stays legal and safe.",
 n:["An NDA protects confidential information but does not set testing boundaries.","A BPA governs a shared business venture, not a security assessment.","An AUP applies to employees' use of company resources, not to an external tester."]},
{id:"x070",obj:"4.3",d:4,q:"A vulnerability report lists: CVE-A on the public web server, CVSS 9.8, exploit available; CVE-B on an internal print server, CVSS 7.5; CVE-C on a lab VM, CVSS 5.3. Which of the following should be remediated FIRST?",
 o:["CVE-A, because it is critical, exposed to the internet, and actively exploitable","CVE-B, because print servers hold sensitive documents","CVE-C, because lab systems have weaker controls","All three at the same time, as severity does not matter"],
 w:"Prioritization combines CVSS with environmental factors; an internet-facing critical flaw with a public exploit is the highest real-world risk.",
 n:["An internal print server with a high score is important but less exposed than a public server with a working exploit.","A medium-severity issue on an isolated lab VM is the lowest priority of the three.","Severity, exposure, and exploitability all matter and drive the order of work."]},
{id:"x071",obj:"3.4",d:3,q:"A company's RPO for its order database is 15 minutes. Nightly full backups are the only protection in place. Which of the following should be added to meet the objective?",
 o:["Continuous transaction journaling or replication to a secondary system","A second nightly full backup to a different tape","Weekly differential backups","A longer retention period for the nightly backups"],
 w:"Meeting a 15-minute RPO requires capturing changes at least that often, which journaling or near-real-time replication provides.",
 n:["Two nightly backups still leave up to a day of data loss.","Weekly differentials capture changes even less frequently than nightly fulls.","Retention affects how far back you can restore, not how much recent data is lost."]},
{id:"x072",obj:"2.4",d:2,q:"A packet capture of a TLS handshake shows the client offered TLS 1.3 but the negotiated version was SSL 3.0 after the server received an altered ClientHello. Which of the following attacks is indicated?",
 o:["Downgrade attack","Birthday attack","Collision attack","Credential replay"],
 w:"Forcing negotiation to an older, weaker protocol version so it can be broken is a downgrade attack.",
 n:["A birthday attack exploits hash collision probability, not protocol negotiation.","A collision attack finds two inputs with the same hash and is unrelated to TLS version selection.","Replay reuses captured authentication data; here the negotiation itself was tampered with."]},
{id:"x073",obj:"4.2",d:4,q:"A company retires 200 laptops that held customer data and sends them to a recycler. Which of the following should the company obtain to demonstrate that the data was properly sanitized?",
 o:["A certificate of destruction or sanitization from the recycler","A copy of the recycler's marketing brochure","A receipt for the shipping costs","A screenshot of the last backup job"],
 w:"A certificate of sanitization or destruction is documented evidence that each device's data was rendered unrecoverable, supporting compliance obligations.",
 n:["A brochure describes services offered but does not prove what was done to these specific devices.","A shipping receipt proves transport, not data destruction.","A backup screenshot shows data was copied, which does nothing to prove it was removed from the laptops."]},
{id:"x074",obj:"5.2",d:5,q:"A business impact analysis for an e-commerce site determines that the site can be down for at most four hours before losses become unacceptable. Which of the following metrics has been defined?",
 o:["Recovery time objective","Recovery point objective","Mean time between failures","Mean time to repair"],
 w:"RTO is the maximum tolerable time a service can be unavailable before recovery must be complete.",
 n:["RPO measures acceptable data loss in time, not tolerable downtime.","MTBF is the average time a component runs between failures, a reliability measure.","MTTR is the observed average time to fix a failure, not the business target for downtime."]},
{id:"x075",obj:"3.4",d:3,q:"A company wants to prove its disaster recovery plan works by actually switching production traffic to the secondary site for a weekend, then switching back. Which of the following testing methods is this?",
 o:["Failover test","Tabletop exercise","Simulation","Parallel processing"],
 w:"A failover test moves live operations to the alternate site to verify the cutover works end to end.",
 n:["A tabletop is a discussion-based walkthrough with no systems changed.","A simulation exercises procedures against a scripted event without moving production.","Parallel processing runs both sites at once and compares results rather than cutting over."]},
{id:"x076",obj:"1.4",d:1,q:"A password database was stolen, and the attacker cracked hundreds of accounts sharing the same password in seconds using a precomputed table. Which of the following would have made this MUCH harder?",
 o:["Adding a unique salt to each password before hashing","Encoding the passwords with Base64","Using a shorter hash output","Storing the passwords with reversible encryption"],
 w:"A per-user salt makes identical passwords produce different hashes and defeats precomputed rainbow tables.",
 n:["Base64 is trivially reversible encoding and offers no protection at all.","A shorter hash weakens collision resistance and does nothing against precomputed tables.","Reversible encryption exposes every password once the key is obtained."]},
{id:"x077",obj:"4.7",d:4,q:"An organization automated user provisioning with a script written years ago by a contractor who has left. No one understands it, it runs as a domain admin, and it fails when the HR system changes a field. Which of the following automation considerations does this illustrate?",
 o:["Technical debt and ongoing supportability","Improved reaction time","Workforce multiplier","Enforcing baselines"],
 w:"Unmaintained, undocumented automation that requires excessive privilege is a supportability burden and accumulated technical debt.",
 n:["Faster reaction is a benefit of automation, not the problem described.","Workforce multiplication is a benefit; here the script consumes effort rather than saving it.","Baseline enforcement is a use case for automation, not the risk in this scenario."]},
{id:"x078",obj:"2.4",d:2,q:"A server's antivirus reports clean, but a network sensor shows the host connecting to a foreign IP every night. Running processes and open ports viewed locally do not show the connection. Which of the following is MOST likely installed?",
 o:["A rootkit hiding its processes and network activity","A worm spreading via SMB","Bloatware from the vendor image","A logic bomb awaiting a date trigger"],
 w:"A rootkit subverts the operating system so its processes and connections are invisible to local tools, which explains why only the network sees the traffic.",
 n:["A worm would be noisy, generating scans and visible processes rather than hiding.","Bloatware is unwanted preinstalled software; it does not conceal itself from the OS.","A logic bomb is dormant until triggered and would not produce nightly connections."]},
{id:"x079",obj:"5.3",d:5,q:"A procurement manager recommends a security vendor without disclosing that a family member owns the company. Which of the following vendor selection concerns has been violated?",
 o:["Conflict of interest","Right to audit","Supply chain analysis","Rules of engagement"],
 w:"A conflict of interest exists when a personal relationship could bias a business decision, and it must be disclosed during due diligence.",
 n:["Right to audit is a contract clause, not a selection integrity issue.","Supply chain analysis evaluates the vendor's own suppliers, not the buyer's relationships.","Rules of engagement govern penetration tests, not procurement ethics."]},
{id:"x080",obj:"4.6",d:4,q:"A company wants its employees to log in to a partner's SaaS application with their corporate credentials, and the partner should never see the employees' passwords. Which of the following should be implemented?",
 o:["SAML-based federation with the company as the identity provider","LDAP synchronization of password hashes to the partner","A shared service account for all employees","Local accounts on the SaaS platform with the same passwords"],
 w:"With SAML federation, users authenticate to their own IdP and the SaaS provider receives a signed assertion, never the credential.",
 n:["Copying password hashes to a third party exposes the credentials the company wanted to protect.","A shared account destroys accountability and violates least privilege.","Duplicate local passwords force users to manage credentials in two places and expose them to the partner."]},
{id:"x081",obj:"3.4",d:3,q:"A company runs its public website on four identical servers. It wants traffic spread across all four and wants a failed server removed automatically without users noticing. Which of the following should be deployed?",
 o:["A load balancer with health checks","A failover cluster with shared storage","A reverse proxy cache","Round-robin DNS only"],
 w:"A load balancer distributes requests and uses health checks to stop sending traffic to a node that fails, delivering both scaling and transparent failover.",
 n:["A failover cluster typically keeps standby nodes idle rather than spreading traffic across all members.","A cache accelerates content delivery but does not manage server health or distribution.","Round-robin DNS keeps handing out the failed server's address until clients time out."]},
{id:"x082",obj:"2.4",d:2,q:"A SOC notices that a file server that normally sends logs every minute has sent nothing for six hours, while the server itself is still online. Which of the following indicators does this represent?",
 o:["Missing logs, possibly from an attacker disabling logging","Impossible travel","Resource consumption","Concurrent session usage"],
 w:"An unexpected gap in logging from a healthy system is a classic sign that an attacker stopped or cleared logs to hide activity.",
 n:["Impossible travel involves logins from distant locations in a short time, not a logging gap.","Resource consumption would show high CPU, disk, or bandwidth usage.","Concurrent sessions would show the same account active from multiple places."]},
{id:"x083",obj:"4.1",d:4,q:"An organization is designing a wireless network for a new warehouse. Before placing access points, the engineer walks the building measuring signal strength and interference. Which of the following is the engineer performing?",
 o:["A site survey to produce a heat map","A vulnerability scan","A penetration test","Packet capture analysis"],
 w:"A site survey measures coverage and interference and produces a heat map that guides access point placement and power.",
 n:["A vulnerability scan looks for software weaknesses, not signal coverage.","A penetration test attacks systems and would not be done before the network exists.","Packet captures analyze traffic content, not RF coverage."]},
{id:"x084",obj:"5.1",d:5,q:"A hospital's IT department manages the storage systems and backups for patient records, but decisions about who may access those records are made by the chief medical officer. Which of the following BEST describes IT's role?",
 o:["Data custodian","Data owner","Data controller","Data subject"],
 w:"The custodian implements and operates the technical safeguards for data on behalf of the owner who sets access decisions.",
 n:["The data owner is accountable for the data and decides its classification and access, which is the CMO here.","The controller determines the purpose of processing, a legal role held by the organization, not the IT team.","Data subjects are the patients whose records are stored."]},
{id:"x085",obj:"1.2",d:1,q:"A contractor emails a signed PDF of a bid. Later the contractor claims the bid was altered and that the signature is not theirs. The company verifies the signature with the contractor's public certificate and it validates. Which of the following security properties does the valid signature provide?",
 o:["Integrity and non-repudiation","Confidentiality and availability","Availability and authentication","Confidentiality only"],
 w:"A digital signature made with a private key proves the document is unchanged and that only the key holder could have produced it, so the signer cannot credibly deny it.",
 n:["A signature does not encrypt the document, so it provides no confidentiality, and availability is unrelated.","Availability is not a property of signatures, and while identity is proven, the key point is the signer cannot deny it.","Signing leaves the PDF readable by anyone; it provides no confidentiality."]},
{id:"x086",obj:"3.4",d:3,q:"A data center has a UPS that can carry the load for 20 minutes. Regional outages in the area regularly last two hours. Which of the following should be added to maintain availability?",
 o:["A backup generator with automatic transfer","A second UPS of the same size","Redundant power supplies in each server","A managed PDU"],
 w:"A generator provides sustained power for long outages, while the UPS bridges the gap until the generator starts.",
 n:["Doubling UPS capacity yields about 40 minutes, still far short of a two-hour outage.","Redundant server power supplies protect against a supply failure, not a loss of utility power.","A managed PDU controls and monitors outlets but supplies no power of its own."]},
{id:"x087",obj:"4.8",d:4,q:"Following a ransomware incident, the security team meets to review what went well, what failed, and which controls should change. Which of the following incident response phases is this?",
 o:["Lessons learned","Containment","Eradication","Preparation"],
 w:"Lessons learned is the final phase in which the response is reviewed and improvements are fed back into preparation.",
 n:["Containment stops the spread of the incident and occurs long before the review.","Eradication removes the malware and root cause from systems.","Preparation happens before an incident; this review updates it, but the meeting itself is lessons learned."]},
{id:"x088",obj:"2.4",d:2,q:"A company's public DNS zone was modified so that its web address resolves to an attacker-controlled server, and customers are being served a fake login page. Which of the following BEST describes the attack?",
 o:["DNS attack via domain hijacking of the registrar account","Cross-site scripting","Bluejacking","Buffer overflow"],
 w:"Altering authoritative DNS records at the registrar redirects every visitor, a DNS-based attack achieved through domain hijacking.",
 n:["XSS injects script into the real site; here the real site is bypassed entirely.","Bluejacking sends unsolicited Bluetooth messages and is unrelated to DNS.","A buffer overflow is a memory corruption flaw, not a record manipulation."]},
{id:"x089",obj:"5.1",d:5,q:"An internal audit finds that the change management policy has not been reviewed in five years and no longer references the cloud platforms the company uses. Which of the following governance activities is missing?",
 o:["Monitoring and revision of the policy","External regulatory reporting","Attestation by the audit committee","Penetration testing"],
 w:"Governance requires policies to be periodically reviewed and revised so they stay aligned with the current environment.",
 n:["Regulatory reporting is about compliance disclosures, not keeping internal policy current.","Attestation confirms a control was performed; it does not update the policy content.","Penetration testing evaluates technical controls, not policy currency."]},
{id:"x090",obj:"2.5",d:2,q:"A company restricts workstations so that only executables on an approved list can run. A user downloads a legitimate but unapproved utility and it is blocked. Which of the following mitigation techniques is in place?",
 o:["Application allow list","Network segmentation","Least privilege","Decommissioning"],
 w:"An application allow list permits only approved software to execute and blocks everything else by default.",
 n:["Segmentation controls network reachability between zones, not which programs run.","Least privilege limits user rights but would not by itself block an unlisted executable.","Decommissioning removes systems from service and is unrelated."]},
{id:"x091",obj:"2.1",d:2,q:"A disgruntled database administrator who was passed over for promotion is found to have scheduled a job that will delete production tables on the day of the next board meeting. Which of the following BEST describes the actor and the malware?",
 o:["Insider threat motivated by revenge using a logic bomb","Nation-state actor using a worm","Hacktivist using ransomware","Unskilled attacker using spyware"],
 w:"An employee with legitimate access acting out of resentment is an insider threat, and a payload that waits for a date or condition is a logic bomb.",
 n:["A nation-state is an external actor, and a worm self-propagates rather than waiting for a date.","No political message or encryption-for-payment is involved.","The administrator is highly skilled, and spyware collects data rather than destroying it."]},
{id:"x092",obj:"1.2",d:1,q:"A security team compares the organization's current controls against the requirements of an industry framework and produces a list of missing or weak controls with a remediation roadmap. Which of the following BEST describes this activity?",
 o:["Gap analysis","Penetration test","Business impact analysis","Tabletop exercise"],
 w:"A gap analysis measures the difference between the current state and a desired standard and identifies what must be done to close it.",
 n:["A penetration test attempts to exploit systems rather than compare controls to a framework.","A BIA identifies critical processes and recovery targets, not control shortfalls.","A tabletop is a discussion-based exercise of a response plan."]}
];
