/* PBQ Lab simulation items (SY0-701) — Chat 3 types: diagram (device placement), appanel (wireless AP config), hardening (endpoint panel).
   Schema per type: see core/sims/<type>.js and dev/specs/secplus.md. All addresses RFC 1918/5737; no real company names.
   Every item: id, obj, d, cat, type, title, prompt (one line, shown in the exam header), task (bullets for the sticky task pane), why (takeaway). */
export const LAB_SIMS = [

/* ====================== DIAGRAM PLACEMENT (3.2 device placement, zones, inline vs tap) ====================== */
{id:"dg-screened",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Build the screened subnet",
 prompt:"Place each security device where it belongs on the topology. Not every palette item is used.",
 task:["Put the device that separates the Internet from every internal zone at slot A.","Protect web01 against HTTP-layer attacks (SQLi, XSS) with the device that understands HTTP, at slot B.","Administrators must reach DMZ servers only by first logging in to a hardened host inside the DMZ (slot C).","Slot D receives a mirrored copy of core-switch traffic and must never be able to drop a packet."],
 nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"core",label:"Core switch",x:240,y:150,k:"sw"},{id:"dmz",label:"DMZ",x:360,y:92,k:"zone",w:224,h:134},{id:"web",label:"web01",x:420,y:72,k:"srv",w:70},{id:"lan",label:"Internal LAN",x:360,y:240,k:"zone",w:224,h:100},{id:"users",label:"Users",x:310,y:245,k:"pc",w:70},{id:"fs",label:"File server",x:416,y:245,k:"srv",w:78}],
 links:[["inet","A"],["A","core"],["core","B"],["B","web"],["core","C"],["core","users"],["core","D"]],
 slots:[{id:"A",label:"A · Edge",x:144,y:150,want:["firewall","ngfw"],why:"The boundary device is a firewall; the screened subnet is the zone it creates between its external and internal interfaces."},
        {id:"B",label:"B · Before web01",x:318,y:72,want:"waf",why:"Only a web application firewall parses HTTP and blocks injection and scripting payloads; a network firewall sees ports, not SQL."},
        {id:"C",label:"C · Admin hop",x:318,y:138,want:["jump","bastion"],why:"A jump box (bastion) in the DMZ is the single hardened entry point for administration; admins never connect straight to the servers."},
        {id:"D",label:"D · SPAN copy",x:144,y:245,want:"ids",why:"A device fed from a SPAN/mirror port is out of band: it can only detect and alert. That is an IDS; an IPS must be inline to block."}],
 palette:["firewall","waf","jump","ids","ips","proxy","lb","vpn"],
 why:"Firewall at the boundary, WAF in front of the web tier, jump box for administration, IDS on a mirror port (passive) vs IPS inline (active). The slot's position tells you active-vs-passive before you even read the label."},

{id:"dg-segments",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Name the segment by its job",
 prompt:"Each segment behind the firewall has a job. Drop the device or zone type that provides it onto the matching slot.",
 task:["Segment 1 hosts the public web server and the mail relay that outside users must reach.","Segment 2 is where remote employees' encrypted tunnels terminate before they touch the LAN.","Segment 3 is the single exit point for all employee web browsing, with URL filtering and caching.","Segment 4 spreads incoming requests across three identical web servers and checks their health."],
 nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"fw",label:"Firewall",x:150,y:150,k:"box",w:70},{id:"core",label:"Core",x:240,y:150,k:"sw",w:56},
        {id:"s1",label:"web01 · smtp-relay\npublic-facing",x:420,y:45,k:"srv",w:112},{id:"s2",label:"Remote staff\n(laptops at home)",x:420,y:115,k:"pc",w:112},{id:"s3",label:"Employee browsing\nexits here",x:420,y:185,k:"pc",w:112},{id:"s4",label:"web01 · web02 · web03\nidentical farm",x:420,y:255,k:"srv",w:112}],
 links:[["inet","fw"],["fw","core"],["core","1"],["1","s1"],["core","2"],["2","s2"],["core","3"],["3","s3"],["core","4"],["4","s4"]],
 slots:[{id:"1",label:"Segment 1",x:318,y:45,want:"dmz",why:"Public-facing servers live in a DMZ / screened subnet so a compromise there cannot reach the internal LAN directly."},
        {id:"2",label:"Segment 2",x:318,y:115,want:"vpn",why:"Remote-access tunnels end on a VPN concentrator; the firewall then controls what the decrypted traffic may reach."},
        {id:"3",label:"Segment 3",x:318,y:185,want:["proxy","webfilter"],why:"A forward proxy (or web filter) is the one place outbound browsing is inspected, filtered and cached."},
        {id:"4",label:"Segment 4",x:318,y:255,want:"lb",why:"A load balancer distributes requests across identical servers and health-checks them; a proxy or firewall does not."}],
 palette:["dmz","vpn","proxy","lb","firewall","ids","jump","waf"],
 why:"DMZ = public servers; VPN concentrator = tunnel endpoint; forward proxy = outbound browsing control; load balancer = distribute + health check. Read the job, not the position."},

{id:"dg-inline",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Inline or out of band?",
 prompt:"Place the monitoring and detection devices. The link each slot sits on tells you whether it can block.",
 task:["Slot A sits directly on the path between the firewall and the core switch and must stop known attacks in real time.","Slot B hangs off the core switch's mirror (SPAN) port and must analyze every packet without ever becoming a point of failure.","Slot C receives syslog and event feeds from the firewall, the core switch and the servers for correlation and alerting.","Slot D is a deliberately exposed decoy host on the server VLAN that should generate an alert on any connection."],
 nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"fw",label:"Firewall",x:140,y:150,k:"box",w:66},{id:"core",label:"Core switch",x:316,y:150,k:"sw"},{id:"users",label:"Users",x:430,y:100,k:"pc",w:70},{id:"srv",label:"Server VLAN",x:430,y:200,k:"srv",w:86}],
 links:[["inet","fw"],["fw","A"],["A","core"],["core","users"],["core","srv"],["core","B"],["fw","C"],["core","C"],["srv","D"]],
 slots:[{id:"A",label:"A · inline",x:228,y:150,want:"ips",why:"Inline on the traffic path = can drop packets = IPS. An IDS placed here would still only alert."},
        {id:"B",label:"B · SPAN feed",x:316,y:252,want:"ids",why:"Fed by a mirror port, the device sees a copy; it can detect and alert but cannot block. That is an IDS (passive)."},
        {id:"C",label:"C · log feeds",x:140,y:252,want:"siem",why:"A SIEM aggregates and correlates logs from every source; it is not on the traffic path at all."},
        {id:"D",label:"D · decoy",x:430,y:265,want:"honeypot",why:"A honeypot is an intentionally vulnerable host with no legitimate users, so any touch is a high-fidelity alert."}],
 palette:["ips","ids","siem","honeypot","tap","waf","proxy","lb"],
 why:"Inline (active) can block: IPS, firewall, WAF. Out of band (passive) only alerts: IDS, sensor, SIEM. A SPAN port or tap feeds the passive devices. Honeypots are deception, not detection, but they alert on any contact."},

{id:"dg-remote",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Remote access and admin paths",
 prompt:"Place the devices that control how people get in.",
 task:["Slot A terminates remote employees' encrypted tunnels behind the firewall.","Slot B is the only host administrators may connect to before reaching the server VLAN.","Slot C authenticates wired and wireless users for 802.1X before the access points let them on.","Slot D is an isolated decoy that alerts the SOC the moment anything scans or connects to it."],
 nodes:[{id:"inet",label:"Internet",x:52,y:150,k:"cloud"},{id:"fw",label:"Firewall",x:140,y:150,k:"box",w:66},{id:"core",label:"Core switch",x:262,y:150,k:"sw"},{id:"srv",label:"Server VLAN",x:430,y:150,k:"srv",w:86},{id:"adm",label:"Admin PC",x:430,y:52,k:"pc",w:76},{id:"ap",label:"Wi-Fi AP",x:262,y:262,k:"box",w:70}],
 links:[["inet","fw"],["fw","core"],["fw","A"],["A","core"],["adm","B"],["B","srv"],["core","srv"],["core","ap"],["core","C"],["ap","C"],["core","D"]],
 slots:[{id:"A",label:"A · tunnels end",x:200,y:60,want:"vpn",why:"A VPN concentrator terminates IPsec/TLS tunnels; the firewall then polices the decrypted traffic."},
        {id:"B",label:"B · admin hop",x:340,y:60,want:["jump","bastion"],why:"A jump box (bastion host) is the hardened, logged chokepoint for administration; MFA and session recording live here."},
        {id:"C",label:"C · 802.1X auth",x:400,y:262,want:"radius",why:"802.1X supplicants authenticate through the authenticator (switch/AP) to a RADIUS authentication server, usually tied to the directory."},
        {id:"D",label:"D · decoy",x:140,y:262,want:"honeypot",why:"A honeypot is deception technology: no legitimate traffic should ever reach it, so every hit is worth an alert."}],
 palette:["vpn","jump","radius","honeypot","proxy","lb","waf","ids"],
 why:"VPN concentrator for tunnels, jump box for admin access, RADIUS behind 802.1X, honeypot as a tripwire. Port security / 802.1X / EAP are the 3.2 wired-and-wireless access controls."},

{id:"dg-webtier",obj:"3.2",d:3,cat:"netsec",type:"diagram",title:"Three-tier web application",
 prompt:"Place the devices that protect and scale the public web application.",w:520,
 task:["Slot A terminates TLS, health-checks web01 and web02, and spreads client requests across them.","Slot B inspects every HTTP request for injection, scripting and other OWASP-style attacks before it reaches the web tier.","Slot C separates the database tier from the web tier and permits only TCP 1433 from the web servers.","Leave the remaining palette devices unused if the topology does not call for them."],
 nodes:[{id:"inet",label:"Internet",x:52,y:140,k:"cloud"},{id:"fw",label:"Edge FW",x:148,y:140,k:"box",w:64},{id:"wt",label:"Web tier",x:432,y:122,k:"zone",w:150,h:120},{id:"w1",label:"web01",x:432,y:100,k:"srv",w:76},{id:"w2",label:"web02",x:432,y:155,k:"srv",w:76},{id:"db",label:"db01 (SQL)",x:432,y:275,k:"srv",w:90}],
 links:[["inet","fw"],["fw","A"],["A","B"],["B","w1"],["B","w2"],["w2","C"],["C","db"]],
 slots:[{id:"A",label:"A · spread load",x:234,y:140,want:"lb",why:"A load balancer distributes across identical servers and removes unhealthy ones from rotation; TLS offload commonly happens here."},
        {id:"B",label:"B · HTTP inspection",x:326,y:140,want:"waf",why:"A WAF understands HTTP semantics (parameters, cookies, headers) and blocks SQLi/XSS; a packet-filter firewall cannot."},
        {id:"C",label:"C · DB tier boundary",x:326,y:275,want:["firewall","ngfw"],why:"An internal firewall segments tiers so a compromised web server can reach only the database port, nothing else."}],
 palette:["lb","waf","firewall","ids","proxy","jump","vpn","dmz"],
 why:"Tiered design: load balancer for availability, WAF for application-layer attacks, internal firewall for tier segmentation. Each device answers a different question: who gets the request, is the request safe, what may this tier talk to."},

/* ====================== WIRELESS AP PANEL (4.1 wireless security, 3.2 802.1X/EAP) ====================== */
{id:"ap-corp",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Configure the corporate SSID",
 prompt:"Change only what the requirement asks for. Every unnecessary change costs points.",device:"AP-HQ-01",deviceSub:"Corporate wireless profile",
 task:["SSID: CorpSecure, 5 GHz only.","Use the strongest security mode that authenticates each user individually against the corporate RADIUS server.","Clients have machine certificates from the internal CA; choose the EAP method that uses them (no passwords).","RADIUS server 10.0.5.20, port 1812, shared secret Kr9!vault-Ridge.","Protected management frames must be mandatory. Push-button setup must be off."],
 start:{ssid:"Linksys-Setup",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"password123",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1645",radiusSecret:"",pmf:"Optional",wps:true,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
 want:{ssid:"CorpSecure",band:"5 GHz",mode:"WPA3-Enterprise",eap:"EAP-TLS",radiusHost:"10.0.5.20",radiusPort:"1812",radiusSecret:"Kr9!vault-Ridge",pmf:"Required",wps:false},
 fieldWhy:{mode:"Per-user authentication against RADIUS is Enterprise mode; WPA3 is the strongest available.",eap:"EAP-TLS is the certificate-based, mutual-authentication method; PEAP and EAP-TTLS tunnel a password.",pmf:"WPA3 requires 802.11w; 'Required' also stops deauthentication/disassociation spoofing.",wps:"WPS PINs are brute-forceable in hours; it has no place on a corporate SSID."},
 why:"Enterprise = 802.1X + RADIUS; EAP-TLS = certificates both ways; WPA3 mandates PMF; WPS always off. Hidden SSID, MAC filtering and client isolation were not requested, so leave them alone."},

{id:"ap-guest",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Set up the guest network",
 prompt:"Build the visitor SSID. Touch only the fields the ticket names.",device:"AP-LOBBY-02",deviceSub:"Guest wireless profile",
 task:["SSID: Visitor-WiFi, broadcast on both bands.","Visitors must not need a passphrase, but the air must still be encrypted so nobody can sniff a neighbor.","Guests must never be able to reach each other's devices.","The AP's admin page must not be reachable from the guest wireless side."],
 start:{ssid:"Guest",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"guest1234",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1812",radiusSecret:"",pmf:"Optional",wps:false,macFilter:"Off",isolation:false,mgmtWifi:true,adminDefault:"Changed to a unique strong password"},
 want:{ssid:"Visitor-WiFi",mode:"OWE (Enhanced Open)",isolation:true,mgmtWifi:false},
 fieldWhy:{mode:"OWE (Wi-Fi Enhanced Open) encrypts each client's session with no passphrase at all; plain Open sends everything in the clear.",isolation:"Client isolation blocks client-to-client forwarding on the AP, so a visitor cannot scan or attack other visitors.",mgmtWifi:"Management interfaces belong on a wired admin VLAN; never expose them to untrusted clients."},
 why:"Open-but-encrypted is OWE. Guest networks get client isolation and no path to management. Hidden SSID and MAC filtering were not asked for, and would not help a guest network anyway."},

{id:"ap-clinic",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"One SSID for old scanners and new laptops",
 prompt:"Meet the ticket for a mixed fleet without locking out the legacy devices.",device:"AP-CLINIC-01",deviceSub:"Staff wireless profile",
 task:["Six handheld scanners support only WPA2 with a passphrase; the new laptops support WPA3. Everyone must share one SSID named ClinicOps.","Pick the strongest security mode that every listed device can still join.","Set the passphrase from the ticket: Sun-Harbor-Maple-77.","Management-frame protection must stay compatible with the scanners (they do not support 802.11w).","Disable the push-button setup feature."],
 start:{ssid:"ClinicOps",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"clinic2019",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1812",radiusSecret:"",pmf:"Disabled",wps:true,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
 want:{mode:"WPA2/WPA3 mixed",psk:"Sun-Harbor-Maple-77",pmf:"Optional",wps:false},
 fieldWhy:{mode:"WPA3 transition (mixed) mode lets WPA3-capable laptops use SAE while WPA2-only scanners still join with the PSK on the same SSID.",pmf:"Transition mode requires PMF to be 'Optional': WPA3 clients negotiate it, legacy WPA2 clients that cannot are still admitted. 'Required' would drop the scanners; 'Disabled' breaks WPA3.",wps:"WPS is a brute-force target regardless of the mode in use."},
 why:"Mixed/transition mode is the bridge between WPA2 and WPA3 fleets, and it needs PMF set to Optional. Replacing a weak passphrase with a long passphrase and killing WPS are the two cheapest wins."},

{id:"ap-byod",obj:"4.6",d:4,cat:"iam",type:"appanel",title:"BYOD SSID with domain credentials",
 prompt:"Staff phones must log in with their Active Directory username and password.",device:"AP-FLOOR3-04",deviceSub:"BYOD wireless profile",
 task:["SSID: Staff-BYOD, visible so onboarding instructions work.","Users authenticate with their domain username and password; personal devices have no certificates installed.","The identity team runs Microsoft NPS (RADIUS) at radius.corp.example, port 1812, secret Byod#Fern-9182.","Use the strongest Enterprise mode the NPS server supports: standard WPA3-Enterprise."],
 start:{ssid:"Staff-BYOD",hidden:true,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"Welcome2024",eap:"EAP-TLS",radiusHost:"",radiusPort:"1645",radiusSecret:"",pmf:"Required",wps:false,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
 want:{hidden:false,mode:"WPA3-Enterprise",eap:"PEAP (MSCHAPv2)",radiusHost:"radius.corp.example",radiusPort:"1812",radiusSecret:"Byod#Fern-9182"},
 fieldWhy:{eap:"PEAP wraps MSCHAPv2 (a password exchange) in a TLS tunnel that only needs a server certificate; EAP-TLS would require a certificate on every phone.",radiusPort:"RADIUS authentication listens on UDP 1812 (1813 accounting); 1645/1646 are the legacy ports.",hidden:"Hiding the SSID adds no security and makes onboarding harder."},
 why:"No client certificates → PEAP-MSCHAPv2 (or EAP-TTLS). Certificates on clients → EAP-TLS. RADIUS auth is UDP 1812. Enterprise mode means each user has their own credential, so one leaked password does not expose the whole network."},

{id:"ap-printers",obj:"4.1",d:4,cat:"harden",type:"appanel",title:"Lock down the printer SSID",
 prompt:"Apply the change request exactly as written, even the parts you would argue with.",device:"AP-BRANCH-07",deviceSub:"PrintNet profile",
 task:["The 12 label printers support only WPA2-PSK on 2.4 GHz; keep that mode and restrict the radio to that band.","Replace the passphrase with the one in the ticket: Granite-Lantern-Orbit-2026.","Per the manager's request: stop broadcasting the SSID and allow only the printers' registered MAC addresses to associate.","Do not change anything else on this profile."],
 start:{ssid:"PrintNet",hidden:false,band:"2.4 + 5 GHz",mode:"WPA2-Personal",psk:"print",eap:"PEAP (MSCHAPv2)",radiusHost:"",radiusPort:"1812",radiusSecret:"",pmf:"Optional",wps:false,macFilter:"Off",isolation:false,mgmtWifi:false,adminDefault:"Changed to a unique strong password"},
 want:{band:"2.4 GHz",psk:"Granite-Lantern-Orbit-2026",hidden:true,macFilter:"Allow list only"},
 fieldWhy:{hidden:"Hiding an SSID only removes it from beacons; probe requests still reveal it. It is obscurity, not security, but the ticket asked for it.",macFilter:"MAC addresses are trivially spoofed after a few seconds of sniffing. An allow list raises the bar slightly and adds management overhead."},
 why:"Follow the spec on a PBQ even when a control is weak. For the MC side of the exam remember: hidden SSIDs and MAC filtering are obscurity controls; the real strength is the passphrase length and WPA2/WPA3 with PMF."},

/* ====================== ENDPOINT HARDENING (2.5 hardening, 4.1 baselines, 4.5 OS security) ====================== */
{id:"hd-web",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"Harden a public web server",
 prompt:"Reduce the attack surface without taking the site down.",host:{name:"web01",os:"Ubuntu Server 22.04",role:"Public HTTPS site; the app reads a local MySQL database; admins SSH in over the VPN"},
 task:["The site must keep serving HTTPS, and HTTP must keep redirecting to it.","Remove every service and open port that the stated role does not need.","MySQL is used only by the local application; it must never be reachable from the network.","Admins connect over SSH from the VPN only; root must not be able to log in over SSH.","Patches must install automatically; the host firewall must be on with a default-deny inbound policy."],
 groups:[{id:"svc",label:"Services"},{id:"fw",label:"Host firewall"},{id:"ports",label:"Listening ports (reachable from the network)"},{id:"acct",label:"Accounts & remote access"},{id:"upd",label:"Updates"}],
 controls:[
  {id:"nginx",g:"svc",l:"nginx (web server)",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"The business function is the website."},
  {id:"mysql",g:"svc",l:"mysqld (database)",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"The application reads the local database; stopping it breaks the site. Restrict it instead."},
  {id:"telnet",g:"svc",l:"telnetd",t:"toggle",on:"Running",off:"Stopped",start:true,want:false,why:"Cleartext remote login; SSH replaces it entirely."},
  {id:"vsftpd",g:"svc",l:"vsftpd (FTP)",t:"toggle",on:"Running",off:"Stopped",start:true,want:false,why:"Cleartext file transfer with no stated use; SFTP over SSH covers any real need."},
  {id:"cups",g:"svc",l:"cups (printing)",t:"toggle",on:"Running",off:"Stopped",start:true,want:false,why:"A web server does not print. Unused services are unpatched attack surface."},
  {id:"sshd",g:"svc",l:"sshd",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"Admins need SSH; the task is to restrict it, not remove it."},
  {id:"fwon",g:"fw",l:"Host firewall (ufw)",t:"toggle",on:"Enabled",off:"Disabled",start:false,want:true},
  {id:"fwpol",g:"fw",l:"Default inbound policy",t:"select",o:["Allow all","Deny all except allowed rules"],start:"Allow all",want:"Deny all except allowed rules",why:"Implicit deny: open only what is listed."},
  {id:"p80",g:"ports",l:"TCP 80 (HTTP)",d:"Redirects to HTTPS",t:"toggle",on:"Open",off:"Closed",start:true,crit:true,why:"The task says HTTP must keep redirecting."},
  {id:"p443",g:"ports",l:"TCP 443 (HTTPS)",t:"toggle",on:"Open",off:"Closed",start:true,crit:true},
  {id:"p22",g:"ports",l:"TCP 22 (SSH) — source",t:"select",o:["Any","VPN subnet 10.0.9.0/24 only","Closed"],start:"Any",want:"VPN subnet 10.0.9.0/24 only",why:"Admins arrive via the VPN; nobody else needs SSH. Closing it entirely locks the admins out."},
  {id:"p3306",g:"ports",l:"TCP 3306 (MySQL)",t:"toggle",on:"Open",off:"Closed",start:true,want:false,why:"The database is local-only; bind it to localhost and close the port."},
  {id:"p21",g:"ports",l:"TCP 21 (FTP)",t:"toggle",on:"Open",off:"Closed",start:true,want:false},
  {id:"p23",g:"ports",l:"TCP 23 (Telnet)",t:"toggle",on:"Open",off:"Closed",start:true,want:false},
  {id:"rootssh",g:"acct",l:"PermitRootLogin (SSH)",t:"toggle",on:"Yes",off:"No",start:true,want:false,why:"Admins log in as themselves and escalate with sudo; that keeps an audit trail and removes the one username every attacker already knows."},
  {id:"guest",g:"acct",l:"Account: guest (default, no password)",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false},
  {id:"webadm",g:"acct",l:"Account: webadmin (sudo)",t:"toggle",on:"Enabled",off:"Disabled",start:true,crit:true,why:"That is how the admins get in."},
  {id:"vnc",g:"acct",l:"VNC remote desktop",t:"toggle",start:true,want:false,why:"Unneeded remote-access path; SSH is the sanctioned one."},
  {id:"autoupd",g:"upd",l:"Unattended security updates",t:"toggle",start:false,want:true},
  {id:"fde",g:"upd",l:"Full-disk encryption (LUKS)",t:"toggle",start:false,why:"Not in the requirement for this change; encrypting a running server's disk is a separate project."}
 ],
 why:"Hardening = remove what the role does not need (services, ports, accounts), restrict what it does need (SSH from the VPN, DB local-only), and turn on the baseline controls (host firewall default-deny, automatic patching). Breaking the business function is a failed change, not a hardened host."},

{id:"hd-finance",obj:"4.1",d:4,cat:"harden",type:"hardening",title:"Apply the workstation baseline",
 prompt:"Bring the accounting PC to the corporate baseline without stopping the user from working.",host:{name:"FIN-WS-17",os:"Windows 11 Pro",role:"Accounting workstation: prints invoices, opens shares on FIN-FS01, runs the ERP client"},
 task:["Protect data at rest if the PC is stolen, turn on the host firewall, and keep it patched automatically.","The user must not be a local administrator.","Nobody remotes in to this PC; close every inbound remote-access path.","Remove the built-in accounts the baseline says must be disabled, and the obsolete file-sharing protocol.","Policy: no USB mass storage, screen locks after 10 minutes. Do not touch anything the user needs to print or reach the file server."],
 groups:[{id:"enc",label:"Encryption & updates"},{id:"acct",label:"Accounts"},{id:"remote",label:"Remote access"},{id:"svc",label:"Services & protocols"},{id:"policy",label:"Device policy"}],
 controls:[
  {id:"bitlocker",g:"enc",l:"BitLocker full-disk encryption",t:"toggle",start:false,want:true,why:"Data at rest on a stolen laptop or PC is only protected by encryption."},
  {id:"wu",g:"enc",l:"Windows Update",t:"select",o:["Automatic","Notify only","Disabled"],start:"Notify only",want:"Automatic"},
  {id:"fw",g:"enc",l:"Windows Defender Firewall",t:"toggle",start:false,want:true},
  {id:"useradmin",g:"acct",l:"Account type: j.alvarez",t:"select",o:["Administrator","Standard user"],start:"Administrator",want:"Standard user",why:"Least privilege: malware runs with the user's rights."},
  {id:"builtinadmin",g:"acct",l:"Built-in Administrator account",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false,why:"A well-known RID-500 account with no lockout; the baseline disables it."},
  {id:"guest",g:"acct",l:"Guest account",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false},
  {id:"rdp",g:"remote",l:"Remote Desktop (inbound)",t:"toggle",start:true,want:false},
  {id:"ra",g:"remote",l:"Remote Assistance",t:"toggle",start:true,want:false},
  {id:"winrm",g:"remote",l:"WinRM (PowerShell remoting, inbound)",t:"toggle",start:true,want:false},
  {id:"spooler",g:"svc",l:"Print Spooler",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true,why:"The user prints invoices; stopping the spooler breaks that."},
  {id:"smb1",g:"svc",l:"SMBv1 client/server",t:"toggle",on:"Installed",off:"Removed",start:true,want:false,why:"SMBv1 is the protocol WannaCry/EternalBlue abused; modern shares use SMBv3."},
  {id:"smbclient",g:"svc",l:"File sharing client (SMBv3) to FIN-FS01",t:"toggle",start:true,crit:true,why:"The user opens shares on the file server."},
  {id:"erp",g:"svc",l:"ERP client service",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
  {id:"usb",g:"policy",l:"USB mass storage",t:"toggle",on:"Allowed",off:"Blocked",start:true,want:false},
  {id:"lock",g:"policy",l:"Screen lock timeout",t:"select",o:["Never","10 minutes","60 minutes"],start:"Never",want:"10 minutes"},
  {id:"bt",g:"policy",l:"Bluetooth",t:"toggle",start:true,why:"Not mentioned in the baseline; the user may have a wireless headset or mouse."}
 ],
 why:"A secure baseline is a checklist of settings applied the same way everywhere: encryption, patching, firewall, least privilege, disabled default accounts, no unnecessary remote access, removable-media control. The user still has to print and reach the file server when you are done."},

{id:"hd-camera",obj:"3.1",d:3,cat:"arch",type:"hardening",title:"Secure an IP camera",
 prompt:"Embedded devices ship insecure. Fix this one without blinding the security office.",host:{name:"CAM-LOBBY-3",os:"Vendor firmware 5.2 (embedded Linux)",role:"Streams RTSP video to the on-site NVR; staff view it only through the NVR"},
 task:["The NVR must keep receiving the video stream.","Nothing on this camera may still use the vendor's default credentials.","Remove every plaintext or discovery protocol the role does not need.","The camera must not phone home to the vendor's cloud relay.","Firmware must update automatically, the admin interface must be encrypted-only, and the camera belongs on the isolated IoT VLAN."],
 groups:[{id:"acct",label:"Accounts"},{id:"svc",label:"Services"},{id:"net",label:"Network"},{id:"upd",label:"Updates"}],
 controls:[
  {id:"admin",g:"acct",l:"admin password",t:"select",o:["Vendor default (admin / 12345)","Unique strong password"],start:"Vendor default (admin / 12345)",want:"Unique strong password",why:"Default credentials are a listed threat vector (2.2) and the first thing IoT botnets try."},
  {id:"svcacct",g:"acct",l:"Hidden vendor support account",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false,why:"Undocumented backdoor accounts are a supply-chain and default-credential risk."},
  {id:"rtsp",g:"svc",l:"RTSP stream (TCP 554)",t:"toggle",start:true,crit:true,why:"That is how the NVR gets video."},
  {id:"telnet",g:"svc",l:"Telnet (TCP 23)",t:"toggle",start:true,want:false},
  {id:"upnp",g:"svc",l:"UPnP (auto port-forwarding on the router)",t:"toggle",start:true,want:false,why:"UPnP lets the device punch holes in the perimeter by itself."},
  {id:"onvif",g:"svc",l:"ONVIF discovery",t:"toggle",start:true,want:false,why:"Discovery broadcasts advertise the device; the NVR is already configured with its address."},
  {id:"http",g:"svc",l:"HTTP admin page (TCP 80)",t:"toggle",start:true,want:false},
  {id:"https",g:"svc",l:"HTTPS admin page (TCP 443)",t:"toggle",start:true,crit:true,why:"Keep the encrypted management path; the task says encrypted-only, not none."},
  {id:"cloud",g:"net",l:"Vendor cloud P2P relay",t:"toggle",start:true,want:false,why:"Outbound relays bypass the firewall and expose the feed to the vendor's cloud."},
  {id:"vlan",g:"net",l:"VLAN assignment",t:"select",o:["VLAN 1 (default / user LAN)","VLAN 40 (IoT, isolated)"],start:"VLAN 1 (default / user LAN)",want:"VLAN 40 (IoT, isolated)",why:"Segmentation limits what a compromised camera can reach."},
  {id:"fwupd",g:"upd",l:"Automatic firmware updates",t:"toggle",start:false,want:true},
  {id:"ntp",g:"upd",l:"NTP time sync",t:"toggle",start:true,why:"Accurate timestamps on video are valuable; nothing asked you to change it."}
 ],
 why:"IoT/embedded hardening: change defaults, kill Telnet/UPnP/discovery/cloud relays, keep only the protocol the role needs (RTSP to the NVR), encrypt management, segment onto an IoT VLAN, patch automatically. Devices that cannot be hardened get isolated instead."},

{id:"hd-sql",obj:"4.5",d:4,cat:"harden",type:"hardening",title:"Lock down the database server",
 prompt:"Tighten the SQL host for the PCI audit without breaking the web application that depends on it.",host:{name:"SQL-PRD-02",os:"Windows Server 2022",role:"Runs the orders database for the web tier (10.0.20.0/24); DBAs manage it from the admin VLAN (10.0.5.0/24)"},
 task:["The web tier must keep reaching the database; nothing else may.","DBAs administer the host only from the admin VLAN, over an encrypted session.","Remove the components, protocols and accounts the audit flagged: SQL Browser, IIS, the sa login, SQL (mixed-mode) authentication, unencrypted client connections.","Encrypt the volumes. Patch during the monthly maintenance window, never with automatic reboots.","Leave the SQL Server engine and its service account alone."],
 groups:[{id:"svc",label:"Services & components"},{id:"net",label:"Network access"},{id:"auth",label:"Authentication"},{id:"data",label:"Data protection & patching"}],
 controls:[
  {id:"engine",g:"svc",l:"SQL Server engine",t:"toggle",on:"Running",off:"Stopped",start:true,crit:true},
  {id:"browser",g:"svc",l:"SQL Server Browser (UDP 1434)",t:"toggle",on:"Running",off:"Stopped",start:true,want:false,why:"Browser advertises instances; with a fixed port the web tier does not need it."},
  {id:"iis",g:"svc",l:"IIS web server role",t:"toggle",on:"Installed",off:"Removed",start:true,want:false,why:"A web server on the database host is unnecessary attack surface."},
  {id:"agent",g:"svc",l:"SQL Server Agent (backup jobs)",t:"toggle",on:"Running",off:"Stopped",start:true,why:"Not mentioned; it runs the backups."},
  {id:"p1433",g:"net",l:"TCP 1433 allowed from",t:"select",o:["Any","Web tier 10.0.20.0/24 only","Closed"],start:"Any",want:"Web tier 10.0.20.0/24 only"},
  {id:"rdp",g:"net",l:"Remote Desktop allowed from",t:"select",o:["Any","Admin VLAN 10.0.5.0/24 only","Off"],start:"Any",want:"Admin VLAN 10.0.5.0/24 only",why:"DBAs still need to administer it; 'Off' breaks that, 'Any' leaves RDP exposed."},
  {id:"nla",g:"net",l:"RDP Network Level Authentication + TLS",t:"toggle",on:"Required",off:"Not required",start:false,want:true},
  {id:"fw",g:"net",l:"Windows Defender Firewall",t:"toggle",start:true,crit:true,why:"The firewall is what enforces the source restrictions above."},
  {id:"sa",g:"auth",l:"sa login",t:"toggle",on:"Enabled",off:"Disabled",start:true,want:false,why:"A well-known superuser login is a brute-force magnet."},
  {id:"authmode",g:"auth",l:"Authentication mode",t:"select",o:["Mixed mode (SQL + Windows)","Windows authentication only"],start:"Mixed mode (SQL + Windows)",want:"Windows authentication only",why:"Windows auth uses Kerberos and central lockout/MFA policy; SQL logins are passwords stored in the database."},
  {id:"svcacct",g:"auth",l:"Engine service account",t:"select",o:["Managed service account (gMSA)","LocalSystem"],start:"Managed service account (gMSA)",why:"Already correct; the task said to leave it alone."},
  {id:"tls",g:"data",l:"Force encryption on client connections (TLS)",t:"toggle",start:false,want:true},
  {id:"bitlocker",g:"data",l:"BitLocker on data and log volumes",t:"toggle",start:false,want:true},
  {id:"patch",g:"data",l:"Patching",t:"select",o:["Automatic, reboot when required","Monthly maintenance window (WSUS), manual reboot","Disabled"],start:"Automatic, reboot when required",want:"Monthly maintenance window (WSUS), manual reboot",why:"Servers get patched on a schedule with a backout plan; surprise reboots are an availability incident."}
 ],
 why:"Server hardening is about scope: allow the one consumer (web tier) on the one port, allow admins from the one VLAN over an encrypted session, remove extra roles, disable well-known logins, encrypt in transit and at rest, and patch in a controlled window."},

{id:"hd-legacy",obj:"2.5",d:2,cat:"vulns",type:"hardening",title:"Compensating controls for an unpatchable HMI",
 prompt:"This box cannot be upgraded. Reduce the risk around it instead.",host:{name:"HMI-LINE2",os:"Windows 7 (vendor-locked, no patches available)",role:"Operator screen for the bottling line PLC; vendor supports it over VNC through the engineering jump host; the HMI software needs SMBv1 to the historian"},
 task:["The HMI must keep talking to the PLC and the historian, and the vendor must keep its VNC support path through the jump host.","Updates cannot be enabled, so isolate the host: put it on the OT VLAN and allow inbound connections only from the engineering jump host.","Turn on the host firewall and the application allow list, and remove the vendor's default account password.","Disable protocols and media paths the role does not need."],
 groups:[{id:"net",label:"Network"},{id:"ctrl",label:"Host controls"},{id:"acct",label:"Accounts"},{id:"svc",label:"Services & media"}],
 controls:[
  {id:"vlan",g:"net",l:"VLAN assignment",t:"select",o:["VLAN 10 (office LAN)","VLAN 200 (OT, isolated)"],start:"VLAN 10 (office LAN)",want:"VLAN 200 (OT, isolated)",why:"Segmentation is the primary compensating control for a host you cannot patch."},
  {id:"inbound",g:"net",l:"Inbound connections allowed from",t:"select",o:["Any","Engineering jump host 10.0.5.10 only","None"],start:"Any",want:"Engineering jump host 10.0.5.10 only",why:"'None' cuts off the vendor's sanctioned support path."},
  {id:"plc",g:"net",l:"Modbus/TCP to PLC (TCP 502)",t:"toggle",start:true,crit:true,why:"That is the production link."},
  {id:"hostfw",g:"ctrl",l:"Host firewall",t:"toggle",start:false,want:true},
  {id:"allowlist",g:"ctrl",l:"Application allow list",t:"toggle",start:false,want:true,why:"Only the HMI software may execute; ransomware and droppers cannot."},
  {id:"updates",g:"ctrl",l:"Windows Update",t:"select",o:["Disabled (no updates exist for this OS)","Automatic"],start:"Disabled (no updates exist for this OS)",why:"There is nothing to install; the risk is handled by isolation and allow-listing. Selecting Automatic changes nothing and signals you missed the point."},
  {id:"vendor",g:"acct",l:"Vendor account hmi_svc",t:"select",o:["Default password (hmi123)","Unique strong password, documented in the vault"],start:"Default password (hmi123)",want:"Unique strong password, documented in the vault"},
  {id:"operator",g:"acct",l:"Operator account (kiosk)",t:"toggle",on:"Enabled",off:"Disabled",start:true,crit:true,why:"Operators run the line with it."},
  {id:"smb1",g:"svc",l:"SMBv1 to historian",t:"toggle",start:true,crit:true,why:"The HMI software needs it; this is exactly why the host is isolated instead."},
  {id:"vnc",g:"svc",l:"VNC (vendor support)",t:"toggle",start:true,crit:true,why:"Sanctioned support path, now reachable only from the jump host."},
  {id:"telnet",g:"svc",l:"Telnet service",t:"toggle",start:true,want:false},
  {id:"autorun",g:"svc",l:"USB AutoRun / AutoPlay",t:"toggle",start:true,want:false,why:"Removable media is a classic path into air-gapped OT networks."},
  {id:"ie",g:"svc",l:"Internet access via web proxy",t:"toggle",start:true,want:false,why:"An HMI never needs to browse; it only needs the PLC and the historian."}
 ],
 why:"When you cannot patch, compensate: isolate (VLAN + allow only the jump host), restrict execution (allow list), harden what remains (firewall, no defaults, no Telnet/AutoRun/Internet). Keep the production and support paths intact; a plant that stops is also a security failure."}
];
