/* Cert Gauntlet — SC-200 KQL Lab drills (60). Sim type "kql" (core/sims/kql/drill.js) runs them against the lab's sample tables.
   Modes: write (prompt → your query, graded by result-set equality so any correct query passes) · fix (exactly one bug) ·
   predict (pick the real output; distractors come from running `alts`). Every drill carries its skills-measured bullet. */
const W = (id, title, obj, prompt, tables, ref, extra = {}) => ({ id, type: "kql", mode: "write", d: 3, cat: "kql", obj, title, prompt, tables, ref, ...extra });
const F = (id, title, obj, prompt, tables, buggy, ref, extra = {}) => ({ id, type: "kql", mode: "fix", d: 3, cat: "kql", obj, title, prompt, tables, buggy, ref, ...extra });
const P = (id, title, obj, prompt, tables, ref, alts, extra = {}) => ({ id, type: "kql", mode: "predict", d: 3, cat: "kql", obj, title, prompt, tables, ref, alts, ...extra });

export const SC200_KQL_DRILLS = [
  /* ---------------- write it (26) ---------------- */
  W("k001", "Failed sign-ins, last 7 days", "3.1.2", "List every failed Entra ID sign-in from the last 7 days. Return only TimeGenerated, UserPrincipalName, IPAddress and ResultType. (Remember what type ResultType is.)", ["SigninLogs"],
    `SigninLogs | where TimeGenerated > ago(7d) | where ResultType != "0" | project TimeGenerated, UserPrincipalName, IPAddress, ResultType`,
    { hint: "ResultType is a string column: compare it with \"0\", not 0.", why: "SigninLogs.ResultType is a string, so the filter must quote the value. ago(7d) is the standard lookback for a hunting query; project narrows the output to what the analyst needs." }),
  W("k002", "Password spray — which IP?", "3.1.2", "Find the source IP that failed with error 50126 (bad password) against the most distinct accounts. Return the IP, the number of distinct users it tried and the total attempts, for IPs that hit more than 5 users.", ["SigninLogs"],
    `SigninLogs | where ResultType == "50126" | summarize Users = dcount(UserPrincipalName), Attempts = count() by IPAddress | where Users > 5`,
    { hint: "dcount() counts distinct values; count() counts rows. Filter the aggregate after summarize.", why: "A spray is one IP, many accounts: dcount(UserPrincipalName) by IPAddress is the signature. The threshold comes after summarize because it's about the aggregate, not individual rows." }),
  W("k003", "Did the spray succeed?", "3.1.2", "The spray came from 203.0.113.57. Which accounts did that IP sign in to successfully? Return TimeGenerated, UserPrincipalName and AppDisplayName.", ["SigninLogs"],
    `SigninLogs | where IPAddress == "203.0.113.57" and ResultType == "0" | project TimeGenerated, UserPrincipalName, AppDisplayName`,
    { why: "After a spray, the single success from the attacker's IP is the compromised account. Both filters belong in the same where (or two where operators)." }),
  W("k004", "Sign-ins per hour", "3.1.3", "Count sign-ins per hour over the last 24 hours. Return the hour bucket and the count, nothing else.", ["SigninLogs"],
    `SigninLogs | where TimeGenerated > ago(24h) | summarize count() by bin(TimeGenerated, 1h)`,
    { why: "bin(TimeGenerated, 1h) rounds every timestamp down to its hour so summarize can group by it — this is the shape every timechart and most scheduled-rule thresholds use." }),
  W("k005", "Impossible travel", "3.1.2", "Which users signed in SUCCESSFULLY from more than one country in the last 7 days? Return the user, a set of the countries, and how many distinct countries. Country is LocationDetails.countryOrRegion.", ["SigninLogs"],
    `SigninLogs | where TimeGenerated > ago(7d) and ResultType == "0" | extend Country = tostring(LocationDetails.countryOrRegion) | summarize Countries = make_set(Country), N = dcount(Country) by UserPrincipalName | where N > 1`,
    { hint: "LocationDetails is dynamic: reach inside it with a dot, then tostring(). Failed attempts from the spray would make everyone look like a traveller — keep successes only.", why: "Dynamic columns are navigated with dot notation; tostring() turns the property into a plain string so make_set/dcount behave. Filtering to ResultType \"0\" matters: the password spray failed against 25 users from Germany, so without it every sprayed user looks like impossible travel. Two users remain — mchen (US/NG) and the compromised rlopez (US/DE)." }),
  W("k006", "Network logon failures by source", "3.1.2", "From Windows Security events, count failed logons (4625) that were network logons (LogonType 3), grouped by IpAddress and Computer. Keep only sources with more than 10 failures.", ["SecurityEvent"],
    `SecurityEvent | where EventID == 4625 and LogonType == 3 | summarize Failures = count() by IpAddress, Computer | where Failures > 10`,
    { why: "EventID and LogonType are numeric in SecurityEvent (unlike SigninLogs.ResultType), so no quotes. LogonType 3 = network; a burst from one IpAddress is a brute force." }),
  W("k007", "Account created then elevated", "3.1.2", "On the domain controllers, list user-account creations (4720) and additions to security-enabled local groups (4732). Return TimeGenerated, Computer, EventID, SubjectUserName and TargetUserName.", ["SecurityEvent"],
    `SecurityEvent | where EventID in (4720, 4732) | project TimeGenerated, Computer, EventID, SubjectUserName, TargetUserName`,
    { why: "in (4720, 4732) is the clean way to match several event IDs. 4720 followed minutes later by 4732 into Administrators is the persistence pattern after a compromise." }),
  W("k008", "Audit log cleared", "3.1.2", "Find every time the Security event log was cleared (event 1102). Return Computer, SubjectUserName and TimeGenerated.", ["SecurityEvent"],
    `SecurityEvent | where EventID == 1102 | project Computer, SubjectUserName, TimeGenerated`,
    { why: "1102 is one of the few events worth alerting on with no threshold at all — a cleared Security log is defense evasion, and the SubjectUserName tells you who." }),
  W("k009", "Office spawning PowerShell", "3.1.3", "In Defender for Endpoint process events, find PowerShell launched by an Office application (WINWORD.EXE, EXCEL.EXE or OUTLOOK.EXE). Return Timestamp, DeviceName, InitiatingProcessFileName and ProcessCommandLine. File name comparisons must ignore case.", ["DeviceProcessEvents"],
    `DeviceProcessEvents | where FileName =~ "powershell.exe" and InitiatingProcessFileName in~ ("WINWORD.EXE", "EXCEL.EXE", "OUTLOOK.EXE") | project Timestamp, DeviceName, InitiatingProcessFileName, ProcessCommandLine`,
    { hint: "=~ and in~ are the case-insensitive forms.", why: "Process names in DeviceProcessEvents keep whatever case the OS reported, so =~ / in~ (case-insensitive) avoid missing WINWORD.EXE vs winword.exe. Office → PowerShell is the classic macro-malware chain." }),
  W("k010", "Encoded PowerShell", "3.1.3", "Find PowerShell processes whose command line uses an encoded command (-enc or -EncodedCommand). Return DeviceName, AccountName and ProcessCommandLine.", ["DeviceProcessEvents"],
    `DeviceProcessEvents | where FileName =~ "powershell.exe" and ProcessCommandLine has_any ("-enc", "-EncodedCommand") | project DeviceName, AccountName, ProcessCommandLine`,
    { why: "has_any matches whole terms against a list, which is both faster and more accurate than several contains clauses. Note the two benign encoded runs from svc-automation: encoding is a signal, not a verdict." }),
  W("k011", "LOLBin download", "3.1.3", "Find certutil being used to download a file (command line contains urlcache). Return Timestamp, DeviceName, ProcessCommandLine and InitiatingProcessFileName.", ["DeviceProcessEvents"],
    `DeviceProcessEvents | where FileName =~ "certutil.exe" and ProcessCommandLine has "urlcache" | project Timestamp, DeviceName, ProcessCommandLine, InitiatingProcessFileName`,
    { why: "certutil -urlcache -split -f is a living-off-the-land download. has works here because 'urlcache' is a whole term in the command line." }),
  W("k012", "Beaconing", "3.1.2", "From Defender network events, find outbound connections to public IPs where one device/process pair connected to the same RemoteIP more than 20 times. Return DeviceName, InitiatingProcessFileName, RemoteIP and the count.", ["DeviceNetworkEvents"],
    `DeviceNetworkEvents | where RemoteIPType == "Public" | summarize Connections = count() by DeviceName, InitiatingProcessFileName, RemoteIP | where Connections > 20`,
    { why: "Repeated connections from one process to one external IP is the C2 beacon shape. Grouping by the process as well as the device is what separates rundll32 talking to 198.51.100.77 from Edge talking to SharePoint." }),
  W("k013", "Beacon interval", "3.1.3", "For the device whose process rundll32.exe talks to 198.51.100.77, list the first and last connection time and the number of connections, grouped by DeviceName.", ["DeviceNetworkEvents"],
    `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" and InitiatingProcessFileName =~ "rundll32.exe" | summarize First = min(Timestamp), Last = max(Timestamp), N = count() by DeviceName`,
    { why: "min()/max() on the timestamp bracket the activity window; dividing the span by the count gives the beacon interval. The analyst needs the window to scope the timeline investigation." }),
  W("k014", "Who is talking to the C2?", "3.1.1", "Using the firewall logs (CEF), find every internal source IP that connected to 198.51.100.77 and how many times. Return SourceIP and the count.", ["CommonSecurityLog"],
    `CommonSecurityLog | where DestinationIP == "198.51.100.77" | summarize count() by SourceIP`,
    { why: "CommonSecurityLog is where CEF firewall/proxy data lands — not SecurityEvent, not DeviceNetworkEvents. Pick the table before you write the where." }),
  W("k015", "Port scan", "3.1.2", "In the firewall log, find source IPs that were denied to more than 20 distinct destination ports. Return SourceIP and the distinct-port count.", ["CommonSecurityLog"],
    `CommonSecurityLog | where DeviceAction == "deny" | summarize Ports = dcount(DestinationPort) by SourceIP | where Ports > 20`,
    { why: "A scanner touches many ports from one source; dcount(DestinationPort) by SourceIP is the shape. DeviceAction values are lower-case in CEF from this vendor — check the data before you assume." }),
  W("k016", "External forwarding rule", "2.3.1", "From the unified audit log, find New-InboxRule operations and show who created them, from which client IP, and the raw Parameters JSON. Return TimeGenerated, UserId, ClientIP and Parameters.", ["OfficeActivity"],
    `OfficeActivity | where Operation == "New-InboxRule" | project TimeGenerated, UserId, ClientIP, Parameters`,
    { why: "OfficeActivity is the Purview audit log in Sentinel. Inbox rules forwarding mail externally are the most common post-compromise persistence in Exchange Online; the Parameters column (JSON text) holds the ForwardTo." }),
  W("k017", "Parse the forwarding address", "2.3.1", "For each New-InboxRule, extract the ForwardTo value from Parameters. Return UserId and the forwarding address as a string column (name it however you like). Parameters is a JSON array of {Name, Value} objects.", ["OfficeActivity"],
    `OfficeActivity | where Operation == "New-InboxRule" | mv-expand P = parse_json(Parameters) | where P.Name == "ForwardTo" | project UserId, ForwardTo = tostring(P.Value)`,
    { hint: "parse_json() then mv-expand turns the array into one row per parameter.", why: "Parameters is JSON text, so parse_json() first; mv-expand makes one row per {Name, Value}; then a where on P.Name picks the one you need. This pattern is reused for every audit record with a parameter bag." }),
  W("k018", "Mass download", "2.3.1", "Find users who downloaded more than 20 files from SharePoint within any 10-minute window. Return UserId, the 10-minute bucket and the count.", ["OfficeActivity"],
    `OfficeActivity | where Operation == "FileDownloaded" | summarize Downloads = count() by UserId, bin(TimeGenerated, 10m) | where Downloads > 20`,
    { why: "Volume in a short window is the exfiltration signature. bin() on 10m gives the window; the threshold applies to the aggregate." }),
  W("k019", "Phish that reached inboxes", "3.1.1", "Which recipients received an email flagged as Phish that was delivered to the Inbox (DeliveryLocation 'Inbox/folder')? Return RecipientEmailAddress, Subject and SenderFromAddress.", ["EmailEvents"],
    `EmailEvents | where ThreatTypes has "Phish" and DeliveryLocation == "Inbox/folder" | project RecipientEmailAddress, Subject, SenderFromAddress`,
    { why: "EmailEvents is Defender for Office 365's mail-flow table. ThreatTypes can hold several comma-separated values, so has (whole term) is the right operator. Delivered + Phish = the users to follow up with." }),
  W("k020", "Phish campaign roll-up", "3.1.3", "Summarize the phishing campaign from northwind-pay.example: for each DeliveryAction, how many messages and how many distinct recipients.", ["EmailEvents"],
    `EmailEvents | where SenderFromDomain == "northwind-pay.example" | summarize Messages = count(), Recipients = dcount(RecipientEmailAddress) by DeliveryAction`,
    { why: "A campaign roll-up by DeliveryAction tells the responder how many landed (Delivered) versus were caught (Junked/Blocked) — the numbers that drive the ZAP and user-notification decision." }),
  W("k021", "Alerts → incidents join", "2.1.7", "Join SecurityIncident to its alerts: for incident number 4104, list the distinct AlertName values. AlertIds is a dynamic array on the incident; SystemAlertId is the key on SecurityAlert. Use the latest row for the incident.", ["SecurityIncident", "SecurityAlert"],
    `SecurityIncident | where IncidentNumber == 4104 | summarize arg_max(LastModifiedTime, AlertIds) | mv-expand AlertId = AlertIds to typeof(string) | join kind=inner (SecurityAlert | project SystemAlertId, AlertName) on $left.AlertId == $right.SystemAlertId | distinct AlertName`,
    { hint: "arg_max picks the newest incident row; mv-expand the AlertIds array; join on $left.X == $right.Y when the key names differ.", why: "SecurityIncident writes a new row on every update, so arg_max(LastModifiedTime, …) gets the current state. mv-expand explodes the AlertIds array, and the join key names differ on each side so the $left/$right form is required." }),
  W("k022", "Current incident queue", "2.1.7", "Using only the latest row per incident, count incidents by Status and Severity.", ["SecurityIncident"],
    `SecurityIncident | summarize arg_max(LastModifiedTime, *) by IncidentNumber | summarize count() by Status, Severity`,
    { why: "Two summarizes: the first collapses the update history to one current row per IncidentNumber (arg_max with * keeps every column), the second counts the queue." }),
  W("k023", "Alert entities — hosts", "3.1.2", "From SecurityAlert, extract the host names mentioned in Entities (JSON text; each entity has Type and HostName) and count alerts per host for alerts in the last 3 days. Return HostName and the distinct alert count.", ["SecurityAlert"],
    `SecurityAlert | where TimeGenerated > ago(3d) | mv-expand E = parse_json(Entities) | where E.Type == "host" | summarize Alerts = dcount(SystemAlertId) by HostName = tostring(E.HostName)`,
    { why: "Entities is JSON text; parse_json + mv-expand yields one row per entity; filter on Type; dcount(SystemAlertId) avoids double-counting an alert with two host entities." }),
  W("k024", "NSG opened to the Internet", "3.1.1", "From Azure Activity, find successful security-rule writes (OperationNameValue contains SECURITYRULES/WRITE) made from a non-private IP. Return TimeGenerated, Caller and CallerIpAddress.", ["AzureActivity"],
    `AzureActivity | where OperationNameValue has "SECURITYRULES/WRITE" and ActivityStatusValue == "Success" and not(ipv4_is_private(CallerIpAddress)) | project TimeGenerated, Caller, CallerIpAddress`,
    { why: "AzureActivity holds control-plane changes. Combining the operation with a caller-IP test (ipv4_is_private) surfaces the admin action done from outside the corporate network." }),
  W("k025", "NTLM brute force on the DC", "3.1.1", "From Defender for Identity logon events, find source IPs with more than 10 failed NTLM logons. Return IPAddress, DeviceName and the count.", ["IdentityLogonEvents"],
    `IdentityLogonEvents | where ActionType == "LogonFailed" and Protocol == "NTLM" | summarize Failures = count() by IPAddress, DeviceName | where Failures > 10`,
    { why: "IdentityLogonEvents is the Defender for Identity sensor's view of domain-controller authentication — the right table for on-premises AD brute force, as opposed to SigninLogs (Entra) or DeviceLogonEvents (endpoint)." }),
  W("k026", "Local-admin logons from the Internet", "3.1.3", "From Defender for Endpoint logon events, find successful RemoteInteractive (RDP) logons from a public IP where the account is a local admin. Return Timestamp, DeviceName, AccountName and RemoteIP.", ["DeviceLogonEvents"],
    `DeviceLogonEvents | where ActionType == "LogonSuccess" and LogonType == "RemoteInteractive" and RemoteIPType == "Public" and IsLocalAdmin == true | project Timestamp, DeviceName, AccountName, RemoteIP`,
    { why: "DeviceLogonEvents.LogonType is a word, not a number, and IsLocalAdmin is a bool. Public RDP with local admin is exactly the exposure the NSG change created." }),

  /* ---------------- fix it (18) ---------------- */
  F("k027", "Quotes on a string column", "3.1.2", "This should list failed sign-ins, but it errors. Fix the one bug.", ["SigninLogs"],
    `SigninLogs\n| where ResultType != 0\n| project TimeGenerated, UserPrincipalName, ResultType`,
    `SigninLogs\n| where ResultType != "0"\n| project TimeGenerated, UserPrincipalName, ResultType`,
    { why: "ResultType is a string in SigninLogs, so comparing it with the number 0 is a type error (\"Cannot compare values of types string and long\"). Quote it." }),
  F("k028", "No quotes on a numeric column", "3.1.2", "This should find network logon failures but returns an error. One bug.", ["SecurityEvent"],
    `SecurityEvent\n| where EventID == "4625" and LogonType == 3\n| summarize count() by IpAddress`,
    `SecurityEvent\n| where EventID == 4625 and LogonType == 3\n| summarize count() by IpAddress`,
    { why: "EventID is an int in SecurityEvent. The opposite of the SigninLogs trap: numbers unquoted, strings quoted. Read the column type in the schema panel before you compare." }),
  F("k029", "Misspelled operator", "3.1.3", "The analyst wants sign-ins per hour, but the editor refuses to parse the query.", ["SigninLogs"],
    `SigninLogs\n| where TimeGenerated > ago(1d)\n| summarise count() by bin(TimeGenerated, 1h)`,
    `SigninLogs\n| where TimeGenerated > ago(1d)\n| summarize count() by bin(TimeGenerated, 1h)`,
    { why: "'summarise' isn't a KQL operator; the editor reports 'Query could not be parsed at summarise'. Operator names are American-spelled and lower-case." }),
  F("k030", "has vs contains", "3.1.2", "This should find connections to any host whose URL contains the fragment 'bad' (the C2 is update-cdn.badexample.net), but it returns no rows. One bug.", ["DeviceNetworkEvents"],
    `DeviceNetworkEvents\n| where RemoteUrl has "bad"\n| summarize count() by RemoteUrl, RemoteIP`,
    `DeviceNetworkEvents\n| where RemoteUrl contains "bad"\n| summarize count() by RemoteUrl, RemoteIP`,
    { hint: "has matches whole terms; 'bad' is only part of the term 'badexample'.", why: "has is a whole-term match: the term in the URL is 'badexample', so has \"bad\" finds nothing. contains is a substring match (or use has \"badexample\"). Any fix that returns the same rows passes." }),
  F("k031", "Case-sensitive equality", "3.1.3", "This should find Word spawning PowerShell, but returns nothing because the data stores the process name in upper case.", ["DeviceProcessEvents"],
    `DeviceProcessEvents\n| where InitiatingProcessFileName == "winword.exe" and FileName =~ "powershell.exe"\n| project Timestamp, DeviceName, ProcessCommandLine`,
    `DeviceProcessEvents\n| where InitiatingProcessFileName =~ "winword.exe" and FileName =~ "powershell.exe"\n| project Timestamp, DeviceName, ProcessCommandLine`,
    { why: "== is case-sensitive; the data has WINWORD.EXE. =~ is the case-insensitive equality operator — use it for file names, user names and anything the OS may capitalize." }),
  F("k032", "Dot on a string column", "2.1.7", "The analyst wants the host names from alert entities, but the query returns no rows: Entities is a string, so mv-expand treats it as one scalar and E.Type is empty. One bug.", ["SecurityAlert"],
    `SecurityAlert\n| mv-expand E = Entities\n| where E.Type == "host"\n| summarize count() by tostring(E.HostName)`,
    `SecurityAlert\n| mv-expand E = parse_json(Entities)\n| where E.Type == "host"\n| summarize count() by tostring(E.HostName)`,
    { why: "Entities is JSON text (string), not dynamic. mv-expand on a string treats it as one scalar value, so nothing expands and E.Type is empty. parse_json() (or todynamic()) converts it to a dynamic array first." }),
  F("k033", "Aggregate without summarize", "3.1.3", "This should count failed logons per IP, but errors. One bug.", ["SecurityEvent"],
    `SecurityEvent\n| where EventID == 4625\n| extend Failures = count() by IpAddress`,
    `SecurityEvent\n| where EventID == 4625\n| summarize Failures = count() by IpAddress`,
    { why: "count() is an aggregation function; it only lives inside summarize (or make-series). extend computes one value per row and can't group." }),
  F("k034", "Threshold before the aggregate exists", "1.4.3", "An analytics rule should alert when one IP fails 50126 against more than 5 users. The query errors. One bug.", ["SigninLogs"],
    `SigninLogs\n| where ResultType == "50126" and Users > 5\n| summarize Users = dcount(UserPrincipalName) by IPAddress`,
    `SigninLogs\n| where ResultType == "50126"\n| summarize Users = dcount(UserPrincipalName) by IPAddress\n| where Users > 5`,
    { why: "Users doesn't exist until summarize creates it. Filter the raw rows first, aggregate, then filter the aggregate with a second where. Order of operators is the whole point of the pipe." }),
  F("k035", "Join key names differ", "2.1.7", "Join incident alert ids to SecurityAlert. The join errors because the key column has a different name on each side. One bug.", ["SecurityIncident", "SecurityAlert"],
    `SecurityIncident\n| where IncidentNumber == 4104\n| summarize arg_max(LastModifiedTime, AlertIds)\n| mv-expand AlertId = AlertIds to typeof(string)\n| join kind=inner (SecurityAlert | project SystemAlertId, AlertName) on AlertId\n| distinct AlertName`,
    `SecurityIncident\n| where IncidentNumber == 4104\n| summarize arg_max(LastModifiedTime, AlertIds)\n| mv-expand AlertId = AlertIds to typeof(string)\n| join kind=inner (SecurityAlert | project SystemAlertId, AlertName) on $left.AlertId == $right.SystemAlertId\n| distinct AlertName`,
    { why: "on Column requires the same column name on both sides. When names differ, write on $left.AlertId == $right.SystemAlertId (or project-rename one side first)." }),
  F("k036", "Wrong join kind", "3.1.2", "The analyst wants sign-ins from IPs that are NOT in the allow list. The query returns the opposite. One bug.", ["SigninLogs"],
    `let allow = datatable(IPAddress: string) ["10.11.4.77", "10.10.0.4"];\nSigninLogs\n| where TimeGenerated > ago(2d)\n| join kind=inner (allow) on IPAddress\n| summarize count() by IPAddress`,
    `let allow = datatable(IPAddress: string) ["10.11.4.77", "10.10.0.4"];\nSigninLogs\n| where TimeGenerated > ago(2d)\n| join kind=leftanti (allow) on IPAddress\n| summarize count() by IPAddress`,
    { why: "inner keeps rows that match the allow list; leftanti keeps left rows with NO match on the right — the 'not in the list' semantics. Exam stems love this swap." }),
  F("k037", "Time window on the wrong side", "3.1.2", "This should return sign-ins from the last 24 hours but returns everything older than that. One bug.", ["SigninLogs"],
    `SigninLogs\n| where TimeGenerated < ago(24h)\n| summarize count() by UserPrincipalName`,
    `SigninLogs\n| where TimeGenerated > ago(24h)\n| summarize count() by UserPrincipalName`,
    { why: "ago(24h) is a point in time 24 hours ago; 'recent' rows are greater than it. < ago(24h) selects the old data." }),
  F("k038", "Comparing a datetime with text", "3.1.3", "This should list process events since noon on Nov 14 2026 (UTC), but the editor reports a type error. One bug.", ["DeviceProcessEvents"],
    `DeviceProcessEvents\n| where Timestamp > "2026-11-14 12:00"\n| summarize count() by DeviceName`,
    `DeviceProcessEvents\n| where Timestamp > datetime(2026-11-14 12:00)\n| summarize count() by DeviceName`,
    { why: "A quoted date is a string; Timestamp is a datetime and KQL won't compare the two implicitly. Wrap the literal in datetime() (or use todatetime())." }),
  F("k039", "or with a dangling value", "3.1.2", "This should match two users but errors on the 'or'. One bug.", ["SigninLogs"],
    `SigninLogs\n| where UserPrincipalName == "rlopez@fabrikam.com" or "mchen@fabrikam.com"\n| summarize count() by UserPrincipalName`,
    `SigninLogs\n| where UserPrincipalName in ("rlopez@fabrikam.com", "mchen@fabrikam.com")\n| summarize count() by UserPrincipalName`,
    { why: "Each side of 'or' must be a complete boolean. Either repeat the comparison or, better, use in (…) for a list of values." }),
  F("k040", "Wrong table", "3.1.1", "The analyst wants on-premises AD failed logons seen by the Defender for Identity sensor, but the query reads the wrong table (and so errors on column names). One bug.", ["IdentityLogonEvents"],
    `DeviceLogonEvents\n| where ActionType == "LogonFailed" and Protocol == "NTLM"\n| summarize count() by IPAddress, DestinationDeviceName`,
    `IdentityLogonEvents\n| where ActionType == "LogonFailed" and Protocol == "NTLM"\n| summarize count() by IPAddress, DestinationDeviceName`,
    { why: "IdentityLogonEvents (Defender for Identity) has IPAddress / DestinationDeviceName; DeviceLogonEvents (Defender for Endpoint) has RemoteIP / DeviceName. 'Identify the appropriate table' is a named SC-200 skill for a reason." }),
  F("k041", "Column name case", "3.1.3", "This should group network connections by the remote address but errors: 'Failed to resolve scalar expression'. One bug.", ["DeviceNetworkEvents"],
    `DeviceNetworkEvents\n| where RemoteIPType == "Public"\n| summarize count() by RemoteIp`,
    `DeviceNetworkEvents\n| where RemoteIPType == "Public"\n| summarize count() by RemoteIP`,
    { why: "Column names are case-sensitive: RemoteIP, not RemoteIp. The editor's 'Failed to resolve scalar expression named' almost always means a typo or case slip in a column name." }),
  F("k042", "String concatenation", "3.1.3", "This should build a 'user@host' label but errors on the plus sign. One bug.", ["DeviceLogonEvents"],
    `DeviceLogonEvents\n| where ActionType == "LogonSuccess" and LogonType == "RemoteInteractive"\n| extend Label = AccountName + "@" + DeviceName\n| summarize count() by Label`,
    `DeviceLogonEvents\n| where ActionType == "LogonSuccess" and LogonType == "RemoteInteractive"\n| extend Label = strcat(AccountName, "@", DeviceName)\n| summarize count() by Label`,
    { why: "KQL doesn't concatenate strings with +; use strcat(). The error message says so." }),
  F("k043", "mv-expand before the filter", "2.3.1", "Extract the ForwardTo address from inbox-rule parameters. The query returns no rows because the filter runs before the array is expanded. One bug (move one line).", ["OfficeActivity"],
    `OfficeActivity\n| where Operation == "New-InboxRule"\n| extend P = parse_json(Parameters)\n| where P.Name == "ForwardTo"\n| mv-expand P\n| project UserId, ForwardTo = tostring(P.Value)`,
    `OfficeActivity\n| where Operation == "New-InboxRule"\n| extend P = parse_json(Parameters)\n| mv-expand P\n| where P.Name == "ForwardTo"\n| project UserId, ForwardTo = tostring(P.Value)`,
    { why: "Before mv-expand, P is the whole array and P.Name is null, so the filter drops everything. Expand first, then filter on the element." }),
  F("k044", "Advanced-hunting custom detection columns", "1.4.1", "This query is meant to become a Defender XDR custom detection. The service rejects it because the output lacks the Timestamp and ReportId columns it needs to track results (the device identifier is also expected). One bug: the project drops them.", ["DeviceProcessEvents"],
    `DeviceProcessEvents\n| where FileName =~ "certutil.exe" and ProcessCommandLine has "urlcache"\n| project DeviceName, ProcessCommandLine`,
    `DeviceProcessEvents\n| where FileName =~ "certutil.exe" and ProcessCommandLine has "urlcache"\n| project Timestamp, ReportId, DeviceId, DeviceName, ProcessCommandLine`,
    { names: true, why: "Custom detection rules need Timestamp and ReportId (and an impacted-entity column such as DeviceId) in the result set so the service can de-duplicate alerts and act on the entity. Keep them in the final project." }),

  /* ---------------- predict it (16) ---------------- */
  P("k045", "count vs dcount", "3.1.2", "What does this query return?", ["SigninLogs"],
    `SigninLogs | where IPAddress == "203.0.113.57" | summarize Attempts = count(), Users = dcount(UserPrincipalName)`,
    [`SigninLogs | where IPAddress == "203.0.113.57" | summarize Attempts = dcount(UserPrincipalName), Users = count()`, `SigninLogs | where IPAddress == "203.0.113.57" | summarize Attempts = count(), Users = count()`, `SigninLogs | where IPAddress == "203.0.113.57" | summarize Attempts = dcount(UserPrincipalName), Users = dcount(UserPrincipalName)`],
    { why: "count() is rows (38 attempts: 36 failures plus 2 successes); dcount() is distinct values (25 users). Mixing them up flips the two numbers." }),
  P("k046", "summarize by changes the columns", "3.1.3", "Which output does this produce?", ["EmailEvents"],
    `EmailEvents | where SenderFromDomain == "northwind-pay.example" | summarize count() by DeliveryAction`,
    [`EmailEvents | where SenderFromDomain == "northwind-pay.example" | summarize count() by DeliveryLocation`, `EmailEvents | where SenderFromDomain == "northwind-pay.example" | summarize dcount(RecipientEmailAddress) by DeliveryAction`, `EmailEvents | where SenderFromDomain == "northwind-pay.example" | count`],
    { why: "summarize count() by DeliveryAction yields exactly two columns: the by column and count_. 22 delivered, 5 junked, 3 blocked for the campaign." }),
  P("k047", "project vs project-away", "3.1.3", "Which output has the right columns?", ["SecurityEvent"],
    `SecurityEvent | where EventID == 1102 | project Computer, SubjectUserName`,
    [`SecurityEvent | where EventID == 1102 | project-away Computer, SubjectUserName | project TimeGenerated, EventID, Activity`, `SecurityEvent | where EventID == 1102 | project SubjectUserName, Computer`, `SecurityEvent | where EventID == 1102 | project Computer, SubjectUserName, TimeGenerated`],
    { why: "project keeps exactly the listed columns in the listed order; project-away removes them. Column order is part of the output." }),
  P("k048", "take vs top", "3.1.3", "The data is newest-first. Which output does this query return?", ["DeviceNetworkEvents"],
    `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" | top 2 by Timestamp asc | project Timestamp, InitiatingProcessFileName`,
    [`DeviceNetworkEvents | where RemoteIP == "198.51.100.77" | top 2 by Timestamp desc | project Timestamp, InitiatingProcessFileName`, `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" | take 1 | project Timestamp, InitiatingProcessFileName`, `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" | summarize min(Timestamp), max(Timestamp)`],
    { ordered: true, why: "top N by X asc sorts ascending first, so you get the two EARLIEST connections — the certutil download and the first rundll32 beacon. take ignores order; top desc would give the newest." }),
  P("k049", "arg_max keeps the current row", "2.1.7", "What is the current state of incident 4103?", ["SecurityIncident"],
    `SecurityIncident | where IncidentNumber == 4103 | summarize arg_max(LastModifiedTime, Status, Classification)`,
    [`SecurityIncident | where IncidentNumber == 4103 | summarize arg_min(LastModifiedTime, Status, Classification)`, `SecurityIncident | where IncidentNumber == 4103 | summarize count() by Status`, `SecurityIncident | where IncidentNumber == 4103 | summarize arg_max(LastModifiedTime, Status, Classification) by Status`],
    { why: "arg_max(LastModifiedTime, …) returns the single newest row: Closed / BenignPositive (the user confirmed travel). arg_min would return the original New row; grouping by Status returns one row per state." }),
  P("k050", "has is whole-term", "3.1.2", "How many rows does each operator match? Pick the correct output.", ["DeviceProcessEvents"],
    `DeviceProcessEvents | summarize Has = countif(ProcessCommandLine has "enc"), HasSwitch = countif(ProcessCommandLine has "-enc"), Contains = countif(ProcessCommandLine contains "enc")`,
    [`DeviceProcessEvents | summarize Has = countif(ProcessCommandLine has "-enc"), HasSwitch = countif(ProcessCommandLine has "-enc"), Contains = countif(ProcessCommandLine has "-enc")`, `DeviceProcessEvents | summarize Has = countif(ProcessCommandLine contains "enc"), HasSwitch = countif(ProcessCommandLine has "-enc"), Contains = countif(ProcessCommandLine contains "enc")`, `DeviceProcessEvents | summarize Has = countif(ProcessCommandLine contains "enc"), HasSwitch = countif(ProcessCommandLine contains "enc"), Contains = countif(ProcessCommandLine contains "enc")`],
    { why: "has matches whole terms: 'enc' is a term inside '-enc' (punctuation splits terms) but not inside '-EncodedCommand' or 'Encoding'; contains is a plain substring match and counts every command line with those letters. Whole-term matching is why has is both faster and stricter." }),
  P("k051", "join kinds", "3.1.2", "Two tables: a watchlist of two IPs and the sign-ins from the last 2 days. Which output comes from kind=leftanti?", ["SigninLogs"],
    `let allow = datatable(IPAddress: string) ["10.11.4.77", "203.0.113.57"]; SigninLogs | where TimeGenerated > ago(2d) | join kind=leftanti (allow) on IPAddress | summarize Rows = count(), IPs = dcount(IPAddress)`,
    [`let allow = datatable(IPAddress: string) ["10.11.4.77", "203.0.113.57"]; SigninLogs | where TimeGenerated > ago(2d) | join kind=inner (allow) on IPAddress | summarize Rows = count(), IPs = dcount(IPAddress)`, `let allow = datatable(IPAddress: string) ["10.11.4.77", "203.0.113.57"]; SigninLogs | where TimeGenerated > ago(2d) | join kind=rightsemi (allow) on IPAddress | summarize Rows = count(), IPs = dcount(IPAddress)`, `let allow = datatable(IPAddress: string) ["10.11.4.77", "203.0.113.57"]; SigninLogs | where TimeGenerated > ago(2d) | join kind=rightanti (allow) on IPAddress | summarize Rows = count(), IPs = dcount(IPAddress)`],
    { why: "leftanti keeps the left rows WITHOUT a match (everything not on the list — many IPs). inner keeps only sign-ins from the listed IPs; rightsemi keeps the list entries that matched (two rows); rightanti keeps list entries that never appeared (zero rows here)." }),
  P("k052", "bin() buckets", "3.1.3", "The beacon runs every 5 minutes for two hours, then hourly. Which output is the hourly count for the first three hours?", ["DeviceNetworkEvents"],
    `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" and RemotePort == 443 | summarize Beacons = count() by Hour = bin(Timestamp, 1h) | sort by Hour asc | take 3`,
    [`DeviceNetworkEvents | where RemoteIP == "198.51.100.77" and RemotePort == 443 | summarize Beacons = count() by Hour = bin(Timestamp, 1d) | sort by Hour asc | take 3`, `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" and RemotePort == 443 | summarize Beacons = count() by Hour = bin(Timestamp, 1h) | sort by Hour desc | take 3`, `DeviceNetworkEvents | where RemoteIP == "198.51.100.77" and RemotePort == 443 | summarize Beacons = count() by Hour = bin(Timestamp, 30m) | sort by Hour asc | take 3`],
    { ordered: true, why: "bin(Timestamp, 1h) groups into hour buckets; the 5-minute phase gives 12 per hour, then 1 per hour. A 1d bin gives a single daily total; 30m halves the counts; desc shows the end of the activity instead of the start." }),
  P("k053", "Null-safe parsing", "2.3.1", "What does this produce for the inbox rule's parameters?", ["OfficeActivity"],
    `OfficeActivity | where Operation == "New-InboxRule" | mv-expand P = parse_json(Parameters) | project Name = tostring(P.Name), Value = tostring(P.Value)`,
    [`OfficeActivity | where Operation == "New-InboxRule" | extend P = parse_json(Parameters) | project Name = tostring(P.Name), Value = tostring(P.Value)`, `OfficeActivity | where Operation == "New-InboxRule" | mv-expand P = parse_json(Parameters) | project Name = tostring(P.Name)`, `OfficeActivity | where Operation == "New-InboxRule" | mv-expand P = parse_json(Parameters) | where P.Name == "ForwardTo" | project Name = tostring(P.Name), Value = tostring(P.Value)`],
    { why: "mv-expand gives one row per parameter (five of them: Name, ForwardTo, DeleteMessage, SubjectContainsWords, MarkAsRead). Without mv-expand, P is the whole array and P.Name is empty; a where on ForwardTo would leave one row." }),
  P("k054", "distinct vs summarize by", "3.1.3", "Which output does this query return?", ["SecurityAlert"],
    `SecurityAlert | where AlertSeverity == "High" | distinct ProviderName`,
    [`SecurityAlert | where AlertSeverity == "High" | summarize count() by ProviderName`, `SecurityAlert | distinct ProviderName`, `SecurityAlert | where AlertSeverity == "High" | distinct ProviderName, ProductName`],
    { why: "distinct ProviderName returns one column with the unique providers that raised a High alert. summarize count() by adds a count column; dropping the severity filter adds providers; adding ProductName adds a column." }),
  P("k055", "make_set vs make_list", "3.1.3", "For mchen's sign-ins, which output is make_set of the country?", ["SigninLogs"],
    `SigninLogs | where UserPrincipalName == "mchen@fabrikam.com" | summarize Countries = make_set(tostring(LocationDetails.countryOrRegion))`,
    [`SigninLogs | where UserPrincipalName == "mchen@fabrikam.com" | summarize Countries = make_list(tostring(LocationDetails.countryOrRegion))`, `SigninLogs | where UserPrincipalName == "mchen@fabrikam.com" | summarize Countries = dcount(tostring(LocationDetails.countryOrRegion))`, `SigninLogs | where UserPrincipalName == "mchen@fabrikam.com" | summarize Countries = count() by tostring(LocationDetails.countryOrRegion)`],
    { why: "make_set returns the distinct values as one dynamic array; make_list keeps every value (duplicates included); dcount is just the number; count() by returns one row per country." }),
  P("k056", "extend keeps, project replaces", "3.1.3", "What is the column list of this output?", ["DeviceLogonEvents"],
    `DeviceLogonEvents | where RemoteIP == "192.0.2.44" | extend Who = strcat(AccountDomain, "\\\\", AccountName) | summarize Attempts = count() by Who, ActionType | top 3 by Attempts`,
    [`DeviceLogonEvents | where RemoteIP == "192.0.2.44" | extend Who = strcat(AccountDomain, "\\\\", AccountName) | summarize Attempts = count() by ActionType | top 3 by Attempts`, `DeviceLogonEvents | where RemoteIP == "192.0.2.44" | project Who = strcat(AccountDomain, "\\\\", AccountName) | summarize Attempts = count() by Who | top 3 by Attempts`, `DeviceLogonEvents | where RemoteIP == "192.0.2.44" | summarize Attempts = count() by AccountName, ActionType, RemoteIP | top 3 by Attempts`],
    { ordered: true, why: "The by clause defines the output: Who and ActionType plus the aggregate Attempts. The brute force spread one or two attempts across many accounts, so the top rows are the accounts hit most, with LogonFailed." }),
  P("k057", "union adds rows, join adds columns", "3.1.2", "Which output comes from this union?", ["DeviceProcessEvents", "DeviceNetworkEvents"],
    `union DeviceProcessEvents, DeviceNetworkEvents | where DeviceName == "fab-wks-117.fabrikam.com" | summarize count() by Type = iff(isnotempty(RemoteIP), "network", "process")`,
    [`DeviceProcessEvents | where DeviceName == "fab-wks-117.fabrikam.com" | summarize count() by Type = "process"`, `union DeviceProcessEvents, DeviceNetworkEvents | where DeviceName == "fab-wks-117.fabrikam.com" | count`, `DeviceProcessEvents | where DeviceName == "fab-wks-117.fabrikam.com" | join kind=inner (DeviceNetworkEvents) on DeviceId | summarize count() by Type = "joined"`],
    { why: "union stacks rows from both tables (columns that exist in only one table are null in the other's rows), so a single summarize can count both kinds. A join would multiply rows by matches; count alone loses the split." }),
  P("k058", "between is inclusive", "3.1.3", "How many SecurityEvent rows fall in this window?", ["SecurityEvent"],
    `SecurityEvent | where Computer == "FAB-DC01.fabrikam.com" and EventID == 4625 | where TimeGenerated between (datetime(2026-11-13T05:00:00Z) .. datetime(2026-11-13T05:03:00Z)) | count`,
    [`SecurityEvent | where Computer == "FAB-DC01.fabrikam.com" and EventID == 4625 | where TimeGenerated between (datetime(2026-11-13T05:00:00Z) .. datetime(2026-11-13T05:06:00Z)) | count`, `SecurityEvent | where Computer == "FAB-DC01.fabrikam.com" and EventID == 4625 | count`, `SecurityEvent | where Computer == "FAB-DC01.fabrikam.com" and EventID == 4625 | where TimeGenerated between (datetime(2026-11-13T05:00:00Z) .. datetime(2026-11-13T05:01:00Z)) | count`],
    { why: "The brute force fires one 4625 every 6 seconds from 05:00:00; between is inclusive on both ends, so 05:00:00 through 05:03:00 contains 31 events (0 s, 6 s, …, 180 s). Widen to 6 minutes and you get 60; 1 minute gives 11." }),
  P("k059", "parse extracts typed columns", "3.1.3", "What does parse produce here?", ["CommonSecurityLog"],
    `CommonSecurityLog | where RequestURL != "" and DeviceAction == "alert" | parse RequestURL with "http://" Host "/" Path | project Host, Path`,
    [`CommonSecurityLog | where RequestURL != "" and DeviceAction == "alert" | parse RequestURL with "http://" Host | project Host`, `CommonSecurityLog | where RequestURL != "" and DeviceAction == "alert" | project Host = DestinationHostName, Path = RequestURL`, `CommonSecurityLog | where RequestURL != "" and DeviceAction == "alert" | parse RequestURL with "http://" Host "/" Path | project Path, Host`],
    { why: "parse walks the string: the literal 'http://' then captures Host up to the next literal '/' and Path takes the rest. With no '/' delimiter, Host would swallow the whole remainder; project order is part of the answer too." }),
  P("k060", "Time math", "3.1.3", "The spray's single success for rlopez came 29 minutes after its first failure. Which output does the query produce?", ["SigninLogs"],
    `SigninLogs | where IPAddress == "203.0.113.57" | summarize First = min(TimeGenerated), Success = minif(TimeGenerated, ResultType == "0") | extend Minutes = datetime_diff('minute', Success, First) | project Minutes`,
    [`SigninLogs | where IPAddress == "203.0.113.57" | summarize First = min(TimeGenerated), Success = minif(TimeGenerated, ResultType == "0") | extend Minutes = datetime_diff('minute', First, Success) | project Minutes`, `SigninLogs | where IPAddress == "203.0.113.57" | summarize First = min(TimeGenerated), Success = minif(TimeGenerated, ResultType == "0") | extend Minutes = datetime_diff('second', Success, First) | project Minutes`, `SigninLogs | where IPAddress == "203.0.113.57" | summarize First = min(TimeGenerated), Last = max(TimeGenerated) | extend Minutes = datetime_diff('minute', Last, First) | project Minutes`],
    { why: "datetime_diff(period, later, earlier) is positive when the first datetime is the later one: 29 minutes. Swapping the arguments gives -29; 'second' gives 1740; min→max spans the whole 31-minute spray." }),
];
