/* Cert Gauntlet — SC-200 portal-navigation / hot-area deck (60 items)
   Paths and region labels verified against Microsoft Learn how-to pages, Oct 2026.
   img is null until screenshots land (Chat 6). */
export const SC200_PORTAL = [
 /* ---------- domain 1: manage a security operations environment ---------- */
 {id:"p001",obj:"1.1.1",portal:"defender",
  q:"Where do you create a rule that emails the on-call analyst whenever a new high-severity incident appears?",
  path:["Settings","Microsoft Defender XDR","Email notifications"],
  target:"The 'Incidents' tab, then 'Add incident notification rule'",
  regions:[{l:"Incidents",ok:true},{l:"Actions",ok:false},{l:"Threat analytics",ok:false},{l:"Email notifications",ok:false},{l:"Alert tuning",ok:false}],
  img:null,
  x:"Incident, response-action and threat-analytics mail rules each live on their own tab of the same Email notifications page. People pick 'Actions' by mistake; that tab only fires when a remediation action needs approval or completes, not when an incident is created."},
 {id:"p002",obj:"1.1.2",portal:"defender",
  q:"Where do you start a rule that automatically resolves a recurring benign alert for one device group?",
  path:["Settings","Microsoft Defender XDR","Alert tuning"],
  target:"The 'Add new rule' button at the top of the Alert tuning list",
  regions:[{l:"Add new rule",ok:true},{l:"Alert tuning",ok:false},{l:"Email notifications",ok:false},{l:"Automated response",ok:false},{l:"Permissions",ok:false}],
  img:null,
  x:"Alert tuning replaced the older suppression list and is scoped per service source with conditions. It is a Defender XDR setting, not an Endpoints setting, so it sits beside Email notifications and Automated response rather than under Settings > Endpoints."},
 {id:"p003",obj:"1.1.3",portal:"defender",
  q:"Where do you turn on the ability to open a remote shell to onboarded workstations?",
  path:["Settings","Endpoints","Advanced features"],
  target:"The 'Enable live response' toggle",
  regions:[{l:"Enable live response",ok:true},{l:"Enable live response for servers",ok:false},{l:"Allow unsigned script execution in live response",ok:false},{l:"Enable EDR in block mode",ok:false},{l:"Enable tamper protection",ok:false}],
  img:null,
  x:"Live response has three related toggles in a row on the Advanced features page: the base feature, a separate switch for server operating systems, and a third that allows unsigned scripts. A stem about Windows Server hosts needs the second toggle as well as the first."},
 {id:"p004",obj:"1.1.3",portal:"defender",
  q:"Where do you stop local admins from disabling Defender Antivirus real-time protection on every onboarded device?",
  path:["Settings","Endpoints","Advanced features"],
  target:"The 'Enable tamper protection' toggle",
  regions:[{l:"Enable tamper protection",ok:true},{l:"Enable EDR in block mode",ok:false},{l:"Automatically resolve alerts",ok:false},{l:"Enable device discovery",ok:false},{l:"Enable live response",ok:false}],
  img:null,
  x:"The tenant-wide tamper protection switch lives among the Advanced features toggles. It is distinct from a per-device Intune antivirus policy; the portal toggle is the quick answer when the stem says 'for all devices in the tenant' rather than 'for a device group'."},
 {id:"p005",obj:"1.1.3",portal:"defender",
  q:"Where do you let Defender for Endpoint block malicious behavior on devices whose primary antivirus is a non-Microsoft product?",
  path:["Settings","Endpoints","Advanced features"],
  target:"The 'Enable EDR in block mode' toggle",
  regions:[{l:"Enable EDR in block mode",ok:true},{l:"Enable tamper protection",ok:false},{l:"Configure custom network indicators",ok:false},{l:"Restrict correlation to within scoped device groups",ok:false},{l:"Enable device discovery",ok:false}],
  img:null,
  x:"EDR in block mode only matters when Defender Antivirus is in passive mode behind a third-party AV; it lets the EDR sensor remediate what the other product missed. Stems mentioning 'passive mode' or a third-party antivirus are the signal for this toggle, not tamper protection."},
 {id:"p006",obj:"1.1.4",portal:"defender",
  q:"Where do you block a known-bad SHA256 across all devices without waiting for an alert?",
  path:["Settings","Endpoints","Indicators"],
  target:"The 'File hashes' tab, then 'Add item'",
  regions:[{l:"File hashes",ok:true},{l:"IP addresses",ok:false},{l:"URLs/Domains",ok:false},{l:"Certificates",ok:false},{l:"Import",ok:false}],
  img:null,
  x:"Indicators are organized by type into tabs, and each tab supports a single Add item or a bulk Import of a CSV. Hash and certificate indicators are enforced by Defender Antivirus, while URL and IP indicators need the network protection prerequisite, so the tab you pick also implies the prerequisite you need."},
 {id:"p007",obj:"1.1.4",portal:"defender",
  q:"Where do you start a policy that blocks gambling sites for one device group but not the others?",
  path:["Settings","Endpoints","Web content filtering"],
  target:"The 'Add policy' button above the policy list",
  regions:[{l:"Add policy",ok:true},{l:"Web content filtering",ok:false},{l:"Indicators",ok:false},{l:"Device groups",ok:false},{l:"Advanced features",ok:false}],
  img:null,
  x:"Web content filtering policies block categories, not individual URLs; a single site exception is an Indicator on the URLs/Domains tab instead. The policy wizard scopes by device group on its Scope page, which is why Device groups sits beside it in the Endpoints settings list."},
 {id:"p008",obj:"1.1.9",portal:"defender",
  q:"Where do you carve the Finance laptops into their own set so a different automation level and RBAC scope apply to them?",
  path:["Settings","Endpoints","Device groups"],
  target:"The 'Add device group' button",
  regions:[{l:"Add device group",ok:true},{l:"Device groups",ok:false},{l:"Indicators",ok:false},{l:"Web content filtering",ok:false},{l:"Advanced features",ok:false}],
  img:null,
  x:"Device groups are the unit for both automation level and role scoping in Defender for Endpoint, so this page is where both questions resolve. A device tag is only a label used in the membership rule; the group, not the tag, carries the remediation level."},
 {id:"p009",obj:["1.1.9","1.1.7"],portal:"defender",
  q:"In the device group wizard, which remediation level lets automated investigation clean up threats on any folder without an analyst approving each action?",
  path:["Settings","Endpoints","Device groups","Add device group"],
  target:"The 'Full - remediate threats automatically' option in the Remediation level list on the General tab",
  regions:[{l:"Full - remediate threats automatically",ok:true},{l:"Semi - require approval for all folders",ok:false},{l:"Semi - require approval for core folders remediation",ok:false},{l:"Semi - require approval for non-temp folders remediation",ok:false},{l:"No automated response",ok:false}],
  img:null,
  x:"The three Semi levels differ only in which folders need approval, and 'No automated response' turns AIR off for the group. Full remediation is also what automatic attack disruption prefers, which is why attack-disruption stems route you back to this same dropdown."},
 {id:"p010",obj:"1.1.9",portal:"defender",
  q:"When building a custom Defender XDR role for tier-1 analysts who only triage incidents and alerts, which permission group do you open?",
  path:["Permissions","Microsoft Defender XDR","Roles","Create custom role","Choose permissions"],
  target:"The 'Security operations' permission group",
  regions:[{l:"Security operations",ok:true},{l:"Security posture",ok:false},{l:"Authorization and settings",ok:false},{l:"Data operations",ok:false},{l:"Assign users and data sources",ok:false}],
  img:null,
  x:"Unified RBAC groups permissions into Security operations (incidents, alerts, response, hunting), Security posture (exposure and vulnerability data) and Authorization and settings (roles and system settings). 'Data operations' is not a permission group. Analysts who should not touch settings never need anything outside Security operations."},
 {id:"p011",obj:"1.1.6",portal:"defender",
  q:"Where do you build a policy that puts ASR rules into Block mode on devices managed straight from the Defender portal, without opening Intune?",
  path:["Endpoints","Configuration management","Endpoint security policies","Create new policy"],
  target:"The 'Attack surface reduction (ASR) rules' template in the policy template list",
  regions:[{l:"Attack surface reduction (ASR) rules",ok:true},{l:"Microsoft Defender Antivirus",ok:false},{l:"Endpoint detection and response (EDR)",ok:false},{l:"Microsoft Defender Firewall",ok:false},{l:"Device control",ok:false},{l:"Defender update controls",ok:false}],
  img:null,
  x:"The Endpoint security policies page in the Defender portal mirrors the Intune endpoint security node for devices enrolled through security settings management. Antivirus and ASR are separate templates; a stem about Office child processes or credential theft is ASR, not Antivirus."},
 {id:"p012",obj:"1.1.6",portal:"intune",
  q:"In the Intune admin center, which profile do you choose so a Windows policy can set 'Block Office applications from creating child processes'?",
  path:["Endpoint security","Attack surface reduction","Create Policy"],
  target:"The 'Attack Surface Reduction Rules' profile",
  regions:[{l:"Attack Surface Reduction Rules",ok:true},{l:"Device Control",ok:false},{l:"Exploit Protection",ok:false},{l:"App and browser isolation",ok:false},{l:"Application control",ok:false},{l:"Web protection (Microsoft Edge Legacy)",ok:false}],
  img:null,
  x:"The Attack surface reduction node holds several unrelated profiles that share the name. Device Control is USB and peripheral rules, Exploit Protection is the per-process mitigations, and App and browser isolation is Application Guard; only the Attack Surface Reduction Rules profile exposes the per-rule Audit, Block and Warn settings."},
 {id:"p013",obj:"1.1.7",portal:"defender",
  q:"Where do you approve the quarantine actions that semi-automated investigations are waiting on?",
  path:["Actions & submissions","Action center"],
  target:"The 'Pending' tab",
  regions:[{l:"Pending",ok:true},{l:"History",ok:false},{l:"Export",ok:false},{l:"Submissions",ok:false},{l:"Action center",ok:false}],
  img:null,
  x:"The Action center splits into Pending (waiting on an approval) and History (already taken, with Undo where supported). Semi-automation levels generate Pending entries; Full remediation never does, which is a common trick in stems that ask why nothing shows up on this tab."},
 {id:"p014",obj:"1.1.8",portal:"defender",
  q:"Where is the tenant-level switch that lets Defender XDR contain devices and disable users during an in-progress attack?",
  path:["Settings","Endpoints","Advanced features"],
  target:"The 'Configure automatic attack disruption' toggle",
  regions:[{l:"Configure automatic attack disruption",ok:true},{l:"Enable live response",ok:false},{l:"Enable EDR in block mode",ok:false},{l:"Enable tamper protection",ok:false},{l:"Enable device discovery",ok:false}],
  img:null,
  x:"Attack disruption is governed in three places: this toggle, the device group remediation level, and the exclusion lists under Settings > Microsoft Defender XDR > Automated response. The toggle is the on/off; the exclusions decide who is spared; the device group level decides whether approval is needed."},
 {id:"p015",obj:"1.1.8",portal:"defender",
  q:"Where do you stop attack disruption from ever disabling the break-glass admin account?",
  path:["Settings","Microsoft Defender XDR","Automated response","Identities"],
  target:"The 'Add user exclusion' button",
  regions:[{l:"Add user exclusion",ok:true},{l:"Identities",ok:false},{l:"Devices",ok:false},{l:"Remove",ok:false},{l:"Alert tuning",ok:false}],
  img:null,
  x:"User exclusions for attack disruption live on the Identities tab of the Automated response settings, separate from device exclusions on the Devices tab. Excluding a user here does not suppress alerts about that user; it only prevents the automatic disable-user response."},
 {id:"p016",obj:"1.1.8",portal:"defender",
  q:"Where do you keep attack disruption from containing anything on the data-center management subnet?",
  path:["Settings","Microsoft Defender XDR","Automated response","Devices"],
  target:"The 'Exclude IP' button on the Policy application tab",
  regions:[{l:"Exclude IP",ok:true},{l:"Policy application",ok:false},{l:"Device groups",ok:false},{l:"Create rule",ok:false},{l:"Identities",ok:false}],
  img:null,
  x:"The Devices side of Automated response has a Device groups tab (set the automation level per group) and a Policy application tab (IP exclusions and tag-based policy rules). A subnet is an IP exclusion; a named server set is handled through a device group or a tag rule instead."},
 {id:"p017",obj:"1.1.10",portal:"defender",
  q:"Where do you begin a rule that auto-assigns every new Sentinel incident tagged Fabrikam-Prod to the night-shift queue?",
  path:["Microsoft Sentinel","Configuration","Automation","Create"],
  target:"The 'Automation rule' entry in the Create menu",
  regions:[{l:"Automation rule",ok:true},{l:"Playbook with incident trigger",ok:false},{l:"Playbook with alert trigger",ok:false},{l:"Playbook with entity trigger",ok:false},{l:"Blank playbook",ok:false}],
  img:null,
  x:"The Create menu on the Automation page mixes automation rules with the playbook starters. Assigning owners, changing status, adding tags and tasks are native automation-rule actions and need no Logic App; only when the stem asks for an external action (ticket, email, API call) do you pick a playbook."},
 {id:"p018",obj:"1.1.10",portal:"defender",
  q:"In the Create new automation rule pane, which trigger do you pick so the rule fires when an analyst changes an incident's severity?",
  path:["Microsoft Sentinel","Configuration","Automation","Create","Automation rule"],
  target:"The 'When incident is updated' option in the Trigger dropdown",
  regions:[{l:"When incident is updated",ok:true},{l:"When incident is created",ok:false},{l:"When alert is created",ok:false},{l:"Conditions",ok:false},{l:"Actions",ok:false},{l:"Rule expiration",ok:false}],
  img:null,
  x:"Three triggers exist: incident created, incident updated, and alert created. Updated-incident rules can condition on which field changed and by whom, which is what a severity-change stem needs. Alert-created rules can only run playbooks, not assign or tag incidents."},
 {id:"p019",obj:"1.1.11",portal:"defender",
  q:"Where do you start a playbook that analysts will run on demand against a single suspicious account from the entity pane?",
  path:["Microsoft Sentinel","Configuration","Automation","Create"],
  target:"The 'Playbook with entity trigger' entry in the Create menu",
  regions:[{l:"Playbook with entity trigger",ok:true},{l:"Playbook with incident trigger",ok:false},{l:"Playbook with alert trigger",ok:false},{l:"Automation rule",ok:false},{l:"Blank playbook",ok:false}],
  img:null,
  x:"The trigger you choose at creation decides where the playbook can later be launched: incident-trigger playbooks run from incidents and automation rules, alert-trigger ones from alerts, and entity-trigger ones from a user, host, IP or other entity. Blank playbook creates a Standard Logic App with no Sentinel trigger yet."},
 {id:"p020",obj:"1.2.1",portal:"azure",
  q:"Which built-in role do you assign to an analyst who must assign and close incidents but must not edit analytics rules?",
  path:["Access control (IAM)","Add","Add role assignment"],
  target:"The 'Microsoft Sentinel Responder' row on the Role tab",
  regions:[{l:"Microsoft Sentinel Responder",ok:true},{l:"Microsoft Sentinel Reader",ok:false},{l:"Microsoft Sentinel Contributor",ok:false},{l:"Microsoft Sentinel Playbook Operator",ok:false},{l:"Microsoft Sentinel Automation Contributor",ok:false},{l:"Job function roles",ok:false}],
  img:null,
  x:"Sentinel roles are Azure RBAC roles assigned on the workspace or resource group through Access control (IAM). Reader views, Responder manages incidents, Contributor also edits content, Playbook Operator may run playbooks, and Automation Contributor is granted to the Sentinel service identity, not to people."},
 {id:"p021",obj:"1.2.2",portal:"azure",
  q:"Where do you extend how long a single table's data stays queryable to two years without changing the whole workspace?",
  path:["Log Analytics workspaces","Tables","Manage table"],
  target:"The 'Interactive retention' (analytics retention) setting in the Data retention settings section",
  regions:[{l:"Interactive retention",ok:true},{l:"Total retention",ok:false},{l:"Analytics",ok:false},{l:"Basic",ok:false},{l:"Auxiliary",ok:false}],
  img:null,
  x:"Manage table exposes the plan (Analytics, Basic or Auxiliary) and two retention values. Interactive (analytics) retention is the window in which data stays queryable, up to two years; Total retention adds the long-term, lower-cost period after it. Stems about 'queryable' or 'searchable' are about the first number; 'kept for compliance' is the second."},
 {id:"p022",obj:"1.2.3",portal:"defender",
  q:"Where do you build a visualization from scratch instead of saving a solution's template?",
  path:["Microsoft Sentinel","Threat management","Workbooks"],
  target:"The 'Add workbook' button",
  regions:[{l:"Add workbook",ok:true},{l:"Templates",ok:false},{l:"My workbooks",ok:false},{l:"Save",ok:false},{l:"View saved workbook",ok:false}],
  img:null,
  x:"The Workbooks page has two tabs: Templates (installed from Content hub, saved with 'Save') and My workbooks (yours). Add workbook starts an empty one. Workbooks are the reporting surface; notebooks, the frequent distractor, are for Python-driven hunting and live under a different menu."},
 {id:"p023",obj:"1.2.4",portal:"defender",
  q:"Where do you review the SOC optimization recommendations you previously set aside?",
  path:["SOC optimization","Overview"],
  target:"The 'Optimization status' view, filtered to Status = Dismissed",
  regions:[{l:"Optimization status",ok:true},{l:"Completed",ok:false},{l:"Overview",ok:false},{l:"Coverage",ok:false},{l:"Data value",ok:false}],
  img:null,
  x:"SOC optimization sorts recommendations into Coverage (threat-scenario gaps) and Data value (unused or costly tables). Each one can be completed, marked in progress or dismissed; the Optimization status view lists them by status, so filtering it to Dismissed shows the set-aside ones, which can be reactivated, the answer to 'bring it back'."},
 {id:"p024",obj:"1.3.1",portal:"defender",
  q:"Where do you add the Syslog solution so its AMA connector and rules become available?",
  path:["Microsoft Sentinel","Content management","Content hub"],
  target:"The 'Install' button on the selected solution",
  regions:[{l:"Install",ok:true},{l:"Manage",ok:false},{l:"Create",ok:false},{l:"View details",ok:false},{l:"Repositories",ok:false},{l:"Community",ok:false}],
  img:null,
  x:"Since connectors ship inside solutions, the Content hub is step zero for most ingestion stems; a connector missing from Data connectors usually means its solution was never installed. Manage opens an installed solution's items, Repositories is for CI/CD from your own Git repo."},
 {id:"p025",obj:"1.3.2",portal:"defender",
  q:"On the Collect tab of the Windows Security Events via AMA rule, which choice keeps only the smallest event set?",
  path:["Microsoft Sentinel","Configuration","Data connectors","Windows Security Events via AMA","Open connector page","+Add data collection rule","Collect"],
  target:"The 'Minimal' option",
  regions:[{l:"Minimal",ok:true},{l:"Common",ok:false},{l:"All Security Events",ok:false},{l:"Custom",ok:false},{l:"Basics",ok:false},{l:"Resources",ok:false}],
  img:null,
  x:"All Security Events, Common, Minimal and Custom are the four collection sets; Custom is where an XPath filter goes when the stem names specific event IDs. The same wizard's Resources tab is where you pick the VMs or Arc servers, which is what installs the Azure Monitor Agent."},
 {id:"p026",obj:"1.3.2",portal:"azure",
  q:"When creating a DCR directly in Azure Monitor, which data source type do you add to capture the Security log from Windows servers?",
  path:["Monitor","Data Collection Rules","Create","Collect and deliver"],
  target:"The 'Windows events' data source type",
  regions:[{l:"Windows events",ok:true},{l:"Performance counters",ok:false},{l:"Syslog",ok:false},{l:"Text log",ok:false},{l:"JSON log",ok:false},{l:"IIS logs",ok:false}],
  img:null,
  x:"A DCR built here is the generic Azure Monitor path; the Sentinel connector pages build the same object with the filter already pointed at the Security channel. Syslog is the Linux counterpart, and Text or JSON log is the custom-table route rather than event-log collection."},
 {id:"p027",obj:"1.3.4",portal:"defender",
  q:"Which connector do you open to receive firewall logs that arrive in ArcSight-style key=value format over a Linux forwarder?",
  path:["Microsoft Sentinel","Configuration","Data connectors"],
  target:"The 'Common Event Format (CEF) via AMA' connector tile",
  regions:[{l:"Common Event Format (CEF) via AMA",ok:true},{l:"Syslog via AMA",ok:false},{l:"Windows Security Events via AMA",ok:false},{l:"Windows Forwarded Events",ok:false},{l:"Threat Intelligence - TAXII",ok:false}],
  img:null,
  x:"CEF and Syslog share the forwarder and agent but land in different tables: CEF via AMA parses into CommonSecurityLog, Syslog via AMA stores raw lines in Syslog. Pick by format the appliance emits, not by transport. Windows Forwarded Events is the WEF collector connector, not a Linux one."},
 {id:"p028",obj:"1.3.5",portal:"azure",
  q:"When assigning the Azure Activity policy, where do you make existing subscriptions start streaming immediately rather than only new ones?",
  path:["Policy","Assignments","Assign policy"],
  target:"The 'Remediation' tab, 'Create a remediation task' checkbox",
  regions:[{l:"Remediation",ok:true},{l:"Basics",ok:false},{l:"Parameters",ok:false},{l:"Non-compliance messages",ok:false},{l:"Review + create",ok:false}],
  img:null,
  x:"The Azure Activity connector hands off to an Azure Policy assignment so every subscription in scope gets a diagnostic setting. DeployIfNotExists policies only touch resources created after assignment unless a remediation task is created, which is why the Remediation tab is the trap."},
 {id:"p029",obj:"1.3.6",portal:"defender",
  q:"Where do you hand-enter a single malicious domain as a STIX indicator the TI analytics rules can match on?",
  path:["Threat intelligence","Intel management","Add new"],
  target:"The 'TI object' entry in the Add new menu",
  regions:[{l:"TI object",ok:true},{l:"TI relationship",ok:false},{l:"Export",ok:false},{l:"Add tags",ok:false},{l:"Ingestion rules",ok:false}],
  img:null,
  x:"Intel management is where manual indicators, threat actors and relationships are created; bulk feeds come in through the TAXII and upload connectors instead. Ingestion rules act on incoming objects (tag, drop, change confidence) and are the distractor when the stem says 'before indicators are stored'."},
 {id:"p030",obj:"1.3.6",portal:"azure",
  q:"On the TAXII connector page, which field controls how often Sentinel pulls from the server collection?",
  path:["Configuration","Data connectors","Threat Intelligence - TAXII","Open connector page"],
  target:"The 'Polling frequency' dropdown",
  regions:[{l:"Polling frequency",ok:true},{l:"Friendly name",ok:false},{l:"API root URL",ok:false},{l:"Collection ID",ok:false},{l:"Username",ok:false},{l:"Password",ok:false}],
  img:null,
  x:"A TAXII 2.x connection needs an API root URL and a Collection ID, with optional credentials; each collection is its own entry. Polling frequency is the only schedule control. The uploaded-indicators and Defender TI connectors have no polling field, which helps separate them in stems."},
 {id:"p031",obj:"1.3.7",portal:"azure",
  q:"While creating a DCR-based custom table, where do you add the TimeGenerated column and reshape the uploaded JSON sample?",
  path:["Log Analytics workspaces","Tables","Create","New custom log (DCR based)"],
  target:"The 'Transformation editor' link in the sample-data step",
  regions:[{l:"Transformation editor",ok:true},{l:"Run",ok:false},{l:"Apply",ok:false},{l:"Next",ok:false},{l:"Create",ok:false}],
  img:null,
  x:"The custom-table wizard generates the _CL table and binds it to a DCR and data collection endpoint. Every table must carry TimeGenerated, so the transformation editor is where a KQL extend adds it from a source timestamp. Run previews the result; Apply commits it to the schema."},
 {id:"p032",obj:"1.4.1",portal:"defender",
  q:"After a hunting query returns the activity you want alerted on, where do you turn it into a recurring custom detection?",
  path:["Hunting","Advanced hunting"],
  target:"The 'Create detection rule' button above the query editor",
  regions:[{l:"Create detection rule",ok:true},{l:"Take actions",ok:false},{l:"Guided mode",ok:false},{l:"Advanced mode",ok:false},{l:"Hunting graph",ok:false}],
  img:null,
  x:"Create detection rule opens the wizard that needs a Timestamp column and a reportable ID in the query results. Take actions remediates the rows you have now; it does not persist. The hunting graph is a separate visual exploration mode, not a detection path."},
 {id:"p033",obj:"1.4.2",portal:"defender",
  q:"Where do you pause a noisy custom detection for a week without deleting its query or history?",
  path:["Hunting","Custom detection rules"],
  target:"The 'Turn off' action on the selected rule",
  regions:[{l:"Turn off",ok:true},{l:"Run",ok:false},{l:"Edit",ok:false},{l:"Modify query",ok:false},{l:"Delete",ok:false}],
  img:null,
  x:"The Custom detection rules list is the management surface: Run forces an immediate execution, Edit changes alert details and actions, Modify query reopens the KQL, and Turn off disables it reversibly. Deleting loses the triggered-alert history, which stems about 'keep the record' rule out."},
 {id:"p034",obj:"1.4.3",portal:"defender",
  q:"Which Create option gives an analytics rule that fires within about a minute of the event instead of on a schedule?",
  path:["Microsoft Sentinel","Configuration","Analytics","Create"],
  target:"The 'NRT query rule' entry in the Create menu",
  regions:[{l:"NRT query rule",ok:true},{l:"Scheduled query rule",ok:false},{l:"Microsoft incident creation rule",ok:false},{l:"Threat intelligence",ok:false},{l:"Active rules",ok:false},{l:"Rule templates",ok:false}],
  img:null,
  x:"Near-real-time rules run every minute with a one-minute lookback and support only a subset of KQL, so they trade flexibility for speed. Microsoft incident creation rules promote alerts from other Microsoft products; Threat intelligence rules match indicators. Templates and Anomalies are tabs, not create options."},
 {id:"p035",obj:"1.4.3",portal:"defender",
  q:"In the analytics rule wizard, which tab holds the setting that rolls alerts from the same rule into one incident?",
  path:["Microsoft Sentinel","Configuration","Analytics","Create","Scheduled query rule"],
  target:"The 'Incident settings' tab (Alert grouping section)",
  regions:[{l:"Incident settings",ok:true},{l:"General",ok:false},{l:"Set rule logic",ok:false},{l:"Automated response",ok:false},{l:"Review and create",ok:false}],
  img:null,
  x:"Alert grouping is an incident-settings concern, not rule logic: it decides whether multiple alerts become one incident and over what window. Event grouping on the Set rule logic tab decides how many alerts a single run creates, and the two are swapped in nearly every distractor."},
 {id:"p036",obj:"1.4.3",portal:"defender",
  q:"Where do you tell a scheduled rule which query column is the account so the incident shows a user entity?",
  path:["Microsoft Sentinel","Configuration","Analytics","Create","Scheduled query rule","Set rule logic"],
  target:"The 'Entity mapping' section under Alert enhancement",
  regions:[{l:"Entity mapping",ok:true},{l:"Rule query",ok:false},{l:"Custom details",ok:false},{l:"Alert details",ok:false},{l:"Query scheduling",ok:false},{l:"Alert threshold",ok:false}],
  img:null,
  x:"Entity mapping is what lets incidents list accounts, hosts and IPs and lets automation rules and playbooks act on them. Custom details surfaces extra columns in the alert, and Alert details overrides the alert name and description; neither creates an entity."},
 {id:"p037",obj:"1.4.4",portal:"azure",
  q:"Where do you see which ATT&CK techniques your active rules and hunting queries already cover?",
  path:["Microsoft Sentinel","Threat management"],
  target:"The 'MITRE ATT&CK (Preview)' entry in the Threat management menu",
  regions:[{l:"MITRE ATT&CK (Preview)",ok:true},{l:"Incidents",ok:false},{l:"Workbooks",ok:false},{l:"Hunting",ok:false},{l:"Notebooks",ok:false},{l:"Threat intelligence",ok:false}],
  img:null,
  x:"The MITRE page overlays active analytics rules and hunting queries on the matrix and can simulate coverage from templates not yet enabled. Workbooks can chart the same data but only after a rule's tactics are set in its General tab, which is the link stems expect you to know."},
 {id:"p038",obj:"1.4.5",portal:"defender",
  q:"Where do you adjust the sensitivity of a built-in anomaly rule without editing the Microsoft-owned original?",
  path:["Microsoft Sentinel","Configuration","Analytics","Anomalies"],
  target:"The 'Duplicate' option in the rule's context menu",
  regions:[{l:"Duplicate",ok:true},{l:"Edit",ok:false},{l:"Enable",ok:false},{l:"Flighting",ok:false},{l:"Production",ok:false}],
  img:null,
  x:"Anomaly rules are enabled by default and can only be tuned on a copy: Duplicate creates a customizable version in Flighting mode, you edit its thresholds, then promote it to Production, which disables the original. Edit on the Microsoft copy only exposes a limited set of parameters."},
 /* ---------- domain 2: respond to security incidents ---------- */
 {id:"p039",obj:"2.1.1",portal:"defender",
  q:"Where do you list every credential-harvesting message delivered to Fabrikam mailboxes in the last seven days?",
  path:["Email & collaboration","Explorer"],
  target:"The 'Phish' view",
  regions:[{l:"Phish",ok:true},{l:"All email",ok:false},{l:"Malware",ok:false},{l:"Campaigns",ok:false},{l:"Content malware",ok:false},{l:"URL clicks",ok:false}],
  img:null,
  x:"Threat Explorer's views are pre-filtered slices of the same mail data. Campaigns groups related phish by sender infrastructure, Content malware covers SharePoint, OneDrive and Teams files, and URL clicks shows Safe Links verdicts. Plan 1 tenants get Real-time detections with fewer views."},
 {id:"p040",obj:"2.1.1",portal:"defender",
  q:"Where do you send Microsoft a phishing message that the filters let through so the verdict gets corrected?",
  path:["Actions & submissions","Submissions"],
  target:"The 'Emails' tab, then 'Submit to Microsoft for analysis'",
  regions:[{l:"Emails",ok:true},{l:"Teams messages",ok:false},{l:"Email attachments",ok:false},{l:"URLs",ok:false},{l:"Files",ok:false},{l:"User reported",ok:false}],
  img:null,
  x:"Admin submissions are split by object type; a missed phish is an Emails submission, a lone attachment or hash belongs on Email attachments or Files. User reported is the inbound queue of messages employees flagged with the Report button, which admins can then escalate from the same page."},
 {id:"p041",obj:"2.1.4",portal:"defender",
  q:"Which policy type do you create so externally shared files containing card numbers are quarantined in Woodgrove's SharePoint?",
  path:["Cloud apps","Policies","Policy templates"],
  target:"The 'File policy' template",
  regions:[{l:"File policy",ok:true},{l:"Activity policy",ok:false},{l:"Session policy",ok:false},{l:"Access policy",ok:false},{l:"App discovery policy",ok:false},{l:"OAuth app policy",ok:false}],
  img:null,
  x:"File policies scan content at rest in connected apps and can quarantine or remove sharing. Session policies act inline on uploads and downloads during a proxied session, and activity policies watch events such as mass download. App discovery and OAuth app policies are about shadow IT and consent, not content."},
 {id:"p042",obj:"2.1.5",portal:"entra",
  q:"Where do you tell Entra ID that a flagged account really was taken over so its risk goes to High and policies kick in?",
  path:["Protection","Identity Protection","Risky users"],
  target:"The 'Confirm compromised' action on the selected user",
  regions:[{l:"Confirm compromised",ok:true},{l:"Dismiss user risk",ok:false},{l:"Reset password",ok:false},{l:"Risky sign-ins",ok:false},{l:"Risk detections",ok:false}],
  img:null,
  x:"Risky users aggregates per-account risk, while Risky sign-ins and Risk detections list the events behind it. Confirming compromise feeds the ML model and raises risk; Dismiss clears it. Reset password or a self-service password change with MFA is what actually remediates the risk."},
 {id:"p043",obj:"2.1.7",portal:"azure",
  q:"Where do you add a checklist item the analyst must complete before closing a Sentinel incident?",
  path:["Microsoft Sentinel","Threat management","Incidents","View full details"],
  target:"The 'Tasks' button in the top bar, then '+ Add task'",
  regions:[{l:"Tasks",ok:true},{l:"Activity log",ok:false},{l:"Logs",ok:false},{l:"Incident actions",ok:false},{l:"Overview",ok:false},{l:"Entities",ok:false}],
  img:null,
  x:"Incident tasks can be added by hand, by an automation rule or by a playbook, and the Tasks panel shows which. Activity log holds the audit trail and comments, Logs opens a query window scoped to the incident, and Incident actions holds Run playbook and Create automation rule."},
 {id:"p044",obj:"2.1.8",portal:"defender",
  q:"After new alerts merge into an incident you are already working, where do you get Copilot to rebuild its summary?",
  path:["Incidents & alerts","Incidents","Copilot pane"],
  target:"The 'Regenerate' control on the incident summary card",
  regions:[{l:"Regenerate",ok:true},{l:"See prompts",ok:false},{l:"Generate",ok:false},{l:"Open in Security Copilot",ok:false},{l:"Cancel",ok:false}],
  img:null,
  x:"The embedded Copilot pane auto-generates a summary when an incident opens; Regenerate refreshes it, Generate is for incidents that did not get one automatically, and Open in Security Copilot hands the session to the standalone portal for prompt-driven investigation."},
 {id:"p045",obj:"2.1.9",portal:"defender",
  q:"Where do you view the alerts of a multi-stage incident on one timeline with the entity graph beside it?",
  path:["Incidents & alerts","Incidents"],
  target:"The 'Attack story' tab of the incident page",
  regions:[{l:"Attack story",ok:true},{l:"Alerts",ok:false},{l:"Assets",ok:false},{l:"Investigations",ok:false},{l:"Evidence and Response",ok:false},{l:"Summary",ok:false}],
  img:null,
  x:"Attack story is the first tab and combines the alert timeline, the incident graph and the selected alert's details. Alerts is the flat list, Assets groups devices, users, mailboxes and apps, Investigations shows AIR runs and Evidence and Response lists every entity with its verdict."},
 {id:"p046",obj:"2.2.1",portal:"defender",
  q:"From a suspicious row on a device's timeline, where do you pivot into advanced hunting for related events?",
  path:["Assets","Devices","Timeline"],
  target:"The 'Hunt for related events' action",
  regions:[{l:"Hunt for related events",ok:true},{l:"Flagged events",ok:false},{l:"Export",ok:false},{l:"Customize columns",ok:false},{l:"Timeline",ok:false},{l:"Overview",ok:false}],
  img:null,
  x:"The device timeline is the chronological event feed for one device, filterable by data type and MITRE technique. Flagging keeps rows for later; Export pulls a CSV. Hunt for related events builds a prefilled advanced hunting query from the selected event rather than only filtering the timeline."},
 {id:"p047",obj:"2.2.2",portal:"defender",
  q:"Where do you open a remote shell on a compromised device to pull a file with getfile?",
  path:["Assets","Devices"],
  target:"The 'Initiate live response session' action on the device page",
  regions:[{l:"Initiate live response session",ok:true},{l:"Initiate automated investigation",ok:false},{l:"Collect investigation package",ok:false},{l:"Run antivirus scan",ok:false},{l:"Manage tags",ok:false},{l:"Isolate device",ok:false}],
  img:null,
  x:"The response-action bar on the device page is where every manual action starts. Live response is interactive; Collect investigation package is a one-shot forensic bundle you download from Action center; Initiate automated investigation hands the device to AIR instead of an analyst."},
 {id:"p048",obj:"2.2.2",portal:"defender",
  q:"Where do you cut a device off the network while keeping its connection to the Defender service?",
  path:["Assets","Devices"],
  target:"The 'Isolate device' action on the device page",
  regions:[{l:"Isolate device",ok:true},{l:"Contain device",ok:false},{l:"Restrict app execution",ok:false},{l:"Run antivirus scan",ok:false},{l:"Collect investigation package",ok:false},{l:"Action center",ok:false}],
  img:null,
  x:"Isolate device works on onboarded endpoints and offers Full or Selective isolation. Contain device is for unmanaged or discovered devices and makes onboarded machines block traffic to it. Restrict app execution leaves networking alone and only blocks unsigned executables."},
 {id:"p049",obj:"2.2.2",portal:"defender",
  q:"Where do you reverse a file quarantine that an automated investigation carried out yesterday?",
  path:["Actions & submissions","Action center"],
  target:"The 'History' tab, then 'Undo' on the action",
  regions:[{l:"History",ok:true},{l:"Pending",ok:false},{l:"Export",ok:false},{l:"Submissions",ok:false},{l:"Action center",ok:false}],
  img:null,
  x:"History is the tenant-wide audit of completed response actions, both automated and manual, and is where Undo appears for reversible actions such as quarantine or isolation. Pending only lists actions still waiting for approval, so a completed quarantine never shows there."},
 {id:"p050",obj:"2.3.1",portal:"purview",
  q:"In the audit search form, where do you enter the raw operation name such as New-InboxRule rather than its display name?",
  path:["Audit","Search"],
  target:"The 'Activities - operations names' field",
  regions:[{l:"Activities - operations names",ok:true},{l:"Activities - friendly names",ok:false},{l:"Date and time range (UTC)",ok:false},{l:"Keyword Search",ok:false},{l:"Record types",ok:false},{l:"Users",ok:false}],
  img:null,
  x:"Audit search has two activity pickers: friendly names for the curated list and operations names for the exact cmdlet or API operation string. Record types narrows by workload schema. Searches run as jobs and results are read from the job dashboard, not inline."},
 {id:"p051",obj:"2.3.2",portal:"purview",
  q:"In an eDiscovery search, where do you switch from the condition builder to typing a raw query?",
  path:["eDiscovery","Cases","Searches","Create a search"],
  target:"The 'Keyword Query Language (KeyQL)' tab in the query area",
  regions:[{l:"Keyword Query Language (KeyQL)",ok:true},{l:"Condition builder",ok:false},{l:"Run query",ok:false},{l:"Save as draft",ok:false},{l:"Generate statistics",ok:false},{l:"Draft a query with Copilot",ok:false}],
  img:null,
  x:"In the current eDiscovery, Content search is itself a case that holds searches, so the same search page applies. Condition builder composes filters visually; the KeyQL tab accepts the query string directly. Generate statistics estimates hits before any export or review set is created."},
 {id:"p052",obj:"2.3.3",portal:"entra",
  q:"Where do you start streaming every Microsoft Graph API call made against the tenant into the Sentinel workspace?",
  path:["Entra ID","Monitoring & health","Diagnostic settings","+ Add diagnostic setting"],
  target:"The 'MicrosoftGraphActivityLogs' category checkbox",
  regions:[{l:"MicrosoftGraphActivityLogs",ok:true},{l:"AuditLogs",ok:false},{l:"SignInLogs",ok:false},{l:"ProvisioningLogs",ok:false},{l:"RiskyUsers",ok:false},{l:"Send to Log Analytics workspace",ok:false}],
  img:null,
  x:"Graph activity logs are an Entra diagnostic-setting category, not a Purview feature, and land in the MicrosoftGraphActivityLogs table. AuditLogs records directory changes and SignInLogs records authentications; only the Graph category shows which app or user called which endpoint."},
 /* ---------- domain 3: perform threat hunting ---------- */
 {id:"p053",obj:"3.1.3",portal:"defender",
  q:"Where do you switch from the point-and-click query builder to writing KQL yourself?",
  path:["Hunting","Advanced hunting"],
  target:"The 'Advanced mode' switch above the editor",
  regions:[{l:"Advanced mode",ok:true},{l:"Guided mode",ok:false},{l:"Create detection rule",ok:false},{l:"Take actions",ok:false},{l:"Hunting graph",ok:false}],
  img:null,
  x:"Guided mode builds a query from dropdowns and never shows KQL; Advanced mode is the editor with schema, functions and shared queries. Both run against the same tables. Custom detection rules require a query, so guided-mode results can still become a detection once converted."},
 {id:"p054",obj:"3.1.4",portal:"defender",
  q:"In a threat analytics report, where do you read Microsoft's narrative on the actor's tooling and tradecraft?",
  path:["Threat analytics","High-impact threats"],
  target:"The 'Analyst report' tab of the opened report",
  regions:[{l:"Analyst report",ok:true},{l:"Overview",ok:false},{l:"Related incidents",ok:false},{l:"Impacted assets",ok:false},{l:"Endpoints exposure",ok:false},{l:"Recommended actions",ok:false}],
  img:null,
  x:"Each report has the same tab layout. Overview is the scorecard, Analyst report is the written intelligence, Related incidents and Impacted assets map the threat to your tenant, Endpoints exposure shows patch status and Recommended actions lists mitigations with their state."},
 {id:"p055",obj:"3.1.5",portal:"defender",
  q:"Which predefined hunting-graph scenario shows every route an attacker could take to a domain admin account?",
  path:["Hunting","Advanced hunting","Create new","Hunting graph"],
  target:"The 'Paths to domain admins' scenario",
  regions:[{l:"Paths to domain admins",ok:true},{l:"Entity relationship map",ok:false},{l:"Paths between two entities",ok:false},{l:"Attack paths to critical asset",ok:false},{l:"Potential data exfiltration by device",ok:false},{l:"Least privilege access",ok:false}],
  img:null,
  x:"The hunting graph renders predefined scenarios over the Sentinel graph rather than returning rows. Attack paths to critical asset starts from an asset you name, while Paths to domain admins starts from the privileged group; the blast-radius view is reached from an entity, not from this list."},
 {id:"p056",obj:["3.1.6","3.1.5"],portal:"defender",
  q:"Which hunting-graph scenario do you run to see how a compromised workstation connects to a particular file server through intermediate identities?",
  path:["Hunting","Advanced hunting","Create new","Hunting graph"],
  target:"The 'Paths between two entities' scenario",
  regions:[{l:"Paths between two entities",ok:true},{l:"Entity relationship map",ok:false},{l:"Paths to domain admins",ok:false},{l:"Attack paths to critical asset",ok:false},{l:"Access to key vaults",ok:false},{l:"Service accounts with RDP to critical devices",ok:false}],
  img:null,
  x:"Paths between two entities takes a source and a destination and traces the relationship chain, which is the Sentinel graph answer to lateral-movement stems. Entity relationship map shows one entity's neighborhood without a target, and the critical-asset scenarios start from asset criticality tags."},
 {id:"p057",obj:"3.2.1",portal:"defender",
  q:"Where do you execute every out-of-the-box hunting query at once to see which ones return results today?",
  path:["Microsoft Sentinel","Threat management","Hunting","Queries"],
  target:"The 'Run all queries' button",
  regions:[{l:"Run all queries",ok:true},{l:"Run selected queries",ok:false},{l:"New hunt",ok:false},{l:"Hunts",ok:false},{l:"Queries",ok:false},{l:"Bookmarks",ok:false}],
  img:null,
  x:"The Hunting page has Hunts, Queries and Bookmarks tabs; livestream is no longer offered there. Run all queries populates the result-count column so you can sort by hits, Run selected limits that to checked rows, and New hunt opens a container that groups queries and bookmarks for one investigation."},
 {id:"p058",obj:"3.2.2",portal:"defender",
  q:"After testing a query against data lake tier data, where do you schedule it to write results into an analytics-tier table?",
  path:["Microsoft Sentinel","Data lake exploration","KQL queries"],
  target:"The 'Create job' button in the query editor",
  regions:[{l:"Create job",ok:true},{l:"Run query",ok:false},{l:"New query",ok:false},{l:"Export",ok:false},{l:"Query history",ok:false},{l:"Async Queries",ok:false}],
  img:null,
  x:"KQL jobs are the data lake way to promote long-term data into a queryable analytics table on a schedule or once. Run query only returns interactive results; Export writes a CSV. Jobs are then managed from the Jobs page in the same Data lake exploration menu."},
 {id:"p059",obj:"3.2.3",portal:"defender",
  q:"In the summary rule wizard, where do you name the custom table that will hold the hourly aggregates?",
  path:["Microsoft Sentinel","Configuration","Summary rules","+ Create"],
  target:"The 'Destination table' field on the Basics tab",
  regions:[{l:"Destination table",ok:true},{l:"Name",ok:false},{l:"Description",ok:false},{l:"Set summary logic",ok:false},{l:"Review + create",ok:false}],
  img:null,
  x:"Summary rules aggregate verbose data, including Auxiliary or data lake tables, into a _CL table that analytics rules can query. The destination is chosen on Basics; the query and its run frequency live on Set summary logic. Unlike a KQL job, a summary rule always runs on a recurring schedule."},
 {id:"p060",obj:"3.2.4",portal:"azure",
  q:"Where do you browse the prebuilt guided-hunting notebooks before copying one into your workspace?",
  path:["Microsoft Sentinel","Threat management","Notebooks"],
  target:"The 'Templates' tab",
  regions:[{l:"Templates",ok:true},{l:"My notebooks",ok:false},{l:"Launch notebook",ok:false},{l:"Create from template",ok:false}],
  img:null,
  x:"Templates lists the Microsoft-provided notebooks; Create from template copies one into My notebooks, and Launch notebook opens it in an Azure Machine Learning workspace. Notebooks run Python with MSTICPy against the workspace, which is what separates them from workbooks."},
];
